Repository dotnet/sdk, pull requests merged in 2018-06, with the labels that each got.

#2298 Add DefaultNetCorePatchVersion and LatestPatchVersionForNetCore2_1 for 2.1
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: Pending Shiproom Approval

#2154 Never mark files from nuget as in-box fx ref assemblies
  src/Tasks/Microsoft.NET.Build.Tasks/ReferenceInfo.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Approved to merge

#2293 Use MemoryMappedViewAccessor to reduce memory consumption of creating apphost
  src/Tasks/Microsoft.NET.Build.Tasks/AppHost.cs
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Approved to merge

#2282 Implement framework-dependent application with apphost.
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAFrameworkDependentApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASelfContainedApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/Microsoft.NET.Publish.Tests.csproj
Labels: Approved to merge

#2330 Add warning for ref to netstandard >= 1.5 from netfx without built-in support
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExeWtihNetStandardLib.cs
  src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs
Labels: Approved to merge

#2346 Add link to runtime roll-forward documentation
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Approved to merge

#2352 Update stage0 and change/disable tests according to it
  global.json
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatAPublishedDepsJsonShouldContainVersionInformation.cs
  src/Tests/Microsoft.NET.TestFramework/SetupTestRoot.targets
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
Labels: Approved to merge, Infrastructure

#2361 Use blob feed instead of myget feed
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateADepsFileForATool.cs
  src/Tests/Microsoft.NET.PerformanceTests/BuildPerf.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToIgnoreObsoleteDotNetCliToolPackages.cs
  src/Tests/Microsoft.NET.TestFramework/NuGetConfigWriter.cs
  src/Tests/Microsoft.NET.TestFramework/SetupTestRoot.targets
Labels: Infrastructure

#2354 Packtool use nuget SuppressDependenciesOnPacking
  build/Versions.props
  src/Assets/TestProjects/PortableToolWithTestProject/App/Program.cs
  src/Assets/TestProjects/PortableToolWithTestProject/App/consoledemo.csproj
  src/Assets/TestProjects/PortableToolWithTestProject/Test/UnitTest1.cs
  src/Assets/TestProjects/PortableToolWithTestProject/Test/XUnitTestProject.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PackTool.targets
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProject.cs
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProjectWithComplexNugetDependency.cs
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProjectWithP2PReference.cs
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToTestPackAToolProject.cs
Labels: Approved to merge

#2336 Insert NuGet Build 4.8.0-preview3.5278 into sdk
  build/Versions.props
  global.json
Labels: Approved to merge

#2365 Use UseBundledNETCoreAppPackageVersionAsDefaultNetCorePatchVersion
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
Labels: Approved to merge

#2369 Add DisableImplicit1xNuGetFallbackFolder flag
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.NuGetOfflineCache.targets
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreProjectsUsingNuGetConfigProperties.cs
Labels: Approved to merge
