Repository dotnet/sdk, pull requests merged in 2018-10, with the labels that each got.

#2561 Consistently use PackagedShimOutputRootDirectory to set the path to generated shims
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PackTool.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProjectWithPackagedShim.cs
Labels: Servicing-approved

#2558 Modify 'SourceTimestamp' value for SDK perf data
  build/uploadperftobenchview.cmd
  build/uploadperftobenchview.sh
Labels: Infrastructure

#2567 Run the SDK performance tests daily.
  perf.groovy
Labels: Infrastructure

#2538 Fix overrides filename
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FSharp.targets
Labels: Approved to merge

#2577 Change in performance tests' working-directory
  perf.groovy
Labels: Infrastructure

#2581 Fix issue where ASP.NET PackageReferences with implicit versions had incorrect PrivateAssets value
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatThereAreImplicitPackageReferences.cs
Labels: Approved to merge
