Repository dotnet/sdk, pull requests merged in 2018-04, with the labels that each got.

#2101 Allow dotnet host path to be overridden via DOTNET_INSTALL_DIR environment variable
  build/Versions.props
  src/Directory.Build.targets
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Infrastructure

#2091 Move DefineConstants where they'll actually apply
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/GivenANETBuildExtensionsError.cs
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
Labels: Approved to merge

#2123 Produce 2 'symbols.nupkg'; SDK
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: build

#2133 Add back NuGetSourceType=Package metadata in package resolution
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToPreserveCompilationContextForBuild.cs
Labels: Approved to merge

#2010 Don't set a default ProjectAssetsFile path in the SDK
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/CheckForTargetInAssetsFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/FilterResolvedFiles.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateRuntimeConfigurationFiles.cs
  src/Tasks/Microsoft.NET.Build.Tasks/LoadAssetsFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/LockFileCache.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ReportAssetsLogMessages.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageDependencies.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePublishAssemblies.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatAProjectHasntBeenRestored.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantDiagnosticsWhenAssetsFileCannotBeRead.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
Labels: Approved to merge

#2148 Update implicit version checks to operate on list of implicit packages
  src/Tasks/Common/MetadataKeys.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolvePackageAssetsTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets
Labels: Approved to merge

#2159 Defend against parallel access to package assets cache
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
Labels: Approved to merge

#2118 Include assembly and file versions in deps file for non self-contained publish
  build/Versions.props
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenADependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/NuGetPackageResolver.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/Microsoft.NET.Build.Tests.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatAPublishedDepsJsonShouldContainVersionInformation.cs
  src/Tests/Microsoft.NET.Publish.Tests/Microsoft.NET.Publish.Tests.csproj
  src/Tests/Microsoft.NET.ToolPack.Tests/Microsoft.NET.ToolPack.Tests.csproj
Labels: Approved to merge

#2174 Set ProjectAssetsFile property in SDK if it's not already set
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatAProjectHasntBeenRestored.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantDiagnosticsWhenAssetsFileCannotBeRead.cs
Labels: Approved to merge

#2166 Merge remote-tracking branch 'dotnet/release/2.1.2xx' into version-tasks
  build/SignToolData.json
  build/Versions.props
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreProjectsUsingNuGetConfigProperties.cs
Labels: Approved to merge

#2177 Insert NuGet Build 4.7.0-rtm.5148 into sdk
  build/Versions.props
Labels: Approved to merge

#2194 Support overriding MSBuildProjectExtensionsPath for a specific project via global properties
  src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.props
Labels: Approved to merge

#2200 Update version to RTM
  build/Versions.props
Labels: Approved to merge
