Repository dotnet/sdk, pull requests merged in 2019-04, with the labels that each got.

#3078 Switching to Jobs from Phases for YAML
  .vsts-ci.yml
  eng/build.yml
Labels: Infrastructure

#3116 Insert NuGet Build 5.0.1-rtm.5946 into sdk
  build/Versions.props
  global.json
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: Servicing-approved

#3117 Insert NuGet Build 5.0.1-rtm.5946 into sdk
  build/Versions.props
  global.json
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: Servicing-approved

#3167 Move the SDK Performance tests to Helix
  .vsts-ci.yml
  build/RunPerfTestsOnHelix.cmd
  build/RunPerfTestsOnHelix.sh
  build/uploadperftobenchview.cmd
  build/uploadperftobenchview.sh
  eng/build.yml
  global.json
  perf.groovy
Labels: performance

#3176 Fix the parameters: Windows call to 'RunPerfTestsOnHelix'
  eng/build.yml
Labels: performance
