Repository dotnet/sdk, pull requests merged in 2019-12, with the labels that each got.

#3994 Enable R2R publishing for library projects
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenThatWeHaveErrorCodes.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Approved to merge, Servicing-approved

#4028 Update stage0
  global.json
Labels: Auto-Merge If Tests Pass, auto-merge

#4044 Generate Content for a Test at Run-time
  src/Assets/TestProjects/HelloWorldWithSubDirs/Program.cs
  src/Assets/TestProjects/HelloWorldWithSubDirs/SmallNameDir/This is a directory with a really long name for one that only contains a small file/.word
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#4045 Generate Content for a Test at Run-time -- release/3.1.2xx
  src/Assets/TestProjects/HelloWorldWithSubDirs/Program.cs
  src/Assets/TestProjects/HelloWorldWithSubDirs/SmallNameDir/This is a directory with a really long name for one that only contains a small file/.word
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#4040 Revert back to 3.1.0 runtime versions
  eng/Version.Details.xml
Labels: Auto-Merge If Tests Pass, auto-merge

#4054 Don't double pack icon in our transport package (#3906)
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Infrastructure, tell-mode

#4055 Don't double pack icon in our transport package (#3906)
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Auto-Merge If Tests Pass, Infrastructure, auto-merge, tell-mode

#4053 3.1.2xx double icon
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: tell-mode

#4082 Make perf run separate
  .vsts-ci.yml
  eng/build.yml
Labels: Infrastructure, tell-mode
