Repository dotnet/sdk, pull requests merged in 2020-11, with the labels that each got.

#14407 Add how to run tests in VS
  documentation/project-docs/developer-guide.md
Labels: Auto-Merge If Tests Pass, auto-merge

#14463 Update branding for 405
  eng/Versions.props
Labels: Branding

#14464 Update branding for 111
  eng/Versions.props
Labels: Branding

#13579 Pass Optimize to CoreGenerateSatelliteAssemblies
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Behavior Change

#14319 Fix design-time build with RuntimeIdentifier specific for .NET Core 2.x
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets
  src/Tests/Microsoft.NET.Build.Tests/DesignTimeBuildTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildWithARuntimeIdentifier.cs
Labels: Servicing-approved

#14532 Enable test in parallel with Helix (and non helix and helix test also in parallel)
  .vsts-ci.yml
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
  documentation/project-docs/repro-helix-failure.md
  eng/build.yml
  eng/runHelixAndNonHelixInParallel.ps1
  eng/runTestsCannotRunOnHelix.ps1
  eng/runTestsCannotRunOnHelix.sh
  src/Assets/TestProjects/TestAppWithSlnAndCsprojFiles/App/App.csproj
  src/Layout/toolset-tasks/OverrideAndCreateBundledNETCoreAppPackageVersion.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.csproj
  src/Tests/ArgumentForwarding.Tests/ArgumentForwarding.Tests.csproj
  src/Tests/HelixTasks/CreateLocalHelixTestLayout.cs
  src/Tests/HelixTasks/HelixTasks.csproj
  src/Tests/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  src/Tests/Microsoft.DotNet.ShellShim.Tests/WindowsEnvironmentPathTests.cs
  src/Tests/Microsoft.DotNet.ToolPackage.Tests/Microsoft.DotNet.ToolPackage.Tests.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/ZipDeployerTaskTests.cs
  src/Tests/Microsoft.NET.TestFramework/TestCommandLine.cs
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
  src/Tests/UnitTests.proj
  src/Tests/testsProjectCannotRunOnHelixList.txt
  src/Tests/xunit-runner/XUnitRunner.targets
Labels: Auto-Merge If Tests Pass, auto-merge

#14517 Fix building projects restored with NuGet 5.7
  src/Tasks/Microsoft.NET.Build.Tasks/LockFileExtensions.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExeWtihNetStandardLib.cs
  src/Tests/Microsoft.NET.Restore.Tests/RestoreWithOlderNuGet.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/NuGetExeRestoreCommand.cs
  src/Tests/Microsoft.NET.TestFramework/TestAsset.cs
Labels: Approved to merge

#14674 Fixing duplicate argument filtering in parser
  src/Cli/dotnet/Program.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#14701 Opting into single argument per option token parser behavior
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/OptionForwardingExtensions.cs
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommandParser.cs
  src/Cli/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/Cli/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/Cli/dotnet/commands/dotnet-store/StoreCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallCommandParser.cs
  src/Cli/dotnet/dotnet.csproj
  src/Tests/dotnet-restore.Tests/GivenThatIWantToRestoreApp.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestContainsEnvironmentVariables.cs
  src/Tests/dotnet.Tests/ParserTests/RestoreParserTests.cs
Labels: Auto-Merge If Tests Pass, auto-merge
