Repository dotnet/sdk, pull requests merged in 2020-08, with the labels that each got.

#12655 Merge Preview 8 to master
  eng/restore-toolset.ps1
  global.json
  src/Assets/TestProjects/TestAppWithLaunchSettings/Program.cs
  src/Assets/TestProjects/TestAppWithLaunchSettings/Properties/launchSettings.json
  src/Assets/TestProjects/TestAppWithLaunchSettings/TestAppWithLaunchSettings.csproj
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ILaunchSettingsProvider.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/LaunchSettingsApplyResult.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/LaunchSettingsManager.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsModel.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsProvider.cs
  src/Cli/dotnet/commands/dotnet-run/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hant.xlf
  src/Layout/redist/minimumMSBuildVersion
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.WindowsSupportedTargetPlatforms.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliNonLibraryProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibraryWithOSMinimumVersion.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsDesktopProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildWithATargetPlatform.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackACppCliProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishACppCliAppProject.cs
  src/Tests/dotnet-list-package.Tests/GivenDotnetListPackage.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#12789 Import WinFX Targets Only When Targeting .NETFramework
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
Labels: Servicing-approved

#12829 Remove the default code owner
  CODEOWNERS
Labels: Auto-Merge If Tests Pass, auto-merge

#12859 Workaround for P2P reference with targetplatform
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAP2PrefernceWithTargetPlatform.cs
Labels: Servicing-consider

#12167 Allow updating PublishUrl
  src/WebSdk/Publish/Targets/PublishProfiles/FileSystem.pubxml
Labels: Web SDK

#12860 [.NET 5.0] [Preview8] Fixing the worker project build in Linux due to a casing issue.
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.props
Labels: Servicing-approved, Web SDK

#12867 Dispose CancellationTokenSource
  src/Cli/dotnet/NugetSearch/NugetToolSearchApiRequest.cs
  src/Cli/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#12862 Fix exception when running "dotnet tool search"
  src/Cli/dotnet/commands/dotnet-tool/search/ToolSearchCommandParser.cs
  src/Tests/dotnet.Tests/ParserTests/ToolSearchParserTests.cs
Labels: auto-merge

#12895 Dev/merge internal 08112020/release/3.1.1xx
  eng/Version.Details.xml
  eng/Versions.props
Labels: Branding

#12910 Dev/merge internal 08132020/release/3.1.4xx
  eng/Versions.props
Labels: Branding

#12943 Pass TargetPlatformMoniker to designer time build
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets
  src/Tests/Microsoft.NET.Build.Tests/GiventThatWeWantDesignerSupport.cs
Labels: Auto-Merge If Tests Pass, Servicing-approved, auto-merge

#12933 Implement template locator on the top of xml manifest reader
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Microsoft.DotNet.TemplateLocator/TemplateLocator.cs
  src/Resolvers/Microsoft.DotNet.WorkloadManifestReader/WorkloadManifest.cs
  src/Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests/GivenAnMSBuildSdkResolver.cs
  src/Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests.csproj
  src/Tests/Microsoft.DotNet.TemplateLocator.Tests/GivenAnMSBuildSdkResolver.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#12989 Template locator
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests.csproj
  src/Tests/Microsoft.DotNet.TemplateLocator.Tests/GivenAnTemplateLocator.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#12880 Update developer-guide.md
  documentation/project-docs/developer-guide.md
Labels: Auto-Merge If Tests Pass, auto-merge

#13085 Adding default ProduceReferenceAssembly value for F#
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FSharp.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExeWithFSharp.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#13111 Fix C++/CLI
  src/Assets/TestProjects/NETCoreCppClApp/NETCoreCppCliTest/NETCoreCppCliTest.vcxproj
  src/Assets/TestProjects/NetCoreCsharpAppReferenceCppCliLib/CSConsoleApp/CSConsoleApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
Labels: Auto-Merge If Tests Pass, auto-merge

#13225 Update Microsoft.CodeAnalysis.NetAnalyzers.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
Labels: auto-merge

#13205 Removed install scripts and tests, added readme
  scripts/obtain/dotnet-install-readme
  scripts/obtain/dotnet-install.ps1
  scripts/obtain/dotnet-install.sh
  sdk.sln
  src/Tests/InstallationScript.Tests/GivenThatIWantToInstallTheSdkFromAScript.cs
  src/Tests/InstallationScript.Tests/InstallationScript.Tests.csproj
Labels: triaged
