Repository dotnet/sdk, pull requests merged in 2020-01, with the labels that each got.

#4115 disable useapphost on mac by default
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToCopyLocalDependencies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseVB.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishItemsOutputGroupTests.cs
  src/Tests/Microsoft.NET.TestFramework/AssertionHelper.cs
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProject.cs
Labels: Pending M2 Approval

#4121 Fix parsing of metadata when looking for COM related CustomAttributes. [3.1.2xx]
  src/Assets/TestProjects/ComServer/ComServer.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ClsidMap.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ComHost.cs
Labels: Approved to merge

#4019 disable useapphost on mac by default
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToCopyLocalDependencies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseVB.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishItemsOutputGroupTests.cs
  src/Tests/Microsoft.NET.TestFramework/AssertionHelper.cs
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProject.cs
Labels: Servicing-consider

#4114 disable useapphost on mac by default
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToCopyLocalDependencies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseVB.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishItemsOutputGroupTests.cs
  src/Tests/Microsoft.NET.TestFramework/AssertionHelper.cs
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProject.cs
Labels: Servicing-consider

#4245 Fix not resolving windowsbase
  src/Assets/TestProjects/CppCliLibWithWpfFrameworkReference/Project1.vcxproj
  src/Assets/TestProjects/CppCliLibWithWpfFrameworkReference/SubImage.cpp
  src/Assets/TestProjects/CppCliLibWithWpfFrameworkReference/SubImage.h
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolutionStubs.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs
Labels: Auto-Merge If Tests Pass, auto-merge
