Repository dotnet/sdk, pull requests merged in 2021-05, with the labels that each got.

#16992 Add initial commit for package validation
  sdk.sln
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticBag.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/BaselinePackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleFrameworkInPackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleTFMValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/GetLastStablePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/Compatibility/Microsoft.DotNet.PackageValidation/NupkgParser.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Package.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/PackageValidationLogger.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/build/Microsoft.DotNet.PackageValidation.props
  src/Compatibility/Microsoft.DotNet.PackageValidation/build/Microsoft.DotNet.PackageValidation.targets
  src/Compatibility/Microsoft.DotNet.PackageValidation/sdk/Sdk.props
  src/Compatibility/Microsoft.DotNet.PackageValidation/sdk/Sdk.targets
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Microsoft.DotNet.PackageValidation.Tests.csproj
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/PackageValidationTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/TestLogger.cs
Labels: Area-Compatibility

#17317 Use cross-genned assemblies in CLI
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore

#16915 Implement sdk support for embedding tlbs into the comhost.
  src/Assets/TestProjects/ComServerWithTypeLibs/ComServerWithTypeLibs.cs
  src/Assets/TestProjects/ComServerWithTypeLibs/ComServerWithTypeLibs.csproj
  src/Assets/TestProjects/ComServerWithTypeLibs/dummy1.tlb
  src/Assets/TestProjects/ComServerWithTypeLibs/dummy2.tlb
  src/Assets/TestProjects/ComServerWithTypeLibs/invalid.tlb
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/CreateComHost.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateRegFreeComManifest.cs
  src/Tasks/Microsoft.NET.Build.Tasks/TypeLibraryDictionaryBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAComServerLibrary.cs
Labels: Area-NetSDK, auto-merge

#17385 Fix UpToDateCheck properties for .NET 6 apps
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-AspNetCore

#17418 Update branding for 5.0.2xx 5.0.2xx
  eng/Versions.props
Labels: Branding

#17419 Update branding for 3.1.4xx 3.1.4xx
  eng/Versions.props
Labels: Branding

#17420 Update branding for 3.1.1xx 3.1.1xx
  eng/Versions.props
Labels: Branding

#17295 Support multiple rights vs same left scenario with a simple call to ApiComparer
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/ElementContainer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/IRuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblySetMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementSide.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/MemberMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/NamespaceMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/TypeMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/MetadataInformation.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Rule.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerContext.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SymbolFactory.cs
Labels: Area-Compatibility

#17092 Use build Wasm Runtime tasks when available
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
Labels: Area-AspNetCore

#17492 Spruce up Razor source generator
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.Helpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.SourceTexts.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.TagHelperDiscovery.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-AspNetCore

#17558 Update merge for 5.0.2xx 5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Branding

#17537 Reuse binaries from compiler directory to reduce SDK size
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/RazorSdk/Tool/Program.cs
Labels: Area-AspNetCore

#17542 [API Compat] Add StrictMode and support it in type must exist rule
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Rule.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ComparingSettings.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerFactory.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleSettings.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.Strict.cs
Labels: Area-Compatibility

#17594 Fix test projects which reference self-contained Exes
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
Labels: Servicing-approved

#17489 Better error strings, null check, Add some more test, use sdk default logger
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/BaselinePackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleFrameworkInPackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleTFMValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/GetLastStablePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/IPackageLogger.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/Compatibility/Microsoft.DotNet.PackageValidation/Package.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/PackageValidationLogger.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Tasks/Common/Logger.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/BaseLineVersionValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/CompatibleFrameworkValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/CompatibleFrameworksInPackageTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/PackageValidationTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/TestLogger.cs
Labels: Area-Compatibility

#17617 Bring back and fix up dependency consolidation changes
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Layout/redist/targets/GenerateLayout.targets
  src/RazorSdk/Tool/Microsoft.NET.Sdk.Razor.Tool.csproj
  src/RazorSdk/Tool/Program.cs
Labels: Area-AspNetCore

#17607 Add IsTrimmable property
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#17612 Update Compatibility version and remove IsShipping
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
Labels: Area-Compatibility

#17540 Refactor how composite image creation works
  src/Tasks/Common/MetadataKeys.cs
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
Labels: Area-ReadyToRun

#17624 Add mock dotnet workload update
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommandParser.cs
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
Labels: Area-Workloads

#17618 Add support for new files
  src/BuiltInTools/dotnet-watch/FileItem.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileSetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/DotnetFileWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/IFileSystemWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/PollingFileWatcher.cs
  src/Tests/dotnet-watch.Tests/FileWatcherTests.cs
Labels: Area-AspNetCore

#17643 Add an option to hot-restart web apps
  sdk.sln
  src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/BuiltInTools/HotRestart/Microsoft.Extensions.HotRestart.csproj
  src/BuiltInTools/HotRestart/Program.cs
  src/BuiltInTools/dotnet-watch.slnf
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationWorkspaceProvider.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-AspNetCore

#17614 Fix FXVersion manifest version bug
  src/Assets/TestProjects/SampleManifest/Sample.json
  src/Assets/TestWorkloads/manifests/Microsoft.NET.Sdk.TestWorkload/WorkloadManifest.json
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/FXVersion.cs
  src/Tests/Microsoft.NET.Restore.Tests/RestoreWithOlderNuGet.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestReaderFunctionalTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
Labels: Area-Workloads

#17512 Generate suggestions for workloads to install
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/ShowMissingWorkloads.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportWorkloads.targets
  src/Tests/Microsoft.NET.Build.Tests/WorkloadTests.cs
Labels: Area-Workloads

#17677 Don't suppress trim warnings for web projects
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: Area-ILLink

#17644 [Api Compat] Add localized resources and update tests to not assert on those resources
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/CompatDifference.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/AssertExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceComparer.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
Labels: Area-Compatibility

#17699 [preview5] Remove linker warnings for native host and COM
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#17693 Update branding for 5.0.3xx 5.0.3xx
  eng/Versions.props
Labels: Branding

#17710 Fix restore for multiple tfms in a tree for PackageValidation
  src/Compatibility/Microsoft.DotNet.PackageValidation/build/Microsoft.DotNet.PackageValidation.targets
Labels: Area-Compatibility

#17737 [release/5.0.3xx] Fix WAP proj problem by removing reliance on Microsoft.NET.Sdk.targets
  src/Assets/TestProjects/TestAppWithWapAndWpf/TestAppWithWapAndWpf.sln
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/Images/LockScreenLogo.scale-200.png
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/Images/SplashScreen.scale-200.png
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/Images/Square150x150Logo.scale-200.png
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/Images/Square44x44Logo.scale-200.png
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/Images/Square44x44Logo.targetsize-24_altform-unplated.png
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/Images/StoreLogo.png
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/Images/Wide310x150Logo.scale-200.png
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/Package.appxmanifest
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/WapProjTemplate1.assets.cache
  src/Assets/TestProjects/TestAppWithWapAndWpf/WapProjTemplate1/WapProjTemplate1.wapproj
  src/Assets/TestProjects/TestAppWithWapAndWpf/WpfApp1/App.xaml
  src/Assets/TestProjects/TestAppWithWapAndWpf/WpfApp1/App.xaml.cs
  src/Assets/TestProjects/TestAppWithWapAndWpf/WpfApp1/AssemblyInfo.cs
  src/Assets/TestProjects/TestAppWithWapAndWpf/WpfApp1/MainWindow.xaml
  src/Assets/TestProjects/TestAppWithWapAndWpf/WpfApp1/MainWindow.xaml.cs
  src/Assets/TestProjects/TestAppWithWapAndWpf/WpfApp1/WpfApp1.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.NuGet.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.Shared.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Shared.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreAppWithWap.cs
Labels: Servicing-approved

#17880 Allow user to manually set the PackageValidationBaselineVersion
  src/Compatibility/Microsoft.DotNet.PackageValidation/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/GetLastStablePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/build/Microsoft.DotNet.PackageValidation.targets
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Tasks/Common/Logger.cs
Labels: Area-Compatibility

#17930 [release/6.0-preview5] Add support for Pgo Mibc files to be used by the SDK for Preview5
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvedFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RuntimePackAssetInfo.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
Labels: Area-ReadyToRun, Servicing-consider

#17676 Remove some ILLink warning suppressions
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#17916 MSBuild server V1
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
Labels: Area-CLI, build
