Repository dotnet/sdk, pull requests merged in 2021-08, with the labels that each got.

#18655 Suppress future ILLink analyzer warnings
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
Labels: Area-ILLink

#19484 Fix unstable test
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetOsArchOptions.cs
Labels: Area-Infrastructure

#19491 Auto-trigger on internal/release/6* commits
  .vsts-ci.yml
Labels: Area-Infrastructure

#19503 Update workload list output strings
  src/Cli/dotnet/commands/dotnet-workload/list/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
Labels: Area-Workloads

#19504 Pin MSBuild, Roslyn and Nuget for package validation, also carry nuget
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/Compatibility/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
Labels: Area-Compatibility

#19492 Update HotReloadAgent to calculate updated types correctly
  src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
Labels: Area-AspNetCore

#19508 Clean up publishing in YAML
  .vsts-ci-richnav.yml
  .vsts-ci.yml
  eng/Publishing.props
  eng/build.yml
Labels: Area-Infrastructure

#19548 Fix the duplicates and self comapare in api compat runner
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleFrameworkInPackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleTFMValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Properties/AssemblyInfo.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ApiCompatRunnerTests.cs
Labels: Area-Infrastructure

#19552 [Package Validation] Don't write suppressions file if there are no suppressions
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ErrorSuppression/SuppressionEngine.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/PackageValidationLogger.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionEngineTests.cs
Labels: Area-Compatibility

#19551 Only allow dlls and executable to be passed to the ReadyToRun infrastructure
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
Labels: Area-ReadyToRun

#19502 Remove DisableFrameworkReferenceAnalyzers property
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
Labels: Area-External

#19571 Fix flaky parser tests
  src/Cli/dotnet/CommandDirectoryContext.cs
Labels: Area-Infrastructure

#19546 Update rich nav yml
  .vsts-ci-richnav.yml
  eng/build.yml
Labels: Area-Infrastructure

#19601 Fix PerfmapFormatVersion in the Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
Labels: Area-ReadyToRun, Area-NetSDK

#19270 [ASP.NET] Add support for JS modules and initializers
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props
  src/BlazorWasmSdk/Tasks/BootJsonData.cs
  src/BlazorWasmSdk/Tasks/GenerateBlazorWebAssemblyBootJson.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.JSModules.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/RazorSdk/Tasks/ApplyJsModules.cs
  src/RazorSdk/Tasks/GenerateJSModuleManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/DiscoverStaticAssets.cs
  src/RazorSdk/Tasks/StaticWebAssets/ReadStaticWebAssetsManifestFile.cs
  src/RazorSdk/Tasks/StaticWebAssets/StaticWebAsset.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/GenerateBlazorBootJsonTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/AspNetSdkBaselineTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/JsModulesIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_IncorporatesInitializersFromClassLibraries.Build.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_IncorporatesInitializersFromClassLibraries.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DiscoversJsModulesBasedOnPatterns.Build.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DiscoversJsModulesBasedOnPatterns.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_PublishesBundleToTheRightLocation.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_PublishesBundleToTheRightLocation.Publish.staticwebassets.json
Labels: Area-AspNetCore

#19667 Require individual languages opt-in to Hot Reload
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.VisualBasic.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Area-Infrastructure

#19669 Make PackageValidation uses the right roslyn when the Microsoft.Net.Compilers.Toolset is used
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Compatibility.Common.targets
Labels: Area-Infrastructure

#19705 Evaluate the FileSetFactory after performing build
  src/BuiltInTools/dotnet-watch/Filters/DotNetBuildFilter.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-Infrastructure

#19599 Update implicit global usings feature
  src/BlazorWasmSdk/Sdk/Sdk.props
  src/BlazorWasmSdk/Sdk/Sdk.targets
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateGlobalUsings.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateGlobalUsings.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateImplicitNamespaceImports.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.VisualBasic.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/EndToEnd.Tests/GivenDotNetUsesMSBuild.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_BlazorWasm.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_DotNet.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_WebApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_Worker.cs
  src/Tests/dotnet-pack.Tests/PackTests.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
  src/Tests/dotnet.Tests/GivenThatICareAboutVBApps.cs
  src/WebSdk/Web/Sdk/Sdk.props
  src/WebSdk/Web/Sdk/Sdk.targets
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.props
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.targets
Labels: Area-NetSDK

#19673 Prune the tfm-rid test pairs for fullframework.
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleTFMValidator.cs
Labels: Area-Compatibility

#19651 Remove WinExe OutputType inference
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenWeWantToRequireWindowsForDesktopApps.cs
Labels: Document for breaking changes, Area-NetSDK

#19649 Integrating source build fixes
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-Infrastructure

#19720 [Static web assets] Additional unit tests and fixes
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Tasks/StaticWebAssets/ComputeReferenceStaticWebAssetItems.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeReferencedProjectAssets.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsForCurrentProject.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsTargetPaths.cs
  src/RazorSdk/Tasks/StaticWebAssets/DiscoverStaticWebAssets.cs
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/MergeConfigurationProperties.cs
  src/RazorSdk/Tasks/StaticWebAssets/ReadStaticWebAssetsManifestFile.cs
  src/RazorSdk/Tasks/StaticWebAssets/StaticAssetsManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/StaticWebAsset.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BackCompatibilityPublish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_HostedApp_ReferencingNetStandardLibrary_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ComputeReferenceStaticWebAssetItemsTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ComputeStaticWebAssetsForCurrentProjectTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DiscoverStaticWebAssetsTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/GenerateStaticWebAssetsManifestTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/MergeConfigurationPropertiesTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ReadStaticWebAssetsManifestFileTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_CorrectlyBundlesScopedCssFiles.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_IncorporatesInitializersFromClassLibraries.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_NoDependencies_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_NoDependencies_GeneratesJsonManifestAndCopiesItToOutputFolder_NoDependencies.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_WorksWithStaticWebAssetsV1ClassLibraries.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_WorksWithStaticWebAssetsV1ClassLibraries.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_WorksWithStaticWebAssetsV1ClassLibraries.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/ScopedCss_IsBackwardsCompatible_WithPreviousVersions.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/ScopedCss_PublishIsBackwardsCompatible_WithPreviousVersions.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.TestFramework/AspNetSdkTest.cs
Labels: Area-AspNetCore

#19598 Add header to workload list command output
  src/Cli/dotnet/commands/dotnet-workload/list/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
Labels: Area-Workloads

#19545 Add workload fallback to previous feature band
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
Labels: Area-Workloads

#19604 Warn instead of error on workload garbage collection exception
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/repair/WorkloadRepairCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/MockPackWorkloadInstaller.cs
Labels: Area-Workloads

#19731 Fix publishing .NET Standard facades
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishWithoutConflicts.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishNetFrameworkApp.cs
Labels: Area-NetSDK

#19630 Update Microsoft.NET.EolTargetFrameworks.targets to add 2.1
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetEolFrameworks.cs
  src/Tests/Microsoft.NET.Clean.Tests/GivenThatWeWantToCleanAProject.cs
Labels: Servicing-approved

#19631 Update Microsoft.NET.EolTargetFrameworks.targets to add 2.1
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetEolFrameworks.cs
  src/Tests/Microsoft.NET.Clean.Tests/GivenThatWeWantToCleanAProject.cs
Labels: Servicing-approved

#19562 Don't show .NET 6 in VS2019 TargetFramework dropdown
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeManifestSupportedFrameworks.cs
Labels: Area-VS

#19516 Update all tests with odd versions of newtonsoft to the 13.0.1 version.
  src/Assets/TestProjects/BlazorMultiApp/BlazorMultipleApps.FirstClient/BlazorMultipleApps.FirstClient.csproj
  src/Assets/TestProjects/PortableTool/consoledemo.csproj
  src/Assets/TestProjects/PortableToolWithTestProject/App/consoledemo.csproj
  src/Tests/Microsoft.NET.Build.Tests/DepsFileSkipTests.cs
  src/Tests/Microsoft.NET.Build.Tests/DesignTimeBuildTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToCopyLocalDependencies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThereAreDefaultItems.cs
  src/Tests/Microsoft.NET.Build.Tests/GiventThatWeWantDesignerSupport.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  src/Tests/dotnet-restore.Tests/GivenThatIWantToRestoreApp.cs
Labels: Area-NetSDK

#19795 Turn off additional publishing conflicts
  .vsts-ci.yml
  eng/CIBuild.cmd
Labels: Area-Infrastructure

#19764 Set the EnableDynamicLoading property before importing Microsoft.PackageDependencyResolution.targets
  src/Assets/TestProjects/ComServerWithDependencies/ComServer.cs
  src/Assets/TestProjects/ComServerWithDependencies/ComServerWithDependencies.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAComServerLibrary.cs
Labels: Area-External

#19791 Disable processing in RazorSourceGenerator when no razor files are involved
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore

#19801 Update Versions.props for RC2
  eng/Versions.props
Labels: Branding

#19804 Preserve environment variable previously configured on ProcessStartInfo
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/Filters/DotNetBuildFilter.cs
  src/BuiltInTools/dotnet-watch/HotReload/ScopedCssFileHandler.cs
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/Tests/dotnet-watch.Tests/Internal/ProcessRunnerTest.cs
Labels: Area-External

#19803 Allow Razor code generation when using the Razor source generator
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-AspNetCore

#19835 Fix workload update
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Tests/dotnet-workload-search.Tests/MockWorkloadResolver.cs
  src/Tests/dotnet-workload-update.Tests/TempDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Workloads

#19882 Fix workload update
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Tests/dotnet-workload-search.Tests/MockWorkloadResolver.cs
  src/Tests/dotnet-workload-update.Tests/TempDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Workloads

#19941 Fix flaky test for workload installer logs
  src/Tests/dotnet.Tests/WindowsInstallerTests.cs
Labels: Area-Workloads

#19906 Increment the package version for Compatibility package
  src/Compatibility/Microsoft.DotNet.Compatibility/Microsoft.DotNet.Compatibility.csproj
Labels: Area-Compatibility

#19890 Follow up to global usings changes
  global.json
  src/Assets/TestProjects/BlazorHostedRID/blazorhosted/blazorhosted-rid.csproj
  src/Assets/TestProjects/HelloWorld/HelloWorld.csproj
  src/Assets/TestProjects/HelloWorldWithSubDirs/HelloWorldWithSubDirs.csproj
  src/BlazorWasmSdk/Sdk/Sdk.props
  src/BuiltInTools/dotnet-watch/Filters/DotNetBuildFilter.cs
  src/BuiltInTools/dotnet-watch/HotReload/ScopedCssFileHandler.cs
  src/Cli/dotnet/Installer/Windows/MsiPackageCache.cs
  src/Cli/dotnet/Installer/Windows/UpgradeAttributes.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Layout/toolset-tasks/toolset-tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.VisualBasic.targets
  src/Tests/EndToEnd.Tests/GivenDotNetUsesMSBuild.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/SampleGlobalTool/consoledemo.csproj
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/SampleGlobalToolWithDifferentCasing/ConsoleDemoWithCasing.csproj
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/SampleGlobalToolWithPreview/consoledemo.csproj
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/SampleGlobalToolWithShim/consoledemo.csproj
  src/Tests/Microsoft.NET.Build.Tests/WorkloadTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmBaselineTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/AspNetSdkBaselineTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ComputeReferenceStaticWebAssetItemsTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ComputeStaticWebAssetsForCurrentProjectTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DiscoverStaticWebAssetsTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/GenerateStaticWebAssetsManifestTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/MergeConfigurationPropertiesTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ReadStaticWebAssetsManifestFileTest.cs
  src/Tests/dotnet-pack.Tests/PackTests.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
  src/WebSdk/Web/Sdk/Sdk.props
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.props
Labels: Area-External

#19873 [Static web assets] Account for HintPath when we compute the build assets
  src/BlazorWasmSdk/.editorconfig
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/BrotliCompress.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorFilesToCompress.cs
  src/BlazorWasmSdk/Tasks/GZipCompress.cs
  src/BlazorWasmSdk/Tool/Program.cs
  src/RazorSdk/.editorconfig
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Tasks/StaticWebAssets/CollectStaticWebAssetsToCopy.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsTargetPaths.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/.editorconfig
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/ComputeBlazorFilesToCompressTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPwaManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/.editorconfig
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PackIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#19960 Fix flaky test for workload installer logs (#19941)
  src/Tests/dotnet.Tests/WindowsInstallerTests.cs
Labels: Area-Workloads

#19902 Cherry pick main changes
  global.json
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Layout/toolset-tasks/OverrideAndCreateBundledNETCoreAppPackageVersion.cs
  src/Tests/HelixTasks/HelixTasks.csproj
  src/Tests/Microsoft.NET.Build.Tests/WorkloadTests.cs
Labels: Area-Workloads

#19901 Fix sdkversion
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Layout/toolset-tasks/OverrideAndCreateBundledNETCoreAppPackageVersion.cs
  src/Tests/Microsoft.NET.Build.Tests/WorkloadTests.cs
Labels: Area-Workloads

#19951 Avoid assuming RSG in non-C# projects
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-AspNetCore

#20021 Avoid assuming RSG in non-C# projects (#19951)
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-External

#20029 Fix path issue when elevating from Program Files
  src/Cli/dotnet/Installer/Windows/InstallClientElevationContext.cs
  src/Cli/dotnet/Installer/Windows/WindowsUtils.cs
Labels: Area-External

#19860 Check that SDK and app archs match before setting `DOTNET_ROOT` when using `dotnet run`
  src/Assets/TestProjects/TestAppEchoDotnetRoot/Program.cs
  src/Assets/TestProjects/TestAppEchoDotnetRoot/TestAppEchoDotnetRoot.csproj
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRootEnv.cs
Labels: Area-External, Team:Runtime

#19963 Backport https://github.com/dotnet/sdk/pull/19873 to RC1
  src/BlazorWasmSdk/.editorconfig
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/BrotliCompress.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorFilesToCompress.cs
  src/BlazorWasmSdk/Tasks/GZipCompress.cs
  src/BlazorWasmSdk/Tool/Program.cs
  src/RazorSdk/.editorconfig
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Tasks/StaticWebAssets/CollectStaticWebAssetsToCopy.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsTargetPaths.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/.editorconfig
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/ComputeBlazorFilesToCompressTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPwaManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/.editorconfig
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PackIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Servicing-approved, Area-AspNetCore

#20020 Do not catch exceptions thrown as part of applying updates
  src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs
Labels: Area-External

#20067 Don't require elevation for workload list
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
Labels: Area-Workloads

#20070 Do not catch exceptions thrown as part of applying updates
  src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs
Labels: Area-External

#20019 Reduce the number of middlewares that dotnet-watch adds by default
  src/BuiltInTools/BrowserRefresh/ApplicationPaths.cs
  src/BuiltInTools/BrowserRefresh/HostingStartup.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserRefreshMiddlewareTest.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/HostingStartupTest.cs
Labels: Area-AspNetCore

#20068 Support custom install paths
  src/Cli/dotnet/Installer/Windows/InstallProperties.cs
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
Labels: Servicing-consider, Area-Workloads

#20079 Reduce the number of middlewares that dotnet-watch adds by default (#…
  src/BuiltInTools/BrowserRefresh/ApplicationPaths.cs
  src/BuiltInTools/BrowserRefresh/HostingStartup.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserRefreshMiddlewareTest.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/HostingStartupTest.cs
Labels: Area-External

#20009 Add toolset zip as source build intermediate
  eng/SourceBuild.props
Labels: Area-Infrastructure

#20063 Only show VS workload list header on windows
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
Labels: Area-Workloads

#20093 Clear hot reload specific environment variables as part of the startup hook
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/Tests/Microsoft.Extensions.DotNetDeltaApplier.Tests/StartupHookTests.cs
Labels: Area-Infrastructure

#20264 Test driven RazorSourceGenerator incrementality
  eng/Version.Details.xml
  eng/Versions.props
  src/RazorSdk/Razor.slnf
  src/RazorSdk/SourceGenerators/IncrementalValueProviderExtensions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.Helpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/RazorSourceGeneratorEventSource.cs
  src/RazorSdk/SourceGenerators/SourceGeneratorProjectItem.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorEventListener.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-DotNet Test

#20248 Support platform discriminator for workload pack records
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
Labels: Area-Workloads

#20256 [release/6.0.1xx] Disable CA1416 for ProcessExtensions
  src/Cli/Microsoft.DotNet.Cli.Utils/Extensions/ProcessExtensions.cs
Labels: Area-External

#20150 Serve aspnet-browser-refresh.js from a rooted path
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserRefreshMiddlewareTest.cs
Labels: Area-AspNetCore

#20271 Hide workload list options only relevant to machine readable
  src/Cli/dotnet/OptionForwardingExtensions.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandNuGetRestoreActionConfigOptions.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommandParser.cs
Labels: Area-Workloads

#20344 Remove explicitly configured LangVersion from RazorSDK
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-Infrastructure

#20349 Search for workloads based on description as well as id
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchCommand.cs
  src/Tests/dotnet-workload-search.Tests/GivenDotnetWorkloadSearch.cs
Labels: Area-Workloads

#20343 Remove explicitly configured LangVersion from RazorSDK
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-Infrastructure

#20209 Test driven RazorSourceGenerator incrementality
  eng/Version.Details.xml
  eng/Versions.props
  src/RazorSdk/Razor.slnf
  src/RazorSdk/SourceGenerators/IncrementalValueProviderExtensions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.Helpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/RazorSourceGeneratorEventSource.cs
  src/RazorSdk/SourceGenerators/SourceGeneratorProjectItem.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorEventListener.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-AspNetCore

#20080 [main] Avoid signing and generating unnecessary packages
  Directory.Build.props
  eng/Publishing.props
  eng/Signing.props
  src/Tests/Directory.Build.props
Labels: Area-Infrastructure

#20081 [release/6.0.1xx] Avoid signing and generating unnecessary packages
  Directory.Build.props
  eng/Publishing.props
  eng/Signing.props
  src/Tests/Directory.Build.props
Labels: Area-Infrastructure

#20102 [release/6.0.1xx] Arch-independent support for `dotnet run`
  src/Assets/TestProjects/TestAppEchoDotnetRoot/Program.cs
  src/Assets/TestProjects/TestAppEchoDotnetRoot/TestAppEchoDotnetRoot.csproj
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRootEnv.cs
Labels: Area-External, Servicing-approved

#20387 Update workload help text
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Workloads

#20378 [Razor] Reenables the ability to set a custom application part factory for an assembly.
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore

#20367 Fix null ref and client shutdown
  src/Cli/Microsoft.DotNet.Cli.Utils/DependencyProvider.cs
  src/Cli/dotnet/Installer/Windows/InstallerBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/DependencyProviderTests.cs
Labels: Servicing-consider, Servicing-approved, Area-Workloads

#20400 Allow the app to rebuild when a new scoped css file is added
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/HotReloadFileSetWatcher.cs
Labels: Area-NetSDK
