Repository dotnet/sdk, pull requests merged in 2021-04, with the labels that each got.

#16702 Disable Razor Source generators from VS Design time builds
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Servicing-approved, auto-merge

#16687 Configure DOTNET_ROOT when running apps
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-AspNetCore

#16704 Include Razor editor config for design time builds
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.razorencconfig
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore

#16726 Fix EditorConfigFiles item group in RSG
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore

#16735 Don't import illink targets for C++
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Area-ILLink

#16766 Add default feature switch.
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#16769 Update ILLink warning tests.
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#16756 Update branding for 3.1.4xx 3.1.4xx
  eng/Versions.props
Labels: Branding

#16755 Update branding for 5.0.2xx 5.0.2xx
  eng/Versions.props
Labels: Branding

#16741 Remove CLI.Utils reference from dotnet-watch
  src/BuiltInTools/dotnet-watch/Filters/DotNetBuildFilter.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/DotnetMuxer.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
Labels: Area-Watch

#16656 Avoid configuring PreserveCompilationContext=true in 6.0 apps
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.BeforeCommon.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTestLegacy.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#16717 Add some notes about how hot reload works
  src/BuiltInTools/dotnet-watch/README.md
Labels: Area-AspNetCore, Auto-Merge If Tests Pass, auto-merge

#16794 Fixing the parsing to handle the zip deploy status
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/CreateZipFile.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploymentStatus.cs
Labels: Area-WebSDK

#16691 Collapse trim warnings for package references
  src/Assets/TestProjects/TrimmedAppWithReferences/App/App.cs
  src/Assets/TestProjects/TrimmedAppWithReferences/App/App.csproj
  src/Assets/TestProjects/TrimmedAppWithReferences/App/TestPackages/_._
  src/Assets/TestProjects/TrimmedAppWithReferences/App/nuget.config
  src/Assets/TestProjects/TrimmedAppWithReferences/PackageReference/PackageReference.cs
  src/Assets/TestProjects/TrimmedAppWithReferences/PackageReference/PackageReference.csproj
  src/Assets/TestProjects/TrimmedAppWithReferences/ProjectReference/ProjectReference.cs
  src/Assets/TestProjects/TrimmedAppWithReferences/ProjectReference/ProjectReference.csproj
  src/Assets/TestProjects/TrimmedAppWithReferences/TransitiveProjectReference/TransitiveProjectReference.cs
  src/Assets/TestProjects/TrimmedAppWithReferences/TransitiveProjectReference/TransitiveProjectReference.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#16577 Eliminate build process hop by loading MSBuild.dll into CLI process
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Cli/dotnet/CommandFactory/CommandResolution/ProjectToolsCommandResolver.cs
  src/Cli/dotnet/PerformanceLogEventSource.cs
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
  src/Tests/dotnet.Tests/ParserTests/MSBuildArgumentCommandLineParserTests.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/DotnetMsbuildInProcTests.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetCleanInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetRestoreInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-CLI

#16888 Update branding for 5.0.2xx 5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  eng/common/SetupNugetSources.ps1
  eng/common/SetupNugetSources.sh
  src/Tests/UnitTests.proj
Labels: Branding

#16893 Unskip tests skipped on MacOS
  src/Tests/dotnet-watch.Tests/FileWatcherTests.cs
Labels: Area-AspNetCore

#16887 Update branding for 3.1.4xx 3.1.4xx
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/SetupNugetSources.ps1
  eng/common/SetupNugetSources.sh
  global.json
Labels: Branding

#16905 Exclude javascript files in sign check
  eng/SignCheckExclusionsFile.txt
Labels: Area-Infrastructure

#16817 Add initial version of ApiCompatibility
  .gitignore
  CODEOWNERS
  sdk.sln
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/CompatDifference.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/DifferenceType.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Filtering/ISymbolFilter.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Filtering/SymbolAccessibilityBasedFilter.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/IDiagnostic.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/IRuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/IRuleRunnerFactory.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/MapperVisitor.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblySetMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/MemberMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/NamespaceMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/TypeMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Rule.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ComparingSettings.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DefaultSymbolsEqualityComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticBag.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiferenceVisitor.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Extensions/TypeSymbolExtensions.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerFactory.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/AssemblySymbolLoaderTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Microsoft.DotNet.ApiCompatibility.Tests.csproj
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SymbolFactory.cs
Labels: Area-Compatibility

#16746 Check dependencies in workload manifests
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/FXVersion.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Strings.resx
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifest.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.NewtonsoftJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.SystemTextJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.cs.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.de.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.es.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.fr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.it.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ja.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ko.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pl.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pt-BR.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ru.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.tr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hans.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/FakeManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet-workload-install.Tests/MockManifestProvider.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#16858 Encode TargetPaths before writing them to the editorconfig
  src/Assets/TestProjects/RazorSimpleMvc/Views/Home/#F{}i+l!e.cshtml
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Tasks/EncodeRazorInputItem.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
Labels: Area-AspNetCore

#16907 Condition illink UsingTasks
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
Labels: Area-ILLink

#16947 Change query
  src/Cli/dotnet/NugetPackageInstaller/NuGetPackageInstaller.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#16836 Apply deltas to Blazor WebAssembly on app start
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
  src/BuiltInTools/BrowserRefresh/BlazorWasmHotReloadMiddleware.cs
  src/BuiltInTools/BrowserRefresh/BrowserScriptMiddleware.cs
  src/BuiltInTools/BrowserRefresh/HostingStartup.cs
  src/BuiltInTools/BrowserRefresh/Microsoft.AspNetCore.Watch.BrowserRefresh.csproj
  src/BuiltInTools/BrowserRefresh/Urls.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BlazorWasmHotReloadMiddlewareTest.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserScriptMiddlewareTest.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/HostingStartupTest.cs
Labels: Area-AspNetCore

#16653 ArPow stage 1: local source-build infrastructure
  eng/SourceBuild.props
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/source-build-patches/0003-Conditionally-include-PrecompileScript.patch
  eng/source-build-patches/0005-Add-reference-and-update-to-use-PVP.patch
  eng/source-build-patches/0006-Remove-test-projects.patch
  eng/source-build-patches/0007-Exclude-System.Text.Json-when-calling-PublishTestCli.patch
  eng/source-build-patches/0008-Patch-out-Windows-Desktop-targets.patch
  eng/source-build-patches/0009-PlatformAbstractions-is-not-produced-in-source-build.patch
  eng/source-build-patches/0010-Use-source-built-MSBuild-for-F.patch
  eng/source-build-patches/0011-Use-source-built-Nuget.patch
  eng/source-build-patches/0012-Remove-unused-Microsoft.Win32.Registry-4.6.0-ref.patch
  eng/source-build-patches/0013-Use-PVP-version-of-System.Text.Json.patch
  eng/source-build-patches/0014-vstest-build-for-.NET-6.patch
  eng/source-build-patches/0016-Lift-NETStandard.Library-to-SBRP-version.patch
  eng/source-build-patches/0018-Ensure-WebSdk-projects-finish-before-PublishNetSdks.patch
  eng/source-build-patches/0018-Remove-dotnet-hello-test-projects.patch
  src/Layout/redist/redist.csproj
Labels: Area-Infrastructure

#16972 Add overflow: scroll to diagnostics display
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-AspNetCore

#16956 Update workload alias resolution behavior
  src/Assets/TestProjects/SampleManifest/NullAliasError.json
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
Labels: Area-Workloads

#16971 Update dotnet path in developer guide
  documentation/project-docs/developer-guide.md
Labels: Auto-Merge If Tests Pass, auto-merge

#15494 [master] Implemented option to preserve the destination folder for File System publishes when Delete existing files option is selected
  src/WebSdk/Publish/Targets/PublishTargets/Microsoft.NET.Sdk.Publish.FileSystem.targets
Labels: Area-WebSDK

#14508 Adding dev comment for WebSDK publish resources
  src/WebSdk/Publish/Tasks/Properties/Resources.resx
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.cs.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.de.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.es.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.fr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.it.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ja.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ko.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pl.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pt-BR.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ru.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.tr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hans.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hant.xlf
Labels: Area-WebSDK

#16631 Use Crossgen2 by default for R2R publishing
  src/Layout/toolset-tasks/OverrideAndCreateBundledNETCoreAppPackageVersion.cs
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
Labels: Area-ReadyToRun

#16865 Make TrimmerDefaultAction public
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
  src/WebSdk/Web/Sdk/Sdk.props
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: Area-ILLink

#17010 Update branding to preview 5
  eng/Versions.props
Labels: Auto-Merge If Tests Pass, auto-merge

#17008 Handle exceptions when delta applied and send acknowledgement
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
Labels: Area-AspNetCore

#17009 Remove workarounds in Crossgen2 tests
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
Labels: Area-ReadyToRun

#17017 Handle exceptions when delta applied and send acknowledgement (#17008)
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
Labels: Area-AspNetCore, Servicing-approved

#17019 [preview4] Make TrimmerDefaultAction public
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
  src/WebSdk/Web/Sdk/Sdk.props
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: Area-ILLink

#17050 Fix SuppressTrimAnalysisWarnings
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishTest.cs
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: Area-ILLink

#17051 [preview4] Fix SuppressTrimAnalysisWarnings
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishTest.cs
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: Area-ILLink

#17053 Fix up delta apply acknowledgement and add logging
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-AspNetCore, Servicing-approved

#16928 Optional workloads: Utilities
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/DependencyProvider.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Extensions/ProcessExtensions.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Interop.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Cli/Microsoft.DotNet.Cli.Utils/Windows.cs
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/DependencyProviderTests.cs
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/ProcessExtensionsTests.cs
Labels: Area-Workloads

#17083 [dotnet-watch] Fix dotnet-watch to account for absolute launchUrls in launchSettings.json
  src/BuiltInTools/dotnet-watch/Filters/LaunchBrowserFilter.cs
Labels: Area-AspNetCore, Servicing-approved

#17064 Upgrade TP, Update coverage tests
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Area-DotNet Test

#16932 [Razor] Introduce razor language version 6.0
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-AspNetCore

#16927 Change default DebugType from 'pdbonly' to 'full'
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.props
Labels: Area-WebSDK

#17042 Fix WAP proj problem by removing reliance on Microsoft.NET.Sdk.targets
  src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.NuGet.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.Shared.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Shared.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Auto-Merge If Tests Pass, auto-merge

#17121 Add a workaround for file contention and empty file reads
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
Labels: Area-AspNetCore, Servicing-approved

#16414 Workload resolver caching
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/NETCoreSdkResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/CachingWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/WorkloadSdkResolver.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAWebApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishToClickOnce.cs
Labels: Area-SdkResolvers

#17203 Pin compiler dependency in Razor source generator
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
Labels: Area-AspNetCore

#17208 Adding work around for sdk root workload install issue
  src/Resolvers/Microsoft.DotNet.NativeWrapper/EnvironmentProvider.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#17230 Use separate copies of dependencies in source generators
  src/Layout/redist/targets/GenerateLayout.targets
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore

#17258 Add OneLocBuild to 5.0.3xx
  eng/build.yml
Labels: Area-Infrastructure

#16840 Embed project.assets.json in binlog
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets
Labels: Area-NetSDK

#17304 [Compatibility] Fix symbol comparison to not include ref/out modifiers and nullable annotations
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DefaultSymbolsEqualityComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Extensions/SymbolExtensions.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Extensions/TypeSymbolExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
Labels: Area-Compatibility
