Repository dotnet/sdk, pull requests merged in 2021-10, with the labels that each got.

#21561 Fix over-warning bug when specifying runtime CLI option on dotnet run
  src/Cli/dotnet/commands/dotnet-run/RunCommandParser.cs
  src/Tests/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
Labels: Area-CLI

#21623 Unconditionally prevent global usings file from being recorded in FileWrites
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateGlobalUsings.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_DotNet.cs
Labels: Area-AspNetCore

#21664 Backport to 6.0 GA `Add support for localized component names msbuild property`
  src/RazorSdk/SourceGenerators/RazorSourceGenerationOptions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.Helpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.CodeGeneration.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Tasks/SdkRazorGenerate.cs
  src/RazorSdk/Tool/GenerateCommand.cs
Labels: Area-Infrastructure, Area-AspNetCore

#21189 Make workload descriptions localizable
  src/Assets/TestProjects/SampleManifest/Sample.loc.json
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadOptionsExtensions.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.Localization.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.NewtonsoftJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.SystemTextJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/FakeManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
  src/Tests/dotnet-workload-install.Tests/MockManifestProvider.cs
  src/Tests/dotnet-workload-update.Tests/TempDirectoryWorkloadManifestProviderTests.cs
Labels: Area-Workloads

#21659 Hide RazorGeneral rule file properties
  src/RazorSdk/Targets/Rules/RazorGeneral.xaml
Labels: Area-AspNetCore

#21704 Update dead link in runtime-configuration-file.md
  documentation/specs/runtime-configuration-file.md
Labels: Area-Infrastructure

#21429 Make aspnet-browser-refresh.js tolerate duplication insertions
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-Infrastructure, Area-AspNetCore

#21663 Backport to Main `Add support for localized component names msbuild property`
  src/RazorSdk/SourceGenerators/RazorSourceGenerationOptions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.Helpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.CodeGeneration.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Tasks/SdkRazorGenerate.cs
  src/RazorSdk/Tool/GenerateCommand.cs
Labels: Area-Infrastructure, Area-AspNetCore

#21757 Update branding for 3.1.415
  eng/Versions.props
Labels: Area-Infrastructure

#21759 Update branding for 5.0.403
  eng/Versions.props
Labels: Area-Infrastructure

#21803 [release/6.0.1xx] Add CPD for installer
  eng/Version.Details.xml
Labels: Area-Infrastructure

#21361 Fix Bash shebang for scripts to run under FreeBSD
  build.sh
  build/RunTestsOnHelix.sh
  build/sdktests.sh
  eng/dogfood.sh
  eng/restore-toolset.sh
  restore.sh
  test.sh
Labels: Area-Infrastructure
