Repository dotnet/sdk, pull requests merged in 2021-02, with the labels that each got.

#15625 Update to 5.0.3xx branding
  eng/Versions.props
Labels: Area-Infrastructure, Auto-Merge If Tests Pass, auto-merge

#15617 [release/5.0.3xx] Fix flaky dotnet test tests
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsprojWithCorrectTestRunParameters.cs
  src/Tests/dotnet-vstest.Tests/VSTestTests.cs
Labels: Area-DotNet Test

#15750 Loc update
  src/BuiltInTools/dotnet-watch/xlf/Resources.cs.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.de.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.es.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.fr.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.it.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ja.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ko.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.pl.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.pt-BR.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ru.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.tr.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.zh-Hans.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.cs.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.de.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.es.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.fr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.it.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ja.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pt-BR.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ru.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hans.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hant.xlf
Labels: Area-Infrastructure

#15770 Default InvariantGlobalization in Blazor WASM
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
Labels: Area-AspNetCore

#15695 Revert 'Opt into IncludePackageReferencesDuringMarkupCompilation'
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsDesktopProject.cs
Labels: Servicing-approved

#15752 Clean up Razor and Blazor WASM Sdk tests
  src/Assets/TestPackages/PackageLibraryDirectDependency/PackageLibraryDirectDependency/PackageLibraryDirectDependency.csproj
  src/Assets/TestProjects/BlazorHosted/blazorhosted/blazorhosted.csproj
  src/Assets/TestProjects/BlazorHosted/blazorwasm/blazorwasm.csproj
  src/Assets/TestProjects/BlazorHostedRID/blazorhosted/blazorhosted-rid.csproj
  src/Assets/TestProjects/BlazorHostedRID/blazorwasm/blazorwasm.csproj
  src/Assets/TestProjects/BlazorMultiApp/BlazorMultipleApps.FirstClient/BlazorMultipleApps.FirstClient.csproj
  src/Assets/TestProjects/BlazorMultiApp/BlazorMultipleApps.SecondClient/BlazorMultipleApps.SecondClient.csproj
  src/Assets/TestProjects/BlazorMultiApp/BlazorMultipleApps.Server/BlazorMultipleApps.Server.csproj
  src/Assets/TestProjects/BlazorWasmMinimal/blazorwasm-minimal.csproj
  src/Assets/TestProjects/BlazorWasmWithLibrary/blazorwasm/blazorwasm.csproj
  src/Assets/TestProjects/RazorAppWithP2PReference/AnotherClassLib/AnotherClassLib.csproj
  src/Assets/TestProjects/RazorAppWithP2PReference/AppWithP2PReference/AppWithP2PReference.csproj
  src/Assets/TestProjects/RazorAppWithP2PReference/ClassLibrary/ClassLibrary.csproj
  src/Assets/TestProjects/RazorAppWithPackageAndP2PReference/AnotherClassLib/AnotherClassLib.csproj
  src/Assets/TestProjects/RazorAppWithPackageAndP2PReference/AppWithPackageAndP2PReference/AppWithPackageAndP2PReference.csproj
  src/Assets/TestProjects/RazorAppWithPackageAndP2PReference/AppWithPackageAndP2PReference/nuget.config
  src/Assets/TestProjects/RazorAppWithPackageAndP2PReference/ClassLibrary/ClassLibrary.csproj
  src/Assets/TestProjects/RazorClassLibrary/ClassLibrary.csproj
  src/Assets/TestProjects/RazorComponentApp/ComponentApp.csproj
  src/Assets/TestProjects/RazorMvcWithComponents/MvcWithComponents.csproj
  src/Assets/TestProjects/RazorSimpleMvc/SimpleMvc.csproj
  src/Assets/TestProjects/RazorSimpleMvc50/SimpleMvc50.csproj
  src/Assets/TestProjects/RazorSimplePages/SimplePages/SimplePages.csproj
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmSdkTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildLazyLoadTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmCompressionTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPwaManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ApplicationPartDiscoveryIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntrospectionTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponents31IntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponentsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/DesignTimeBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/Microsoft.NET.Sdk.Razor.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTestLegacy.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PackIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.TestFramework/AspNetSdkTest.cs
Labels: Area-AspNetCore

#15702 Adding default feature switch for CustomResourceTypesSupport
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Auto-Merge If Tests Pass

#15743 Update branding for 3.1.4xx 3.1.4xx
  .vsts-ci.yml
  NuGet.config
  eng/Versions.props
Labels: Branding

#15756 Add support for source generators in Razor compiler/SDK
  sdk.sln
  src/Assets/TestProjects/RazorMvcWithComponents/MvcWithComponents.csproj
  src/Assets/TestProjects/RazorMvcWithComponents/Views/Home/FileName.cshtml
  src/Assets/TestProjects/RazorSimpleMvc50/SimpleMvc50.csproj
  src/Layout/redist/targets/GenerateLayout.targets
  src/RazorSdk/SourceGenerators/ConfigureRazorCodeGenerationOptions.cs
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
  src/RazorSdk/SourceGenerators/RazorDiagnostics.cs
  src/RazorSdk/SourceGenerators/RazorInputItem.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/SourceGeneratorProjectItem.cs
  src/RazorSdk/SourceGenerators/SourceTextRazorSourceDocument.cs
  src/RazorSdk/SourceGenerators/StaticCompilationTagHelperFeature.cs
  src/RazorSdk/SourceGenerators/StaticTagHelperFeature.cs
  src/RazorSdk/SourceGenerators/TagHelperSerializer.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.CodeGeneration.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Compilation.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPwaManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/DesignTimeBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTest50.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTestLegacy.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
Labels: Area-AspNetCore

#15821 Use Process.Kill(true) instead of KillTree
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/BuiltInTools/dotnet-watch/ProcessExtensions.cs
  src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
Labels: Area-AspNetCore

#15838 have style analyzers version with the compiler
  src/Layout/redist/redist.csproj
Labels: auto-merge

#15843 have style analyzers version with the compiler
  eng/Versions.props
  src/Layout/redist/redist.csproj
Labels: auto-merge

#15855 Set up targets and props for AOT compilation
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
Labels: Area-AspNetCore

#15912 Use TagHelperDiscoveryFilter when performing tag helper discovery
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/StaticCompilationTagHelperFeature.cs
Labels: Area-AspNetCore

#15914 Skip flaky test Publish_WithBuildReferencesDisabled_CopiesStaticWebAssetsToDestinationFolder
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore, Auto-Merge If Tests Pass, auto-merge

#15858 Adding Support for Zip Deploy
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/ZipDeploy/ZipDeployerTaskTests.cs
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/ZipDeploy/ZipDeploymentStatusTests.cs
  src/WebSdk/Publish/Tasks/Properties/Resources.Designer.cs
  src/WebSdk/Publish/Tasks/Properties/Resources.resx
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.cs.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.de.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.es.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.fr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.it.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ja.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ko.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pl.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pt-BR.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ru.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.tr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hans.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hant.xlf
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/DefaultHttpClient.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/DeployStatus.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpClientHelpers.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpResponseMessageForStatusCode.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpResponseMessageWrapper.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/IHttpClient.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/IHttpResponse.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploymentStatus.cs
Labels: Area-WebSDK

#15909 Propagate generator's cancellation token to Parallel.For
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore, Auto-Merge If Tests Pass, auto-merge

#15837 Add test for trim mode link
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#15920 Respect IsConcurrentBuild flag from compiler
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore, Auto-Merge If Tests Pass, auto-merge

#15958 Remove unneeded file writes in Razor source generator
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
Labels: Area-AspNetCore

#15529 Launch Crossgen2 via explicitly specified .NET host
  src/Tasks/Common/MetadataKeys.cs
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
Labels: Area-ReadyToRun

#15967 blazor-wasm: Fix dest path when copying versioned dotnet.js
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
Labels: Area-AspNetCore

#15970 Address feedback from RSG caching review
  src/RazorSdk/SourceGenerators/MetadataReferenceExtensions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore

#15981 [Razor] Adds CSS isolation support for MVC views and pages
  src/Assets/TestProjects/RazorMvcWithComponents/Components/Counter.razor
  src/Assets/TestProjects/RazorMvcWithComponents/Components/Counter.razor.css
  src/Assets/TestProjects/RazorMvcWithComponents/Views/Home/Index.cshtml
  src/Assets/TestProjects/RazorMvcWithComponents/Views/Home/Index.cshtml.css
  src/Assets/TestProjects/RazorSimpleMvc/Views/Home/About.cshtml.css
  src/Assets/TestProjects/RazorSimpleMvc/Views/Home/Contact.cshtml.css
  src/Assets/TestProjects/RazorSimpleMvc/Views/Home/Index.cshtml.css
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.targets
  src/RazorSdk/Tasks/ApplyCssScopes.cs
  src/RazorSdk/Tasks/DiscoverDefaultScopedCssItems.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ApplyCssScopesTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/DiscoverDefaultScopedCssItemsTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#15998 Fix EmitCompilerGeneratedFiles property in compilation
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Compilation.targets
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
Labels: Area-AspNetCore

#16023 Remove unused compiler property
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore

#15944 Allow runtime packs to not be downloaded
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
Labels: Area-NetSDK

#16021 Suppress illink roslyn analyzer warnings
  eng/Version.Details.xml
  eng/Versions.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#16008 Append hosting startup variable to existing variable if set
  src/BuiltInTools/dotnet-watch/LaunchBrowserFilter.cs
Labels: Area-AspNetCore

#16057 Clean up SDK code driving Crossgen2 compilation
  src/Tasks/Common/MetadataKeys.cs
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
Labels: Area-ReadyToRun

#16076 Ensure Razor design time targets are correctly wired up
  src/Assets/TestProjects/RazorComponentApp/ComponentApp.csproj
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Component.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntrospectionTest.cs
Labels: Area-AspNetCore

#16110 Correctly resolve metadata reference from current assembly
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore
