Repository dotnet/sdk, pull requests merged in 2021-03, with the labels that each got.

#16081 Update branding for 5.0.2xx 5.0.2xx
  eng/Versions.props
Labels: Branding

#16080 Update branding for 3.1.1xx 3.1.1xx
  eng/Versions.props
Labels: Branding

#16079 Update branding for 3.1.4xx 3.1.4xx
  eng/Versions.props
Labels: Branding

#16094 Enable additional ways to opt in to trimming
  eng/Version.Details.xml
  eng/Versions.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#16096 Respect EmitSymbols in composite mode
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
Labels: Area-ReadyToRun

#16114 Add support for Zip Deploy in WebSDK
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/ZipDeploy/ZipDeployerTaskTests.cs
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/ZipDeploy/ZipDeploymentStatusTests.cs
  src/WebSdk/Publish/Tasks/Properties/Resources.Designer.cs
  src/WebSdk/Publish/Tasks/Properties/Resources.resx
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.cs.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.de.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.es.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.fr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.it.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ja.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ko.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pl.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pt-BR.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ru.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.tr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hans.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hant.xlf
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/DefaultHttpClient.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/DeployStatus.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpClientHelpers.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpResponseMessageForStatusCode.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpResponseMessageWrapper.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/IHttpClient.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/IHttpResponse.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploymentStatus.cs
Labels: Area-WebSDK

#16017 Fix: dotnet-new locale is not correctly set
  src/Cli/dotnet/commands/dotnet-new/NewCommandShim.cs
Labels: Area-Templates

#16059 Trim down Razor SDK size
  src/Layout/redist/targets/GenerateLayout.targets
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Configuration.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Tasks/Microsoft.NET.Sdk.Razor.Tasks.csproj
  src/RazorSdk/Tool/Microsoft.NET.Sdk.Razor.Tool.csproj
Labels: Area-AspNetCore

#16214 When discovering tag helpers, use the codegened assembly
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore

#16210 Update expected illink warnings
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#16230 Remove Windows only condition from test
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
Labels: Area-NetSDK

#16251 Support for performance improvement effort
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Cli/dotnet/Program.cs
  src/Cli/dotnet/Telemetry/AllowListToSendFirstAppliedOptions.cs
  src/Cli/dotnet/Telemetry/AllowListToSendFirstArgument.cs
  src/Cli/dotnet/Telemetry/IParseResultLogRule.cs
  src/Cli/dotnet/Telemetry/TelemetryFilter.cs
  src/Cli/dotnet/Telemetry/TopLevelCommandNameAndOptionToLog.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurer.cs
  src/Tests/dotnet.Tests/TelemetryCommandTest.cs
  src/Tests/dotnet.Tests/TelemetryFilterTest.cs
Labels: Servicing-approved

#16098 Add new properties for analyzer
  eng/Version.Details.xml
  eng/Versions.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#16168 Unify app and view assembly for Razor
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Compilation.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Configuration.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishIncrementally.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntrospectionTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponentsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTest50.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PackIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PublishIntegrationTest.cs
Labels: Area-AspNetCore

#16273 Append file name to test asset
  src/Tests/Microsoft.NET.TestFramework/TestAssetsManager.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#16297 Update branding for 5.0.1xx 5.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalTool/consoledemo.csproj
  src/Tests/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalToolWithDifferentCasing/ConsoleDemoWithCasing.csproj
  src/Tests/Microsoft.DotNet.ToolPackage.Tests/SampleGlobalToolWithShim/consoledemo.csproj
  src/Tests/Microsoft.DotNet.ToolPackage.Tests/ToolPackageInstallerTests.cs
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/EndToEnd/FolderPublish50.cs
  src/Tests/dotnet-msbuild.Tests/GivenDotnetMSBuildBuildsProjects.cs
Labels: Branding

#16276 Merge internal changes for 5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Branding

#16316 Changing the default names for default profiles
  sdk.sln
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
  src/WebSdk/Publish/Targets/PublishProfiles/FileSystem.pubxml
  src/WebSdk/Publish/Targets/PublishProfiles/MSDeploy.pubxml
  src/WebSdk/Publish/Targets/PublishProfiles/MSDeployPackage.pubxml
Labels: Area-WebSDK

#16358 Adding default publish profiles
  sdk.sln
  src/WebSdk/Publish/Targets/PublishProfiles/Default.pubxml
  src/WebSdk/Publish/Targets/PublishProfiles/DefaultMSDeploy.pubxml
  src/WebSdk/Publish/Targets/PublishProfiles/DefaultMSDeployPackage.pubxml
  src/WebSdk/Publish/Targets/PublishProfiles/DefaultZipDeploy.pubxml
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/CreateZipFile.cs
Labels: Area-WebSDK

#16327 Change linker defaults to "link" with warnings
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
  src/WebSdk/Web/Sdk/Sdk.props
Labels: Area-ILLink

#16382 Fix condition for setting RelatedAssemblyAttribute
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Configuration.targets
Labels: Area-AspNetCore

#16434 Workaround O# path bug
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/RazorSdk/Razor.slnf
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
Labels: Area-AspNetCore

#16468 Suppress generating source checksum attribute
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore

#16453 Add test project for Razor source generator
  sdk.sln
  src/RazorSdk/SourceGenerators/Properties/AssemblyInfo.cs
  src/RazorSdk/SourceGenerators/SourceTextRazorSourceDocument.cs
  src/RazorSdk/SourceGenerators/SourceTextSourceLineCollection.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/SourceGeneratorProjectItemTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/SourceTextSourceLineCollectionTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestAdditionalText.cs
Labels: Area-AspNetCore

#16486 Enable OneLocBuild in pipeline
  eng/build.yml
Labels: Area-NetSDK

#16507 Add support for updating scoped css files
  src/BuiltInTools/BrowserRefresh/HostingFilter.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/HotReload/HotReload.cs
  src/BuiltInTools/dotnet-watch/HotReload/ScopedCssFileHandler.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-AspNetCore

#16528 Update DiaSymReader library path for crossgen.exe
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: Area-ReadyToRun

#16531 Add ETW start and stop events for file changes
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/HotReload.cs
  src/BuiltInTools/dotnet-watch/HotReload/HotReloadEventSource.cs
  src/BuiltInTools/dotnet-watch/HotReload/ScopedCssFileHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/StaticFileHandler.cs
Labels: Auto-Merge If Tests Pass, auto-merge

#16547 Update branding to preview 4
  eng/Versions.props
Labels: Area-Infrastructure

#16502 Add support for caching generated SourceTexts
  src/RazorSdk/SourceGenerators/RazorInputItem.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore

#16623 Hide RazorExtension rule file properties
  src/RazorSdk/Targets/Rules/RazorExtension.xaml
Labels: Area-AspNetCore

#16648 Disable Razor source generator for design time builds
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore, Servicing-approved
