Repository dotnet/sdk, pull requests merged in 2021-11, with the labels that each got.

#22103 Add a target and tests for re-generating scoped css files as part of hot reload
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
Labels: Area-AspNetCore

#22337 Update branding for 6.0.200
  eng/Versions.props
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure

#22350 [Port to 6.0.2xx] Fix run warning output formatting issue
  src/Cli/dotnet/commands/dotnet-run/Program.cs
Labels: Area-CLI

#22251 Fix nuget authenticated feed interaction
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
Labels: Area-Workloads

#22444 Update branding for 5.0.210
  eng/Versions.props
Labels: Area-Infrastructure

#22443 Update branding for 3.1.416
  eng/Versions.props
Labels: Area-Infrastructure

#22180 Add support for `--arch`
  src/Assets/TestProjects/VSTestForwardDotnetRootEnvironmentVariables/Tests.cs
  src/Assets/TestProjects/VSTestForwardDotnetRootEnvironmentVariables/VSTestForwardDotnetRootEnvironmentVariables.csproj
  src/Cli/dotnet/commands/dotnet-test/VSTestForwardingApp.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestForwardDotnetRootEnvironmentVariables.cs
Labels: Area-DotNet Test

#22442 Update Versions.props for 6.0.101 and servicing
  eng/Versions.props
Labels: Area-Infrastructure

#22445 Update branding for 5.0.404
  eng/Versions.props
Labels: Area-Infrastructure

#22364 Fix version parsing that depended on current culture
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/FXVersion.cs
Labels: Area-NetSDK

#22463 [Razor] Unskip Build_WithCustomOutputPath_Works
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
Labels: Area-AspNetCore

#22381 Re-enable a couple of old tests that were left disabled.
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatAPublishedDepsJsonShouldContainVersionInformation.cs
  src/Tests/dotnet.Tests/PackagedCommandTests.cs
Labels: Area-Infrastructure

#22331 Add tool install implicit RIDs
  src/Cli/dotnet/ShellShim/ShellShimTemplateFinder.cs
  src/Cli/dotnet/ToolPackage/IToolPackage.cs
  src/Cli/dotnet/ToolPackage/ToolPackageInstance.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/ToolPackageInstallerTests.cs
  src/Tests/Microsoft.DotNet.ShellShim.Tests/ShellShimRepositoryTests.cs
  src/Tests/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageInstallerMock.cs
  src/Tests/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageMock.cs
  src/Tests/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageStoreMock.cs
Labels: Area-Tools

#22458 Remove OpCodes from event source to make events appear correctly
  src/RazorSdk/SourceGenerators/RazorSourceGeneratorEventSource.cs
Labels: Area-AspNetCore

#22472 Add disable build server CLI option
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/commands/dotnet-build/BuildCommandParser.cs
  src/Cli/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/Cli/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetRestoreInvocation.cs
Labels: Area-CLI

#22460 Update the target framework for the test projects
  src/Assets/TestProjects/WebApp/web.csproj
  src/Assets/TestProjects/XUnitTestProject/XUnitTestProject.csproj
  src/Assets/TestProjects/XunitCore/XunitCore.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAUnitTestProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAWebApp.cs
Labels: Area-Infrastructure

#22426 Cleanup NoWarn duplication by moving its handling to the Suppression Engine
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticBag.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ErrorSuppression/SuppressionEngine.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Extensions/CollectionsExtensions.cs
  src/Compatibility/Microsoft.DotNet.Compatibility/CompatibilityLogger.cs
  src/Compatibility/Microsoft.DotNet.Compatibility/ValidatePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/BaselinePackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleFrameworkInPackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleTFMValidator.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionEngineTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ApiCompatRunnerTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/BaseLineVersionValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/CompatibleFrameworkValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/CompatibleFrameworksInPackageTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
Labels: Area-Compatibility

#20865 Switch to 1ES servicing pools on 5.0.4xx
  .vsts-ci.yml
Labels: Area-Infrastructure

#22470 Ensure references added using "Reference" are correctly copied in BlazorWASM projects
  src/BlazorWasmSdk/BlazorWasmSdk.slnf
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/ComputeBlazorBuildAssetsTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
Labels: Area-AspNetCore

#22522 Merging internal commits for release/5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#22523 Merging internal commits for release/5.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#22497 Remove -r parameter for dotnet test, and change -a parameter to be shorthand for --arch, instead of --test-adapter-path
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Area-Infrastructure

#22446 Treat SDK previews as separate workload feature bands
  eng/Versions.props
  src/Cli/dotnet/commands/dotnet-workload/install/IInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallRecords/SdkFeatureBand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadOptionsExtensions.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkFeatureBand.cs
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkFeatureBandTests.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
Labels: Area-Workloads

#22616 Use MessageImportance.Low for log statements.
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorFilesToCompress.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
  src/BlazorWasmSdk/Tasks/GenerateBlazorWebAssemblyBootJson.cs
  src/RazorSdk/Tasks/GenerateJSModuleManifest.cs
  src/RazorSdk/Tasks/GenerateV1StaticWebAssetsManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/CollectStaticWebAssetsToCopy.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeReferenceStaticWebAssetItems.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsForCurrentProject.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsTargetPaths.cs
  src/RazorSdk/Tasks/StaticWebAssets/DefineStaticWebAssets.cs
  src/RazorSdk/Tasks/StaticWebAssets/DiscoverStaticWebAssets.cs
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/MergeConfigurationProperties.cs
Labels: Area-AspNetCore

#22542 Ensure references added using "Reference" are correctly copied in BlazorWASM projects
  eng/Version.Details.xml
  eng/Versions.props
  src/BlazorWasmSdk/BlazorWasmSdk.slnf
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/ComputeBlazorBuildAssetsTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
Labels: Servicing-approved, Area-AspNetCore

#22573 Do not advertise workload updates on run output
  src/Cli/dotnet/commands/RestoringCommand.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
Labels: Area-Workloads

#22557 Tell user when workload has already been installed
  eng/Version.Details.xml
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
Labels: Area-Workloads

#22254 Remove reference to PlatformAbstractions
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Servicing-approved

#22638 Use MessageImportance.Low for log statements.
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorFilesToCompress.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
  src/BlazorWasmSdk/Tasks/GenerateBlazorWebAssemblyBootJson.cs
  src/RazorSdk/Tasks/GenerateJSModuleManifest.cs
  src/RazorSdk/Tasks/GenerateV1StaticWebAssetsManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/CollectStaticWebAssetsToCopy.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeReferenceStaticWebAssetItems.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsForCurrentProject.cs
  src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsTargetPaths.cs
  src/RazorSdk/Tasks/StaticWebAssets/DefineStaticWebAssets.cs
  src/RazorSdk/Tasks/StaticWebAssets/DiscoverStaticWebAssets.cs
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/MergeConfigurationProperties.cs
Labels: Area-AspNetCore

#22674 Bump system command line source build version
  NuGet.config
  eng/Version.Details.xml
Labels: Area-Infrastructure

#22666 Don't split collect command into multiple collect commands
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Area-Infrastructure

#22284 Switch the non-windows test builds to also run helix and non-helix in parallel.
  .vsts-ci.yml
  eng/build.yml
  eng/runHelixAndNonHelixInParallelNonWindows.ps1
Labels: Area-Infrastructure

#22684 Fix version comparison for dotnet tool install
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
Labels: Area-Tools

#22713 set encoding to UTF8 in case output is redirected (sdk-wide)
  src/Cli/dotnet/Program.cs
Labels: Area-Infrastructure

#22750 Fix ILLink test instalibility
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#22636 Change messages for ILLink
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishTestUtils.cs
Labels: Area-ILLink

#22760 Remove expected warning from linker test as it's no longer expected.
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#22722 Merge pull request #22284 from dotnet/marcpopMSFT-parallelnonwindows
  .vsts-ci.yml
  eng/build.yml
  eng/runHelixAndNonHelixInParallelNonWindows.ps1
Labels: Area-Infrastructure
