Repository dotnet/sdk, pull requests merged in 2021-06, with the labels that each got.

#17921 Tweak API compat messages
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Package.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/BaseLineVersionValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/CompatibleFrameworkValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Microsoft.DotNet.PackageValidation.Tests.csproj
Labels: Area-Compatibility

#18013 Update branding for 3.1.1xx 3.1.1xx
  eng/Versions.props
Labels: Branding

#18015 Update branding for 3.1.4xx 411
  eng/Versions.props
Labels: Branding

#18016 Update branding for 5.0.3xx to 302
  eng/Versions.props
Labels: Branding

#18000 MSBuild property for the AutoreleasePool feature.
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-External

#18039 Prevent infinite loops in wasm hot reload
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/Filters/LaunchBrowserFilter.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
Labels: Area-AspNetCore

#18043 Remove hot restart until we can stabilize ALC issues
  sdk.sln
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/BuiltInTools/HotRestart/Microsoft.Extensions.HotRestart.csproj
  src/BuiltInTools/HotRestart/Program.cs
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.slnf
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-AspNetCore

#18065 Update restart gesture to be Ctrl+Shift+R
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.slnf
Labels: Area-AspNetCore

#18052 Use task to get around unexpected batching behavior
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GetPublishItemsOutputGroupOutputsTests.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/GetPublishItemsOutputGroupOutputs.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenWeWantToRequireWindowsForDesktopApps.cs
Labels: Servicing-approved

#18072 Support for preview features
  eng/dogfood.sh
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.TestFramework/AssemblyInfo.cs
Labels: Area-NetSDK, auto-merge

#18404 Fix splitting of DOTNETSDK_WORKLOAD_PACK_ROOTS environment variable
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
Labels: Area-Workloads

#18185 Add Validation suppression engine
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ErrorSuppression/Suppression.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ErrorSuppression/SuppressionEngine.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/BaselinePackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleFrameworkInPackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleTFMValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/IPackageLogger.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/PackageValidationLogger.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/build/Microsoft.DotNet.PackageValidation.targets
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Compatibility/compatibility.slnf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionEngineTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/BaseLineVersionValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/TestLogger.cs
Labels: Area-Compatibility

#18440 [Preview 6] Add Package Validation suppression engine
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ErrorSuppression/Suppression.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ErrorSuppression/SuppressionEngine.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/BaselinePackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleFrameworkInPackageValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/CompatibleTFMValidator.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/IPackageLogger.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/PackageValidationLogger.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/build/Microsoft.DotNet.PackageValidation.targets
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Compatibility/compatibility.slnf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionEngineTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/BaseLineVersionValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/TestLogger.cs
Labels: Area-Compatibility, Servicing-approved

#18451 Add StrictMode to MembersMustExist rule
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.Strict.cs
Labels: Area-Compatibility

#18411 Migrate Razor source generator incremental API
  src/RazorSdk/SourceGenerators/IncrementalValueProviderExtensions.cs
  src/RazorSdk/SourceGenerators/MetadataReferenceExtensions.cs
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
  src/RazorSdk/SourceGenerators/RazorInputItem.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerationContext.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerationOptions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.Helpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.SourceTexts.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.TagHelperDiscovery.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.TagHelpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/SourceGeneratorProjectItem.cs
  src/RazorSdk/SourceGenerators/StaticCompilationTagHelperFeature.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/SourceGeneratorProjectItemTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponentsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
Labels: Area-AspNetCore

#18498 Escaping the ConnectionString values for Migrations
  src/WebSdk/Publish/Tasks/Tasks/GenerateEFSQLScripts.cs
Labels: Area-WebSDK

#18499 Escaping the ConnectionString values for Migrations
  src/WebSdk/Publish/Tasks/Tasks/GenerateEFSQLScripts.cs
Labels: Area-WebSDK

#18537 Pull language version from compilation parse options
  src/RazorSdk/SourceGenerators/RazorSourceGenerationOptions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.Helpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore

#18526 Disable "MSBuild Server v1" by default
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
Labels: Servicing-approved, Servicing-consider

#18533 [API Compat] Add support to specify custom names for left and right on errors
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/MetadataInformation.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ComparingSettings.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerContext.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerFactory.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CustomSideNameTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/CompatibleFrameworksInPackageTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
Labels: Area-Compatibility

#18567 Only run incremental RSG on .razor/.cshtml files
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore

#18571 Process all TagHelpers from compilation at once
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore
