Repository dotnet/sdk, pull requests merged in 2021-09, with the labels that each got.

#20405 Doc for build deb and rpm locally
  documentation/general/build-deb-rpm-locally.md
Labels: Area-Infrastructure

#20417 Allow the app to rebuild when a new scoped css file is added
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/HotReloadFileSetWatcher.cs
Labels: Area-NetSDK

#20447 [Razor][Backport] Reenables the ability to set a custom application part factory for an assembly. (#20378)
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-AspNetCore

#20451 [Razor] Allow optionally specifying an alternative package path when packing
  src/RazorSdk/Tasks/GenerateStaticWebAsssetsPropsFile.cs
Labels: Area-AspNetCore

#20424 Do not clear DOTNET_MODIFIABLE_ASSEMBLIES in startup hook
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/Tests/Microsoft.Extensions.DotNetDeltaApplier.Tests/StartupHookTests.cs
Labels: Area-Infrastructure

#20468 Fix bad merge re-apply de34d98c4f282888a257b2941c46e5baaa2cc2f9
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-Infrastructure

#20484 Add platform descriminator to workload records
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallRecords/RegistryWorkloadInstallationRecordRepository.cs
Labels: Area-Workloads

#20465 [Razor] [Backport] Allow optionally specifying an alternative package path when packing (#20451)
  src/RazorSdk/Tasks/GenerateStaticWebAsssetsPropsFile.cs
Labels: Area-AspNetCore

#20412 dotnet-watch ux changes
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/RudeEditPreference.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-Infrastructure

#20541 dotnet-watch ux changes (#20412)
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/RudeEditPreference.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-AspNetCore

#20542 Do not clear DOTNET_MODIFIABLE_ASSEMBLIES in startup hook (#20424)
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/Tests/Microsoft.Extensions.DotNetDeltaApplier.Tests/StartupHookTests.cs
Labels: Area-Infrastructure

#20579 Revert "Ensure the server and client are valid when sending / receiving hot reload messages"
  src/BuiltInTools/BrowserRefresh/BrowserScriptMiddleware.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshFilter.cs
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserScriptMiddlewareTest.cs
Labels: Servicing-consider, Area-AspNetCore, Area-Watch

#20594 Revert "Ensure the server and client are valid when sending / receiving hot reload messages (#18912)" (#20579)
  src/BuiltInTools/BrowserRefresh/BrowserScriptMiddleware.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshFilter.cs
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserScriptMiddlewareTest.cs
Labels: Servicing-approved, Area-AspNetCore

#20481 Fix cross-os symbol generation
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
Labels: Area-ReadyToRun

#20626 [port to release/6.0.1xx] Fix cross-os symbol generation (#20481)
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
Labels: Area-ReadyToRun

#20645 Update onelocbuild.yml
  eng/common/templates/job/onelocbuild.yml
Labels: Area-Infrastructure

#20624 Reorder the EmbedProjectAssetsFile condtion to skip probing the file …
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets
Labels: Area-NetSDK

#20647 Add manifest description to get on loc train
  src/Cli/dotnet/commands/dotnet-workload/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Workloads

#20600 [Razor] Unskip tests
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#20646 Fix workload hidden options
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandNuGetRestoreActionConfigOptions.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommandParser.cs
Labels: Area-Workloads

#20719 Prevent null ref in RazorSourceGenerator
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-AspNetCore

#20712 Update branding for 5.0.208
  eng/Versions.props
Labels: Area-Infrastructure

#20711 Update branding for 3.1.414
  eng/Versions.props
Labels: Area-Infrastructure

#20708 Update branding for 5.0.402
  eng/Versions.props
Labels: Area-Infrastructure

#20704 Fix PlatformNotSupportedException for Windows (arm64)
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/Extensions/ProcessExtensions.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/ProcessExtensionsTests.cs
Labels: Area-Workloads

#20705 Update branding for 3.1.120
  eng/Versions.props
Labels: Area-Infrastructure

#20607 [Razor] Ensure the manifest is not generated when there are no assets or discovery patterns
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifest.cs
Labels: Area-AspNetCore

#20603 [Razor] Fix casing issue when matching projects to configurations
  src/RazorSdk/Tasks/StaticWebAssets/MergeConfigurationProperties.cs
  src/RazorSdk/Tasks/StaticWebAssets/OSPath.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/MergeConfigurationPropertiesTest.cs
Labels: Area-AspNetCore

#20609 [Razor] Fixes packing on multitargeting projects
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/RazorSdk/Tasks/GenerateStaticWebAsssetsPropsFile.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/ScopedCss_IsBackwardsCompatible_WithPreviousVersions.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/ScopedCss_PublishIsBackwardsCompatible_WithPreviousVersions.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#20766 [Razor] Ensure the manifest is not generated when there are no assets or discovery patterns (#20607)
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifest.cs
Labels: Area-AspNetCore

#20771 [Razor] Fixes packing on multitargeting projects (#20609)
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/RazorSdk/Tasks/GenerateStaticWebAsssetsPropsFile.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/ScopedCss_IsBackwardsCompatible_WithPreviousVersions.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/ScopedCss_PublishIsBackwardsCompatible_WithPreviousVersions.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#20770 [Razor] Fix casing issue when matching projects to configurations (#20603)
  src/RazorSdk/Tasks/StaticWebAssets/MergeConfigurationProperties.cs
  src/RazorSdk/Tasks/StaticWebAssets/OSPath.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/MergeConfigurationPropertiesTest.cs
Labels: Area-AspNetCore

#19878 Restore preferred packages functionality
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
Labels: Area-NuGet

#20781 Make ICUDataMode less prone to accidental breakage
  src/BlazorWasmSdk/Tasks/BootJsonData.cs
Labels: Area-AspNetCore

#20567 Only warn about references that are actually needed at runtime
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/CompatDifference.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/TypeMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ComparingSettings.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticBag.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/AssertExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceComparer.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AssemblyIdentityMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddAbstractMemberTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddMemberToInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotRemoveBaseTypeOrInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotSealTypeTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
Labels: Area-Compatibility

#18823 Support installing workloads in user folder
  src/Cli/Microsoft.DotNet.Configurer/CliFolderPathCalculator.cs
  src/Cli/Microsoft.DotNet.Configurer/Microsoft.DotNet.Configurer.csproj
  src/Cli/dotnet/commands/RestoringCommand.cs
  src/Cli/dotnet/commands/dotnet-new/OptionalWorkloadProvider.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkManagedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallRecords/NetSdkManagedInstallationRecordInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallerFactory.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadOptionsExtensions.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/repair/WorkloadRepairCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/uninstall/WorkloadUninstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Cli/dotnet/dotnet.csproj
  src/Common/CliFolderPathCalculatorCore.cs
  src/Common/WorkloadFileBasedInstall.cs
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Microsoft.DotNet.TemplateLocator/TemplateLocator.cs
  src/RazorSdk/Tool/Microsoft.NET.Sdk.Razor.Tool.csproj
  src/RazorSdk/Tool/ServerCommand.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/CachingWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/WorkloadSdkResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ShowMissingWorkloads.cs
  src/Tests/Microsoft.DotNet.TemplateLocator.Tests/GivenAnTemplateLocator.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestReaderFunctionalTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/WorkloadSuggestionFinderTests.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/GivenNetSdkManagedWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
  src/Tests/dotnet-workload-list.Tests/GivenWorkloadInstallerAndWorkloadsInstalled.cs
  src/Tests/dotnet-workload-repair.Tests/GivenDotnetWorkloadRepair.cs
  src/Tests/dotnet-workload-uninstall.Tests/GivenDotnetWorkloadUninstall.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: Area-Workloads

#19570 Cache results of ResolveTargetingPackAssets across builds
  src/Common/EnvironmentVariableNames.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolveTargetingPackAssetsTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/ResolveTargetingPackAssetsTests.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs
Labels: Area-NetSDK

#20648 Disable main loc build while release/6.0.1xx is running
  eng/build.yml
Labels: Area-Infrastructure

#20413 Adding issue templates for repo [skip ci]
  .github/ISSUE_TEMPLATE/10_bug_report.md
  .github/ISSUE_TEMPLATE/20_feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: Area-Infrastructure

#20800 [Blazor] Respect BlazorWebAssemblyLoadAllGlobalizationData in hosted projects during publish
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
Labels: Area-AspNetCore

#20835 [Blazor] Respect BlazorWebAssemblyLoadAllGlobalizationData in hosted projects during publish (#20800)
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
Labels: Area-AspNetCore

#20602 [Blazor] Fix duplicate entries in blazor.boot.json manifest extensions
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/GenerateBlazorWebAssemblyBootJson.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/GenerateBlazorBootJsonTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
Labels: Area-AspNetCore

#20850 [Blazor] Fix duplicate entries in blazor.boot.json manifest extensions (#20602)
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/GenerateBlazorWebAssemblyBootJson.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/GenerateBlazorBootJsonTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
Labels: Area-AspNetCore

#20644 Use 1ES build pools
  .vsts-ci-richnav.yml
  .vsts-ci.yml
Labels: Area-Infrastructure

#20792 [main] Add targeting pack VS.Redist dependencies
  eng/Version.Details.xml
Labels: Area-Infrastructure

#20791 [release/6.0.1xx] Add targeting pack VS.Redist dependencies
  eng/Version.Details.xml
Labels: Area-Infrastructure

#20577 Do not specify a protocol if server does not require secrets
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-AspNetCore

#20822 [Release 6.0.1xx] [PackageValidation] Improve warnings about references when running PackageValidation in a project after packaging it.
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/CompatDifference.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/TypeMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ComparingSettings.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticBag.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/AssertExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceComparer.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AssemblyIdentityMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddAbstractMemberTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddMemberToInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotRemoveBaseTypeOrInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotSealTypeTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
Labels: Servicing-consider, Area-Compatibility

#20874 Revert "Revert "Ensure the server and client are valid when sending / receiving hot reload messages""
  src/BuiltInTools/BrowserRefresh/BrowserScriptMiddleware.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshFilter.cs
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserScriptMiddlewareTest.cs
Labels: Area-AspNetCore

#20867 Remove MMI dependency
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/Extensions/ProcessExtensions.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Cli/Microsoft.DotNet.Cli.Utils/NativeMethods.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Windows.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/ProcessExtensionsTests.cs
Labels: Area-Workloads

#20877 Merge release/6.0.1xx with rc1
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshFilter.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallRecords/RegistryWorkloadInstallationRecordRepository.cs
Labels: Area-Workloads

#20897 [Static web assets] Ensure subpath is always normalized
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/GenerateStaticWebAssetsDevelopmentManifestTest.cs
Labels: Area-AspNetCore

#20898 Ensure dotnet root is not null
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallerFactory.cs
Labels: Area-Workloads

#20904 [Backport][Static web assets] Ensure subpath is always normalized (#20897)
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/GenerateStaticWebAssetsDevelopmentManifestTest.cs
Labels: Area-AspNetCore

#20912 Add command-line-api source-build dependency
  eng/Version.Details.xml
Labels: Area-Infrastructure

#20630 Blazor AOT Cache Busting
  .gitignore
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
  src/BlazorWasmSdk/Tasks/FileHasher.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmBaselineTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/AspNetSdkBaselineTest.cs
Labels: Area-AspNetCore

#20918 Port updates to source generator from main
  src/RazorSdk/SourceGenerators/RazorSourceGeneratorEventSource.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorEventListener.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-AspNetCore

#20924 Fix workload pack repair
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
Labels: Area-Workloads

#20936 Backport `Merge pull request #20630 from dotnet/taparik/blazorAOTCacheBusting`
  .gitignore
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
  src/BlazorWasmSdk/Tasks/FileHasher.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmBaselineTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/AspNetSdkBaselineTest.cs
Labels: Area-AspNetCore

#20920 Vary the cache key for TagHelpersFromReferences on SuppressRazorSourceGenerator
  eng/Version.Details.xml
  eng/Versions.props
  src/RazorSdk/Razor.slnf
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Servicing-approved, Area-AspNetCore

#20876 Fix workload pack records serialization
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadPackId.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/dotnet-workload-install.Tests/GivenNetSdkManagedWorkloadInstall.cs
Labels: Area-Workloads

#20964 Change Compatibility projects' TargetFrameworks
  src/Compatibility/Microsoft.DotNet.Compatibility/Microsoft.DotNet.Compatibility.csproj
  src/Compatibility/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
Labels: Area-Infrastructure

#20965 Fix the casing for the default PublishUrl property
  src/WebSdk/Publish/Targets/PublishProfiles/Default.pubxml
Labels: Area-WebSDK

#20553 [release/3.1.1xx] Remove blob feeds
  NuGet.config
  build/sdktests.ps1
  build/sdktests.sh
  src/Tests/Microsoft.NET.TestFramework/NuGetConfigWriter.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
Labels: Area-Infrastructure

#20959 Update the target framework for the test projects
  src/Assets/TestProjects/NewtonSoftDependentProject/NewtonSoftDependentProject.csproj
Labels: Area-Infrastructure

#20793 Support multi-targeting for Roslyn components
  src/Assets/TestPackages/Library.ContainsAnalyzer/Class1.cs
  src/Assets/TestPackages/Library.ContainsAnalyzer/Library.ContainsAnalyzer.csproj
  src/Assets/TestPackages/Library.ContainsAnalyzer2/Class1.cs
  src/Assets/TestPackages/Library.ContainsAnalyzer2/Library.ContainsAnalyzer2.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets
  src/Tests/Microsoft.NET.TestFramework/BuildTestPackages.targets
  src/Tests/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
Labels: Area-NetSDK

#20971 Update Microsoft.SourceBuild.Intermediate.source-build reference
  eng/Version.Details.xml
Labels: Area-Infrastructure

#20961 [Blazor] Allow duplicates in resolved files to publish
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
Labels: Area-AspNetCore

#20986 [release/6.0.1xx-rc1] Revert rc1 branch back to rc1 tooling versions
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#20983 Hide unused workload verbosity options
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchCommandParser.cs
Labels: Area-Workloads

#20980 [Blazor] Improves dotnet.js detection on ComputeBlazorPublishAssets
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmBaselineTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
Labels: Area-AspNetCore

#20972 Only throw missing reference path error when running with references
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
Labels: Area-Compatibility

#20988 [Backport] [Blazor] Allow duplicates in resolved files to publish (#20961)
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
Labels: Area-AspNetCore

#20742 [release/6.0.1xx] Update BlazorWebAssembly targets to work with updated wasm targets
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: Area-AspNetCore

#20990 Only throw missing reference path error when running with references
  src/Compatibility/Microsoft.DotNet.PackageValidation/ApiCompatRunner.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
Labels: Area-Compatibility

#20995 Merging internal commits for release/5.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#20809 Update Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
Labels: Area-Infrastructure

#20979 Update the target framework for the test projects
  src/Assets/TestProjects/PortableTool/consoledemo.csproj
  src/Assets/TestProjects/TestAppWithMultipleSlnFiles/App/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCaseSensitiveSolutionFolders/src/App/App.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAToolProjectWithPackagedShim.cs
Labels: Area-Infrastructure

#20955 remove unused env var: `DOTNET_SKIP_FIRST_TIME_EXPERIENCE`
  eng/common/tools.ps1
  eng/common/tools.sh
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
  src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
  src/WebSdk/Publish/Tasks/Tasks/GenerateEFSQLScripts.cs
Labels: Area-Infrastructure

#20996 Merging internal commits for release/5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: Area-Infrastructure

#21027 Update ShowMissingWorkloads for IPA VS top level workloads
  src/Tasks/Microsoft.NET.Build.Tasks/ShowMissingWorkloads.cs
Labels: Area-Workloads

#21033 Update branding for 6.0.1xx branch
  eng/Versions.props
Labels: Area-Infrastructure

#20148 Update a bunch of test projects to the current target framework
  src/Assets/TestProjects/AllResourcesInSatellite/AllResourcesInSatellite.csproj
  src/Assets/TestProjects/AllResourcesInSatelliteDisableVersionGenerate/AllResourcesInSatellite.csproj
  src/Assets/TestProjects/AppOutputsExecutablePath/AppOutputsExecutablePath.csproj
  src/Assets/TestProjects/AppWithApplicationUrlInLaunchSettings/AppWithApplicationUrlInLaunchSettings.csproj
  src/Assets/TestProjects/AppWithCorruptedLaunchSettings/AppWithCorruptedLaunchSettings.csproj
  src/Assets/TestProjects/AppWithDepOnToolWithOutputName/AppWithDepOnToolWithOutputName.csproj
  src/Assets/TestProjects/AppWithDirectAndToolDep/AppWithDirectAndToolDep.csproj
  src/Assets/TestProjects/AppWithDirectDep/AppWithDirectDep.csproj
  src/Assets/TestProjects/AppWithDirectDepWithOutputName/AppWithDirectDepWithOutputName.csproj
  src/Assets/TestProjects/AppWithFallbackFolderToolDependency/AppWithFallbackFolderToolDependency.csproj
  src/Assets/TestProjects/AppWithLaunchSettings/AppWithLaunchSettings.csproj
  src/Assets/TestProjects/AppWithLaunchSettingsNoDefault/AppWithLaunchSettingsNoDefault.csproj
  src/Assets/TestProjects/AppWithLibrary/TestApp/TestApp.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryFS/TestApp/TestApp.fsproj
  src/Assets/TestProjects/AppWithLibraryVB/TestApp/TestApp.vbproj
  src/Assets/TestProjects/AppWithMultipleFxAndTools/MSBuildAppWithMultipleFrameworksAndTools.csproj
  src/Assets/TestProjects/AppWithNetCoreAppLib/lib/lib.csproj
  src/Assets/TestProjects/AppWithNetCoreAppLib/main/main.csproj
  src/Assets/TestProjects/AppWithSharedProject/TestApp/TestApp.csproj
  src/Assets/TestProjects/AppWithToolDependency/AppWithToolDependency.csproj
  src/Assets/TestProjects/AppWithTransitiveProjectRefs/TestApp/TestApp.csproj
  src/Assets/TestProjects/AppxReferencingCrossTargeting/Appx/Appx.csproj
  src/Assets/TestProjects/AppxReferencingCrossTargeting/CrossTargeted/CrossTargeted.csproj
  src/Assets/TestProjects/ComServer/ComServer.csproj
  src/Assets/TestProjects/ComServerWithTypeLibs/ComServerWithTypeLibs.csproj
  src/Assets/TestProjects/CompilationContext/TestApp/TestApp.csproj
  src/Assets/TestProjects/CrossTargeting/DesktopAndNetStandard/DesktopAndNetStandard.csproj
  src/Assets/TestProjects/CrossTargeting/NetStandardAndNetCoreApp/NetStandardAndNetCoreApp.csproj
  src/Assets/TestProjects/DependencyContextFromTool/DependencyContextFromTool.csproj
  src/Assets/TestProjects/DeployProjectReferencingSdkProject/HelloWorld/HelloWorld.csproj
  src/Assets/TestProjects/FSharpTestAppSimple/TestAppSimple.fsproj
  src/Assets/TestProjects/InferredTypeVariableName/InferredTypeVaraibleName.vbproj
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/Assets/TestProjects/MSBuildAppWithMultipleFrameworks/MSBuildAppWithMultipleFrameworks.csproj
  src/Assets/TestProjects/MSBuildAppWithMultipleFrameworksAndTools/MSBuildAppWithMultipleFrameworksAndTools.csproj
  src/Assets/TestProjects/MSBuildTestApp/MSBuildTestApp.csproj
  src/Assets/TestProjects/MultiDependentProject/MultiDependentProject.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantAllResourcesInSatellite.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantSatelliteAssembliesHaveassemblyVersion.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAComServerLibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACrossTargetedLibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithLibrariesAndRid.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithLibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithSharedProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithTransitiveProjectRefs.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithoutTransitiveProjectRefs.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseVB.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackACrossTargetedLibrary.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAComServerLibrary.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASelfContainedApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAppWithLibrariesAndRid.cs
  src/Tests/Microsoft.NET.TestFramework/TestAsset.cs
  src/Tests/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
  src/Tests/dotnet-clean.Tests/GivenDotnetCleanCleansBuildArtifacts.cs
  src/Tests/dotnet-list-package.Tests/GivenDotnetListPackage.cs
  src/Tests/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
Labels: Area-Infrastructure

#20929 Add a test for SuppressRazorSourceGenerator incrementalism
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-AspNetCore

#20937 Fix EnableTrimAnalyzer for TFMs < 6.0
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#21057 Update build.yml
  eng/build.yml
Labels: Area-Infrastructure

#20930 Fix nuget config not being honored
  src/Cli/dotnet/StatInterop.cs
  src/Cli/dotnet/SudoEnvironmentDirectoryOverride.cs
Labels: Area-Infrastructure

#21063 Fix null ref in update command
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallRecords/RegistryWorkloadInstallationRecordRepository.cs
Labels: Area-Workloads

#21049 Update the target framework for the test projects
  src/Assets/TestProjects/SlnFileWithNoProjectReferencesAndFSharpProject/FSharpProject/FSharpProject.fsproj
  src/Assets/TestProjects/TestAppSimple/TestAppSimple.csproj
  src/Assets/TestProjects/TestAppThatWaits/TestAppThatWaits.csproj
  src/Assets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedCS/MultitargetedCS.csproj
  src/Assets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedFS/MultitargetedFS.fsproj
  src/Assets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/MultitargetedVB/MultitargetedVB.vbproj
  src/Tests/dotnet-add-package.Tests/GivenDotnetPackageAdd.cs
  src/Tests/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
  src/Tests/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
Labels: Area-Infrastructure

#20991 Allow specifying url for workload rollback
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
Labels: Area-Workloads

#21058 Tweak the hot reload update toast
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-AspNetCore

#20987 Warn when Targeting net6.0 with 16.11 and the 6.0 SDK
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tests/Microsoft.NET.Clean.Tests/GivenThatWeWantToCleanAProject.cs
Labels: Servicing-consider, Area-NetSDK

#21084 Update the target framework for the test projects
  src/Assets/TestProjects/TestAppWithLaunchSettings/TestAppWithLaunchSettings.csproj
  src/Assets/TestProjects/TestAppWithProjDepTool/TestAppWithProjDepTool.csproj
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAProjectDependencyCommandResolver.cs
Labels: Area-Infrastructure

#21104 [release/6.0.1xx-rc2] BlazorWasm: Fix including the target assembly
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: Area-AspNetCore

#21102 Fix 10 minutes time out of TransactionScope
  src/Cli/dotnet/TransactionalAction.cs
Labels: Area-Workloads

#20984 [release/6.0.1xx] Add System.ServiceProcess.ServiceController dependency
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/dotnet.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-Infrastructure

#21177 Update top level help with workload string
  src/Cli/dotnet/BuiltInCommandsCatalog.cs
  src/Cli/dotnet/commands/dotnet-help/HelpUsageText.cs
  src/Cli/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
Labels: Area-Workloads

#21233 Switch to 1ES Servicing pools in 3.1.1xx
  .vsts-ci.yml
Labels: Area-Infrastructure

#21232 Switch to 1ES Servicing pools in 3.1.4xx
  .vsts-ci.yml
Labels: Area-Infrastructure

#21272 Update the documentation to include Zip Deploy
  src/WebSdk/README.md
Labels: Area-WebSDK

#21022 Update BlazorWebAssembly targets to work with updated wasm targets
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: Area-AspNetCore

#21324 ensure analysis level 5 is set for .NET 5 TFM
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
Labels: Area-Infrastructure

#21329 Fix workload nuget retry issue
  src/Cli/Microsoft.DotNet.Cli.Utils/ExponentialRetry.cs
  src/Tests/dotnet.Tests/GivenExponentialRetry.cs
Labels: Area-Workloads

#21103 Create UpdateToNewTargetFramework.md
  documentation/general/UpdateToNewTargetFramework.md
Labels: Area-Infrastructure

#21310 Update the target framework for the test projects
  src/Assets/TestProjects/SimpleDependencies/SimpleDependencies.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/PublishCommand.cs
Labels: Area-Infrastructure

#20993 Add a static cache for GetAssemblyVersion
  src/Tasks/Common/FileUtilities.MetadataReader.cs
Labels: Area-NetSDK

#20863 Switch to 1ES servicing pools on 5.0.2xx
  .vsts-ci.yml
Labels: Area-Infrastructure

#21085 Use a BlockingCollection in the logger to reduce CPU usage
  src/Cli/dotnet/Installer/Windows/TimestampedFileLogger.cs
Labels: Area-Install, Area-Workloads

#21283 Add rollback option to install command and allow missing manifest ids
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
Labels: Area-Workloads

#21435 Fix RID resolution on x64 emulated installations
  src/Cli/dotnet/CommonOptions.cs
Labels: Area-CLI

#19786 Update ValidateExecutableReferences with new schema
  src/Tasks/Microsoft.NET.Build.Tasks/ValidateExecutableReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Area-CLI

#21358 Fix failure when manifest that is expected to exist isn't found
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
Labels: Area-Workloads

#21422 Update the target framework for the test projects
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDir/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirToRemove/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojToRemove/App/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndDuplicateProjectReferences/App/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndExistingCsprojReferences/App/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndExistingCsprojReferencesWithEscapedDirSep/App/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndLastCsprojInSubDirToRemove/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndSolutionFolders/src/App/App.csproj
  src/Assets/TestProjects/TestAppWithSlnProjectDependencyToRemove/App/App.csproj
  src/Assets/TestProjects/TestRazorApp/TestRazorApp.csproj
  src/Assets/TestProjects/TestWebAppSimple/TestWebAppSimple.csproj
  src/Assets/TestProjects/TrimmedAppWithReferences/App/App.csproj
  src/Assets/TestProjects/TrimmedAppWithReferences/PackageReference/PackageReference.csproj
  src/Assets/TestProjects/TrimmedAppWithReferences/ProjectReference/ProjectReference.csproj
  src/Assets/TestProjects/TrimmedAppWithReferences/TransitiveProjectReference/TransitiveProjectReference.csproj
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
Labels: Area-Infrastructure

#21453 [Backport][Blazor] from main: BlazorWasm: Fix including the target assembly
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: Area-AspNetCore

#21390 Clean up client/server shutdown
  src/Cli/dotnet/Installer/Windows/TimestampedFileLogger.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerServer.cs
  src/Tests/dotnet.Tests/WindowsInstallerTests.cs
Labels: Area-Workloads

#21502 Rename DeploymentReleasesVersion Versions.props entry.
  eng/Versions.props
  src/Cli/dotnet/dotnet.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
Labels: Area-Infrastructure

#21487 Update the target framework for the test projects
  src/Assets/TestProjects/TestAppWithEmptySln/App/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojFiles/App/App.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojProjectGuidFiles/App/App.csproj
  src/Assets/TestProjects/Unpublishable/Unpublishable.csproj
  src/Assets/TestProjects/VBTestApp/VBTestApp.vbproj
  src/Assets/TestProjects/VSTestCore/VSTestCore.csproj
  src/Assets/TestProjects/VSTestEnvironmentVariables/VSTestEnvironmentVariables.csproj
  src/Assets/TestProjects/VSTestMulti/VSTestDesktopAndNetCore.csproj
  src/Assets/TestProjects/VSTestTestRunParameters/VSTestTestRunParameters.csproj
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromDll.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsprojWithCorrectTestRunParameters.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestContainsEnvironmentVariables.cs
  src/Tests/dotnet-vstest.Tests/VSTestTests.cs
  src/Tests/dotnet.Tests/GivenThatICareAboutVBApps.cs
Labels: Area-Infrastructure

#21506 [Razor] Fixes pack incrementalism issue
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#21505 Update Microsoft.SourceBuild.Intermediate.source-build dependency
  eng/Version.Details.xml
Labels: Area-Infrastructure

#21541 [Razor] Fixes pack incrementalism issue (#21506)
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Servicing-consider, Area-AspNetCore

#21464 Remove sql-cache from dotnet help
  src/Cli/dotnet/commands/dotnet-help/HelpUsageText.cs
  src/Cli/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
Labels: Area-Infrastructure

#21252 Fix up some test packages
  src/Assets/NonRestoredTestProjects/ToolWithRandomPackageName/AppWithDepOnTool/NuGet.Config
  src/Assets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  src/Assets/TestProjects/11TestAppWith10CLIToolReferences/11TestAppWith10CLIToolReferences.csproj
  src/Assets/TestProjects/RazorAppWithPackageAndP2PReference/AppWithPackageAndP2PReference/nuget.config
  src/Assets/TestProjects/TrimmedAppWithReferences/App/nuget.config
  src/Tests/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
Labels: Area-Infrastructure

#21460 Prevent GlobalUsings file from being cleaned.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateGlobalUsings.targets
  src/Tasks/Microsoft.NET.slnf
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_DotNet.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/CleanCommand.cs
Labels: Area-AspNetCore

#21590 [Blazor] Improves dotnet.js detection on ComputeBlazorPublishAssets (#20980)
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmBaselineTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
Labels: Area-AspNetCore

#21593 [ASP.NET] Include missing commits in main
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-AspNetCore

#21549 Switch to 1ES R&D pools on main
  .vsts-ci-richnav.yml
  .vsts-ci.yml
Labels: Area-Infrastructure

#21598 [release/6.0.1xx] Introduce explicit dependency on System.IO.Pipelines
  eng/Version.Details.xml
Labels: Area-Infrastructure
