Repository dotnet/sdk, pull requests merged in 2021-12, with the labels that each got.

#22770 Update Test project XunitMulti to current framework
  src/Assets/TestProjects/XunitMulti/VSTestXunitDesktopAndNetCore.csproj
Labels: Area-Infrastructure

#22532 Update Test project x64SolutionBuild to current framework
  src/Assets/TestProjects/x64SolutionBuild/x64SolutionBuild.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASolutionWithNonAnyCPUPlatform.cs
Labels: Area-Infrastructure

#22805 Update the hardcoded TFM to the current framework
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_BlazorWasm.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_DotNet.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_WebApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_Worker.cs
Labels: Area-FSharp

#22833 [main] Merged missed Version.Details.xml source-build changes from release/6.0.1xx
  eng/Version.Details.xml
Labels: Area-Infrastructure, source-build

#22759 Use Environment.Process{Path,Id} & delete wrappers
  src/BuiltInTools/dotnet-watch/Filters/DotNetBuildFilter.cs
  src/BuiltInTools/dotnet-watch/Internal/DotnetMuxer.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/DebugHelper.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Muxer.cs
  src/Cli/dotnet/PerformanceLogEventListener.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerServer.cs
  src/RazorSdk/Tasks/DotnetToolTask.cs
  src/RazorSdk/Tool/DebugMode.cs
  src/RazorSdk/Tool/DefaultRequestDispatcher.cs
  src/RazorSdk/Tool/ServerCommand.cs
  src/RazorSdk/Tool/ServerProtocol/ServerLogger.cs
  src/Resolvers/Microsoft.DotNet.NativeWrapper/EnvironmentProvider.cs
  src/Tests/dotnet-watch.Tests/MsBuildFileSetFactoryTest.cs
Labels: Area-Infrastructure

#22885 Add documentation for workload rollback
  documentation/general/workload-rollback.md
Labels: Area-Infrastructure

#22898 Change -a parameter to be shorthand for --arch, instead of --test-adapter-path
  src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs
  src/Tests/dotnet.Tests/ParserTests/VSTestArgumentConverterTests.cs
Labels: Area-Infrastructure, Area-DotNet Test

#22897 Transform --arch switch to --platform for dll tests container scenario
  src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromDll.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
  src/Tests/dotnet.Tests/ParserTests/VSTestArgumentConverterTests.cs
Labels: Area-DotNet Test

#22835 Update build.yml to change the loc build to target .2xx
  eng/build.yml
Labels: Area-Infrastructure

#22922 Update build.yml for loc build
  eng/build.yml
Labels: Area-Infrastructure

#22700 Update developer-guide to instruct to source the dogfood bash script
  documentation/project-docs/developer-guide.md
Labels: Area-Infrastructure

#22912 Transformed --arch switch to --platform for dll tests container scenario
  src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromDll.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
  src/Tests/dotnet.Tests/ParserTests/VSTestArgumentConverterTests.cs
Labels: Area-DotNet Test

#22658 Exclude runtimeidentifiers for runtimepack
  src/Tasks/Common/Logger.cs
  src/Tasks/Common/MetadataKeys.cs
  src/Tasks/Microsoft.NET.Build.Tasks/NuGetUtils.NuGet.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveAppHosts.cs
  src/Tests/Microsoft.NET.Build.Tests/KnownRuntimePackTests.cs
Labels: Area-Workloads

#22938 Update branding to 5.0.211
  eng/Versions.props
Labels: Area-Infrastructure

#22937 Update branding to 3.1.417
  eng/Versions.props
Labels: Area-Infrastructure

#22939 Update branding to 5.0.405
  eng/Versions.props
Labels: Area-Infrastructure

#22940 Update branding to 6.0.102
  eng/Versions.props
Labels: Area-Infrastructure

#22946 Remove AoT `Publish Test Results` Step
  eng/build.yml
Labels: Area-Infrastructure

#22861 Merge 6.0.1xx into the 6.0.2xx branch to catch it up to current
  eng/Version.Details.xml
  eng/Versions.props
  src/Assets/TestProjects/WebApp/web.csproj
  src/Assets/TestProjects/XUnitTestProject/XUnitTestProject.csproj
  src/Assets/TestProjects/XunitCore/XunitCore.csproj
  src/Assets/TestProjects/XunitMulti/VSTestXunitDesktopAndNetCore.csproj
  src/Assets/TestProjects/x64SolutionBuild/x64SolutionBuild.csproj
  src/BlazorWasmSdk/BlazorWasmSdk.slnf
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASolutionWithNonAnyCPUPlatform.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAUnitTestProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_BlazorWasm.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_DotNet.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_WebApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_Worker.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAWebApp.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/ComputeBlazorBuildAssetsTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
Labels: Area-Infrastructure

#22947 Update macos leg to 1015
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
Labels: Area-Infrastructure

#22919 Improve error message for path mismatch
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Strings.resx
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.cs.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.de.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.es.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.fr.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.it.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ja.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ko.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.pl.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.pt-BR.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ru.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.tr.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.zh-Hans.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildWithGlobalJson.cs
Labels: Area-Infrastructure

#22967 Remove AoT Build Publish Args To Prevent Un-necessary Uploads
  eng/build.yml
Labels: Area-Infrastructure

#22945 Unskip Blazor Integration Tests
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
Labels: Area-AspNetCore

#22968 Merge pull request #22947 from dotnet/marcpopMSFT-macosleg
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
Labels: Area-Infrastructure

#22970 Merge pull request #22947 from dotnet/marcpopMSFT-macosleg
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishIncrementally.cs
Labels: Area-Infrastructure

#22969 Merge pull request #22947 from dotnet/marcpopMSFT-macosleg
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
Labels: Area-Infrastructure

#23017 Update .vsts-ci.yml
  .vsts-ci.yml
Labels: Area-Infrastructure

#23019 Update .vsts-ci.yml
  .vsts-ci.yml
Labels: Area-Infrastructure

#23021 Update .vsts-ci.yml
  .vsts-ci.yml
Labels: Area-Infrastructure

#23018 Update .vsts-ci.yml
  .vsts-ci.yml
Labels: Area-Infrastructure

#23020 Update .vsts-ci.yml
  .vsts-ci.yml
Labels: Area-Infrastructure

#22971 Merge pull request #22947 from dotnet/marcpopMSFT-macosleg
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishIncrementally.cs
Labels: Area-Infrastructure

#23045 Stop Using Darwin CIBuild Script for AoT Tests
  eng/build.yml
Labels: Area-Infrastructure

#23048 Fix ordering of gathering files from Sdks
  src/Layout/redist/redist.csproj
Labels: Area-Infrastructure

#23039 Upgrade vstest packages and fix tests
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Area-DotNet Test

#23068 Skip Wasm-Tools Workload Install and Test Run When Build Fails
  eng/build.yml
Labels: Area-AspNetCore

#23058 Merging internal commits for release/5.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  eng/runHelixAndNonHelixInParallel.ps1
Labels: Area-Infrastructure

#22902 Update to use new Razor transport packages
  eng/Version.Details.xml
  eng/Versions.props
  src/Layout/redist/targets/GenerateLayout.targets
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
  src/RazorSdk/Tool/Microsoft.NET.Sdk.Razor.Tool.csproj
  src/Tests/Microsoft.NET.Sdk.Razor.Tool.Tests/Microsoft.NET.Sdk.Razor.Tool.Tests.csproj
Labels: Area-AspNetCore

#23094 [release/6.0.2xx] Update to 6.0.1 runtimes
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/dotnet.csproj
Labels: Area-Infrastructure

#23097 Fix dotnet tool list command
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListCommandParser.cs
Labels: Area-Workloads

#23057 Merging internal commits for release/6.0.1xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  eng/runHelixAndNonHelixInParallel.ps1
  src/Cli/dotnet/dotnet.csproj
Labels: Area-Infrastructure

#23185 Assume basline capabilities
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
Labels: Area-AspNetCore

#22918 include props and targets for code style packages
  src/Layout/redist/targets/GenerateLayout.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
Labels: Area-Infrastructure

#23184 Use project path instead of working directory to resolve launchSettings.json
  src/Assets/TestProjects/WatchAppWithLaunchSettings/Program.cs
  src/Assets/TestProjects/WatchAppWithLaunchSettings/Properties/launchSettings.json
  src/Assets/TestProjects/WatchAppWithLaunchSettings/WatchAppWithLaunchSettings.csproj
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/Utilities/WatchableApp.cs
Labels: Area-AspNetCore
