Repository dotnet/sdk, pull requests merged in 2021-07, with the labels that each got.

#18744 Update branding for 3.1.4xx to 412
  eng/Versions.props
Labels: Branding

#18745 Update branding for 3.1.1xx to 118
  eng/Versions.props
Labels: Branding

#18743 Update branding for 5.0.2xx to 206
  eng/Versions.props
Labels: Branding

#18742 Update branding for 5.0.3xx to 303
  eng/Versions.props
Labels: Branding

#18778 Move linker semaphore to IntermediateLinkDir
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#18789 Don't rebuild when changes to cshtml files are made with runtime comp…
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-AspNetCore

#18757 [API Compat] Add rule to validate an abstract member is not added
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Filtering/SymbolAccessibilityBasedFilter.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/MemberMapper.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Extensions/SymbolExtensions.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerContext.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddAbstractMemberTests.cs
Labels: Area-Compatibility

#18459 Add global usings for .NET projects (.NET SDK, Web and Worker)
  src/Assets/TestProjects/BlazorHostedRID/blazorhosted/blazorhosted-rid.csproj
  src/Layout/toolset-tasks/toolset-tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateImplicitNamespaceImports.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.VisualBasic.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/EndToEnd.Tests/GivenDotNetUsesMSBuild.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AssemblyIdentityMustMatchTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenFrameworkReferences.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibraryWithOSSupportedVersion.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsDesktopProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateImplicitNamespaceImports_DotNet.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateImplicitNamespaceImports_WebApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateImplicitNamespaceImports_Worker.cs
  src/Tests/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASelfContainedApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishTrimmedWindowsFormsAndWPFApps.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishWpfApp.cs
  src/WebSdk/Web/Sdk/Sdk.props
  src/WebSdk/Web/Sdk/Sdk.targets
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.props
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.targets
Labels: Area-NetSDK, Area-WebSDK

#18796 Separate launching a browser from injecting browser refresh middleware
  src/BuiltInTools/dotnet-watch/DotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Filters/BrowserRefreshFilter.cs
  src/BuiltInTools/dotnet-watch/Filters/LaunchBrowserFilter.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Tests/dotnet-watch.Tests/BrowserLaunchTests.cs
Labels: Area-AspNetCore

#18812 Default EnableUnsafeBinaryFormatterSerialization and EnableUnsafeUTF7Encoding in trimmed applications
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink

#18834 [API Compat] Add rule to validate members are not added to interfaces
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddMemberToInterface.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AssemblyIdentityMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddMemberToInterfaceTests.cs
Labels: Area-Compatibility

#18817 Bump RZL and don't use source generator if not Dev17
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-AspNetCore

#18850 Added Microsoft.Extensions.* default using to blazor wasm
  src/BlazorWasmSdk/Sdk/Sdk.props
  src/BlazorWasmSdk/Sdk/Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateImplicitNamespaceImports_BlazorWasm.cs
Labels: Area-AspNetCore

#18874 [API Compat] Make sure test syntax trees don't have any syntax errors
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CustomSideNameTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddAbstractMemberTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddMemberToInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SymbolFactory.cs
Labels: Area-Compatibility

#18216 Add property for opting out of apphost signing in macOS
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/CreateAppHost.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToCopyLocalDependencies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseVB.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.TestFramework/AssertionHelper.cs
  src/Tests/Microsoft.NET.TestFramework/TestAsset.cs
  src/Tests/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
  src/Tests/dotnet.Tests/TestAssetExtensions.cs
Labels: Team:Runtime

#18853 Relocate VB import items to props file
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.VisualBasic.targets
  src/Tests/dotnet.Tests/GivenThatICareAboutVBApps.cs
Labels: Area-NetSDK, Urgency-Soon

#18877 Fix matching analyzers from packages to TargetFramework
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
Labels: Urgency-Soon

#18811 Add build retry
  .vsts-ci.yml
  eng/BuildConfiguration/build-configuration.json
Labels: Urgency-Soon

#18840 adding dotnet format command handlers
  CODEOWNERS
  src/Cli/dotnet/BuiltInCommandsCatalog.cs
  src/Cli/dotnet/Parser.cs
  src/Cli/dotnet/commands/dotnet-cleanup/CleanupCommand.cs
  src/Cli/dotnet/commands/dotnet-cleanup/CleanupCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/FormatCommand.cs
  src/Cli/dotnet/commands/dotnet-format/FormatCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-format/analyzers/FormatAnalyzersCommand.cs
  src/Cli/dotnet/commands/dotnet-format/analyzers/FormatAnalyzersCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/common/AbstractFormatCommand.cs
  src/Cli/dotnet/commands/dotnet-format/common/DotnetFormatForwardingApp.cs
  src/Cli/dotnet/commands/dotnet-format/common/FormatCommandCommon.cs
  src/Cli/dotnet/commands/dotnet-format/style/FormatStyleCommand.cs
  src/Cli/dotnet/commands/dotnet-format/style/FormatStyleCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/whitespace/FormatWhitespaceCommand.cs
  src/Cli/dotnet/commands/dotnet-format/whitespace/FormatWhitespaceCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-help/HelpUsageText.cs
  src/Cli/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
  src/Tests/dotnet-format.Tests/GivenDotnetFormatAnalyzersIsInvoked.cs
  src/Tests/dotnet-format.Tests/GivenDotnetFormatIsInvoked.cs
  src/Tests/dotnet-format.Tests/GivenDotnetFormatStyleIsInvoked.cs
  src/Tests/dotnet-format.Tests/GivenDotnetFormatWhitespaceIsInvoked.cs
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/CommandTests/CompleteCommandTests.cs
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Format

#18944 [ASP.NET] Generate a runtime manifest for the list of static web assets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/GenerateStaticWebAssetsDevelopmentManifestTest.cs
Labels: Area-AspNetCore

#18931 Rewrite assembly identity must match tests to use in memory assemblies
  src/Assets/TestProjects/PublicKeyTokenValidation/Class1.cs
  src/Assets/TestProjects/PublicKeyTokenValidation/PublicKeyTokenValidation.csproj
  src/Assets/TestProjects/PublicKeyTokenValidation/test.snk
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AssemblyIdentityMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SymbolFactory.cs
Labels: Area-Compatibility

#18957 Don't re-run discovery for files that haven't changed
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore

#18815 Set attribute and LangVersion properly for a TFM
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
Labels: Area-NetSDK, auto-merge

#18929 [API Compat] Add rule that validates a base type or interface is not removed
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Filtering/SymbolAccessibilityBasedFilter.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/IRuleRunnerFactory.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ComparingSettings.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Extensions/SymbolExtensions.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerFactory.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleSettings.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddAbstractMemberTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotRemoveBaseTypeOrInterfaceTests.cs
Labels: Area-Compatibility

#18910 Add workload restore command
  src/Cli/dotnet/CommonOptionsExtension.cs
  src/Cli/dotnet/Parser.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/restore/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/restore/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommonCrossTargeting.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.GetRequiredWorkloads.CrossTargeting.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportWorkloads.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Workloads.CrossTargeting.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets
  src/Tests/Microsoft.NET.Build.Tests/WorkloadTests.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/GetValuesCommand.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
  src/Tests/dotnet-workload-list.Tests/GivenWorkloadInstallerAndWorkloadsInstalled.cs
  src/Tests/dotnet-workload-repair.Tests/GivenDotnetWorkloadRepair.cs
  src/Tests/dotnet-workload-restore.Tests/DiscoverAllProjectsTests.cs
  src/Tests/dotnet-workload-search.Tests/GivenDotnetWorkloadSearch.cs
  src/Tests/dotnet-workload-uninstall.Tests/GivenDotnetWorkloadUninstall.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Urgency-Soon

#19063 [API Compat] Add rule that validates an inheritable type is not sealed
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Extensions/SymbolExtensions.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotSealType.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotSealTypeTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
Labels: Area-Compatibility

#18794 Adding BeforeBundle target
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Area-ILLink

#19080 [Static web assets] Fixes issues we discovered while integrating the static web assets improvements on to the ASP.NET Core repo
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Tasks/StaticWebAssets/ComputeReferencedProjectAssets.cs
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/MergeManifestProperties.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmBaselineTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/AspNetSdkBaselineTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_NoDependencies_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_NoDependencies_GeneratesJsonManifestAndCopiesItToOutputFolder_NoDependencies.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DoesNotUpdateManifest_WhenHasNotChanged.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_UpdatesManifest_WhenFilesChange.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Clean_RemovesManifestFrom_BuildAndIntermediateOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Rebuild_RegeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Rebuild_RegeneratesJsonManifestAndCopiesItToOutputFolder_Rebuild.Build.staticwebassets.json
Labels: Area-AspNetCore, Servicing-approved

#19128 Improve caching in RazorSourceGenerator (#18985)
  src/RazorSdk/SourceGenerators/IncrementalValueProviderExtensions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerationOptions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.Helpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.TagHelpers.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/StaticCompilationTagHelperFeature.cs
Labels: Area-AspNetCore, Servicing-approved

#18986 Don't produce errors when an Exe project references a test project
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
Labels: Servicing-approved

#19123 [API Compat] Support suppressing an error globally for the same left and right with no target
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ErrorSuppression/SuppressionEngine.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionEngineTests.cs
Labels: Area-Compatibility

#18889 Adding OS and arch command line options
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/OptionForwardingExtensions.cs
  src/Cli/dotnet/ParseResultExtensions.cs
  src/Cli/dotnet/commands/dotnet-build/BuildCommandParser.cs
  src/Cli/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/Cli/dotnet/commands/dotnet-run/Program.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetOsArchOptions.cs
Labels: Servicing-approved, Urgency-Soon

#18837 Update self contained/ runtime command line options for build and publish
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/commands/dotnet-build/BuildCommand.cs
  src/Cli/dotnet/commands/dotnet-build/BuildCommandParser.cs
  src/Cli/dotnet/commands/dotnet-publish/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-publish/Program.cs
  src/Cli/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
  src/Tests/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
Labels: Servicing-approved, Urgency-Soon

#19132 Add SDK support for perfmap format version
  src/Tasks/Common/MetadataKeys.cs
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
Labels: Area-ReadyToRun

#19295 Use explicit StringComparison for string.EndsWith
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
Labels: Area-AspNetCore

#19209 Move PackageValidation to sdk with opt-in flag
  src/Assets/TestProjects/PackageValidationTestProject/PackageValidationTestProject.csproj
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/MetadataInformation.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticBag.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/ErrorSuppression/Suppression.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/Compatibility/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/Compatibility/Microsoft.DotNet.PackageValidation/Resources.resx
  src/Compatibility/Microsoft.DotNet.PackageValidation/ValidatePackage.cs
  src/Compatibility/Microsoft.DotNet.PackageValidation/build/Microsoft.DotNet.PackageValidation.targets
  src/Compatibility/Microsoft.DotNet.PackageValidation/buildMultiTargeting/Microsoft.DotNet.PackageValidation.props
  src/Compatibility/Microsoft.DotNet.PackageValidation/buildMultiTargeting/Microsoft.DotNet.PackageValidation.targets
  src/Compatibility/Microsoft.DotNet.PackageValidation/sdk/Sdk.props
  src/Compatibility/Microsoft.DotNet.PackageValidation/sdk/Sdk.targets
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.PackageValidation/xlf/Resources.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Compatibility.Common.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Compatibility.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Compatibility.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceComparer.cs
Labels: Area-Compatibility

#19393 Use MetadataUpdater APIs for hot reload
  src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
Labels: Area-AspNetCore

#19432 Update SDK to support new DI and Attribute feature switches
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-ILLink
