Repository dotnet/sdk, pull requests merged in 2022-08, with the labels that each got.

#26935 Invoke PackageValidation only when inputs have changed
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
Labels: Area-Compatibility

#26926 Add baseline package validation strict mode option
  src/Assets/TestProjects/PackageValidationTestProject/PackageValidationTestProject.csproj
  src/Assets/TestProjects/PackageValidationTestProject/Program.cs
  src/Compatibility/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/Compatibility/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/Compatibility/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Task/ValidatePackageTargetIntegrationTests.cs
Labels: Area-Compatibility

#26936 Enable nullability checks in rules and avoid reflection during start-up
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/IRule.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Abstractions/Rule.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddMemberToInterface.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotSealType.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/EnumsMustMatch.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleLocator.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerContext.cs
Labels: Area-Compatibility

#26942 Update branding to 6.0.401
  eng/Versions.props
Labels: Area-Infrastructure

#26940 Update branding to 6.0.109
  eng/Versions.props
Labels: Area-Infrastructure

#26508 Merge pull request #22974 from dotnet/marcpopMSFT-updateappinsights
  eng/Versions.props
  src/Cli/dotnet/Program.cs
  src/Cli/dotnet/Telemetry/ITelemetry.cs
  src/Cli/dotnet/Telemetry/Telemetry.cs
  src/Cli/dotnet/commands/dotnet-internal-reportinstallsuccess/InternalReportinstallsuccessCommand.cs
  src/Tests/dotnet.Tests/FakeRecordEventNameTelemetry.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/FakeTelemetry.cs
Labels: Area-Infrastructure

#22233 Delete unnecessary test project files
  src/Assets/TestProjects/RazorSimplePages/LinkedDir/LinkedErrorFile.cshtml
  src/Assets/TestProjects/RazorSimplePages/LinkedDir/LinkedFile.cshtml
  src/Assets/TestProjects/RazorSimplePages/LinkedDir/LinkedFile2.cshtml
  src/Assets/TestProjects/RazorSimplePages/LinkedDir/LinkedFile3.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Areas/Products/Pages/Index.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Areas/Products/Pages/_ViewImports.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Areas/Products/Pages/_ViewStart.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/About.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/About.cshtml.cs
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/Contact.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/Contact.cshtml.cs
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/Index.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/Index.cshtml.cs
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/_Layout.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/_ViewImports.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Pages/_ViewStart.cshtml
  src/Assets/TestProjects/RazorSimplePages/SimplePages/Program.cs
  src/Assets/TestProjects/RazorSimplePages/SimplePages/SimplePages.csproj
Labels: Area-Infrastructure

#26939 Update branding to 3.1.423
  eng/Versions.props
Labels: Area-Infrastructure

#26941 Update branding to 6.0.304
  eng/Versions.props
Labels: Area-Infrastructure

#26937 Added a possibility to enable MSBuild evaluation for dotnet new also by env variable
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
Labels: Area-Templates

#26954 Enable nullable for ApiCompatibility
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/CompatDifference.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/ElementContainer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/IRule.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/MapperVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblySetMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/MemberMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/NamespaceMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/TypeMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/MetadataInformation.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparerFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/AssemblyLoadWarning.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoaderFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ComparingSettings.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DefaultSymbolsEqualityComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Extensions/CollectionsExtensions.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IApiComparerFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IAssemblySymbolLoaderFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IMetadataStreamProvider.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ICompatibilityLogger.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ISuppressionEngine.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/MessageImportance.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/Suppression.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/SuppressionEngine.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/MetadataStreamProvider.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddMemberToInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotSealType.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/EnumsMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleLocator.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerContext.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleSettings.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunnerOptions.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunnerWorkItem.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/IApiCompatRunner.cs
Labels: Area-ApiCompat

#26862 Avoid parallel workload MSI extraction
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
Labels: Servicing-approved

#26948 Add helper for safe access to CLI options when accessing outside of a command invocation
  src/Cli/dotnet/ParseResultExtensions.cs
  src/Cli/dotnet/Telemetry/TelemetryFilter.cs
Labels: Area-CLI, cli-ux

#26956 Enable nullable for additional ApiCompatibility types
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/CompatDifference.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/IDiagnostic.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/AssemblyLoadWarning.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IAssemblySymbolLoader.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/AssemblySymbolLoaderTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Runner/ApiCompatRunnerTests.cs
Labels: Area-ApiCompat

#26916 Fix StatInterop to include new signature
  src/Cli/dotnet/StatInterop.cs
Labels: Area-Infrastructure

#26627 Trim response file lines to prevent forwarding along whitespace-only tokens
  src/Cli/dotnet/Parser.cs
Labels: Area-Infrastructure

#26966 [Blazor] Update SDK to account for the crypto worker file
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/BootJsonData.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs
  src/BlazorWasmSdk/Tasks/ComputeBlazorPublishAssets.cs
  src/BlazorWasmSdk/Tasks/GenerateBlazorWebAssemblyBootJson.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
Labels: Area-AspNetCore

#26989 Enable nullable for the mapper types and code clean-up
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/ElementContainer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblySetMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/MemberMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/NamespaceMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/TypeMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
Labels: Area-ApiCompat

#27020 CFS tool configuration for templating testfile
  .sscignore
  src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithConditions/nuget.config
Labels: Area-Infrastructure

#27030 Fix the loc build and the CI build
  eng/build.yml
Labels: Area-Infrastructure

#27035 Fix job OneLocBuild is added duplicately by template engine job
  eng/build.yml
Labels: Area-Infrastructure

#27053 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#27055 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#26994 Fix exception message when using an argument without a required value.
  src/Cli/dotnet/Telemetry/TopLevelCommandNameAndOptionToLog.cs
Labels: Area-Infrastructure

#27021 Removed own implementation of Reporter in `TemplateEngine.Cli`
  src/Cli/Microsoft.TemplateEngine.Cli/AnsiColorExtensions.cs
  src/Cli/Microsoft.TemplateEngine.Cli/AnsiConsole.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/BaseCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.Help.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.NoMatchHandling.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.TabCompletion.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Microsoft.TemplateEngine.Cli.csproj
  src/Cli/Microsoft.TemplateEngine.Cli/NuGet/CliNuGetLogger.cs
  src/Cli/Microsoft.TemplateEngine.Cli/PostActionDispatcher.cs
  src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors/AddProjectsToSolutionPostAction.cs
  src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors/AddReferencePostActionProcessor.cs
  src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors/ChmodPostActionProcessor.cs
  src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors/DotnetRestorePostActionProcessor.cs
  src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors/InstructionDisplayPostActionProcessor.cs
  src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors/ProcessStartPostActionProcessor.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Reporter.cs
  src/Cli/Microsoft.TemplateEngine.Cli/ReporterExtensions.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TabularOutput/TemplateGroupDisplay.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateInvoker.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateListCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateSearch/CliHostSearchCacheData.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateSearch/CliTemplateSearchCoordinator.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/Microsoft.TemplateEngine.Cli.UnitTests.csproj
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/HelpTests.Resolution.cs
Labels: Area-Infrastructure

#27057 [Blazor] Handle _GlobalPropertiesToRemoveFromProjectReferences in the SDK
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
Labels: Area-AspNetCore

#27024 Support left and right names for assembly set
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/ElementContainer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblySetMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/MemberMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/NamespaceMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/TypeMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/MetadataInformation.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ComparingSettings.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunnerFactory.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CustomSideNameTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddAbstractMemberTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddMemberToInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotRemoveBaseTypeOrInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotSealTypeTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Runner/ApiCompatRunnerTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SymbolFactory.cs
Labels: Area-ApiCompat

#27054 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#27090 Remove SystemInformation dependency
  src/Cli/Microsoft.DotNet.Cli.Utils/Interop.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Windows.cs
  src/Cli/dotnet/Installer/Windows/Interop.cs
  src/Cli/dotnet/Installer/Windows/WindowsUtils.cs
Labels: Area-Workloads

#27095 Fix registry redirection
  src/Cli/dotnet/Installer/Windows/WindowsUtils.cs
Labels: Area-Workloads

#27091 Fix templating to be source-buildable
  eng/Versions.props
  source-build.slnf
  src/Cli/Microsoft.TemplateEngine.Cli/Microsoft.TemplateEngine.Cli.csproj
Labels: Area-Infrastructure

#27102 [Blazor] Allow customizing the static web assets base manifest paths if defined by the environment
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
Labels: Area-AspNetCore

#27087 Adding support for VS Designtime targets for worker projects
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.targets
Labels: Area-WebSDK

#27107 Include templating in source-build
  eng/Version.Details.xml
Labels: Area-Infrastructure

#27064 Fix for --print-download-link only
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/IWorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Tests/dotnet-workload-install.Tests/MockWorkloadManifestUpdater.cs
Labels: Servicing-consider, Area-Infrastructure

#27086 Parser for actual MSBuild Property option syntax
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs
  src/Cli/dotnet/OptionForwardingExtensions.cs
  src/Tests/dotnet.Tests/ParserTests/MSBuildArgumentCommandLineParserTests.cs
Labels: Bug, Servicing-approved, Area-CLI

#27159 Corresponding PublishAOT changes to match the runtime cleanup changes
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-Infrastructure

#27181 Don't calculate package path manually
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
Labels: Area-ApiCompat

#27155 Clean-up rules (styling) and make CompatDifference a readonly struct
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/CompatDifference.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/IDiagnostic.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddMemberToInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotSealType.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/EnumsMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
Labels: Area-ApiCompat

#27199 Support different Windows SDK package versions for different target frameworks
  src/Tasks/Microsoft.NET.Build.Tasks/CreateWindowsSdkKnownFrameworkReferences.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsDesktopProject.cs
Labels: Servicing-approved

#27108 .NET 6 Fix .NET MAUI Blazor Scoped CSS Hot Reload
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
Labels: Servicing-approved, Area-AspNetCore

#27203 Support multiple unique assembly ids in packages and tasks
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/CompatDifference.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/MetadataInformation.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DefaultSymbolsEqualityComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DifferenceVisitorFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IDifferenceVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddMemberToInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotSealType.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/EnumsMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/IRuleContext.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/IRuleRunner.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleContext.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/ApiCompatRunnerExtensions.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Package.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/BaselinePackageValidator.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/CompatibleFrameworkInPackageValidator.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/CompatibleTFMValidator.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/AssertExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CompatDifferenceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CustomSideNameTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AssemblyIdentityMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddAbstractMemberTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddMemberToInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddOrRemoveVirtualKeywordTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotRemoveBaseTypeOrInterfaceTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotSealTypeTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/EnumsMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.Strict.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/TypeMustExistTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Runner/ApiCompatRunnerTests.cs
Labels: Area-ApiCompat

#27197 Support directories and globs as lefts and rights
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
Labels: Area-ApiCompat

#26811 Stop double copying all of the watch and format files.
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure

#27237 Support loading assembly references when multiple assemblies are passed to the AssemblySymbolLoader
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/IApiCompatServiceProviderModule.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IAssemblySymbolLoader.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IMetadataStreamProvider.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/MetadataStreamProvider.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunnerWorkItem.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/CompatibleFrameworkInPackageValidatorIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Task/ValidatePackageTargetIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/AssemblySymbolLoaderTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Runner/ApiCompatRunnerTests.cs
Labels: Area-ApiCompat

#27194 Loc fix in ApiCompat
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
Labels: Area-ApiCompat

#27209 Port predownload changes into .3xx
  build/RunTestsOnHelix.cmd
  src/Tests/UnitTests.proj
Labels: Area-Infrastructure

#27178 Port pre-download changes into the 6.0.4xx branch
  build/RunTestsOnHelix.cmd
  src/Tests/UnitTests.proj
Labels: Area-Infrastructure

#27208 Port predownload changes into 6.0.1xx
  build/RunTestsOnHelix.cmd
  src/Tests/UnitTests.proj
Labels: Area-Infrastructure

#27233 Use Logger and apply fix in AssemblyIdentity rule
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/IApiCompatServiceProviderModule.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblySetMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/IRuleContext.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleContext.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/CompatibleFrameworkInPackageValidatorIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Microsoft.DotNet.ApiCompat.IntegrationTests.csproj
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Task/ValidateAssembliesTargetIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Task/ValidatePackageTargetIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AssemblyIdentityMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/TestLogger.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Microsoft.DotNet.PackageValidation.Tests.csproj
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Validators/BaselinePackageValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Validators/CompatibleTFMValidatorTests.cs
Labels: Area-ApiCompat

#26676 Handle error when status runtime information cannot find version in productCollection.
  src/Cli/dotnet/commands/dotnet-sdk/check/BundleOutputWriter.cs
  src/Cli/dotnet/commands/dotnet-sdk/check/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-sdk/check/RuntimeOutputWriter.cs
  src/Cli/dotnet/commands/dotnet-sdk/check/SdkOutputWriter.cs
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure

#27255 Remove obsolete diagnostic message in ApiCompatRunner
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
Labels: Area-ApiCompat

#27201 Update Blazor WASM Baselines for new files
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
Labels: Area-Infrastructure, DO NOT MERGE

#26963 Fix dotnet test --blame parameters to validate incoming values, and update help
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-DotNet Test

#27317 Fix typos in Runtime Configuration Files doc
  documentation/specs/runtime-configuration-file.md
Labels: Area-Infrastructure

#21986 Update handling of SelfContained and RuntimeIdentifier properties when specified on the command line
  documentation/general/SelfContainedBreakingChangeNotification.md
  src/Tasks/Microsoft.NET.Build.Tasks/ValidateExecutableReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThereAreDefaultItems.cs
  src/Tests/Microsoft.NET.Build.Tests/GlobalPropertyFlowTests.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/DotnetBuildCommand.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
  src/Tests/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
Labels: Area-NetSDK

#27321 Use SymbolComparer in MembersMustExist rule
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
Labels: Area-ApiCompat

#27296 Switch localization to 7.0.1xx release branch
  eng/build.yml
Labels: Area-Infrastructure

#27223 dotnet new: switched telemetry to use `TelemetryEventEntry`
  src/Cli/Microsoft.DotNet.Cli.Utils/Sha256Hasher.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/BaseCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/NewCommand.Legacy.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/NewCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/alias/AliasAddCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/alias/AliasCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/alias/AliasShowCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/alias/BaseAliasAddCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/alias/BaseAliasShowCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/alias/LegacyAliasAddCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/alias/LegacyAliasShowCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/install/BaseInstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/install/InstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/install/LegacyInstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/list/BaseListCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/list/LegacyListCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/list/ListCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/search/BaseSearchCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/search/LegacySearchCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/search/SearchCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/uninstall/BaseUninstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/uninstall/LegacyUninstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/uninstall/UninstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/BaseUpdateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/LegacyUpdateApplyCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/LegacyUpdateCheckCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/UpdateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/ITelemetryLogger.cs
  src/Cli/Microsoft.TemplateEngine.Cli/NewCommandFactory.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TelemetryConstants.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TelemetryHelper.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TelemetryLogger.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateInvoker.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateListCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/dotnet-new3/New3CommandFactory.cs
  src/Cli/dotnet/commands/dotnet-internal-reportinstallsuccess/InternalReportinstallsuccessCommand.cs
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/HelpTests.Resolution.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/HelpTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/InstallTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/InstantiateTests.NoMatchHandling.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/InstantiateTests.Subcommand.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/InstantiateTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/ListTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/MiscTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/SearchTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/TabCompletionTests.Approval.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/TabCompletionTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/TemplateCommandTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/UninstallTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/UpdateTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/TelemetryHelperTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/TemplateResolutionTests/ListTemplateResolverTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/TemplateSearchCoordinatorTests.cs
  src/Tests/Microsoft.TemplateEngine.EndToEndTestHarness/Program.cs
Labels: area: dotnet new

#26891 add rule for detecting attribute differences
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/NullableAttributes.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AttributesMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AttributesMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/TempDirectory.cs
Labels: Area-ApiCompat

#27322 Only reference the needed packages
  eng/Versions.props
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
Labels: Area-ApiCompat

#27362 Fix resolving assembly reference paths from dirs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/AssemblySymbolLoader.cs
Labels: Area-ApiCompat

#27330 added and altered readme files after moving `dotnet new` and templates
  README.md
  src/Cli/dotnet/commands/dotnet-new/README.md
  template_feed/README.md
Labels: Area-Templates, area: dotnet new

#27328 Add solution filter for template engine
  TemplateEngine.slnf
Labels: Area-Infrastructure, area: dotnet new

#27361 Added support of C#11 to templates
  .editorconfig
  src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.7.0/content/ClassLibrary-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.7.0/content/ConsoleApplication-CSharp/.template.config/template.json
Labels: Servicing-approved, Area-Templates

#27419 Update Microsoft.Web.Xdt version
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-CodeFlow

#27380 add rule to detect change in method parameter names
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotChangeParameterName.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/ParameterNamesCannotChangeTests.cs
Labels: Area-ApiCompat

#27431 ApiCompat/AttributesMustMatch: add test case for attributes with array and type arguments
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AttributesMustMatchTests.cs
Labels: Area-ApiCompat

#27425 Move non-eng-common builds to NetCore1ESPool-Svc-* version
  .vsts-ci-richnav.yml
  .vsts-ci.yml
  eng/template-engine.yml
Labels: Area-Infrastructure

#27454 Add EnableRuleAttributesMustMatch switch
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AttributesMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleFactory.cs
Labels: Area-ApiCompat

#27465 Build 7.0.1xx branches internally
  .vsts-ci.yml
Labels: Area-Infrastructure

#27426 Move 7.0.1xx (sans eng/common) to -Svc build pools
  .vsts-ci-richnav.yml
  .vsts-ci.yml
  eng/template-engine.yml
Labels: Area-Infrastructure

#27458 Update dotnet tool update description.
  src/Cli/dotnet/commands/dotnet-tool/update/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Tools

#27421 emit diagnostic for adding sealed to interface member
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddOrRemoveVirtualKeywordTests.cs
Labels: Area-ApiCompat

#27500 apicompat: sort suppressions
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/SuppressionEngine.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Logging/SuppressionEngineTests.cs
Labels: Area-ApiCompat

#27457 Added `new` to the list of commands to track the second verb
  src/Cli/dotnet/Telemetry/TelemetryFilter.cs
Labels: area: dotnet new

#27554 Pass in reference assemblies to ApiCompat
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.NonCrossTargeting.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
Labels: Area-ApiCompat

#27574 Update AOT test (#27334)
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-Infrastructure

#27193 Update ubuntu version
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Assets/TestProjects/VSTestForwardDotnetRootEnvironmentVariables/VSTestForwardDotnetRootEnvironmentVariables.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure

#26306 Removing default ProduceReferenceAssembly value for F#
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FSharp.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
Labels: Area-Infrastructure

#27601 apicompat: treat IntPtr as nint and UIntPtr as nuint
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Extensions/SymbolExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
Labels: Area-ApiCompat
