Repository dotnet/sdk, pull requests merged in 2022-04, with the labels that each got.

#24702 Revert "deploy common roslyn assemblies used by multiple dotnet tools"
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure

#24701 Revert "deploy common roslyn assemblies used by multiple dotnet tools"
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure

#24707 Fix broken blog post link
  src/Cli/Microsoft.DotNet.Cli.Utils/ArgumentEscaper.cs
  src/RazorSdk/Tool/CommandLine/ArgumentEscaper.cs
Labels: Area-Infrastructure

#24770 Don't retarget testhost
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-DotNet Test

#24662 Add a netsdk code to the preview message so we can support things like nowarn and documentation
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Area-NetSDK

#24795 [release/6.0.2xx] Add source-build metadata to razor-compiler
  eng/Version.Details.xml
Labels: Area-Infrastructure

#24794 Add SourceBuild metadata to razor-compiler dependencies
  eng/Version.Details.xml
Labels: Area-Infrastructure

#24796 [release/6.0.3xx] Add source-build metadata to razor-compiler
  eng/Version.Details.xml
Labels: Area-Infrastructure

#24710 Update branding to 3.1.419
  eng/Versions.props
Labels: Area-Infrastructure

#24713 Update branding to 6.0.105
  eng/Versions.props
Labels: Area-Infrastructure

#24714 Update branding to 6.0.203
  eng/Versions.props
Labels: Area-Infrastructure

#24711 Update branding to 5.0.214
  eng/Versions.props
Labels: Area-Infrastructure

#24712 Update branding to 5.0.408
  eng/Versions.props
Labels: Area-Infrastructure

#24820 Merging internal commits for release/5.0.2xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#24822 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#24821 Merging internal commits for release/6.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#24819 Merging internal commits for release/5.0.4xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#24661 Turn test back on.
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishIncrementally.cs
Labels: Area-Infrastructure

#24831 Stabilize branding for the SDK 6.0.300
  eng/Versions.props
Labels: Area-Infrastructure

#24836 Update the hardcoded net6.0 to the current framework
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenFrameworkReferences.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibraryWithOSSupportedVersion.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/Tests/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishTrimmedWindowsFormsAndWPFApps.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/MergeConfigurationPropertiesTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
  src/Tests/dotnet-add-reference.Tests/GivenDotnetAddReference.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRootEnv.cs
Labels: Area-Infrastructure

#23881 Update the hardcoded net5.0 to the current framework
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/AssemblySymbolLoaderTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/CompatibleFrameworksInPackageTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenFrameworkReferences.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeHaveAPackageReferenceWithAliases.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToResolveConflicts.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/dotnet-add-package.Tests/GivenDotnetPackageAdd.cs
  src/Tests/dotnet-add-reference.Tests/GivenDotnetAddReference.cs
  src/Tests/dotnet-restore.Tests/GivenThatIWantToRestoreApp.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromCsprojForMultipleTFM.cs
  src/Tests/dotnet-watch.Tests/NoRestoreFilterTest.cs
Labels: Area-Infrastructure

#24871 Update specific package versions
  src/Assets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  src/Assets/TestPackages/dotnet-portable-v1-prefercli/dotnet-portable-v1-prefercli.csproj
  src/Assets/TestPackages/dotnet-portable-v1/dotnet-portable-v1.csproj
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
Labels: Area-Infrastructure

#24927 [release/6.0.3xx] Ensure stable property is set on asset manifest
  eng/Publishing.props
Labels: Area-Infrastructure

#24922 Switch updates to include for the targeted package references
  src/Assets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  src/Assets/TestPackages/dotnet-portable-v1-prefercli/dotnet-portable-v1-prefercli.csproj
  src/Assets/TestPackages/dotnet-portable-v1/dotnet-portable-v1.csproj
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishIncrementally.cs
Labels: Area-Infrastructure

#24968 Expand the system.private.uri coverage to the .net core builds and ad…
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
Labels: Area-Infrastructure

#24589 Add a fabricbot.json file to auto close issues with "Area-NuGet" label
  .github/fabricbot.json
Labels: Area-Infrastructure

#24958 Update the wasm install to skip manifest updates
  eng/build.yml
Labels: Area-Infrastructure

#24693 Publish support in SDK for Native Aot Application
  eng/Version.Details.xml
  eng/Versions.props
  src/Layout/redist/targets/BundledSdks.targets
  src/Layout/toolset-tasks/OverrideAndCreateBundledNETCoreAppPackageVersion.cs
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILCompiler.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-Infrastructure

#25038 Fix copy-paste mistakes
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
Labels: Area-Infrastructure

#25018 Update SDK to 6.0.4
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#25023 Try to update a couple of more versions of the cryptography file
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/TestApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/dotnet.new.project.lock.json
Labels: Area-Infrastructure

#25049 Update baselines for Blazor static web assets
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
Labels: Area-AspNetCore

#25054 Reduce parallel copies of the test .zip file that were overlapping
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests.csproj
Labels: Area-Infrastructure

#24971 Allow file changes from tar as it's just a warning
  src/Tests/HelixTasks/TarGzFileCreateFromDirectory.cs
Labels: Area-Infrastructure

#25021 Lingering use of System.Private.Uri v.old
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
Labels: Area-Infrastructure

#25081 Update the lock file to a newer version to see if that helps.
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/dotnet.new.project.lock.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/simple.dependencies.project.lock.json
Labels: Area-Infrastructure

#25056 Change tests to target 4.6.2 instead of 4.6.1
  src/Assets/DesktopTestProjects/MultiTFMXunitProject/XUnitProject/XUnitProject.csproj
  src/Assets/DesktopTestProjects/NETFrameworkReferenceNETStandard20/MultiTFMTestApp/MultiTFMTestApp.csproj
  src/Assets/DesktopTestProjects/NETFrameworkReferenceNETStandard20/TestApp/TestApp.csproj
  src/Assets/TestProjects/DesktopAppWithLibrary-NonSDK/TestApp/TestApp.csproj
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/TestApp.csproj
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/packages.config
  src/Assets/TestProjects/DesktopAppWithLibrary/TestApp/TestApp.csproj
  src/Assets/TestProjects/RazorSimpleMvc21NetFx/SimpleMvc21NetFx.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolvePackageDependenciesTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenWriteAppConfigWithSupportedRuntimeTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFileSnippets.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/dotnet.new.project.lock.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/simple.dependencies.project.lock.json
  src/Tests/EndToEnd.Tests/GivenNetFrameworkSupportsNetStandard2.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ApiCompatRunnerTests.cs
  src/Tests/Microsoft.NET.Build.Tests/AspNetCoreOnFullFramework.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExe.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExeWtihNetStandardLib.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopLibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithoutTransitiveProjectRefs.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToPreserveCompilationContextForBuild.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetNet471.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatThereAreImplicitPackageReferences.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackANetFrameworkLibrary.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishWithoutConflicts.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishNetFrameworkApp.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreProjectsUsingNuGetConfigProperties.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTest21NetFx.cs
  src/Tests/dotnet-watch.Tests/MsBuildFileSetFactoryTest.cs
Labels: Area-Infrastructure

#24650 Update ubuntu version
  .vsts-ci.yml
  src/Assets/TestPackages/dotnet-hello/v1/dotnet-hello/dotnet-hello.csproj
  src/Assets/TestPackages/dotnet-hello/v2/dotnet-hello/dotnet-hello.csproj
  src/Assets/TestProjects/AppWithCorruptedLaunchSettings/AppWithCorruptedLaunchSettings.csproj
  src/Assets/TestProjects/AppWithLaunchSettings/AppWithLaunchSettings.csproj
  src/Assets/TestProjects/AppWithLaunchSettingsNoDefault/AppWithLaunchSettingsNoDefault.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Assets/TestProjects/MSBuildTestApp/MSBuildTestApp.csproj
  src/Tests/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs
Labels: Area-Infrastructure

#24973 update exception message for invalid rollback file
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/ManifestVersion.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Strings.resx
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.cs.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.de.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.es.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.fr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.it.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ja.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ko.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pl.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pt-BR.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ru.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.tr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hans.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hant.xlf
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: Area-Workloads

#25126 Force rebuilding R2R images if project files have been changed
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
Labels: Area-ReadyToRun

#25151 Fix typo in GivenThatWeWantToPublishReadyToRun.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
Labels: Area-ReadyToRun
