Repository dotnet/sdk, pull requests merged in 2022-10, with the labels that each got.

#28278 don't issue diagnostic when virtual is removed from member in sealed type
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddOrRemoveVirtualKeywordTests.cs
Labels: Area-ApiCompat

#28301 [release/7.0.1xx] Fix msbuild evaluation of ApiCompat task pkg
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.Task.targets
Labels: Servicing-approved, Area-ApiCompat

#28321 Update branding to 3.1.425
  eng/Versions.props
Labels: Area-Infrastructure

#28336 Add missing EnableRuleAttributesMustMatch task parameter
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
Labels: Area-ApiCompat

#28330 Enable codeql
  .vsts-ci.yml
Labels: Area-Infrastructure

#28338 [release/7.0.1xx] Add missing EnableRuleAttributesMustMatch task property
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
Labels: Servicing-approved, Area-ApiCompat

#28224 Add warning when targeting 7.0 in 17.3 and remove 7.0 from the list of supported targets
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props
Labels: Servicing-approved, Area-Infrastructure

#28348 normalize accessibility when not including internal symbols
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotChangeVisibility.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotChangeVisibilityTests.cs
Labels: Area-ApiCompat

#28304 Switch to 7.0.2xx for loc build
  eng/build.yml
Labels: Area-Infrastructure

#28327 Fix checking for updated workload packs in advertising manifests
  src/Assets/TestProjects/SampleManifest/MockListSampleUpdated.json
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
Labels: Servicing-consider, Area-Workloads

#28369 [release/7.0.1xx] Disable msbuild server by default
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
Labels: Servicing-approved, Area-CLI

#28404 [release/7.0.1xx] backport APICompat changes for GA
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AttributesMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotChangeVisibility.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AttributesMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddOrRemoveVirtualKeywordTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotChangeVisibilityTests.cs
Labels: Servicing-approved, Area-ApiCompat

#27964 Avoid extra copies of dotnet-watch build outputs in the SDK directory
  src/Layout/redist/redist.csproj
Labels: Area-Infrastructure, Area-Watch

#28430 6.0.1xx branding and test disablement
  eng/Versions.props
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/JsModulesIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-Infrastructure

#28194 Update windows images for release/6.0.1xx
  .vsts-ci-richnav.yml
  .vsts-ci.yml
Labels: Area-Infrastructure

#27943 Expand existing EOL warning to target 5.0
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetEolFrameworks.cs
Labels: Servicing-approved

#28324 Update branding to 6.0.403
  eng/Versions.props
Labels: Area-Infrastructure

#28323 Update branding to 6.0.306
  eng/Versions.props
Labels: Area-Infrastructure

#28428 Add actionable output to templating destructive changes notification
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateInvoker.cs
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CannotOverwriteFilesWithoutForce.verified.txt
  src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.Approval.cs
Labels: Area-dotnet new

#27859 revert perma-escaping of semicolons and support semicolon-delimited unquoted property values
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs
  src/Cli/dotnet/OptionForwardingExtensions.cs
  src/Tests/dotnet.Tests/ParserTests/MSBuildArgumentCommandLineParserTests.cs
Labels: Bug, Servicing-approved, Area-CLI

#28425 [release/7.0.1xx] Reference net7.0 version of msbuild for source-build
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
Labels: Area-Infrastructure

#28400 Add an official builder assembly attribute
  src/Common/CompileOptions.cs
Labels: Area-Infrastructure

#28380 ResolveReadyToRunCompilers: map non-portable rids when targetOS is determined.
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: Area-Infrastructure

#28485 Stable branding
  eng/Versions.props
Labels: Area-Infrastructure

#27971 Add --ucr shorthand for --use-current-runtime
  src/Cli/dotnet/CommonOptions.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
Labels: Area-CLI, Priority:3, cli-ux

#27973 Add Description to Workload --info
  src/Cli/dotnet/commands/dotnet-workload/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-CLI, Priority:3, cli-ux

#28477 [GA / 7.0.1xx Internal -> External Port] Fix SDK Temp Paths
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Cli/Microsoft.DotNet.InternalAbstractions/DirectoryWrapper.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/FilePath.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/IDirectory.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/Microsoft.DotNet.InternalAbstractions.csproj
  src/Cli/Microsoft.DotNet.InternalAbstractions/TemporaryDirectory.cs
  src/Cli/dotnet/ShellShim/ShellShimRepository.cs
  src/Cli/dotnet/SudoEnvironmentDirectoryOverride.cs
  src/Cli/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/dotnet.csproj
  src/Common/PathUtilities.cs
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Interop.cs
  src/Tasks/Common/FileUtilities.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenAFirstTimeUseNoticeSentinel.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenAFunctionReturnStringAndFakeFileSystem.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/ToolPackageInstallerTests.cs
  src/Tests/Microsoft.NET.TestFramework/Mock/FileSystemMockBuilder.cs
Labels: Area-Infrastructure, Priority:0

#28512 Trusted roots: 2022-09 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure

#28135 Improve the example with specified language when language option is given with invalid option
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.NoMatchHandling.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateOptionResult.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateResult.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/InstantiateTests.NoMatchHandling.cs
  src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.cs
Labels: Area-dotnet new

#28541 Trusted roots: 2022-09 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Servicing-approved, Area-Infrastructure

#28548 [Internal to External Port] Templating Nuget Config Changes, MSBuild
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolvePackageAssetsTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Mocks/MockPackageResolver.cs
  src/Tasks/Microsoft.NET.Build.Tasks/IPackageResolver.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetEolFrameworks.cs
  src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.cs.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.en.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.es.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.fr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.it.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.ja.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.ko.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.pl.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.pt-BR.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.ru.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.tr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.zh-Hans.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/localize/templatestrings.zh-Hant.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Nuget/.template.config/template.json
  testAsset.props
Labels: Area-Infrastructure, Area-NuGet, Priority:0, Area-dotnet new

#28559 Change the build machine to have a larger hard drive
  .vsts-ci.yml
Labels: Area-Infrastructure

#28467 Merging internal commits for release/3.1.4xx
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-CodeFlow

#28552 The loc build changes didn't flow to main so going directly.
  eng/build.yml
Labels: Area-Infrastructure

#28469 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Cli/Microsoft.DotNet.InternalAbstractions/DirectoryWrapper.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/FilePath.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/IDirectory.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/Microsoft.DotNet.InternalAbstractions.csproj
  src/Cli/Microsoft.DotNet.InternalAbstractions/TemporaryDirectory.cs
  src/Cli/dotnet/NugetPackageDownloader/FirstPartyNuGetPackageSigningVerifier.cs
  src/Cli/dotnet/ShellShim/ShellShimRepository.cs
  src/Cli/dotnet/SudoEnvironmentDirectoryOverride.cs
  src/Cli/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Common/PathUtilities.cs
  src/Tasks/Common/FileUtilities.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenAFirstTimeUseNoticeSentinel.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenAFunctionReturnStringAndFakeFileSystem.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/ToolPackageInstallerTests.cs
  src/Tests/Microsoft.NET.TestFramework/Mock/FileSystemMockBuilder.cs
Labels: Area-Infrastructure

#28470 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Cli/Microsoft.DotNet.InternalAbstractions/DirectoryWrapper.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/FilePath.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/IDirectory.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/Microsoft.DotNet.InternalAbstractions.csproj
  src/Cli/Microsoft.DotNet.InternalAbstractions/TemporaryDirectory.cs
  src/Cli/dotnet/NugetPackageDownloader/FirstPartyNuGetPackageSigningVerifier.cs
  src/Cli/dotnet/ShellShim/ShellShimRepository.cs
  src/Cli/dotnet/SudoEnvironmentDirectoryOverride.cs
  src/Cli/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Common/PathUtilities.cs
  src/Tasks/Common/FileUtilities.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenAFirstTimeUseNoticeSentinel.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenAFunctionReturnStringAndFakeFileSystem.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/ToolPackageInstallerTests.cs
  src/Tests/Microsoft.NET.TestFramework/Mock/FileSystemMockBuilder.cs
Labels: Area-Infrastructure, Priority:0

#28295 [dotnet-new] Add inRoot option for AddProjectsToSolutionPostAction
  TemplateEngine.slnf
  src/Assets/TestPackages/dotnet-new/Microsoft.TemplateEngine.TestTemplates.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectToSolution/BasicInSolutionRoot/.template.config/template.json
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectToSolution/BasicInSolutionRoot/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectToSolution/BasicInSolutionRoot/Program.cs
  src/Cli/dotnet/commands/dotnet-new/DotnetCommandCallbacks.cs
  src/Cli/dotnet/commands/dotnet-new/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-new/PostActions/DotnetSlnPostActionProcessor.cs
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-new.Tests/PostActionTests.cs
  src/Tests/dotnet.Tests/dotnet-new/DotnetSlnPostActionTests.cs
Labels: Area-dotnet new

#28662 Fix parsing for arguments ending with dll/exe
  src/Cli/dotnet/commands/dotnet-test/Program.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromDll.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Area-DotNet Test

#28627 Return workload manifests in defined, controllable order
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
Labels: Servicing-approved, Area-Workloads

#28623 Run less tests per Helix Proc to Increase Pipeline Performance
  src/Tests/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
Labels: Infrastructure

#28636 Fix typo in tab-completion.md
  documentation/general/tab-completion.md
Labels: Area-Infrastructure

#28628 Allow Implicit RID Opt Out + Don't Infer RID for non EXE Type Projects
  src/Assets/TestProjects/AppWithLibrarySDKStyleThatPublishesSingleFile/Program.cs
  src/Assets/TestProjects/AppWithLibrarySDKStyleThatPublishesSingleFile/lib/Class1.cs
  src/Assets/TestProjects/AppWithLibrarySDKStyleThatPublishesSingleFile/lib/lib.csproj
  src/Assets/TestProjects/AppWithLibrarySDKStyleThatPublishesSingleFile/newc.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileLibrary.cs
  src/Tests/Microsoft.NET.Publish.Tests/RuntimeIdentifiersTests.cs
Labels: Bug, Servicing-consider

#28553 Adding some loc locked tags
  src/Cli/dotnet/commands/dotnet-new/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure

#28677 Create workloads enumerator lazily in dotnet-new host
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/Cli/dotnet/commands/dotnet-new/WorkloadsInfoProvider.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Tests/dotnet.Tests/dotnet-new/WorkloadsInfoProviderTests.cs
Labels: Area-Infrastructure, Area-dotnet new

#28422 Use latest docker containers
  .vsts-ci.yml
  eng/template-engine.yml
Labels: Area-Infrastructure

#28333 [dotnet tool] Add ability to check if a tool is installed
  src/Cli/dotnet/commands/dotnet-tool/list/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListCommandParser.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet.Tests/CommandTests/ToolListGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolListLocalCommandTests.cs
Labels: Area-Tools

#28736 [Cherrypick main->7.0.2xx] Create workloads enumerator lazily in dotnet-new host
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/Cli/dotnet/commands/dotnet-new/WorkloadsInfoProvider.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Tests/dotnet.Tests/dotnet-new/WorkloadsInfoProviderTests.cs
Labels: Area-dotnet new

#28608 Ensure workload installers can be read by other users
  src/Cli/dotnet/Installer/Windows/MsiPackageCache.cs
Labels: Area-Workloads

#28484 RuntimeIdentifiers Code Coverage + Implicit RuntimeIdentifiers (not just runtimeIdentifier)
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Publish.Tests/RuntimeIdentifiersTests.cs
Labels: Area-ILLink
