Repository dotnet/sdk, pull requests merged in 2022-01, with the labels that each got.

#23229 Backport changes from main
  src/Assets/TestProjects/WatchAppWithLaunchSettings/Program.cs
  src/Assets/TestProjects/WatchAppWithLaunchSettings/Properties/launchSettings.json
  src/Assets/TestProjects/WatchAppWithLaunchSettings/WatchAppWithLaunchSettings.csproj
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/Utilities/WatchableApp.cs
Labels: Area-AspNetCore

#22879 upgrade ubuntu version
  .vsts-ci.yml
  eng/restore-toolset.sh
  src/Assets/TestProjects/AllResourcesInSatellite/AllResourcesInSatellite.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/SimpleDependencies/SimpleDependencies.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantAllResourcesInSatellite.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithLibrariesAndRid.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithLibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithTransitiveProjectRefs.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/PublishCommand.cs
Labels: Area-Infrastructure

#23211 cherry-pick "include props and targets for code style packages"
  src/Layout/redist/targets/GenerateLayout.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
Labels: Area-Infrastructure

#23022 Update .vsts-ci.yml
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithLibrariesAndRid.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAppWithLibrariesAndRid.cs
Labels: Area-Infrastructure

#23249 Opt into IEventSource4
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildLogger.cs
Labels: Area-NetSDK

#23164 fixes dotnet/sdk#23162 dotnet new console --help doesn't work starting 6.0.2xx
  src/Cli/dotnet/Parser.cs
  src/Tests/dotnet-new.Tests/NewCommandTests.cs
Labels: Area-Infrastructure

#23059 Merging internal commits for release/5.0.2xx
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  eng/runHelixAndNonHelixInParallel.ps1
Labels: Area-Infrastructure

#23236 reenable test
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
Labels: Area-Infrastructure

#23060 Merging internal commits for release/3.1.4xx
  .vsts-ci.yml
Labels: Area-Infrastructure

#23280 Add an environment variable to prevent prompting rude edits (#22891)
  src/BuiltInTools/dotnet-watch/HotReload/RudeEditPreference.cs
Labels: Area-AspNetCore

#22927 Handle the case when procfs is inaccessible
  src/Cli/dotnet/PerformanceLogEventSource.cs
  src/Cli/dotnet/Telemetry/DockerContainerDetectorForTelemetry.cs
Labels: Area-Infrastructure

#23285 Update Version.Details.xml to account for package renames
  eng/Version.Details.xml
Labels: Area-Infrastructure

#23321 Pin Microsoft.CodeAnalysis version for API Compat to the 4.0.x stable package.
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
Labels: Area-Compatibility

#23284 Update runHelixAndNonHelixInParallel.ps1
  eng/runHelixAndNonHelixInParallel.ps1
Labels: Area-Infrastructure

#23316 Catch dotnet watch task cancellation after `CTRL+C`
  src/BuiltInTools/dotnet-watch/HotReload/CompilationWorkspaceProvider.cs
Labels: Area-AspNetCore

#22676 [release/6.0.1xx] bump the error number for CompressionInSingleFileRequiresSelfContained
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Servicing-approved

#23309 Add an option to run dotnet-watch in non-interactive mode
  src/Assets/TestProjects/WatchAppWithLaunchSettings/Program.cs
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/BuiltInTools/dotnet-watch/DotNetWatchOptions.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
Labels: Area-AspNetCore

#23324 Update old preview aka.ms link
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Area-Infrastructure

#23358 Better caching for RazorSourceGenerator when SuppressRazorSourceGener…
  src/RazorSdk/SourceGenerators/IncrementalValueProviderExtensions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerationOptions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/RazorSourceGeneratorComparer.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGenerationOptionsTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorComparerTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-AspNetCore

#23386 [release/6.0.2xx] Backport Catch dotnet watch task cancellation (#23316)
  src/BuiltInTools/dotnet-watch/HotReload/CompilationWorkspaceProvider.cs
Labels: Area-AspNetCore

#23231 I noticed that another test handled this better so cleaning up the test code.
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithLibrariesAndRid.cs
Labels: Area-Infrastructure

#23409 Upgrade Test Platform and fix tests
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Area-DotNet Test

#23434 Fixed vstest version in release/6.0.2xx
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-DotNet Test

#23447 Forward Port `dotnet watch` emoji changes
  src/BuiltInTools/dotnet-watch/DotNetWatchOptions.cs
  src/BuiltInTools/dotnet-watch/DotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Filters/LaunchBrowserFilter.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/ScopedCssFileHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/StaticFileHandler.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/ConsoleReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/ConsoleRequester.cs
  src/BuiltInTools/dotnet-watch/Internal/NullReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/PhysicalConsole.cs
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Tests/dotnet-watch.Tests/BrowserLaunchTests.cs
  src/Tests/dotnet-watch.Tests/CommandLineOptionsTests.cs
  src/Tests/dotnet-watch.Tests/ConsoleReporterTests.cs
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/GlobbingAppTests.cs
  src/Tests/dotnet-watch.Tests/MsBuildFileSetFactoryTest.cs
  src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
  src/Tests/dotnet-watch.Tests/Utilities/WatchableApp.cs
Labels: Area-AspNetCore

#23266 Build Microsoft.NET.Build.Tasks for netfx during source-build
  src/Compatibility/Microsoft.DotNet.Compatibility/Microsoft.DotNet.Compatibility.csproj
  src/Compatibility/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-Infrastructure

#23470 Allow skipping ILLink target
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
Labels: Area-ILLink

#23483 Allow pdb deltas to be applied to Blazor WASM app
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-AspNetCore

#23489 Prevent errors when building a 5.0 app with .cshtml.css files
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.targets
  src/RazorSdk/Tasks/DiscoverDefaultScopedCssItems.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/DiscoverDefaultScopedCssItemsTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTest50.cs
Labels: Area-AspNetCore

#23502 Workloads: Enable support for SxS previews
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallerFactory.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkFeatureBand.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkFeatureBandTests.cs
Labels: Area-Workloads

#23423 Update 6.0.2xx to the 6.0.102 version of the SDK
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  eng/common/build.sh
  eng/common/cross/build-rootfs.sh
  eng/common/cross/toolchain.cmake
  eng/common/native/find-native-compiler.sh
  eng/common/sdk-task.ps1
  eng/common/templates/job/execute-sdl.yml
  eng/common/templates/job/onelocbuild.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/templates/jobs/jobs.yml
  eng/common/templates/steps/send-to-helix.yml
  eng/common/tools.ps1
  eng/common/tools.sh
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
  eng/runHelixAndNonHelixInParallel.ps1
  global.json
  src/Assets/TestProjects/FSharpTestAppSimple/TestAppSimple.fsproj
  src/Common/WorkloadFileBasedInstall.cs
  src/Layout/redist/redist.csproj
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
  src/Tests/Microsoft.NET.TestFramework/TestPackageReference.cs
  src/Tests/dotnet-restore.Tests/GivenThatIWantToRestoreApp.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: Area-Infrastructure

#23519 Fix version.details entry for System.Commandline
  eng/Version.Details.xml
Labels: Area-Infrastructure

#23534 Skip restoring 1.x in Source Build
  eng/restore-toolset.sh
Labels: Area-Infrastructure

#23538 rtm Branding for 6.0.2xx
  eng/Versions.props
  eng/build.yml
Labels: Area-Infrastructure

#23419 Better caching for RazorSourceGenerator when SuppressRazorSourceGener…
  src/RazorSdk/SourceGenerators/IncrementalValueProviderExtensions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerationOptions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/RazorSourceGeneratorComparer.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGenerationOptionsTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorComparerTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-AspNetCore

#23521 `dotnet watch` test fix search console history
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
Labels: Area-Infrastructure

#23575 Switch to 1ES pools for publishing
  .vsts-ci.yml
Labels: Area-Infrastructure

#23326 Allow print rollback when non-admin.
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
Labels: Area-Workloads

#23581 Allow pdb deltas to be applied to Blazor WASM app
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-AspNetCore

#23636 Prevent errors when building a 5.0 app with .cshtml.css files
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.targets
  src/RazorSdk/Tasks/DiscoverDefaultScopedCssItems.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/DiscoverDefaultScopedCssItemsTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTest50.cs
Labels: Area-AspNetCore
