Repository dotnet/sdk, pull requests merged in 2022-11, with the labels that each got.

#28795 Update branding to 7.0.101
  eng/Versions.props
Labels: Area-Infrastructure

#28838 Update branding to 3.1.426
  eng/Versions.props
Labels: Area-Infrastructure

#28840 Update branding to 6.0.307
  eng/Versions.props
Labels: Area-Infrastructure

#28839 Update branding to 6.0.112
  eng/Versions.props
Labels: Area-Infrastructure

#28745 Update Arcade to Use svc providers - release/6.0.3xx branch
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/build.ps1
  eng/common/generate-sbom-prep.ps1
  eng/common/generate-sbom-prep.sh
  eng/common/init-tools-native.ps1
  eng/common/internal/NuGet.config
  eng/common/internal/Tools.csproj
  eng/common/templates/job/execute-sdl.yml
  eng/common/templates/job/onelocbuild.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/jobs/jobs.yml
  eng/common/templates/post-build/post-build.yml
  eng/common/tools.ps1
  global.json
Labels: Area-Infrastructure

#28841 Update branding to 6.0.404
  eng/Versions.props
Labels: Area-Infrastructure

#28605 Enable codeql in servicing
  .vsts-ci.yml
Labels: Area-Infrastructure

#28785 Switch back to the shipped RC2 build
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#27914 Fix typo in GivenThatWeWantToPublishReadyToRun.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
Labels: Area-ReadyToRun

#27542 Add Blazor SWA Baseline Mismatched Assets Logging
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/AspNetSdkBaselineTest.cs
Labels: Area-AspNetCore

#28717 Introduce PublishRuntimeIdentifier
  src/Cli/dotnet/commands/dotnet-publish/Program.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Build.Tests/GlobalPropertyFlowTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/RuntimeIdentifiersTests.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
  src/Tests/Microsoft.NET.TestFramework/TestAsset.cs
  src/Tests/Microsoft.NET.TestFramework/TestAssetsManager.cs
Labels: Area-CLI

#28696 Improve Tests for Implicit RIDs and Libraries
  src/Assets/TestProjects/AppWithLibrarySDKStyleThatPublishesSingleFile/Program.cs
  src/Assets/TestProjects/AppWithLibrarySDKStyleThatPublishesSingleFile/lib/Class1.cs
  src/Assets/TestProjects/AppWithLibrarySDKStyleThatPublishesSingleFile/lib/lib.csproj
  src/Assets/TestProjects/AppWithLibrarySDKStyleThatPublishesSingleFile/newc.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileLibrary.cs
  src/Tests/Microsoft.NET.Publish.Tests/RuntimeIdentifiersTests.cs
Labels: Area-Infrastructure

#28877 Enable Codeql
  .vsts-ci.yml
Labels: Area-Infrastructure

#28744 Update Arcade to Use svc providers - release/6.0.1xx branch
  eng/common/templates/job/execute-sdl.yml
  eng/common/templates/job/onelocbuild.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/jobs/jobs.yml
  eng/common/templates/post-build/post-build.yml
Labels: Area-Infrastructure

#28879 Switch the resolver to target net7 as we expect VSMac to move forward…
  Directory.Build.props
Labels: Area-Infrastructure

#28776 removed `v` prefix from `dotnetcli` host version
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstallTests.CanShowWarning_WhenConstraintTemplateIsInstalled.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.Constraints_CanIgnoreConstraints_WhenForceIsSpecified.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.Constraints_Error_IfTemplateIsRestricted.verified.txt
  src/Tests/dotnet-new.Tests/BaseIntegrationTest.cs
  src/Tests/dotnet-new.Tests/DotnetNewDebugOptionsTests.cs
  src/Tests/dotnet-new.Tests/DotnetNewInstallTests.Approval.cs
  src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.Approval.cs
Labels: Area-dotnet new

#28917 Upgrade the verbosity of error headers
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs
Labels: Area-ApiCompat

#28934 Support multiple suppression files
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/SuppressionFileHelper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ISuppressionEngine.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/SuppressionEngine.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.Common.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Logging/SuppressionEngineTests.cs
Labels: Area-ApiCompat

#28918 Add diagnostic id docs link to suppression file
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/SuppressionEngine.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Logging/SuppressionEngineTests.cs
Labels: Area-ApiCompat

#28941 [release/7.0.2xx] Make mapping infrastructure unit testable, Ignore effectively sealed members and types and add tests
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblyMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/AssemblySetMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ElementMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/IAssemblyMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/IAssemblySetMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/IElementMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/IMemberMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/INamespaceMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/ITypeMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/MemberMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/NamespaceMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Abstractions/Mappers/TypeMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparer.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ElementMapperFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Extensions/SymbolExtensions.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IDifferenceVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/MapperSettings.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleRunner.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Mappers/AssemblyMapperTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Mappers/TypeMapperTests.cs
Labels: Area-ApiCompat

#28908 Support calling unique launch profiles with a case-insensitive nature & Improve errors around launch profiles
  src/Assets/TestProjects/AppWithDuplicateLaunchProfiles/My Project/launchSettings.json
  src/Assets/TestProjects/AppWithDuplicateLaunchProfiles/Program.vb
  src/Assets/TestProjects/AppWithDuplicateLaunchProfiles/VbAppWithLaunchSettings.vbproj
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/LaunchSettingsManager.cs
  src/Cli/dotnet/commands/dotnet-run/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsVbProj.cs
Labels: Area-Infrastructure

#28945 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#28950 Merging internal commits for release/7.0.1xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
Labels: Area-Infrastructure

#28949 Update to the RTM version of 7.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#28946 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#28894 [release/6.0.1xx] Backport Add Blazor SWA Baseline Mismatched Assets Logging
  src/RazorSdk/update-test-baselines.ps1
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/AspNetSdkBaselineTest.cs
Labels: Area-AspNetCore

#27961 Handle test parser forwarded args
  src/Assets/TestProjects/VSTestMSBuildParameters/Tests.cs
  src/Assets/TestProjects/VSTestMSBuildParameters/VSTestMSBuildParameters.csproj
  src/Cli/dotnet/commands/dotnet-test/Program.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/TestCommand.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsprojWithCorrectTestRunParameters.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestContainsMSBuildParameters.cs
Labels: Servicing-approved, Area-DotNet Test, Area-CLI, cli-ux

#29010 Fix templating support for multiple parameters with same prefix
  src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithParamsSharingPrefix/.template.config/template.json
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/AliasAssignmentCoordinator.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/AliasAssignmentTests.cs
  src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.cs
Labels: Area-Infrastructure, Area-dotnet new

#28967 Introduce Roslyn-based GenAPI
  sdk.sln
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Microsoft.DotNet.GenAPI.Tool.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Program.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpSyntaxWriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/Filters/ImplicitSymbolsFilter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/IAssemblySymbolWriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Filtering/AttributeSymbolFilter.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Filtering/CompositeFilter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpSyntaxWriterTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/Microsoft.DotNet.GenAPI.Tests.csproj
Labels: Area-GenAPI

#27566 Use architecture specific DOTNET_ROOT variable name
  src/BuiltInTools/DotNetWatchTasks/FileSetSerializer.cs
  src/BuiltInTools/dotnet-watch/DotNetWatch.targets
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/MSBuildFileSetResult.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/ProjectInfo.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Common/EnvironmentVariableNames.cs
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/NoDepsAppTests.cs
  src/Tests/dotnet.Tests/EnvironmentVariableNamesTests.cs
Labels: Area-Infrastructure, Area-CLI, Area-Watch, feature-dotnetwatch

#28782 [release/6.0.1xx] ResolveReadyToRunCompilers: map non-portable rids when targetOS is determined (backport #28380)
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: Area-ReadyToRun

#29068 fixed error reporting
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/AliasAssignmentCoordinator.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/AliasAssignmentTests.cs
Labels: Area-Infrastructure

#29073 Fix typo in WebSocketScriptInjection.js
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-Infrastructure

#28984 Retarget Microsoft.Extensions.DotNetDeltaApplier to netstandard2.1
  src/Assets/TestProjects/WatchApp60/Program.cs
  src/Assets/TestProjects/WatchApp60/WatchApp60.csproj
  src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs
  src/BuiltInTools/DotNetDeltaApplier/Microsoft.Extensions.DotNetDeltaApplier.csproj
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/NamedPipeContract.cs
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/HotReload/UpdatePayloadTest.cs
Labels: Servicing-approved, Area-Watch

#28994 Simplify output testing
  src/Tests/dotnet-watch.Tests/AppWithDepsTests.cs
  src/Tests/dotnet-watch.Tests/BrowserLaunchTests.cs
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/GlobbingAppTests.cs
  src/Tests/dotnet-watch.Tests/NoDepsAppTests.cs
  src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
  src/Tests/dotnet-watch.Tests/Utilities/WatchableApp.cs
Labels: Area-Infrastructure

#28963 Deps.json should include project references that aren't present in project.assets.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenADependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ReferenceInfo.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithTransitiveNonSdkProjectRefs.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithTransitiveProjectRefs.cs
Labels: Area-Infrastructure

#29052 [release/7.0.1xx] ResolveReadyToRunCompilers: map non-portable rids when targetOS is determined. (#28380)
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: Area-ReadyToRun

#29101 Add missing dependencies
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#29065 Add error when specifying --output option for a solution
  src/Cli/dotnet/OptionForwardingExtensions.cs
  src/Cli/dotnet/commands/dotnet-build/BuildCommandParser.cs
  src/Cli/dotnet/commands/dotnet-clean/CleanCommandParser.cs
  src/Cli/dotnet/commands/dotnet-pack/PackCommandParser.cs
  src/Cli/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/Cli/dotnet/commands/dotnet-store/StoreCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions-ver/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets
  src/Tests/dotnet.Tests/OutputPathOptionTests.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetCleanInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
Labels: Area-CLI

#28596 Disable the windows SDK automated references for c++
  src/Assets/TestProjects/CppCliLibWithWpfFrameworkReference/Project1.vcxproj
  src/Assets/TestProjects/NetCoreCppCliLibWithTransitiveDeps/NETCoreCppCliTest/NETCoreCppCliTest.vcxproj
  src/Assets/TestProjects/NetCoreCppCliLibWithTransitiveDeps/NETCoreCppCliTestB/NETCoreCppCliTestB.vcxproj
  src/Assets/TestProjects/NetCoreCppCliLibWithTransitiveDeps/NETCoreCppCliTestC/NETCoreCppCliTestC.vcxproj
  src/Assets/TestProjects/NetCoreCsharpAppReferenceCppCliLib/CSConsoleApp/CSConsoleApp.csproj
  src/Assets/TestProjects/NetCoreCsharpAppReferenceCppCliLib/NETCoreCppCliTest/NETCoreCppCliTest.vcxproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackACppCliProject.cs
Labels: Area-NetSDK

#29017 Add new option for json output of dotnet list package to release 7.2.xx branch
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommandParser.cs
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ReportOutputFormat.cs
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure

#29128 Avoid potential NRE
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-AspNetCore

#29140 Avoid potential NRE (#29128)
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-AspNetCore

#29142 Don't stabilize package versions in main
  eng/Versions.props
Labels: Area-Infrastructure

#29058 Use CodeAnalysis.Simplification to expand and reduce generated subtrees. Add tests to cover CSharpFileBuilder and CSharpSyntaxWriter classes.
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Program.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpSyntaxWriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/Filters/ImplicitSymbolsFilter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/IAssemblySymbolWriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoader.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/IAssemblySymbolLoader.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpSyntaxWriterTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/Microsoft.DotNet.GenAPI.Tests.csproj
Labels: Area-GenAPI

#29154 Make sure the test theories go into different folders.
  src/Tests/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
Labels: Area-Infrastructure

#29146 Introduce MSBuild task frontend for the Roslyn-based GenAPI
  sdk.sln
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/GenAPITask.cs
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/build/Microsoft.DotNet.GenAPI.Task.targets
Labels: Area-GenAPI

#29209 Adjust test due to different behaviors for disabled parameter between main and release/7.0.2xx
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CannotInstantiateTemplate_WithDisabledParams_parameters=A.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CannotInstantiateTemplate_WithDisabledParams_parameters=AB.verified.txt
Labels: Area-Infrastructure

#29221 simplified conditions in C# class library template
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ClassLibrary-CSharp/.template.config/template.json
Labels: Area-Infrastructure, Area-dotnet new

#28769 add console message for package validation success or failure
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/CommonResources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/SuppressionFileHelper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.zh-Hant.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/MSBuildCompatibilityLogger.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/ConsoleCompatibilityLogger.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ICompatibilityLogger.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/TestLogger.cs
Labels: Area-ApiCompat

#29257 Deploy watch to redist
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/PublishDotnetWatch.targets
  src/Tests/dotnet-watch.Tests/dotnet-watch.Tests.csproj
Labels: Area-Infrastructure, Area-Watch

#29270 [release/7.0.2xx] inverted language version conditions in console / classlib templates to support new language features for newer language versions
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.7.0/content/ClassLibrary-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.7.0/content/ConsoleApplication-CSharp/.template.config/template.json
Labels: Area-Common templates

#29284 Update branding to 6.0.113
  eng/Versions.props
Labels: Area-Infrastructure

#29287 Update branding to 7.0.102
  eng/Versions.props
Labels: Area-Infrastructure

#29036 Migrate the nuget state from earlier SDKs
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
Labels: Servicing-approved, Area-Infrastructure

#29180 Remove tmp from the default includes for tests
  src/Assets/Directory.Build.props
  src/Tests/Directory.Build.props
Labels: Area-Infrastructure

#29182 Improve build stability by ensuring we aren't double publishing everywhere
  .vsts-ci-richnav.yml
  .vsts-ci.yml
  eng/CIBuild.cmd
  eng/build.yml
Labels: Area-Infrastructure

#29286 Update branding to 6.0.405
  eng/Versions.props
Labels: Area-Infrastructure

#29285 Update branding to 6.0.308
  eng/Versions.props
Labels: Area-Infrastructure

#29041 Migrate the nuget state from earlier SDKs
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
Labels: Area-Infrastructure

#29039 Migrate the nuget state from earlier SDKs
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
Labels: Area-Infrastructure

#29040 Migrate the nuget state from earlier SDKs
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
Labels: Area-Infrastructure

#29095 Deps.json should include project references that aren't present in project.assets.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenADependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ReferenceInfo.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithTransitiveNonSdkProjectRefs.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithTransitiveProjectRefs.cs
Labels: Servicing-approved, Area-Infrastructure

#28932 Update the target framework for the desktop test projects
  src/Assets/DesktopTestProjects/MultiTFMXunitProject/XUnitProject/XUnitProject.csproj
  src/Assets/DesktopTestProjects/NETFrameworkReferenceNETStandard20/MultiTFMTestApp/MultiTFMTestApp.csproj
  src/Tests/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
  src/Tests/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromCsprojForMultipleTFM.cs
Labels: Area-Infrastructure

#29281 Fix stabilize package version for 7.0.2xx
  eng/Versions.props
  src/Tests/dotnet.Tests/OutputPathOptionTests.cs
Labels: Area-Infrastructure
