Repository dotnet/sdk, pull requests merged in 2022-06, with the labels that each got.

#25372 Replace hardcoded error string in source with string from resources
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
Labels: localization, area-Meta

#25324 Switch the last non-helix test over to running on helix.
  eng/runHelixAndNonHelixInParallel.ps1
  eng/runHelixAndNonHelixInParallelNonWindows.ps1
  src/Cli/dotnet/CommonOptions.cs
  src/Tests/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  src/Tests/Microsoft.DotNet.ShellShim.Tests/WindowsEnvironmentPathTests.cs
  src/Tests/dotnet-new.Tests/NewCommandTests.cs
  src/Tests/dotnet-pack.Tests/PackTests.cs
  src/Tests/dotnet-remove-reference.Tests/GivenDotnetRemoveP2P.cs
  src/Tests/dotnet-restore.Tests/GivenThatIWantToRestoreApp.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRootEnv.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromCsprojForMultipleTFM.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet.Tests/CommandTests/CompleteCommandTests.cs
  src/Tests/dotnet.Tests/GivenThatTheUserRequestsHelp.cs
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
  src/Tests/testsProjectCannotRunOnHelixList.txt
  src/Tests/xunit-runner/XUnitRunner.targets
Labels: Area-Infrastructure

#25454 add tests to cover the resolution of AnalysisLevel known-strings
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToFloatWarningLevels.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-NetSDK

#25798 Add -lp alias for --launch-profile on dotnet run
  src/Cli/dotnet/commands/dotnet-run/RunCommandParser.cs
Labels: Area-CLI

#25687 Add fallback root certificate bundle for code signing and timestamping
  sdk.sln
  src/Layout/redist/redist.csproj
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Tests/trustedroots.Tests/GivenCodeSigningCtlFile.cs
  src/Tests/trustedroots.Tests/trustedroots.Tests.csproj
Labels: Area-Infrastructure

#25757 [main] Integrate dotnet user-jwts tools into SDK
  documentation/general/aspnetcore-tools.md
  eng/Version.Details.xml
  src/Cli/dotnet/CommandFactory/CommandFactoryUsingResolver.cs
  src/Cli/dotnet/commands/dotnet-help/HelpUsageText.cs
  src/Cli/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
Labels: Area-AspNetCore

#25771 [release/7.0.1xx-preview5] Integrate new user-jwts tool into SDK
  documentation/general/aspnetcore-tools.md
  eng/Version.Details.xml
  src/Cli/dotnet/CommandFactory/CommandFactoryUsingResolver.cs
  src/Cli/dotnet/commands/dotnet-help/HelpUsageText.cs
  src/Cli/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
Labels: Servicing-approved, Area-AspNetCore

#25733 Include requested .NET SDK version when known
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Strings.resx
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.cs.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.de.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.es.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.fr.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.it.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ja.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ko.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.pl.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.pt-BR.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.ru.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.tr.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.zh-Hans.xlf
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/xlf/Strings.zh-Hant.xlf
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Interop.cs
  src/Resolvers/Microsoft.DotNet.NativeWrapper/SdkResolutionResult.cs
  src/Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests/GivenAnMSBuildSdkResolver.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildWithGlobalJson.cs
Labels: Area-Infrastructure

#25837 Switch NuGet assets for tests as tools to be under the test execution…
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
Labels: Area-Infrastructure

#25832 Add support for specifying launch profile to `dotnet watch run`
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/BuiltInTools/dotnet-watch/DotNetWatchContext.cs
  src/BuiltInTools/dotnet-watch/Filters/LaunchBrowserFilter.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/LaunchSettingsProfile.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/BuiltInTools/dotnet-watch/README.md
  src/Tests/dotnet-watch.Tests/CommandLineOptionsTests.cs
Labels: Area-Infrastructure

#25505 Implement functionality for templating workload and version constraints
  src/Cli/Microsoft.DotNet.Cli.Utils/Product.cs
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/commands/dotnet-new/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/Cli/dotnet/commands/dotnet-new/SdkInfoProvider.cs
  src/Cli/dotnet/commands/dotnet-new/WorkloadsInfoProvider.cs
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-new/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/IWorkloadRecordHelper.cs
  src/Cli/dotnet/commands/dotnet-workload/list/IWorkloadsRepositoryEnumerator.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListHelper.cs
  src/Cli/dotnet/dotnet.csproj
  src/Layout/redist/targets/GenerateLayout.targets
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/WorkloadResolverTests.cs
  src/Tests/dotnet-new.Tests/NewCommandTests.cs
  src/Tests/dotnet-new.Tests/SdkInfoProviderTests.cs
  src/Tests/dotnet-new.Tests/WorkloadsInfoProviderTests.cs
  src/Tests/dotnet-workload-search.Tests/MockWorkloadResolver.cs
Labels: Area-Infrastructure

#25892 Update branding to 6.0.302
  eng/Versions.props
Labels: Area-Infrastructure

#25890 Update branding to 3.1.421
  eng/Versions.props
Labels: Area-Infrastructure

#25891 Update branding to 6.0.107
  eng/Versions.props
Labels: Area-Infrastructure

#25905 Explain the Purpose of Dogfood in The Dev Guide
  documentation/project-docs/developer-guide.md
Labels: Area-Infrastructure

#25842 Exclude documentation changes from triggering builds
  .vsts-ci.yml
Labels: Area-Infrastructure

#25939 [Static web assets] Fix pack when no assets exist
  src/Assets/TestPackages/PackageLibraryNoStaticAssets/PackageLibraryNoStaticAssets.csproj
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.Pack.targets
  src/RazorSdk/Tasks/StaticWebAssets/StaticWebAssetsGeneratePackManifest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#25900 Fix Description for Pre-Release Reinstallation Updates
  src/Cli/dotnet/commands/dotnet-tool/update/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
Labels: Area-Infrastructure

#25919 fix(cli): handle sln folders in workload restore command
  src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs
  src/Tests/dotnet-workload-restore.Tests/DiscoverAllProjectsTests.cs
Labels: Area-Workloads

#25963 Enable PublishReadyToRunComposite for R2R singlefile apps
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Area-SingleFile

#25927 Getting Aot HelloWorld to be warning free
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-ILLink

#25834 Add --skip-sign-check option to repair, uninstall, and update
  src/Cli/dotnet/commands/dotnet-workload/repair/WorkloadRepairCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/uninstall/WorkloadUninstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommandParser.cs
Labels: Area-Workloads

#25641 [release/6.0.3xx] Update pre-release label to servicing
  eng/Versions.props
Labels: Area-Infrastructure

#26011 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#25995 Fix the path detection logic for MSDeploy executable
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/MSDeploy.cs
  src/WebSdk/WebSdk.slnf
Labels: Area-WebSDK

#26012 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/runHelixAndNonHelixInParallelNonWindows.ps1
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
Labels: Area-Infrastructure

#25947 Fix copy&paste mistake in PublicSign preservation
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PreserveCompilationContext.targets
Labels: Area-Infrastructure

#26013 Merging internal commits for release/3.1.4xx
  .vsts-ci.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/templates/post-build/channels/generic-internal-channel.yml
  eng/common/templates/post-build/channels/generic-public-channel.yml
  eng/common/templates/post-build/post-build.yml
Labels: Area-Infrastructure

#26046 Force rebuilding R2R images if project files have been changed
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
Labels: Area-ReadyToRun

#26007 Define SystemCollectionsImmutableVersion Versions.props
  eng/Versions.props
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-Infrastructure

#26105 Rollback razor tooling version
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/dotnet-new.Tests/NewCommandTests.cs
Labels: Area-CodeFlow

#26080 Reference older MSBuild for .NET Framework tasks
  eng/Versions.props
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-VS

#26106 Fix error log message string.Format exception for failed ZipDeploy
  src/WebSdk/Publish/Tasks/Properties/Resources.Designer.cs
  src/WebSdk/Publish/Tasks/Properties/Resources.resx
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.cs.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.de.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.es.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.fr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.it.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ja.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ko.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pl.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pt-BR.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ru.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.tr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hans.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hant.xlf
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploy.cs
Labels: Area-Infrastructure

#26074 add post actions tests for dotnet new
  src/Tests/dotnet-new.Tests/NewCommandTests.cs
  src/Tests/dotnet.Tests/TestTemplates/AddPackageReference/.template.config/template.json
  src/Tests/dotnet.Tests/TestTemplates/AddPackageReference/Basic.csproj
  src/Tests/dotnet.Tests/TestTemplates/AddPackageReference/Program.cs
  src/Tests/dotnet.Tests/TestTemplates/AddProjectReference/.template.config/template.json
  src/Tests/dotnet.Tests/TestTemplates/AddProjectReference/Project1/Program.cs
  src/Tests/dotnet.Tests/TestTemplates/AddProjectReference/Project1/Project1.csproj
  src/Tests/dotnet.Tests/TestTemplates/AddProjectReference/Project2/MyClass.cs
  src/Tests/dotnet.Tests/TestTemplates/AddProjectReference/Project2/Project2.csproj
  src/Tests/dotnet.Tests/TestTemplates/AddProjectToSolution/.template.config/template.json
  src/Tests/dotnet.Tests/TestTemplates/AddProjectToSolution/Basic.csproj
  src/Tests/dotnet.Tests/TestTemplates/AddProjectToSolution/Program.cs
  src/Tests/dotnet.Tests/TestTemplates/AddProjectToSolution/Solution1.sln
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Infrastructure

#25734 add rules to catch addition or removal of 'virtual' modifier
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddOrRemoveVirtualKeywordTests.cs
Labels: Area-Compatibility

#25991 Allow Opt-In to change the default to Release for Pack/Pub
  src/Cli/dotnet/commands/dotnet-pack/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-pack/PackCommand.cs
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-publish/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-publish/Program.cs
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.de.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
  src/Tests/dotnet-store.Tests/GivenDotnetStoresAndPublishesProjects.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
Labels: Area-NetSDK

#26290 Update razor-compiler dependencies and re-enable flow
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-CodeFlow

#24383 [Blazor] Add support for RazorLangVersion 7.0
  src/RazorSdk/SourceGenerators/Diagnostics/RazorSourceGeneratorResources.resx
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: Area-AspNetCore

#26361 Update to the shipped 6.0.6 runtime.
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#26362 [6.0.400] Display manifest version inside of workload list
  src/Cli/dotnet/commands/dotnet-workload/list/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hant.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
  src/Tests/dotnet-workload-search.Tests/MockWorkloadResolver.cs
Labels: Area-Infrastructure

#26366 Support wwwroot/.well-known in web/Razor publish output
  src/Assets/TestProjects/RazorSimpleMvc/wwwroot/.not-copied/test.txt
  src/Assets/TestProjects/RazorSimpleMvc/wwwroot/.well-known/security.txt
  src/RazorSdk/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PublishIntegrationTest.cs
Labels: Area-AspNetCore

#26395 [release/7.0.1xx-preview6] Revert branding to p6
  eng/Versions.props
Labels: Area-Infrastructure
