Repository dotnet/sdk, pull requests merged in 2022-03, with the labels that each got.

#24100 Backport #24086 to release/6.0.2xx
  eng/Versions.props
Labels: Area-Infrastructure

#24159 Update branding to 3.1.418
  eng/Versions.props
Labels: Area-Infrastructure

#24157 Update branding to 6.0.202
  eng/Versions.props
Labels: Area-Infrastructure

#24156 Update branding to 6.0.104
  eng/Versions.props
Labels: Area-Infrastructure

#24154 Update branding to 5.0.213
  eng/Versions.props
Labels: Area-Infrastructure

#23976 Update some test package versions
  src/Assets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  src/Assets/TestProjects/11TestAppWith10CLIToolReferences/11TestAppWith10CLIToolReferences.csproj
  src/Tests/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
Labels: Area-Infrastructure

#23871 Hard code a few system.net.http versions
  src/Assets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  src/Assets/TestProjects/11TestAppWith10CLIToolReferences/11TestAppWith10CLIToolReferences.csproj
  src/Tests/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
Labels: Area-Infrastructure

#23934 reenable composite r2r singlefile test on OSX
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Area-SingleFile

#23722 Blame switch args should not swallow following arg
  src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs
  src/Tests/dotnet.Tests/ParserTests/VSTestArgumentConverterTests.cs
Labels: Area-DotNet Test

#24191 Temporarily disable test that's failing 10%
  src/Tests/dotnet.Tests/TelemetryCommandTest.cs
Labels: Area-Infrastructure

#24212 Reapply fsharpcore update
  eng/Versions.props
  src/Layout/tool_fsharp/tool_fsc.csproj
Labels: Area-Infrastructure

#23977 Update 6.0.3xx with the 6.0.200 version of files
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  eng/common/templates/steps/source-build.yml
  eng/runHelixAndNonHelixInParallelNonWindows.ps1
Labels: Area-Infrastructure

#24235 Hostfxr changes
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
Labels: Area-Infrastructure

#24104 Workload update timer
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  src/Tests/dotnet-workload-install.Tests/MockManifestProvider.cs
Labels: Area-Workloads

#24285 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#24168 deploy common roslyn assemblies used by multiple dotnet tools
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure

#24266 Remove the package DeploymentReleasesVersion
  eng/Versions.props
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
Labels: Area-Infrastructure

#24209 Clarify NuGet version conflicts
  src/Layout/redist/redist.csproj
Labels: Area-Infrastructure

#24166 Detect if a particular execution of the SDK is on a CI system or not
  src/Cli/dotnet/Telemetry/CIEnvironmentDetectorForTelemetry.cs
  src/Cli/dotnet/Telemetry/ICIEnvironmentDetector.cs
  src/Cli/dotnet/Telemetry/TelemetryCommonProperties.cs
  src/Tests/dotnet.Tests/TelemetryCommonPropertiesTests.cs
Labels: Area-Infrastructure

#24287 [release/6.0.3xx] Fix FSharp publishing
  eng/Publishing.props
  eng/Versions.props
  src/Layout/redist/redist.csproj
Labels: Area-Infrastructure

#24284 Merging internal commits for release/6.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#24253 Update CODEOWNERS
  CODEOWNERS
Labels: Area-Infrastructure

#24283 Merging internal commits for release/5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#23302 Block loading the 7.0.100 SDK in 16.11 and below VS and MSBuild versions
  .vsts-ci.yml
  src/Assets/TestProjects/DesktopAppWithLibrary-NonSDK/TestApp/TestApp.csproj
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/TestApp.csproj
  src/Layout/redist/minimumMSBuildVersion
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExeWtihNetStandardLib.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsRuntimeComponent.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseVB.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantAutomaticTargetingPackReferences.cs
Labels: Area-Infrastructure

#21186 Add test retry
  eng/BuildConfiguration/build-configuration.json
  eng/test-configuration.json
  src/Tests/Microsoft.NET.TestFramework/TestAssetsManager.cs
  src/Tests/UnitTests.proj
Labels: Area-Infrastructure

#24363 [release/6.0.1xx] Add job dependency on source build
  .vsts-ci.yml
Labels: Area-Infrastructure

#24364 [release/6.0.2xx] Add job dependency on source build
  .vsts-ci.yml
Labels: Area-Infrastructure

#24365 [release/6.0.3xx]Add job dependency on source build
  .vsts-ci.yml
Labels: Area-Infrastructure

#24366 Add job dependency on source build
  .vsts-ci.yml
Labels: Area-Infrastructure

#24324 Improve error message for the case when Crossgen2 package is not present
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: Area-ReadyToRun

#24362 Pin Microsoft.CodeAnalysis version for API Compat to the 4.0.x stable package
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
Labels: Area-Compatibility

#24070 Add design for cross-version workloads
  documentation/general/workloads/README.md
  documentation/general/workloads/cross-version-workloads.md
Labels: Area-Workloads

#24407 [dotnet-watch] Skip dotnet watch flaky test 602xx
  src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs
Labels: Area-AspNetCore

#24411 Port the helix update to VS 2022
  .vsts-ci.yml
  src/Assets/TestProjects/DesktopAppWithLibrary-NonSDK/TestApp/TestApp.csproj
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/TestApp.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExeWtihNetStandardLib.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsRuntimeComponent.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseVB.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantAutomaticTargetingPackReferences.cs
Labels: Area-Infrastructure

#24410 Fix unstable test
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
Labels: Area-Infrastructure

#24237 Move WebAssembly ProjectCapability to props file
  src/BlazorWasmSdk/Sdk/Sdk.targets
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props
Labels: Area-AspNetCore

#24426 Update feature flag logic to disable only semantics
  src/Cli/dotnet/commands/dotnet-test/Program.cs
  src/Cli/dotnet/commands/dotnet-test/VSTestFeatureFlag.cs
  src/Cli/dotnet/commands/dotnet-vstest/Program.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsArtifactPostProcessing.cs
Labels: Area-DotNet Test

#24333 Properly handle empty solution and project paths in SDK resolver
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
  src/Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests/GivenAnMSBuildSdkResolver.cs
Labels: Area-SdkResolvers

#24449 Fix help infinite loop.
  src/Cli/dotnet/HelpException.cs
  src/Cli/dotnet/ParseResultExtensions.cs
  src/Cli/dotnet/Program.cs
  src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunThrowsAParseError.cs
Labels: Bug, Area-CLI

#24288 Error using skip-manifest-update and --from-rollback-file
  src/Cli/dotnet/Parser.cs
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-add-reference.Tests/GivenDotnetAddReference.cs
  src/Tests/dotnet-list-reference.Tests/GivenDotnetListReference.cs
  src/Tests/dotnet-remove-reference.Tests/GivenDotnetRemoveP2P.cs
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnList.cs
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
Labels: Area-Infrastructure

#24488 Refactor some workload APIs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/IWorkloadPackInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadOptionsExtensions.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/ReadableWorkloadManifest.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifest.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestInfo.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.NewtonsoftJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.SystemTextJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/FakeManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet-workload-install.Tests/GivenFileBasedWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/MockManifestProvider.cs
  src/Tests/dotnet-workload-install.Tests/MockPackWorkloadInstaller.cs
  src/Tests/dotnet-workload-search.Tests/MockWorkloadResolver.cs
  src/Tests/dotnet-workload-update.Tests/TempDirectoryWorkloadManifestProviderTests.cs
Labels: Area-Workloads

#24450 Change the missing workload message to recommend doing a restore.
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/ShowMissingWorkloads.cs
Labels: Area-Workloads

#24169 deploy common roslyn assemblies used by multiple dotnet tools
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure

#24451 Hide manifest updates during workload install
  src/Cli/dotnet/Telemetry/Telemetry.cs
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurerWIthStateSetup.cs
  src/Tests/Microsoft.NET.TestFramework/TestConstants.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet.Tests/TelemetryCommandTest.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/DotnetMsbuildInProcTests.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetCleanInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetRestoreInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetRunInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/NullCurrentSessionIdFixture.cs
Labels: Area-Workloads

#24518 Change LastIndexOf to use invariant culture
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
Labels: Area-NetSDK

#24512 Detect arm64 hostfxr.dll
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Interop.cs
Labels: Area-Workloads

#24540 Make enabling C++/CLI activation feature also enable native hosting
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets
Labels: Area-ILLink

#24412 Port the prep machine change and the helix update to VS 2022
  .vsts-ci.yml
  eng/runHelixAndNonHelixInParallel.ps1
  src/Assets/TestProjects/DesktopAppWithLibrary-NonSDK/TestApp/TestApp.csproj
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/TestApp.csproj
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantAllResourcesInSatellite.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACrossTargetedLibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExeWtihNetStandardLib.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASolutionWithNonAnyCPUPlatform.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsRuntimeComponent.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseVB.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThereAreDefaultItems.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackACrossTargetedLibrary.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackASimpleLibrary.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantAutomaticTargetingPackReferences.cs
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
Labels: Area-Infrastructure

#24541 Remove 'reflecting any global.json' from info label
  src/Cli/Microsoft.DotNet.Cli.Utils/LocalizableStrings.resx
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-CLI

#24557 Porting a 6.0 error message improvement that I should have targeted at 3xx originally
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Area-Infrastructure

#24582 [release/6.0.3xx] changed names of `dotnet new` providers
  src/Cli/dotnet/commands/dotnet-new/BuiltInTemplatePackageProviderFactory.cs
  src/Cli/dotnet/commands/dotnet-new/OptionalWorkloadProviderFactory.cs
Labels: Area-Infrastructure

#24565 changed names of `dotnet new` providers
  src/Cli/dotnet/commands/dotnet-new/BuiltInTemplatePackageProviderFactory.cs
  src/Cli/dotnet/commands/dotnet-new/OptionalWorkloadProviderFactory.cs
Labels: Area-Infrastructure

#24566 Enable arm64 targeting for .Net Framework 4.8.1 and newer
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Area-NetSDK

#24130 Pin the compiler version in RSG to an exact version
  eng/Versions.props
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
Labels: Area-AspNetCore

#24562 Cherry pick #24130
  eng/Versions.props
  src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
Labels: Area-Infrastructure

#24563 Update to the 6.0.3 runtime for preview 3
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#24139 Add default file inclusion support in .NET SDK for RESW and image files in WinAppSDK .NET projects.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThereAreDefaultItems.cs
Labels: Area-WebSDK

#24545 Workload feature band fallback with rollback files
  src/Cli/dotnet/commands/dotnet-workload/install/IWorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  src/Tests/dotnet-workload-install.Tests/MockWorkloadManifestUpdater.cs
  src/Tests/dotnet-workload-list.Tests/GivenWorkloadInstallerAndWorkloadsInstalled.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: Area-Workloads
