Repository dotnet/sdk, pull requests merged in 2022-05, with the labels that each got.

#25141 Add back build retry
  eng/BuildConfiguration/build-configuration.json
Labels: Area-Infrastructure

#25060 Add a test for native lib
  .vsts-ci.yml
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-ILLink

#25189 Update branding to 6.0.106
  eng/Versions.props
Labels: Area-Infrastructure

#25188 Update branding to 3.1.420
  eng/Versions.props
Labels: Area-Infrastructure

#25057 Next helix test move
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
  src/Tests/EndToEnd.Tests/EndToEnd.Tests.csproj
  src/Tests/UnitTests.proj
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/testsProjectCannotRunOnHelixList.txt
Labels: Area-Infrastructure

#25190 Update branding to 6.0.301
  eng/Versions.props
Labels: Area-Infrastructure

#25155 Fix MSI workload garbage collection
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
Labels: Servicing-approved

#25001 Assign names to arguments for nuget commands
  src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs
Labels: Area-NuGet, Area-CLI, cli-ux

#25087 Port changes from Main for fixing binary version issues.
  src/Assets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  src/Assets/TestPackages/dotnet-portable-v1-prefercli/dotnet-portable-v1-prefercli.csproj
  src/Assets/TestPackages/dotnet-portable-v1/dotnet-portable-v1.csproj
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/TestApp.csproj
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
  src/Tests/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
Labels: Area-Infrastructure

#25103 Version updates for compliance checks
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/TestApp.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenWeWantToRequireWindowsForDesktopApps.cs
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
Labels: Area-Infrastructure

#25104 Port changes from Main for fixing binary version issues.
  src/Assets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  src/Assets/TestPackages/dotnet-portable-v1-prefercli/dotnet-portable-v1-prefercli.csproj
  src/Assets/TestPackages/dotnet-portable-v1/dotnet-portable-v1.csproj
  src/Assets/TestProjects/DesktopAppWithLibrary-PackagesConfig/TestApp/TestApp.csproj
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
  src/Tests/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
Labels: Area-Infrastructure

#25197 Next two test projects to move to helix
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Tests/Microsoft.DotNet.Tools.Tests.Utilities.Tests/Microsoft.DotNet.Tools.Tests.Utilities.Tests.csproj
  src/Tests/testsProjectCannotRunOnHelixList.txt
Labels: Area-Infrastructure

#25195 Update build.yml to target loc build at 6.0.4xx
  eng/build.yml
Labels: Area-Infrastructure

#24826 bump WarningLevel to 7 for .NET 7
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToFloatWarningLevels.cs
Labels: Area-Infrastructure

#25272 Two more tests running on helix
  src/Tests/dotnet-sln.Tests/dotnet-sln.Tests.csproj
  src/Tests/msbuild.Integration.Tests/msbuild.Integration.Tests.csproj
  src/Tests/testsProjectCannotRunOnHelixList.txt
Labels: Area-Infrastructure

#24656 Set TargetFrameworkMonikerDisplayName for .NET Standard and .NET Core/.NET5+ projects.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DisableStandardFrameworkResolution.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
Labels: Area-Infrastructure

#25306 Move the publish task tests to helix including netfx run
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests.csproj
  src/Tests/UnitTests.proj
  src/Tests/testsProjectCannotRunOnHelixList.txt
Labels: Area-Infrastructure

#25301 Enable Aot, Trim and single file analyzers if PublishAot is set
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-ILLink

#25326 Merging internal commits for release/6.0.1xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
Labels: Area-Infrastructure

#25327 Merging internal commits for release/6.0.2xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
Labels: Area-Infrastructure

#25328 Merging internal commits for release/6.0.3xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
Labels: Area-Infrastructure

#25333 Marcpop msft upgraderuntime605
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#25330 Merging internal commits for release/5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#25117 Use System.Environment to obtain user HOME dir
  src/Common/CliFolderPathCalculatorCore.cs
  src/RazorSdk/Tool/ServerCommand.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tool.Tests/ServerCommandTest.cs
  src/Tests/dotnet.Tests/GivenThatDotNetRunsCommands.cs
Labels: Area-Infrastructure

#25258 Update the RID target from lower win to the latest one
  src/Assets/TestProjects/DesktopNeedsBindingRedirects/DesktopNeedsBindingRedirects.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExe.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.TestFramework/TestAsset.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
  src/Tests/dotnet-clean.Tests/GivenDotnetCleanCleansBuildArtifacts.cs
Labels: Area-Infrastructure

#25257 Update the hardcoded netcoreapp2.0 to the current framework
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToExcludeTheMainProjectFromTheDepsFile.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAnAssembly.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThereAreDefaultItems.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatThereAreImplicitPackageReferences.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToCrossPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToFilterSatelliteAssemblies.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs
  src/Tests/dotnet.Tests/ParserTests/InstallToolParserTests.cs
  src/Tests/dotnet.Tests/ParserTests/UpdateToolParserTests.cs
Labels: Area-Infrastructure

#25325 Servicing F#
  eng/Versions.props
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
Labels: Servicing-approved, Area-Infrastructure

#25367 Always detect if SelfContained was specified by the user
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
Labels: Servicing-approved, Area-NetSDK

#25420 Remove transitive dependencies for System.Private.Uri
  eng/Versions.props
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
Labels: Area-Workloads

#25419 Remove transitive dependencies for System.Private.Uri
  eng/Versions.props
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Microsoft.DotNet.NativeWrapper.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
Labels: Area-Workloads

#25395 Enable signature checks in the package downloader
  eng/Versions.props
  src/Cli/dotnet/commands/dotnet-workload/SignCheck.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/repair/WorkloadRepairCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/repair/WorkloadRepairCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/uninstall/WorkloadUninstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/uninstall/WorkloadUninstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommandParser.cs
  src/Tests/dotnet.Tests/WindowsInstallerTests.cs
Labels: Servicing-approved, Area-Workloads

#25443 Remove duplicated PackageReference
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
Labels: Area-Infrastructure

#24678 Feature band fallback with workload update
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  src/Tests/dotnet-workload-install.Tests/MockNuGetPackageInstaller.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: Area-Workloads

#25393 Enable the 4.8.1 target in sdk style projects
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenThatWeWantToGenerateSupportedTargetFrameworkAlias.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
Labels: Area-Infrastructure

#25490 document long paths-related error message when building on windows
  documentation/project-docs/developer-guide.md
Labels: Area-Infrastructure

#25132 Update Microsoft.NET.Compatibility.Common.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Compatibility.Common.targets
Labels: Area-Compatibility

#25541 Remove dotnet-format option parsing and have them pass-through.
  src/Cli/dotnet/Parser.cs
  src/Cli/dotnet/commands/dotnet-format/DotnetFormatForwardingApp.cs
  src/Cli/dotnet/commands/dotnet-format/FormatCommand.cs
  src/Cli/dotnet/commands/dotnet-format/FormatCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-format/analyzers/FormatAnalyzersCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/common/FormatCommandCommon.cs
  src/Cli/dotnet/commands/dotnet-format/style/FormatStyleCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/whitespace/FormatWhitespaceCommandParser.cs
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-format/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
  src/Tests/dotnet-format.Tests/GivenDotnetFsiExecutesAndGeneratesHelpText.cs
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Infrastructure

#25526 Update the RID target from lower win to the latest one
  src/Assets/TestProjects/AppWithCorruptedLaunchSettings/AppWithCorruptedLaunchSettings.csproj
  src/Assets/TestProjects/AppWithLaunchSettings/AppWithLaunchSettings.csproj
  src/Assets/TestProjects/AppWithLaunchSettingsNoDefault/AppWithLaunchSettingsNoDefault.csproj
  src/Assets/TestProjects/AppsWithFrameworkReferences/EntityFrameworkApp/EntityFrameworkApp.csproj
  src/Assets/TestProjects/CompilationContext/TestApp/TestApp.csproj
  src/Assets/TestProjects/MSBuildTestApp/MSBuildTestApp.csproj
  src/Assets/TestProjects/VbAppWithLaunchSettings/VbAppWithLaunchSettings.vbproj
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/GivenAFrameworkDependencyFile.cs
  src/Tests/Microsoft.NET.Build.Tests/DesignTimeBuildTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantRuntimeConfigInBuiltProjectOutputGroup.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAComServerLibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAppsWithFrameworkRefs.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildWithARuntimeIdentifier.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenWeWantToRequireWindowsForDesktopApps.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPreserveCompilationContext.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/dotnet.Tests/TelemetryCommandTest.cs
Labels: Area-Infrastructure

#25534 [dotnet-watch] Updates the request path to always be host relative
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
Labels: Servicing-approved, Area-AspNetCore

#25533 [dotnet-watch] Fixes an infinite loop of reloads when the process fails to start
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Servicing-approved, Area-AspNetCore

#25590 Version Microsoft.DotNet.Compatibility same as SDK
  src/Compatibility/Microsoft.DotNet.Compatibility/Microsoft.DotNet.Compatibility.csproj
Labels: Area-Compatibility

#24928 Cache pipeline inputs when suppressed:
  src/RazorSdk/SourceGenerators/IncrementalValueProviderExtensions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerationOptions.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
  src/RazorSdk/SourceGenerators/RazorSourceGenerator.cs
  src/RazorSdk/SourceGenerators/StaticCompilationTagHelperFeature.cs
  src/Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Labels: Area-AspNetCore

#25039 Update the netcoreapp2.1 and netcoreapp2.2 to the current framework
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/PathUtilityTests.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/LocalToolsResolverCacheTests.cs
  src/Tests/Microsoft.NET.Build.Tests/DesignTimeBuildTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAWebApp.cs
  src/Tests/dotnet-add-reference.Tests/GivenDotnetAddReference.cs
  src/Tests/dotnet-list-reference.Tests/GivenDotnetListReference.cs
  src/Tests/dotnet-remove-reference.Tests/GivenDotnetRemoveP2P.cs
  src/Tests/dotnet-watch.Tests/MsBuildFileSetFactoryTest.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallCommandTests.cs
  src/Tests/dotnet.Tests/RuntimeConfigTests.cs
Labels: Area-Infrastructure

#25350 Update the hardcoded netcoreapp1.1 to the current framework
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/LockFileMatcherTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreAppForTelemetry.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
  src/Tests/dotnet-add-reference.Tests/GivenDotnetAddReference.cs
  src/Tests/dotnet-back-compat.Tests/GivenThatWeWantToBeBackwardsCompatibleWith1xProjects.cs
Labels: Area-Infrastructure

#25597 [6.0.3xx] Disable Microsoft.DN.Compatibility pkg
  src/Compatibility/Microsoft.DotNet.Compatibility/Microsoft.DotNet.Compatibility.csproj
Labels: Area-Compatibility

#25011 [ASP.NET] Fix pack for static web assets in cross-targeting scenarios
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.ScopedCss.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.5_0.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.Pack.CrossTargeting.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.Pack.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/RazorSdk/Tasks/StaticWebAssets/ComputeReferenceStaticWebAssetItems.cs
  src/RazorSdk/Tasks/StaticWebAssets/GenerateStaticWebAsssetsPropsFile.cs
  src/RazorSdk/Tasks/StaticWebAssets/GenerateV1StaticWebAssetsManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/ResolveStaticWebAssetsEffectiveTargetFramework.cs
  src/RazorSdk/Tasks/StaticWebAssets/StaticWebAssetsGeneratePackManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/StaticWebAssetsGeneratePackagePropsFile.cs
  src/RazorSdk/Tasks/StaticWebAssets/StaticWebAssetsReadPackManifest.cs
  src/RazorSdk/Tasks/StaticWebAssets/ValidateStaticWebAssetsUniquePaths.cs
  src/RazorSdk/Tasks/StaticWebAssetsGeneratePackagePropsFile.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#25621 Preview 6 branding
  eng/Versions.props
Labels: Area-Infrastructure

#25600 Define 'DeploymentResponse' to parse Zip Deploy status response
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/ZipDeploy/ZipDeploymentStatusTests.cs
  src/WebSdk/Publish/Tasks/Properties/Resources.Designer.cs
  src/WebSdk/Publish/Tasks/Properties/Resources.resx
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.cs.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.de.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.es.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.fr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.it.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ja.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ko.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pl.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.pt-BR.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.ru.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.tr.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hans.xlf
  src/WebSdk/Publish/Tasks/Properties/xlf/Resources.zh-Hant.xlf
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/DeploymentResponse.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploymentStatus.cs
Labels: Area-Infrastructure

#25542 add rules to make sure enums match
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/Rules/EnumsMustMatch.cs
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  src/Compatibility/compatibility.slnf
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/EnumsMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.Strict.cs
Labels: Area-Compatibility

#25713 Delete unused resource files in ApiCompatibility
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.cs.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.de.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.es.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.fr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.it.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.ja.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.ko.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.pl.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.pt-BR.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.ru.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.tr.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.zh-Hans.xlf
  src/Compatibility/Microsoft.DotNet.ApiCompatibility/xlf/Strings.zh-Hant.xlf
Labels: Area-Compatibility

#25712 Update rid to the latest one
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACrossTargetedLibrary.cs
  src/Tests/dotnet.Tests/ParserTests/VSTestArgumentConverterTests.cs
Labels: Area-Infrastructure
