Repository dotnet/sdk, pull requests merged in 2022-02, with the labels that each got.

#23701 Update branding to 5.0.212
  eng/Versions.props
Labels: Area-Infrastructure

#23686 Cherry pick build config changes
  .vsts-ci.yml
Labels: Area-Infrastructure

#23703 Update branding to 6.0.103
  eng/Versions.props
Labels: Area-Infrastructure

#23702 Update branding to 5.0.406
  eng/Versions.props
Labels: Area-Infrastructure

#23723 Use Component.SdkAnalyzers for 6.0 and earlier apps
  eng/Version.Details.xml
  eng/Versions.props
  src/WebSdk/Web/Sdk/Sdk.props
  src/WebSdk/Web/Tasks/Microsoft.NET.Sdk.Web.Tasks.csproj
Labels: Area-AspNetCore

#23685 Cherry pick build config changes
  .vsts-ci.yml
Labels: Area-Infrastructure

#23177 Build Single-File for Windows 7
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Area-External, Area-SingleFile

#23336 [release/6.0.x] Build Single-File for Windows 7
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Servicing-approved, Area-ILLink

#23779 Embed FSharp.Core.nuget package in dotnet SDK
  eng/Versions.props
  src/Layout/redist/redist.csproj
  src/Layout/tool_fsharp/tool_fsc.csproj
Labels: Area-Infrastructure

#23844 fix: dotnet Program.cs: Pass telemetryClient onto the overload
  src/Cli/dotnet/Program.cs
Labels: Area-NetSDK

#23834 Opt into IEventSource4
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingLogger.cs
Labels: Area-NetSDK

#23821 Merging internal commits for release/6.0.1xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/templates/steps/source-build.yml
Labels: Area-Infrastructure

#23818 [release/6.0.3xx] Update to 1ES pools
  .vsts-ci.yml
Labels: Area-Infrastructure

#23194 make a parallel sdk build env script for powershell, not just batch
  documentation/project-docs/developer-guide.md
  eng/restore-toolset.ps1
Labels: Area-Infrastructure

#23830 Enable launch profile arguments with dotnet run
  src/Assets/TestProjects/TestAppWithLaunchSettings/Program.cs
  src/Assets/TestProjects/TestAppWithLaunchSettings/Properties/launchSettings.json
  src/Cli/Microsoft.DotNet.Cli.Utils/BuiltInCommand.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Command.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/ICommand.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
Labels: Area-CLI

#23856 Embed fSharp.Core --- retarget to release/6.0.3xx branch
  eng/Versions.props
  src/Layout/redist/redist.csproj
  src/Layout/tool_fsharp/tool_fsc.csproj
Labels: Area-Infrastructure

#23831 6.0.201 servicing branding
  eng/Versions.props
Labels: Area-Infrastructure, Branding

#23823 Merging internal commits for release/5.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#23822 Merging internal commits for release/5.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#23381 Enable additional test projects to run on helix
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
  src/Tests/Directory.Build.targets
  src/Tests/HelixTasks/AssemblyScheduler.cs
  src/Tests/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  src/Tests/Microsoft.DotNet.Cli.Sln.Internal.Tests/Microsoft.DotNet.Cli.Sln.Internal.Tests.csproj
  src/Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests.csproj
  src/Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests/xunit.runner.json
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/Microsoft.DotNet.PackageInstall.Tests.csproj
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Microsoft.DotNet.PackageValidation.Tests.csproj
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/ValidatePackageTargetTests.cs
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
  src/Tests/UnitTests.proj
  src/Tests/dotnet-msbuild.Tests/dotnet-msbuild.Tests.csproj
  src/Tests/testsProjectCannotRunOnHelixList.txt
Labels: Area-Infrastructure

#23832 Merging internal commits for release/6.0.2xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  eng/common/templates/steps/source-build.yml
  eng/runHelixAndNonHelixInParallelNonWindows.ps1
Labels: Area-Infrastructure

#22631 [Razor] Fix some pack tests and skip a failing test
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#23748 Reverse versions in error message
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
Labels: Area-Workloads

#23928 Update source-build dependency to source-build-externals
  eng/Version.Details.xml
Labels: Area-Infrastructure

#23983 Templating update 7.0.100 preview.2.22116.8
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-CodeFlow

#23992 Add snapshot tests for 5.0 and 6.0 Blazor WASM apps
  src/Assets/TestProjects/BlazorWasmHosted50/BlazorWasmHosted50.sln
  src/Assets/TestProjects/BlazorWasmHosted50/Client/App.razor
  src/Assets/TestProjects/BlazorWasmHosted50/Client/BlazorWasmHosted50.Client.csproj
  src/Assets/TestProjects/BlazorWasmHosted50/Client/Pages/Index.razor
  src/Assets/TestProjects/BlazorWasmHosted50/Client/Program.cs
  src/Assets/TestProjects/BlazorWasmHosted50/Client/Shared/MainLayout.razor
  src/Assets/TestProjects/BlazorWasmHosted50/Client/Shared/MainLayout.razor.css
  src/Assets/TestProjects/BlazorWasmHosted50/Client/_Imports.razor
  src/Assets/TestProjects/BlazorWasmHosted50/Client/wwwroot/css/app.css
  src/Assets/TestProjects/BlazorWasmHosted50/Client/wwwroot/index.html
  src/Assets/TestProjects/BlazorWasmHosted50/Server/BlazorWasmHosted50.Server.csproj
  src/Assets/TestProjects/BlazorWasmHosted50/Server/Controllers/WeatherForecastController.cs
  src/Assets/TestProjects/BlazorWasmHosted50/Server/Program.cs
  src/Assets/TestProjects/BlazorWasmHosted50/Server/Properties/launchSettings.json
  src/Assets/TestProjects/BlazorWasmHosted50/Server/Startup.cs
  src/Assets/TestProjects/BlazorWasmHosted50/Server/appsettings.Development.json
  src/Assets/TestProjects/BlazorWasmHosted50/Server/appsettings.json
  src/Assets/TestProjects/BlazorWasmHosted50/Shared/BlazorWasmHosted50.Shared.csproj
  src/Assets/TestProjects/BlazorWasmHosted50/Shared/WeatherForecast.cs
  src/Assets/TestProjects/BlazorWasmHosted60/BlazorWasmHosted60.sln
  src/Assets/TestProjects/BlazorWasmHosted60/Client/App.razor
  src/Assets/TestProjects/BlazorWasmHosted60/Client/BlazorWasmHosted60.Client.csproj
  src/Assets/TestProjects/BlazorWasmHosted60/Client/Pages/Index.razor
  src/Assets/TestProjects/BlazorWasmHosted60/Client/Program.cs
  src/Assets/TestProjects/BlazorWasmHosted60/Client/Shared/MainLayout.razor
  src/Assets/TestProjects/BlazorWasmHosted60/Client/Shared/MainLayout.razor.css
  src/Assets/TestProjects/BlazorWasmHosted60/Client/_Imports.razor
  src/Assets/TestProjects/BlazorWasmHosted60/Client/wwwroot/css/app.css
  src/Assets/TestProjects/BlazorWasmHosted60/Client/wwwroot/index.html
  src/Assets/TestProjects/BlazorWasmHosted60/Server/BlazorWasmHosted60.Server.csproj
  src/Assets/TestProjects/BlazorWasmHosted60/Server/Controllers/WeatherForecastController.cs
  src/Assets/TestProjects/BlazorWasmHosted60/Server/Program.cs
  src/Assets/TestProjects/BlazorWasmHosted60/Server/Properties/launchSettings.json
  src/Assets/TestProjects/BlazorWasmHosted60/Server/appsettings.Development.json
  src/Assets/TestProjects/BlazorWasmHosted60/Server/appsettings.json
  src/Assets/TestProjects/BlazorWasmHosted60/Shared/BlazorWasmHosted60.Shared.csproj
  src/Assets/TestProjects/BlazorWasmHosted60/Shared/WeatherForecast.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorLegacyIntegrationTest50.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorLegacyIntegrationTest60.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/LegacyBuildIntegrationTestBase.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.staticwebassets.json
Labels: Area-AspNetCore

#23995 Backport PR #23748 to 6.0.3xx
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
Labels: Area-Infrastructure

#23955 Rename "NetSdkManaged" types to "FileBased"
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallRecords/FileBasedInstallationRecordInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallerFactory.cs
  src/Tests/dotnet-workload-install.Tests/GivenFileBasedWorkloadInstall.cs
Labels: Area-Workloads

#24012 Add artifacts post processing
  src/Assets/TestProjects/VSTestDataCollectorSample/AttachmentProcessorDataCollector.csproj
  src/Assets/TestProjects/VSTestDataCollectorSample/SampleDataCollector.cs
  src/Assets/TestProjects/VSTestDataCollectorSample/TestExtensionTypesAttribute.cs
  src/Assets/TestProjects/VSTestDataCollectorSampleNoMerge/AttachmentProcessorDataCollector.csproj
  src/Assets/TestProjects/VSTestDataCollectorSampleNoMerge/SampleDataCollector.cs
  src/Assets/TestProjects/VSTestMultiProjectSolution/sln.sln
  src/Assets/TestProjects/VSTestMultiProjectSolution/test1/UnitTest1.cs
  src/Assets/TestProjects/VSTestMultiProjectSolution/test1/test1.csproj
  src/Assets/TestProjects/VSTestMultiProjectSolution/test2/UnitTest1.cs
  src/Assets/TestProjects/VSTestMultiProjectSolution/test2/test2.csproj
  src/Assets/TestProjects/VSTestMultiProjectSolution/test3/UnitTest1.cs
  src/Assets/TestProjects/VSTestMultiProjectSolution/test3/test3.csproj
  src/Cli/dotnet/commands/dotnet-test/Program.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs
  src/Cli/dotnet/commands/dotnet-test/VSTestFeatureFlag.cs
  src/Cli/dotnet/commands/dotnet-test/VSTestForwardingApp.cs
  src/Cli/dotnet/commands/dotnet-test/VSTestTrace.cs
  src/Cli/dotnet/commands/dotnet-vstest/Program.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsArtifactPostProcessing.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Area-DotNet Test

#24035 Enable artifacts post processing
  src/Cli/dotnet/commands/dotnet-test/VSTestFeatureFlag.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestFromCsprojForMultipleTFM.cs
Labels: Area-DotNet Test

#23988 Fix escaping function when argument ends with odd number of backslashes
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
  src/Tests/dotnet-test.Tests/TestCommandParserTests.cs
Labels: Area-DotNet Test

#24005 Add Visual Studio workloads to dotnet workload list
  eng/Versions.props
  src/Cli/dotnet/commands/dotnet-workload/list/InstalledWorkloadsCollection.cs
  src/Cli/dotnet/commands/dotnet-workload/list/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/list/VisualStudioWorkloads.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
Labels: Area-Workloads

#24063 Fix DefaultExcludesInProjectFolder value ignored
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
Labels: Area-WebSDK

#24086 Remove override into preview version of System.Security.Cryptography.ProtectedData
  eng/Versions.props
Labels: Area-Infrastructure

#24091 Add EnableAotAnalyzer support into SDK
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-ILLink
