Repository dotnet/sdk, pull requests merged in 2023-06, with the labels that each got.

#32956 ApiCompat log breaking changes footer as error
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/SuppressionFileHelper.cs
Labels: untriaged, Area-ApiCompat

#32952 Explicitly enable BF for WinForms and WPF in Microsoft.NET.Sdk.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: untriaged, Area-NetSDK

#32895 [release/7.0.4xx] excluded containerize from source-build
  source-build.slnf
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/Containers/containerize/containerize.csproj
  src/Containers/packaging/package.csproj
  src/Layout/redist/targets/GenerateLayout.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/PackageTests.cs
Labels: Area-Containers

#32919 Containers: include the registry name when pushing an image.
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/ContainerHelpersTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: Area-Infrastructure, untriaged

#32950 Enable interceptors compiler feature when RDG is enabled
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.BeforeCommon.targets
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
Labels: untriaged, Area-AspNetCore

#33031 Log success or error only for error suppressions
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/SuppressionFileHelper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/SuppressableMSBuildLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/SuppressableConsoleLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ISuppressableLog.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressableTestLog.cs
Labels: Area-ApiCompat

#33004 [port to main] Explicitly enable BF for WinForms and WPF in Microsoft.NET.Sdk.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: untriaged, Area-NetSDK

#33005 Do not fail dotnet watch on workspace errors
  src/BuiltInTools/dotnet-watch/HotReload/CompilationWorkspaceProvider.cs
Labels: untriaged

#33006 Do not fail dotnet watch on workspace errors
  src/BuiltInTools/dotnet-watch/HotReload/CompilationWorkspaceProvider.cs
Labels: untriaged

#32883 Update the rid to the latest
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/GivenAFrameworkDependencyFile.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantACustomTFM.cs
  src/Tests/Microsoft.NET.Build.Tests/GlobalPropertyFlowTests.cs
Labels: Area-Infrastructure, untriaged

#33056 Update branding to 6.0.411
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33057 Update branding to 7.0.108
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33059 Update branding to 7.0.305
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33055 Update branding to 6.0.314
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33054 Update branding to 6.0.119
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33036 PackageValidation compare TargetFrameworkInformation instead of TargetFramework property directly
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/ApiCompatRunnerExtensions.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Package.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Task/ValidatePackageTargetIntegrationTests.cs
Labels: untriaged, Area-ApiCompat

#32375 [release/7.0.3xx] added `Microsoft.DotNet.Cli.Utils.dll` to package content
  src/Containers/packaging/package.csproj
Labels: Servicing-approved, Area-Containers

#32734 Add PackageReference to new Roslyn package (#29787)
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: Servicing-approved, Area-Compilers

#33043 add GarbageCollectionAdaptationMode msbuild property
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: untriaged, Area-ILLink

#33039 Add dependencies needed for source-build PVP flow
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#33045 Don't run helix tests if the build fails
  eng/build.yml
Labels: Area-Infrastructure, untriaged

#33007 Startup race condition
  src/Assets/TestProjects/WatchAppWithProjectDeps/AppWithDeps/AppWithDeps.csproj
  src/Assets/TestProjects/WatchAppWithProjectDeps/AppWithDeps/Program.cs
  src/Assets/TestProjects/WatchAppWithProjectDeps/Dependency/Foo.cs
  src/Assets/TestProjects/WatchAppWithProjectDeps/FSharp/Lib.fs
  src/Assets/TestProjects/WatchAppWithProjectDeps/FSharp/Lib.fsproj
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationWorkspaceProvider.cs
  src/BuiltInTools/dotnet-watch/HotReload/HotReload.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Properties/launchSettings.json
  src/Tests/dotnet-watch.Tests/Watch/AppWithDepsTests.cs
Labels: Area-Infrastructure, untriaged

#33102 Fix duplicate error code
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: Area-Infrastructure, untriaged

#33122 [Blazor WASM] Don't apply hot reload deltas if Blazor has not been initialized
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-AspNetCore

#32970 Add warning about version/distro-specific RID assets in .NET 8+
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: untriaged, Area-NetSDK

#32783 Containers: add support for using 'podman' without a system 'docker' alias.
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/KnownLocalRegistryTypes.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ContainerCli.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/DockerAvailableUtils.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/DockerDaemonTests.cs
Labels: untriaged, Area-Containers

#33179 Add additional dependencies for PVP flow
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#33185 Expose EnableComHosting to analyzers
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
Labels: area-runtime

#33197 [release/7.0.1xx] Fix error code to maintain consistency
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#33159 [release/7.0.4xx] Backport '[Blazor WASM] Don't apply hot reload deltas if Blazor has not been initialized'
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Servicing-approved, Area-AspNetCore

#33160 [release/6.0.4xx] Backport '[Blazor WASM] Don't apply hot reload deltas if Blazor has not been initialized'
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Servicing-approved, Area-AspNetCore

#32981 Enable error when using BinaryFormatter in GenerateResource
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: untriaged

#33003 Set PlatformName and other properties early enough in outer build
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommonCrossTargeting.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACrossTargetedLibrary.cs
Labels: untriaged, Area-NetSDK

#33213 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/ToolManifest/ToolManifestFinder.cs
  src/Common/EnvironmentVariableNames.cs
  src/Tests/dotnet.Tests/CommandTests/ToolManifestFinderTests.cs
Labels: Area-Infrastructure, untriaged

#33209 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/ToolManifest/ToolManifestFinder.cs
  src/Common/EnvironmentVariableNames.cs
  src/Tests/dotnet.Tests/CommandTests/ToolManifestFinderTests.cs
Labels: Area-Infrastructure, untriaged

#33212 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/ToolManifest/ToolManifestFinder.cs
  src/Common/EnvironmentVariableNames.cs
  src/Tests/dotnet.Tests/CommandTests/ToolManifestFinderTests.cs
Labels: Area-Infrastructure, untriaged

#33227 Allow MSBuild to use BinaryFormatter
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#33228 Fix duplicate NETSDK1183
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-Infrastructure, untriaged

#33216 Merging internal commits for release/7.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/ToolManifest/ToolManifestFinder.cs
  src/Common/EnvironmentVariableNames.cs
  src/Tests/dotnet.Tests/CommandTests/ToolManifestFinderTests.cs
Labels: Area-Infrastructure, untriaged

#33215 Merging internal commits for release/7.0.1xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/ToolManifest/ToolManifestFinder.cs
  src/Common/EnvironmentVariableNames.cs
  src/Tests/dotnet.Tests/CommandTests/ToolManifestFinderTests.cs
Labels: Area-Infrastructure, untriaged

#33328 Adjust test approval following the change to .gitignore template
  src/Tests/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitignore-file#-n#item.verified/dotnet-gitignore-file/.gitignore
Labels: Area-Infrastructure, untriaged

#33348 Normalize line endings in GenAPI consistently
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
Labels: untriaged, Area-GenAPI

#33309 Enable dynamic adaptive GC by default in Web SDK when PublishAot==true
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
Labels: untriaged, Area-WebSDK

#33312 First Run: Update ASP.NET cert message to be OS-specific
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Cli/Microsoft.DotNet.Configurer/LocalizableStrings.resx
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#33225 Fix R2R map generation on OSX
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
Labels: untriaged, Area-ReadyToRun

#33394 Update branding to 7.0.306
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33393 Update branding to 7.0.109
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33392 Update branding to 6.0.412
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33391 Update branding to 6.0.315
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33390 Update branding to 6.0.120
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33405 Update to Svc Pool
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#33292 Fix Source Link cross-targeting targets
  src/Assets/TestProjects/SourceLinkTestApp/SourceLinkTestApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.SourceLink.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.SourceLink.targets
  src/Tests/Microsoft.NET.Build.Tests/SourceLinkTests.cs
Labels: untriaged, Area-NetSDK

#33266 Containers: Registry: support pulling from quay.io.
  src/Containers/Microsoft.NET.Build.Containers/Registry.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/RegistryTests.cs
Labels: untriaged, Area-Containers

#33037 Add support for starting the application through CMD (instead of ENTRYPOINT).
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageConfig.cs
  src/Containers/Microsoft.NET.Build.Containers/KnownAppCommandInstructions.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/containerize/ContainerizeCommand.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/Microsoft.NET.Build.Containers.UnitTests.csproj
Labels: untriaged, Area-Containers

#33280 Containers: add mappings for s390x and ppc64le platform architectures to corresponding rids.
  src/Containers/Microsoft.NET.Build.Containers/Registry.cs
Labels: untriaged, Area-Containers

#33038 Update ValleySoft.DockerCredsProvider to get better support for podman authentication
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
Labels: Area-Infrastructure, untriaged

#33470 Prevent built-in artifacts output functionality from conflicting with Microsoft.Build.Artifacts SDK
  src/Assets/TestProjects/ArtifactsSdkTest/ArtifactsSdkTest.sln
  src/Assets/TestProjects/ArtifactsSdkTest/Directory.Build.props
  src/Assets/TestProjects/ArtifactsSdkTest/MSBuildSdk/Class1.cs
  src/Assets/TestProjects/ArtifactsSdkTest/MSBuildSdk/MSBuildSdk.csproj
  src/Assets/TestProjects/ArtifactsSdkTest/PackageReference/PackageReference.csproj
  src/Assets/TestProjects/ArtifactsSdkTest/PackageReference/Program.cs
  src/Assets/TestProjects/ArtifactsSdkTest/global.json
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultArtifactsPath.props
  src/Tests/Microsoft.NET.Build.Tests/ArtifactsOutputPathTests.cs
Labels: Area-Infrastructure, untriaged

#33475 Updating branding to preview 7
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33282 Do not look in root for .`config\dotnet-tools.json ` manifest for windows
  src/Common/EnvironmentVariableNames.cs
Labels: Area-Infrastructure, untriaged

#33406 Add a unique error message when workloads are disabled but a customer is trying to use workloads
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
  src/Tests/Microsoft.NET.Build.Tests/WorkloadTests.cs
Labels: Area-Infrastructure, untriaged

#33441 Support setting workload set versions in global.json
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadInfoHelper.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadOptionsExtensions.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadResolverFactory.cs
  src/Cli/dotnet/commands/dotnet-workload/repair/WorkloadRepairCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/uninstall/WorkloadUninstallCommand.cs
  src/Microsoft.DotNet.TemplateLocator/TemplateLocator.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/CachingWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/WorkloadSdkResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.GlobalJsonReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Strings.resx
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.NewtonsoftJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.SystemTextJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.cs.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.de.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.es.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.fr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.it.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ja.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ko.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pl.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pt-BR.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ru.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.tr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hans.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ShowMissingWorkloads.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/WorkloadPackGroupTests.cs
Labels: untriaged, Area-Workloads

#33576 adjust item templates to langVersion changes in Roslyn
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.class.verified/class/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.targetFramework=netstandard2.0.verified/ClassLib.csproj
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.targetFramework=netstandard2.0.verified/enum/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.targetFramework=netstandard2.0.verified/std-streams/stdout.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.verified/enum/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.interface.verified/interface/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.record.verified/record/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.struct.verified/struct/TestItem1.cs
  src/Tests/dotnet-new.Tests/DotnetClassTemplateTests.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Class-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Enum-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Interface-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Record-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Struct-CSharp/.template.config/template.json
Labels: Area-Infrastructure, untriaged

#33445 Add `--disable-build-servers` to Run and Store CLI commands
  src/Cli/dotnet/commands/dotnet-run/RunCommandParser.cs
  src/Cli/dotnet/commands/dotnet-store/StoreCommandParser.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetMSBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetRunInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetTestInvocation.cs
Labels: untriaged, Area-CLI

#33515 don't install older runtimes on arm64 architectures as they aren't supported
  eng/restore-toolset.ps1
Labels: Area-Infrastructure, untriaged

#33584 Make non-portable RID warning check all available NETCore.App RIDS for the current TFM
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: untriaged, Area-NetSDK

#33621 Make non-portable RID warning check all available NETCore.App RIDS for the current TFM
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: untriaged, Area-NetSDK

#33511 Set XLF files to be collapsed by default in PR reviews
  .gitattributes
Labels: Area-Infrastructure, untriaged

#33305 Update .gitignore to ignore .env files
  src/Tests/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitignore-file#-n#item.verified/dotnet-gitignore-file/.gitignore
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitignore/.gitignore
Labels: Area-Infrastructure, untriaged

#33655 [release/7.0.4xx] containers: add read support for oci manifest v1
  src/Containers/Microsoft.NET.Build.Containers/Registry/HttpExtensions.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/SchemaTypes.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/RegistryTests.cs
Labels: untriaged, Area-Containers

#33537 [release/7.0.4xx] Containers release notes
  src/Containers/docs/ReleaseNotes/v7.0.400.md
  src/Containers/packaging/package.csproj
Labels: untriaged, Area-Containers

#33184 Enable the task unit test projects in helix and apply fixes to them.
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf~RF243dc495.TMP
  src/Tasks/Common/Resources/xlf/Strings.it.xlf~RF30a3de88.TMP
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAGenerateRuntimeConfigurationFiles.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolvePackageDependenciesTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolveRuntimePackAssetsTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenThatWeHaveErrorCodes.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenThatWeWantToGetDependenciesViaDesignTimeBuild.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/all.asset.types.project.lock.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/dependencies.withgraphs.project.lock.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/dotnet.new.project.lock.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/simple.dependencies.project.lock.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/MockNeverCacheBuildEngine4.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/ProcessFrameworkReferencesTests.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ShowPreviewMessage.cs
  src/Tests/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantAMessageWhenBuildingWithAPreviewSdk.cs
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
  src/Tests/UnitTests.proj
Labels: Area-Infrastructure, untriaged

#33670 Updating the runtime to 7.0.8
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33682 Fix "Registry is not supported on this platform" with mono
  src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs
Labels: untriaged, Area-CLI

#22576 GenerateRuntimeConfig now uses stream serialization instead of loading file in memory
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenADependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateRuntimeConfigurationFiles.cs
Labels: Area-Infrastructure

#33669 [iOS] Add HybridGlobalization flag in dotnet/sdk
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: untriaged, Area-ILLink

#33731 build fix
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/details/DetailsCommand.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/TabCompletionTests.Approval.cs
Labels: Area-Infrastructure, untriaged

#33695 Pass editorconfig files to RazorCoreCompile
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Compilation.targets
Labels: untriaged, Area-AspNetCore
