Repository dotnet/sdk, pull requests merged in 2023-12, with the labels that each got.

#37278 Fix the runtime and emsdk versions
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#37276 Mark ApiCompatValidatePackageSemaphoreFile as internal
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
Labels: Area-Infrastructure, untriaged

#37282 Mark ApiCompatValidateAssembliesSemaphoreFile as internal
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets
Labels: untriaged, Area-ApiCompat

#37310 Minimize and update MSBuild in dotnet-watch
  Directory.Packages.props
  eng/Versions.props
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Layout/redist/redist.csproj
  src/Layout/tool_msbuild/tool_msbuild.csproj
Labels: Area-Infrastructure, untriaged

#37316 Avoid copying containerize to SDK root
  src/Layout/redist/redist.csproj
Labels: Area-Infrastructure, untriaged

#37072 Containers support was moved higher to enable creating image of CLI apps
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.props
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
Labels: untriaged, Area-WebSDK, Area-Containers

#36505 [Issue #35173] `--verbosity quiet` suppress success message
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUninstallGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
Labels: untriaged, Area-Tools

#37233 Add support for test and build commands
  src/Assets/TestProjects/WatchNoDepsApp/WatchNoDepsApp.csproj
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Tests/dotnet-watch.Tests/CommandLineOptionsTests.cs
  src/Tests/dotnet-watch.Tests/Watch/ProgramTests.cs
  src/Tests/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: Servicing-approved, Area-Watch

#37305 Correct emsdk Version.Details.xml sha
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#37114 Fix incorrect app host used in build when PublishSingleFile=true
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
Labels: untriaged, area-Single-File

#37164 Disable Source Link's EmbedUntrackedSources in desktop WPF projects
  src/Assets/TestProjects/DesktopWpf/FxWpf/AssemblyInfo.cs
  src/Assets/TestProjects/DesktopWpf/FxWpf/FxWpf.csproj
  src/Assets/TestProjects/DesktopWpf/FxWpf/MainWindow.xaml
  src/Assets/TestProjects/DesktopWpf/FxWpf/MainWindow.xaml.cs
  src/Assets/TestProjects/DesktopWpf/FxWpf/Program.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.SourceLink.targets
  src/Tests/Microsoft.NET.Build.Tests/SourceLinkTests.cs
Labels: Servicing-approved, Area-SourceLink

#37381 Check dependencies of Microsoft.DotNet.MSBuildSdkResolver against baseline
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
Labels: Area-Infrastructure, untriaged

#37370 Trusted roots: 2023-11 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#37405 [release/6.0.4xx] Trusted roots: 2023-11 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#37404 [release/7.0.1xx] Trusted roots: 2023-11 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#37401 [release/7.0.3xx] Trusted roots: 2023-11 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#37407 Fix stage 2 VMR source-build
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: source-build, untriaged, Area-NetSDK

#37384 Remove Microsoft.SourceBuild.Intermediate from prebuilt baseline
  eng/SourceBuildPrebuiltBaseline.xml
Labels: Area-Infrastructure, untriaged

#37471 Add SkipGetTargetFrameworkProperties to redist.csproj
  src/Layout/redist/redist.csproj
Labels: Area-Infrastructure, untriaged

#37448 Add -f alias for framework option to list package command
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommandParser.cs
  test/dotnet-list-package.Tests/GivenDotnetListPackage.cs
Labels: untriaged, Area-CLI

#37411 Fix typos of Register-ArgumentCompleter parameters
  scripts/register-completions.ps1
Labels: Area-Infrastructure, untriaged

#37518 Remove pinning from xdt
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#37517 Update minimum VS version to 17.8 in 8.0.2xx
  Directory.Build.props
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Layout/redist/minimumMSBuildVersion
Labels: Area-Infrastructure, untriaged, breaking-change, needs-breaking-change-doc-created

#37516 Fix sln add for duplicate projects under different paths with same root
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/App.sln
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Class1.cs
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Class2.cs
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Class1.cs
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Class2.cs
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Class3.cs
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Second.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Test.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/TestCollision.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Third/Class1.cs
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Third/Class2.cs
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Third/Second.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Second/Third/TestCollision.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/Test.csproj
  src/Assets/TestProjects/TestAppWithSlnAndCsprojInSubDirVSErrors/Base/TestCollision.csproj
  src/Cli/dotnet/SlnFileExtensions.cs
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
Labels: Area-Infrastructure, untriaged

#37546 Use dotnet home instead of null when writing state file
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
Labels: untriaged, Area-Workloads

#36707 Bump dockercredsprovider to pick up a bugfix
  Directory.Packages.props
  eng/SourceBuildPrebuiltBaseline.xml
Labels: Area-Infrastructure, untriaged

#37221 don't use cookies to unblock CSRF workflows
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
Labels: untriaged, Area-Containers

#37054 Improve Container support for AOT publishing and targeting musl runtimes.
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageAndTag.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageTag.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.props
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerTestsFixture.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ProjectInitializer.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/RegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ToolsetUtils.cs
Labels: untriaged, Area-Containers

#37055 wrap and handle cancellation exceptions in .NET Task
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
Labels: untriaged, Area-Containers

#37474 Pass SelfContained=true in CheckIlcVersions
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: untriaged, Area-ILLink

#37346 Permit setting whether to use workload sets or loose manifests Fixes #34561
  src/Cli/dotnet/Installer/Windows/InstallMessageDispatcher.cs
  src/Cli/dotnet/Installer/Windows/InstallRequestMessage.cs
  src/Cli/dotnet/Installer/Windows/InstallRequestType.cs
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/InstallStateContents.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/IInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerServer.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-workload-install.Tests/GivenFileBasedWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/MockPackWorkloadInstaller.cs
Labels: untriaged, Area-Workloads

#37625 Base version
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerServer.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Tests/dotnet-workload-install.Tests/MockPackWorkloadInstaller.cs
Labels: untriaged, Area-Workloads

#37659 Handle HTTP 403 Forbidden in Containers
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultBlobOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultManifestOperations.cs
Labels: untriaged, Area-Containers

#37609 Swap 9.0 to current target framework
  test/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/PackageTests.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeManifestSupportedFrameworks.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToFloatWarningLevels.cs
  test/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToTestAMultitargetedSolutionWithPublishReleaseOrPackRelease.cs
  test/Microsoft.NET.Publish.Tests/PublishTestUtils.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
  test/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure, untriaged
