Repository dotnet/sdk, pull requests merged in 2023-08, with the labels that each got.

#34371 Update branding to 7.0.308
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#34367 Update branding to 6.0.122
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#34368 Update branding to 6.0.317
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#34369 Update branding to 6.0.414
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#34370 Update branding to 7.0.111
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#34143 Fix package verification for some valid packages on windows
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
Labels: Servicing-approved, Area-Infrastructure

#34144 Fix package verification for some valid packages on windows
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
Labels: Servicing-approved, Area-Infrastructure

#34390 Ensure GenAPI replaces init method body
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/BodyBlockCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: untriaged, Area-GenAPI

#34406 Fix ApiCompat.Tool execution
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
Labels: untriaged, Area-ApiCompat

#33700 Reenable in-test timeout
  src/Tests/dotnet-run.Tests/GivenDotnetRunIsInterrupted.cs
Labels: Area-Infrastructure, untriaged

#34385 Change prerelease label to servicing
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33471 When Hot Reload change fails to apply in the browser send full error …
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
Labels: untriaged, Area-AspNetCore

#34279 Enable "portable" RID graph when targeting .NET 8 and higher
  src/Layout/redist/PortableRuntimeIdentifierGraph.json
  src/Layout/redist/targets/BuildToolsetTasks.targets
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/toolset-tasks/UpdatePortableRuntimeIdentifierGraph.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/RuntimeIdentifierGraphTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToCrossPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure, untriaged

#34430 Rework of Allow ResolveReadyToRunCompilers to be run under FreeBSD
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: untriaged, Area-ReadyToRun

#34434 Automate the version label
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#34461 Speed up template packing during overlay
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#34481 Revert "Speed up template packing during overlay"
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#34511 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/ForwardingAppImplementation.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/WindowsExePreferredCommandSpecFactory.cs
  src/Cli/dotnet/Telemetry/MacAddressGetter.cs
  src/Cli/dotnet/commands/dotnet-help/HelpCommand.cs
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAProjectPathCommandResolver.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAnAppBaseCommandResolver.cs
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenForwardingApp.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenMsbuildForwardingApp.cs
Labels: Area-Infrastructure, untriaged

#34512 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/ForwardingAppImplementation.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/WindowsExePreferredCommandSpecFactory.cs
  src/Cli/dotnet/Telemetry/MacAddressGetter.cs
  src/Cli/dotnet/commands/dotnet-help/HelpCommand.cs
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAProjectPathCommandResolver.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAnAppBaseCommandResolver.cs
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenForwardingApp.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenMsbuildForwardingApp.cs
Labels: Area-Infrastructure, untriaged

#34515 Merging internal commits for release/7.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/ForwardingAppImplementation.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/WindowsExePreferredCommandSpecFactory.cs
  src/Cli/dotnet/Telemetry/MacAddressGetter.cs
  src/Cli/dotnet/commands/dotnet-help/HelpCommand.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/LocalDocker.cs
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAProjectPathCommandResolver.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAnAppBaseCommandResolver.cs
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenForwardingApp.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenMsbuildForwardingApp.cs
Labels: Area-Infrastructure, untriaged

#34518 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/ForwardingAppImplementation.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/WindowsExePreferredCommandSpecFactory.cs
  src/Cli/dotnet/Telemetry/MacAddressGetter.cs
  src/Cli/dotnet/commands/dotnet-help/HelpCommand.cs
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAProjectPathCommandResolver.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAnAppBaseCommandResolver.cs
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenForwardingApp.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenMsbuildForwardingApp.cs
Labels: Area-Infrastructure, untriaged

#34519 Handle unknown version in EnvironmentInfo test helper
  src/Tests/Microsoft.NET.TestFramework/EnvironmentInfo.cs
Labels: Area-Infrastructure, untriaged

#34459 don't copy over the .dotnet dependencies if they are already there
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#34266 Change the hard code of newtonsoft package version
  src/Assets/TestProjects/BlazorMultiApp/BlazorMultipleApps.FirstClient/BlazorMultipleApps.FirstClient.csproj
  src/Assets/TestProjects/ComServerWithDependencies/ComServerWithDependencies.csproj
  src/Assets/TestProjects/CompilationContext/TestApp/TestApp.csproj
  src/Assets/TestProjects/CppCliLibWithWpfFrameworkReference/Project1.vcxproj
  src/Assets/TestProjects/CrossTargeting/DesktopAndNetStandard/DesktopAndNetStandard.csproj
  src/Assets/TestProjects/CrossTargeting/NetStandardAndNetCoreApp/NetStandardAndNetCoreApp.csproj
  src/Assets/TestProjects/KitchenSink/TestLibrary/TestLibrary.csproj
  src/Assets/TestProjects/MultiDependentProject/MultiDependentProject.csproj
  src/Assets/TestProjects/NETCoreCppClApp/NETCoreCppCliTest/NETCoreCppCliTest.vcxproj
  src/Assets/TestProjects/NewtonSoftDependentProject/NewtonSoftDependentProject.csproj
  src/Assets/TestProjects/NewtonsoftProfile/NewtonsoftFilterProfile.xml
  src/Assets/TestProjects/NewtonsoftProfile/NewtonsoftProfile.xml
  src/Assets/TestProjects/PortableTool/consoledemo.csproj
  src/Assets/TestProjects/PortableToolWithTestProject/App/consoledemo.csproj
  src/Assets/TestProjects/SimpleDependencies/SimpleDependencies.csproj
  src/Assets/TestProjects/StoreManifests/NewtonsoftFilterProfile.xml
  src/Assets/TestProjects/StoreManifests/NewtonsoftMultipleVersions.xml
  src/Assets/TestProjects/TargetManifests/NewtonsoftFilterProfile.xml
  src/Assets/TestProjects/TargetManifests/NewtonsoftMultipleVersions.xml
  src/Assets/TestProjects/TargetManifests/PrunePackages.xml
  src/Assets/TestProjects/TestAppWithSlnAndSolutionFolders/src/App/App.csproj
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerExtractTests.cs
  src/Tests/Microsoft.NET.Build.Tests/DepsFileSkipTests.cs
  src/Tests/Microsoft.NET.Build.Tests/DesignTimeBuildTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExe.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToCopyLocalDependencies.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThereAreDefaultItems.cs
  src/Tests/Microsoft.NET.Build.Tests/GiventThatWeWantDesignerSupport.cs
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackACppCliProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPreserveCompilationContext.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishToClickOnce.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantAutomaticTargetingPackReferences.cs
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
  src/Tests/Microsoft.NET.TestFramework/TestAsset.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
  src/Tests/dotnet-add-package.Tests/GivenDotnetPackageAdd.cs
  src/Tests/dotnet-list-package.Tests/GivenDotnetListPackage.cs
  src/Tests/dotnet-restore.Tests/GivenThatIWantToRestoreApp.cs
Labels: Area-Infrastructure, untriaged

#34513 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/ForwardingAppImplementation.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/WindowsExePreferredCommandSpecFactory.cs
  src/Cli/dotnet/Telemetry/MacAddressGetter.cs
  src/Cli/dotnet/commands/dotnet-help/HelpCommand.cs
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAProjectPathCommandResolver.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAnAppBaseCommandResolver.cs
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenForwardingApp.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenMsbuildForwardingApp.cs
Labels: Area-Infrastructure, untriaged

#34516 Merging internal commits for release/7.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/ForwardingAppImplementation.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/WindowsExePreferredCommandSpecFactory.cs
  src/Cli/dotnet/Telemetry/MacAddressGetter.cs
  src/Cli/dotnet/commands/dotnet-help/HelpCommand.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/LocalDocker.cs
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAProjectPathCommandResolver.cs
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAnAppBaseCommandResolver.cs
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenForwardingApp.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenMsbuildForwardingApp.cs
Labels: Area-Infrastructure, untriaged

#33163 Add a concept of image family to container base image inference
  src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageTag.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: untriaged, Area-Containers

#34537 Output the digest of the generated image
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
Labels: Area-Containers

#34534 fix AppHostShellShimMaker to make it work well with Crossplatform ResourceUpdater
  src/Cli/dotnet/ShellShim/AppHostShimMaker.cs
Labels: Area-Infrastructure, untriaged

#34433 Support Records in GenAPI
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/Common/NullableAttributes.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/Filtering/ImplicitSymbolFilter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/TypeDeclarationCSharpSyntaxRewriter.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/SymbolExtensions.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: untriaged, Area-GenAPI

#34021 Don't fire NETSDK1206 if known RID platforms were not determined
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: untriaged, Area-NetSDK

#34565 Update minimumMSBuildVersion to 17.7.0
  eng/Versions.props
  src/Layout/redist/minimumMSBuildVersion
Labels: Area-Infrastructure, untriaged

#33945 Containers: 8.0.1xx readme notes
  src/Containers/docs/ReleaseNotes/v8.0.100.md
  src/Containers/packaging/package.csproj
Labels: Area-Containers

#34402 Revert "Allow MSBuild to use BinaryFormatter"
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#30085 Update README.md
  src/WebSdk/README.md
Labels: Area-WebSDK

#34645 .NET 9 branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#22420 Allow overriding ServerGarbageCollection in WebSdk
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.props
Labels: Area-WebSDK

#34307 One option for fixing the locked file issue in the test
  src/Tests/dotnet-new.Tests/BaseIntegrationTest.cs
  src/Tests/dotnet-new.Tests/TemplateDiscoveryTests.cs
Labels: Area-Infrastructure, untriaged

#34654 Enable the backport flow similar to other repos
  .github/workflows/backport.yml
Labels: Area-Infrastructure, untriaged

#34237 Containers: implementation of OAuth2
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
Labels: untriaged, Area-Containers

#34606 MSBuild terminal logger enamblement.
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildLogger.cs
Labels: Area-Infrastructure, untriaged

#34678 [Containers] Implement OAuth token login for container registries
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
Labels: Area-Containers

#34680 [release/8.0.1xx-rc1] Add WorkloadPublishProperties telemetry event
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildLogger.cs
Labels: untriaged, Area-NetSDK

#34681 [release/8.0.1xx] Add WorkloadPublishProperties telemetry event
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildLogger.cs
Labels: untriaged, Area-NetSDK

#34656 reenable CI for the 1xx branch
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#34345 Remove a nowarn line added for preview 1
  Directory.Build.props
Labels: Area-Infrastructure, untriaged

#34322 First-run workload experience
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstRunConfiguration.cs
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/Program.cs
  src/Cli/dotnet/commands/dotnet-workload/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandBase.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadIntegrityChecker.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/IInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallerFactory.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadResolverFactory.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hant.xlf
  src/Common/EnvironmentVariableNames.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurer.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurerWIthStateSetup.cs
Labels: untriaged, Area-Workloads

#34587 Fix redist.csproj build failure on SLN rebuild in VS
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#34650 Add AdditionalRuntimeIdentifier if building from source
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#34658 [release/8.0.1xx] Fix runtime pack selection for `dotnet build` with PublishAot=true and PublishAotUsingRuntimePack=true
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
Labels: untriaged, Area-WebSDK

#34657 [release/8.0.1xx-rc1] Fix runtime pack selection for `dotnet build` with PublishAot=true and PublishAotUsingRuntimePack=true
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
Labels: untriaged, Area-WebSDK

#34666 Fix in Microsoft.NET.Sdk.DefaultItems.targets for .DS_Store causing build failures on MacOSX
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
Labels: untriaged, Area-WebSDK

#34712 [release/8.0.1xx-rc1] Fix in Microsoft.NET.Sdk.DefaultItems.targets for .DS_Store causing build failures on MacOSX
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
Labels: untriaged, Area-WebSDK

#34710 [release/8.0.1xx] Fix in Microsoft.NET.Sdk.DefaultItems.targets for .DS_Store causing build failures on MacOSX
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
Labels: untriaged, Area-WebSDK

#34702 [release/8.0.1xx] Add AdditionalRuntimeIdentifier if building from source
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#34716 add note about supporting identity token auth for containers in .NET 8
  src/Containers/docs/ReleaseNotes/v8.0.100.md
Labels: Area-Containers

#34687 Add back the current version of MSBuild that got removed by accident in the CPM PR
  eng/Versions.props
  src/Layout/tool_msbuild/tool_msbuild.csproj
Labels: Area-Infrastructure, untriaged

#34651 Remove platform from output path
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultOutputPaths.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExe.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/ComposeStoreCommand.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/MSBuildCommand.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/PublishCommand.cs
  src/Tests/Microsoft.NET.TestFramework/OutputPathCalculator.cs
Labels: Area-Infrastructure, untriaged

#34759 Disable failing tests
  src/Tests/dotnet-new.Tests/DotnetNewDetailsTest.Approval.cs
Labels: Area-Infrastructure, untriaged

#34694 Backport of 'First-run workload experience #34322' to release/8.0.1xx
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstRunConfiguration.cs
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/Program.cs
  src/Cli/dotnet/commands/dotnet-workload/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandBase.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadIntegrityChecker.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/IInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallerFactory.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadResolverFactory.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hant.xlf
  src/Common/EnvironmentVariableNames.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurer.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurerWIthStateSetup.cs
Labels: Area-Infrastructure, untriaged

#34768 I noticed a copy issue in another PR which may be related to the reference here that shouldn't be necessary.
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Infrastructure, untriaged

#34820 [release/8.0.1xx-rc1] Update dependencies from microsoft/vstest
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#34838 Fix CanSortByDownloadCountAndThenByName test by using CurrentCulture comparison to match product
  src/Tests/dotnet-new.Tests/DotnetNewSearchTests.cs
Labels: Area-Infrastructure, untriaged

#34840 Enable interceptors feature when ConfigurationBindingGenerator is enabled
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
Labels: untriaged, Area-AspNetCore

#34836 Make UseRidGraph property map to runtime config option
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantRuntimeConfigInBuiltProjectOutputGroup.cs
Labels: untriaged, Area-NetSDK

#34848 Update dependabot.yml to target 8.0.1xx
  .github/dependabot.yml
Labels: Area-Infrastructure, untriaged

#34419 Allow PublishSingleFile and PublishAot specified simultaneously
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
Labels: untriaged, Area-ILLink

#34871 Validate "this" extension methods and limit visibility
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddMemberToInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotSealType.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/SymbolExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
Labels: Area-Infrastructure, untriaged

#34899 Removing stale msbuild feed
  NuGet.config
Labels: Area-Infrastructure, untriaged

#34889 Enable Windows thread pool config switch via Project file
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
Labels: Area-Infrastructure, untriaged

#34872 Validate member types
  src/Microsoft.DotNet.ApiSymbolExtensions/SymbolExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/CompatibleFrameworkInPackageValidatorIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
Labels: untriaged, Area-ApiCompat

#34845 [Blazor] Remove hot reload deltas cache
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-AspNetCore

#34873 Test for aot library with eventpipe
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: untriaged, Area-NativeAOT

#34585 Update our TFM support and error messaging for 17.7
  eng/Versions.props
  src/Layout/redist/redist.csproj
  src/Layout/tool_msbuild/tool_msbuild.csproj
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenThatWeHaveErrorCodes.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeManifestSupportedFrameworks.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToFloatWarningLevels.cs
  src/Tests/Microsoft.NET.Build.Tests/SourceLinkTests.cs
  src/Tests/Microsoft.NET.Clean.Tests/GivenThatWeWantToCleanAProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: Area-Infrastructure, untriaged

#34893 [release/7.0.4xx] Fix CanSortByDownloadCountAndThenByName test by using CurrentCulture …
  src/Tests/dotnet-new.Tests/DotnetNewSearchTests.cs
Labels: Area-Infrastructure, untriaged

#34903 Add internal _UseManagedNtlm feature switch
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
Labels: Area-Infrastructure, untriaged

#34999 [release/8.0.1xx] Validate this extension methods and member types in APICompat
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddAbstractMember.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddMemberToInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotSealType.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/SymbolExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/CompatibleFrameworkInPackageValidatorIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/MembersMustExistTests.cs
Labels: Servicing-approved, Area-ApiCompat

#34978 Allow ArtifactsPath telemetry to flow
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildLogger.cs
Labels: Area-Infrastructure, untriaged

#34954 [release/8.0] Update IsTargetFrameworkCompatible check
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
Labels: untriaged, Area-WebSDK

#34394 Crossplatform ResourceUpdater
  src/Cli/dotnet/ShellShim/AppHostShimMaker.cs
  src/Tasks/Microsoft.NET.Build.Tasks/CreateAppHost.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateShims.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenWeWantToRequireWindowsForDesktopApps.cs
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProjectWithPackagedShim.cs
Labels: untriaged, Area-NetSDK

#34863 [release/8.0.1xx] Containers: prefer starting the app using 'dotnet <assembly.dll>'.
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: untriaged, Area-Containers

#35044 Fix workload info
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/list/InstalledWorkloadsCollection.cs
Labels: untriaged, Area-Workloads

#35045 Enable interceptors feature when ConfigurationBindingGenerator is enabled
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
Labels: untriaged, Area-AspNetCore

#35062 Containers: LogHttpResponseAsync: include request method, and don't format a message when trace logging is not enabled.
  src/Containers/Microsoft.NET.Build.Containers/Registry/HttpExtensions.cs
Labels: untriaged, Area-Containers

#35061 Update CODEOWNERS for libraries compat tools
  CODEOWNERS
Labels: Area-Infrastructure
