Repository dotnet/sdk, pull requests merged in 2023-05, with the labels that each got.

#32121 Remove reference to 'BINDING' in 'BlazorHotReload.js'
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
Labels: untriaged, Area-AspNetCore

#32145 Make TryGetInternalDefaultConstructor work without internal metadata
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
Labels: untriaged, Area-GenAPI

#32170 [wasm] Move SelfContained=true from pack to SDK
  src/WasmSdk/Sdk/Sdk.props
Labels: Area-WasmSdk

#32166 Trusted roots: 2023-04 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
  src/Tests/trustedroots.Tests/GivenTimestampingCtlFile.cs
Labels: Area-Infrastructure, untriaged

#32177 Update branding to 6.0.118
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32178 Update branding to 6.0.313
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32180 Update branding to 7.0.107
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32179 Update branding to 6.0.410
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31957 #30336 Default Dotnet Tool to Run on Latest Runtime - Build time change
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProject.cs
Labels: Review for breaking changes, untriaged, breaking-change, Area-Tools, needs-breaking-change-doc-created

#32182 Update branding to 7.0.301
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32181 Update branding to 7.0.205
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32197 [release/7.0.1xx] Trusted roots: 2023-04 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
  src/Tests/trustedroots.Tests/GivenTimestampingCtlFile.cs
Labels: Area-Infrastructure, untriaged

#32199 [release/7.0.3xx] Trusted roots: 2023-04 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
  src/Tests/trustedroots.Tests/GivenTimestampingCtlFile.cs
Labels: Area-Infrastructure, untriaged

#32213 Add AssemblyName metadata to references based on FrameworkList.xml
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolveTargetingPackAssetsTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs
Labels: Area-Infrastructure, untriaged

#32161 Enable preview branch codeflow going forward
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#31766 Add IsAotCompatible flag to enable all analyzers and IsTrimmable
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: untriaged, Area-ILLink

#32276 Fix GenAPI when reading assemblies from metadata
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ApiCompatServiceProvider.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/Filtering/ImplicitSymbolFilter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/IMethodSymbolExtensions.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoader.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoaderFactory.cs
  src/Tests/Microsoft.DotNet.ApiSymbolExtensions.Tests/SymbolFactory.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-Infrastructure, untriaged

#32302 Remove template runtimeconfig
  src/Tests/Common/runtimeconfig.template.json
  src/Tests/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#32301 [release/7.0.4xx] added `Microsoft.DotNet.Cli.Utils.dll` to package content
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/packaging/package.csproj
Labels: Area-Infrastructure, untriaged

#32127 Add debian to the SupportsTargetFramework logic.
  src/Tests/Microsoft.NET.TestFramework/EnvironmentInfo.cs
Labels: Area-Infrastructure, untriaged

#32347 Remove duplicate packages
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32058 Fix the NETSDK1094 errors
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#32333 add known TFMs to multitarget-publish error message
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CrossTargeting.targets
Labels: untriaged

#32131 Clarifying .NET version in test
  src/Assets/TestProjects/WatchApp60/WatchApp60.csproj
Labels: Area-Infrastructure, untriaged

#32355 [Own build] Don't use AssemblyInformationCachePaths
  Directory.Build.props
Labels: Area-Infrastructure, untriaged

#32461 Update 303 branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32484 [release/7.0.4xx] fixed `_ContainerIsTargetingNet8TFM` evaluation
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ProjectInitializer.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
Labels: Area-Containers

#29787 Add PackageReference to new Roslyn package
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: Area-ILLink

#32477 Remove Cli integration tests which are migrated to dotnet/templating
  TemplateEngine.slnf
  eng/build.yml
  sdk.sln
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/DefaultIfOptionWithoutValueTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/EndToEndTestBase.cs
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/FileRenameTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/KitchenSinkTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Microsoft.TemplateEngine.Cli.IntegrationTests.csproj
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/RegexMatchMacroTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/CaseSensitiveNameBasedRenamesTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/ConfigurationKitchenSink.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/CustomSourceAndTargetPathRenameTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/CustomSourcePathRenameTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/CustomTargetPathRenameTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/DerivedSymbolFileRenameTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/DerivedSymbolWithValueForms.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/FileRenamesTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/MultipleRenamesOnSameFileHandlesInducedOverlapTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/MultipleRenamesOnSameFileHandlesOverlapTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/MultipleRenamesOnSameFileTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/NegativeFileRenamesTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/NoValueDefaultForChoiceParamIsUsed.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/NoValueDefaultForStringParamIsUsed.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/NoValueDefault_UserProvidedValuesAreIsUsed.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/NoValueDefaultsNotUsedIfSwitchesNotSpecified.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/RegexMatchMacroNegative.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/RegexMatchMacroPositive.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/SourceNameFileRenamesTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/TemplateWithJoinAndFolderRename.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/TemplateWithPlaceholderFilesTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/TemplateWithPortsAndCoalesceTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/TemplateWithSourceNameInTargetPathGetsRenamedTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/TemplateWithSourcePathOutsideConfigRootTest.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/Resources/TemplateWithValueForms.json
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/TemplateWithPortsAndCoalesceTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/TemplateWithTagsTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.IntegrationTests/ValueFormsTests.cs
  src/Tests/Microsoft.TemplateEngine.EndToEndTestHarness/BuiltInTemplatePackagesProviderFactory.cs
  src/Tests/Microsoft.TemplateEngine.EndToEndTestHarness/Microsoft.TemplateEngine.EndToEndTestHarness.csproj
  src/Tests/Microsoft.TemplateEngine.EndToEndTestHarness/ParserFactory.cs
  src/Tests/Microsoft.TemplateEngine.EndToEndTestHarness/Program.cs
Labels: untriaged

#32456 [release/7.0.4xx] corrected strings in containers
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
Labels: Area-Containers

#32426 Add warning for optional workload EOL
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetEolFrameworks.cs
Labels: Area-Infrastructure, untriaged

#32107 Try installing wasm-tools from a rollback file instead of from the feed
  eng/Version.Details.xml
  eng/Versions.props
  eng/build.yml
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.AoT.Tests/WasmAoTPublishIntegrationTest.cs
Labels: Area-Infrastructure, untriaged

#32537 [release/7.0.3xx] Update to 7.0.304
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32529 Create README.md for CTLs
  src/Layout/redist/trustedroots/README.md
Labels: Area-DotNet Test, untriaged

#32517 Convert the DotnetCommand that call "new" to DotnetNewCommand
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: Area-Infrastructure, untriaged

#32564 Trusted roots: 2023-04 CTL
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#32471 Support side by side workload manifests in SDK resolver
  src/Common/EnvironmentVariableNames.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/CachingWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/ManifestSpecifier.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Strings.resx
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.cs.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.de.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.es.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.fr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.it.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ja.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ko.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pl.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pt-BR.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ru.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.tr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hans.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
Labels: untriaged

#32572 [release/7.0.1xx] Trusted roots: 2023-04
  src/Layout/redist/trustedroots/README.md
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#32575 [release/7.0.4xx] Trusted roots: 2023-04
  src/Layout/redist/trustedroots/README.md
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#32573 [release/7.0.2xx] Trusted roots: 2023-04
  src/Layout/redist/trustedroots/README.md
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#32574 [release/7.0.3xx] Trusted roots: 2023-04
  src/Layout/redist/trustedroots/README.md
  src/Layout/redist/trustedroots/timestampctl.pem
Labels: Area-Infrastructure, untriaged

#32530 Enable documentation files in GenAPI & APICompat
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/Microsoft.DotNet.ApiCompat.Task.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Microsoft.DotNet.ApiCompat.Tool.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/CompatDifference.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/DifferenceVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/IDifferenceVisitor.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ISuppressionEngine.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Mapping/AssemblyMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Mapping/AssemblySetMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Mapping/ElementMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Mapping/IElementMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Mapping/MemberMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Mapping/NamespaceMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Mapping/TypeMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddMemberToInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotChangeVisibility.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotRemoveBaseTypeOrInterface.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotSealType.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/MembersMustExist.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleContext.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Package.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/BaselinePackageValidator.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/CompatibleFrameworkInPackageValidator.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/CompatibleTFMValidator.cs
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Microsoft.DotNet.GenAPI.Tool.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Program.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/AssemblySymbolOrderer.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
  src/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoaderFactory.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/AttributeDataExtensions.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Filtering/CompositeSymbolFilter.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/IAssemblySymbolLoader.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Microsoft.DotNet.ApiSymbolExtensions.csproj
  src/Tasks/Common/Logger.cs
Labels: Area-ApiCompat

#32259 Fix typo in Directory.Build.props
  Directory.Build.props
Labels: untriaged

#32630 #24909 Add condition for System.NET.http to work for Multitargeting .NETFramework
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_DotNet.cs
Labels: untriaged

#32656 Update the help description for "--sc, --self-contained" option after the breaking change
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#32698 Update MSBuildLocator version
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#32606 Containers/Layer: trim x-bit based on filesystem permissions on Unix.
  src/Containers/Microsoft.NET.Build.Containers/Layer.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/LayerEndToEndTests.cs
Labels: Area-Infrastructure, untriaged, Area-Containers

#32473 [release/7.0.4xx] Default all containers to linux instead of the current SDK's OS
  src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ProjectInitializer.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: Area-Containers

#32716 Containers.IntegrationTests: support running with podman.
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ContainerCli.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerSupportsArchInlineData.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: Area-Infrastructure, untriaged

#32700 Fix StaticWebAssets Brotli asset deduplication
  src/StaticWebAssetsSdk/Tasks/ResolveCompressedAssets.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/ResolveCompressedAssetsTest.cs
Labels: untriaged

#32738 Add back legacy JS hot reload function
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
Labels: untriaged, Area-AspNetCore

#31837 Update dependabot to run on 4xx
  .github/dependabot.yml
Labels: Area-Infrastructure, untriaged

#32745 Update the manifests from the rollback file in the overlay target rather than the yml
  eng/build.yml
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorReadSatelliteAssemblyFileTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BackCompatibilityPublish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/VanillaWasmTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildLazyLoadTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmCompressionTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPwaManifestTests.cs
Labels: Area-Infrastructure, untriaged

#32772 Port some of the auth changes from 7.0.4xx
  src/WebSdk/Publish/Tasks/MsDeploy/VsMSDeployObject.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpClientHelpers.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploymentStatus.cs
Labels: Area-Infrastructure, untriaged

#32538 Enable EventSourceSupport in ASP.NET Native AOT apps
  sdk.sln
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.BeforeCommon.targets
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
  src/WebSdk/Web/Targets/Sdk.Server.targets
Labels: untriaged, Area-WebSDK

#32085 [release/7.0.4xx] support correct property name and ensure compat with old name
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net7.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ParseContainerProperties.cs
  src/Containers/containerize/ContainerizeCommand.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/FullFramework/CreateNewImageToolTaskTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/Microsoft.NET.Build.Containers.IntegrationTests.csproj
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ParseContainerPropertiesTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
  src/Tests/containerize.UnitTests/ParserTests.cs
Labels: Area-Containers

#32826 Back up to latest 17.7 build for p5
  eng/Version.Details.xml
  eng/Versions.props
  src/Layout/tool_fsharp/tool_fsc.csproj
Labels: Area-Infrastructure, untriaged

#32877 Fix Directory.Build.props ArtifactsPath intendation
  src/Tests/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#MSBuild-Directory-Build-props-file#-n#item#--inherit#--use-artifacts.verified/MSBuild-Directory-Build-props-file/Directory.Build.props
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/BuildProps/Directory.Build.props
Labels: untriaged

#32890 [release/7.0.4xx] bug fixes related to AWS ECR
  src/Containers/Microsoft.NET.Build.Containers/Layer.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
Labels: Area-Containers

#32876 Containers: fix handling of ContainerBaseImage without a registry.
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/ReferenceParser.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ParseContainerProperties.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ParseContainerPropertiesTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/ContainerHelpersTests.cs
Labels: untriaged

#32766 Read workload sets in workload manifest reader
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Strings.resx
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSet.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.cs.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.de.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.es.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.fr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.it.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ja.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ko.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pl.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pt-BR.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ru.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.tr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hans.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: Area-Workloads

#32796 Preview 6 branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31798 Prevent restore loop in VS
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
Labels: Area-External, untriaged

#32905 Rename GenAPI IncludeVisibleOutsideOfAssembly
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/GenAPITask.cs
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/build/Microsoft.DotNet.GenAPI.Task.targets
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Program.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoader.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoaderFactory.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/SymbolExtensions.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI
