Repository dotnet/sdk, pull requests merged in 2023-09, with the labels that each got.

#35073 Update branding to 7.0.309
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35069 Update branding to 6.0.123
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35070 Update branding to 6.0.318
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35071 Update branding to 6.0.415
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35072 Update branding to 7.0.112
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35074 Update branding to 7.0.402
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35138 Container Build: Handle multiple tags wtihin one image
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/DestinationImageReference.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/ILocalRegistry.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/SourceImageReference.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: untriaged, Area-Containers

#34642 Update onelocbuild to 8.0.1xx
  eng/build.yml
Labels: Area-Infrastructure, untriaged

#35167 Add mac signing to the other fork of the code path
  src/Cli/dotnet/ShellShim/AppHostShimMaker.cs
Labels: Area-Infrastructure, untriaged

#35158 [release/6.0.4xx] Bump System.Security.Cryptography.Pkcs to 6.0.4
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
Labels: Area-Infrastructure, untriaged

#35024 Move to granular opt-in for interceptors preview
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
Labels: Area-Infrastructure, untriaged

#35029 Add DOTNET_LAUNCH_PROFILE environment when invoking dotnet run
  src/Assets/TestProjects/AppThatOutputsDotnetLaunchProfile/AppThatOutputsDotnetLaunchProfile.csproj
  src/Assets/TestProjects/AppThatOutputsDotnetLaunchProfile/Program.cs
  src/Assets/TestProjects/AppThatOutputsDotnetLaunchProfile/Properties/launchSettings.json
  src/Assets/TestProjects/TestAppWithLaunchSettings/Program.cs
  src/Assets/TestProjects/WatchKitchenSink/Program.cs
  src/Assets/TestProjects/WatchKitchenSink/Properties/launchSettings.json
  src/BuiltInTools/dotnet-watch/DotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/LaunchSettingsProfile.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ILaunchSettingsProvider.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/LaunchSettingsManager.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsModel.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsProvider.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
  src/Tests/dotnet-watch.Tests/Watch/DotNetWatcherTests.cs
Labels: untriaged, Area-CLI

#35151 Container Build: Add tar.gz (Docker Archive) file writing
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/DestinationImageReference.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/ArchiveFileRegistry.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/containerize/ContainerizeCommand.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ContainerCli.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: untriaged, Area-Containers

#34909 Prefer docker tool when both podman and docker are present
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerSupportsArchInlineData.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/DockerAvailableUtils.cs
Labels: Area-Containers

#34980 Change containers publish target to require IsPublishable (and explicit SDK Container support)
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
Labels: untriaged, Area-Containers

#34460 Add better error messages when we can't fetch manifests
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/DiagnosticMessage.cs
  src/Containers/Microsoft.NET.Build.Containers/Exceptions/ContainerHttpException.cs
  src/Containers/Microsoft.NET.Build.Containers/Exceptions/RepositoryNotFoundException.cs
  src/Containers/Microsoft.NET.Build.Containers/Exceptions/UnableToAccessRepositoryException.cs
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultBlobOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultManifestOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/DiagnosticMessageTests.cs
Labels: untriaged, Area-Containers

#34624 Copying the test project to a unique temporary folder is to change the hard coding of the tfm and package version
  src/Assets/TestPackages/dotnet-new/test_templates/AddPackageReference/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/AddProjectReference/Project1/Project1.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/AddProjectReference/Project2/Project2.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/AddProjectToSolution/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddPackageReference/Basic/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddPackageReference/BasicWithFiles/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectReference/Basic/Project1/Project1.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectReference/Basic/Project2/Project2.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectToSolution/Basic/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectToSolution/BasicInSolutionRoot/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectToSolution/BasicWithFiles/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectToSolution/BasicWithIndexes/Client/Client.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectToSolution/BasicWithIndexes/Server/Server.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/Basic/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/BasicWithFiles/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/CustomSourcePath/Custom/Path/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/CustomSourcePathFiles/Custom/Path/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/CustomSourceTargetPath/Src/Custom/Path/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/CustomSourceTargetPathFiles/Src/Custom/Path/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/CustomTargetPath/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/CustomTargetPathFiles/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/Invalid/Invalid.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/Invalid_ContinueOnError/Invalid.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/SourceRename/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/SourceRenameFiles/Basic.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/TwoProjectsFiles/Custom/MyTestProject.Tests/MyTestProject.Tests.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/TwoProjectsFiles/Custom/MyTestProject/MyTestProject.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/TwoProjectsPrimaryOutputs/Custom/MyTestProject.Tests/MyTestProject.Tests.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/TwoProjectsPrimaryOutputs/Custom/MyTestProject/MyTestProject.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/TwoProjectsWithSourceRenames/TemplateProject1/TemplateProject1.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/TwoProjectsWithSourceRenames/TemplateProject2/TemplateProject2.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/TwoProjectsWithSourceRenames2/TemplateProject1/TemplateProject1.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/RestoreNuGet/TwoProjectsWithSourceRenames2/TemplateProject2/TemplateProject2.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/UnknownPostAction/UnknownPostAction.csproj
  src/Tests/dotnet-new.Tests/BaseIntegrationTest.cs
  src/Tests/dotnet-new.Tests/PostActionTests.Approval.cs
  src/Tests/dotnet-new.Tests/PostActionTests.cs
Labels: Area-Infrastructure, untriaged

#35208 fix: resource typo
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#35077 Avoid loading all types when invoking Hot Reload handlers, handle type load failures
  src/Assets/TestProjects/WatchAppTypeLoadFailure/App/App.csproj
  src/Assets/TestProjects/WatchAppTypeLoadFailure/App/Program.cs
  src/Assets/TestProjects/WatchAppTypeLoadFailure/App/Update.cs
  src/Assets/TestProjects/WatchAppTypeLoadFailure/Dep/Dep.cs
  src/Assets/TestProjects/WatchAppTypeLoadFailure/Dep/Dep.csproj
  src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs
  src/Tests/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  src/Tests/dotnet-watch.Tests/HotReload/DefaultDeltaApplierTests.cs
  src/Tests/dotnet-watch.Tests/HotReload/UpdatePayloadTests.cs
  src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
  src/Tests/dotnet-watch.Tests/Watch/AppWithDepsTests.cs
  src/Tests/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: untriaged, Area-AspNetCore

#35253 Update Newtonsoft.Json from 13.0.1 to 13.0.3
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
Labels: untriaged, Area-CodeFlow

#35190 Update Asp.Net FrameworkReference in BrowserRefresh
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  src/BuiltInTools/BrowserRefresh/Microsoft.AspNetCore.Watch.BrowserRefresh.csproj
Labels: untriaged, Area-AspNetCore

#35281 Msbuild.Test.Utilites build fix for VS
  src/Tests/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
Labels: Area-Infrastructure, untriaged

#34693 Implement automated cleanup of stage 0
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
Labels: Area-Infrastructure, untriaged

#35320 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35319 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35318 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35317 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35316 Merging internal commits for release/7.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35265 Improve test logging, reliability
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/Tests/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  src/Tests/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
  src/Tests/dotnet-watch.Tests/Watch/BrowserLaunchTests.cs
  src/Tests/dotnet-watch.Tests/Watch/DotNetWatcherTests.cs
  src/Tests/dotnet-watch.Tests/Watch/GlobbingAppTests.cs
  src/Tests/dotnet-watch.Tests/Watch/NoDepsAppTests.cs
  src/Tests/dotnet-watch.Tests/Watch/ProgramTests.cs
  src/Tests/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: Area-Infrastructure, untriaged

#35339 Update NuGet certificate thumbprints
  src/Cli/dotnet/NugetPackageDownloader/FirstPartyNuGetPackageSigningVerifier.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
Labels: Servicing-consider, Area-Workloads

#35310 Add dependency on non shipping package and use it's version
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#35273 Use MVC extensions from Razor transport
  src/RazorSdk/Tool/DiscoverCommand.cs
  src/RazorSdk/Tool/GenerateCommand.cs
Labels: untriaged, Area-AspNetCore

#35315 Merging internal commits for release/7.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35231 Add support for Haiku
  src/Cli/Microsoft.DotNet.Cli.Utils/RuntimeEnvironment.cs
  src/Layout/redist/PortableRuntimeIdentifierGraph.json
Labels: Area-Infrastructure, untriaged

#35371 [8.0.1xx] Use MVC extensions from Razor transport
  src/RazorSdk/Tool/DiscoverCommand.cs
  src/RazorSdk/Tool/GenerateCommand.cs
Labels: untriaged, Area-AspNetCore

#35309 Fix package version in Microsoft.TemplateEngine.Mocks
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#35380 Update NuGet certificate thumbprints
  src/Cli/dotnet/NugetPackageDownloader/FirstPartyNuGetPackageSigningVerifier.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
Labels: Area-Infrastructure, untriaged

#35437 Containers: don't push manifest digest when pushing manifest tags.
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
Labels: untriaged, Area-Containers

#35444 Add workload
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#35407 Merging internal commits for release/8.0.1xx
  .vsts-ci.yml
  eng/build.yml
  eng/common/sdl/trim-assets-version.ps1
Labels: Area-Infrastructure, untriaged

#35418 Metrics switch support in the SDK
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
Labels: untriaged, area-runtime

#35398 Include APICompat resources
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/Microsoft.DotNet.ApiCompat.Task.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Microsoft.DotNet.ApiCompat.Tool.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/Microsoft.DotNet.ApiSymbolExtensions/Microsoft.DotNet.ApiSymbolExtensions.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Microsoft.DotNet.ApiCompat.IntegrationTests.csproj
  src/Tests/Microsoft.DotNet.ApiCompat.Tests/Microsoft.DotNet.ApiCompat.Tests.csproj
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Microsoft.DotNet.ApiCompatibility.Tests.csproj
  src/Tests/Microsoft.DotNet.ApiSymbolExtensions.Tests/Microsoft.DotNet.ApiSymbolExtensions.Tests.csproj
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Microsoft.DotNet.PackageValidation.Tests.csproj
Labels: untriaged, Area-ApiCompat

#35441 Add explicit reference to Microsoft.SourceBuild.Intermediate.templating
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#35482 Remove warning disablements that are no longer needed
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/AliasAssignmentTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/InstantiateTests.NoMatchHandling.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/InstantiateTests.Subcommand.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/InstantiateTests.cs
  src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs
Labels: Area-Infrastructure, untriaged

#35450 Trigger enhanced page nav on hot reload
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: untriaged, Area-AspNetCore

#35366 Add escape hatch for PublishAot without RuntimeIdentifier. Fixes #33414.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
Labels: Area-External, untriaged

#33835 Download tool packages from NuGet feeds directly, instead of implicitly restoring
  src/Cli/dotnet/NugetPackageDownloader/INuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/LocalizableStrings.resx
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/ShellShim/ShellShimTemplateFinder.cs
  src/Cli/dotnet/ToolPackage/IToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/IToolPackageInstaller.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageFactory.cs
  src/Cli/dotnet/ToolPackage/ToolPackageInstaller.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ParseResultExtension.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalInstaller.cs
  src/Cli/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateLocalCommand.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/ToolPackageDownloaderTests.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/ToolPackageInstallerNugetCacheTests.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/ToolPackageUninstallerTests.cs
  src/Tests/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageDownloaderMock.cs
  src/Tests/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageInstallerMock.cs
  src/Tests/dotnet-install-tool.Tests/GivenDotnetInstallTool.cs
  src/Tests/dotnet-workload-install.Tests/FailingNuGetPackageInstaller.cs
  src/Tests/dotnet-workload-install.Tests/MockNuGetPackageInstaller.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallLocalCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolRestoreCommandWithMultipleNugetConfigTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUninstallGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateLocalCommandTests.cs
Labels: untriaged, Area-Tools

#35409 Find dotnet.exe from VS's MSBuild
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
Labels: untriaged, Area-AspNetCore

#35507 Include NuGet.Packaging in ApiCompat.Task package
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/Microsoft.DotNet.ApiCompat.Task.csproj
Labels: Area-Infrastructure, untriaged

#33084 Standardize error messages
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Mapping/ElementMapper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#35446 Create default.json file (targeted at 8.0.100)
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: Area-Infrastructure, untriaged

#35478 [release/8.0.1xx] Update dependencies from https://github.com/dotnet/deployment-tools build 20230913.1
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#35457 Add net7 wasm workload to the recognized list
  src/Tasks/Microsoft.NET.Build.Tasks/ShowMissingWorkloads.cs
Labels: untriaged

#35499 Enable Razor server to quickly find dotnet.exe from VS
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
Labels: Servicing-consider, Area-Infrastructure, untriaged

#35500 Find dotnet.exe from VS's MSBuild
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
Labels: Area-Infrastructure, untriaged

#35501 Find dotnet.exe from VS's MSBuild
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
Labels: Area-Infrastructure, untriaged

#35503 Find dotnet.exe from VS's MSBuild
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
Labels: Area-Infrastructure, untriaged

#35504 Find dotnet.exe from VS's MSBuild
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
Labels: Area-Infrastructure, untriaged

#35502 Find dotnet.exe from VS's MSBuild
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
Labels: Area-Infrastructure, untriaged

#35268 Update .editorconfig template
  src/Tests/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#EditorConfig-file#-n#item.verified/EditorConfig-file/.editorconfig
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/EditorConfig/Dotnet/.editorconfig
Labels: Area-Infrastructure, untriaged

#35487 Fix typo in MSBuildAllProject(File)s
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets
Labels: Area-Infrastructure, untriaged

#35048 [main] Update dotnet/runtime
  Directory.Build.props
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  global.json
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/Microsoft.DotNet.ApiCompat.Task.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Microsoft.DotNet.ApiCompat.Tool.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/Assets/WasmOverride/Directory.Build.props
  src/Assets/WasmOverride/Directory.Build.targets
  src/Assets/WasmOverride/WasmOverridePacks.targets
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Microsoft.DotNet.GenAPI.Tool.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
  src/Layout/toolset-tasks/OverrideAndCreateBundledNETCoreAppPackageVersion.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Microsoft.DotNet.ApiSymbolExtensions.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tests/HelixTasks/HelixTasks.csproj
  src/Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests/Microsoft.DotNet.MSBuildSdkResolver.Tests.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishWebApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishWpfApp.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.TestFramework/AspNetSdkTest.cs
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
  src/Tests/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Windows.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Windows.verified.txt
  src/Tests/trustedroots.Tests/trustedroots.Tests.csproj
  src/Tests/xunit-runner/XUnitRunner.targets
Labels: untriaged, Area-CodeFlow

#35546 Make NETSDK1083 link to RID doc
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#35601 Update to 9.0 version of targeting pack
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#35623 Update dependency names for windows desktop
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#35538 Rtm Branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35634 Make NETSDK1083 link to doc
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Servicing-approved, Area-Infrastructure

#35600 Skip getting Windows GUI bit on non-Windows in AppHostShellShimMaker
  src/Cli/dotnet/ShellShim/AppHostShimMaker.cs
Labels: Servicing-approved, Area-CLI

#35594 We don't need this 🙃
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/BaseCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/NewCommand.Legacy.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/NewCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/alias/AliasCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InvalidTemplateOptionResult.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/install/BaseInstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/install/LegacyInstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/list/BaseListCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/list/LegacyListCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/search/BaseSearchCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/search/LegacySearchCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/uninstall/BaseUninstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/uninstall/LegacyUninstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/BaseUpdateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/LegacyUpdateApplyCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/LegacyUpdateCheckCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/UpdateCommand.cs
  src/Cli/dotnet-new3/CompleteCommand.cs
  src/Cli/dotnet/commands/dotnet-new/OptionalWorkloadProvider.cs
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/containerize/ContainerizeCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/CachingWorkloadResolver.cs
  src/Tasks/Common/ConflictResolution/ConflictResolver.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ApplyImplicitVersions.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurerWIthStateSetup.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishItemsOutputGroupTests.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/CoreMSBuildAndWindowsOnlyFactAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/CoreMSBuildAndWindowsOnlyTheoryAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/CoreMSBuildOnlyFactAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/CoreMSBuildOnlyTheoryAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/FullMSBuildOnlyFactAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/FullMSBuildOnlyTheoryAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/PlatformSpecificFact.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/PlatformSpecificTheory.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/RequiresSpecificFrameworkFactAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/RequiresSpecificFrameworkTheoryAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/WindowsOnlyRequiresMSBuildVersionFactAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/Attributes/WindowsOnlyRequiresMSBuildVersionTheoryAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/MacOsOnlyFactAttribute.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
  src/Tests/Microsoft.NET.TestFramework/SharedTestOutputHelper.cs
  src/Tests/Microsoft.NET.TestFramework/TestAsset.cs
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
  src/Tests/Microsoft.NET.TestFramework/TestPackageReference.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsprojWithCorrectTestRunParameters.cs
  src/Tests/dotnet-vstest.Tests/VSTestTests.cs
  src/WebSdk/Publish/Tasks/MsDeploy/VsMSDeployObject.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/ImportParameterFile.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/MSDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/NormalizeServiceUrl.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/VsMsdeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/Xdt/TransformXml.cs
Labels: Area-Infrastructure, untriaged

#35620 Fix version of targeting pack
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#34166 [wasm] Remove `UsingMicrosoftNETSdkBlazorWebAssembly` from Wasm SDK
  src/WasmSdk/Sdk/Sdk.props
Labels: untriaged, Area-WasmSdk

#35609 Containers: support using OCI base images.
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/Layer.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultManifestOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/LayerEndToEndTests.cs
Labels: Servicing-approved, Area-Containers

#35636 Avoid running new APIs under older TFMs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Servicing-approved, Area-AspNetCore

#35662 Upgrade MSBuildLocator ref from 1.6.1 to 1.6.10
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35637 Update RID parsing's `LastIndexOf` call to use invariant culture
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetOsArchOptions.cs
Labels: Area-Infrastructure, untriaged

#35710 Add ProjectCapability for Native AOT properties.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Servicing-approved, Area-VS

#35760 Declare dependencies for two Extensions.Logging packages
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#35679 IDE0017 "Object initialization can be simplified" cleanup
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/PollingFileWatcher.cs
  src/Cli/Microsoft.DotNet.Cli.Sln.Internal/SlnFile.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/ProcessStartInfoExtensions.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateResult.cs
  src/Cli/dotnet/Telemetry/Telemetry.cs
  src/Cli/dotnet/ToolManifest/ToolManifestEditor.cs
  src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsProvider.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-vstest/VSTestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadResolverFactory.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/StaticWebAssetsSdk/Tasks/ReferencedProjectConfiguration.cs
  src/StaticWebAssetsSdk/Tasks/StaticWebAssetsDiscoveryPattern.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GetPublishItemsOutputGroupOutputsTests.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenADependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAProduceContentsAssetsTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolveTargetingPackAssetsTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenUnresolvedSDKProjectItemsAndImplicitPackages.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/ProcessFrameworkReferencesTests.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateRuntimeConfigurationFiles.cs
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RuntimePackAssetInfo.cs
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/BlockingMemoryStreamTests.cs
  src/Tests/Microsoft.NET.Build.Tests/ArtifactsOutputPathTests.cs
  src/Tests/Microsoft.NET.Build.Tests/DesignTimeBuildTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenFrameworkReferences.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeManifestSupportedFrameworks.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACrossTargetedLibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibraryWithFSharp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibraryWithOSSupportedVersion.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibraryWithVB.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsDesktopProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToResolveConflicts.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenTransitiveFrameworkReferencesAreDisabled.cs
  src/Tests/Microsoft.NET.Build.Tests/WorkloadTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Restore.Tests/RestoreWithOlderNuGet.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ApplyCssScopesTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/GenerateStaticWebAssetsManifestTest.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/WorkloadPackGroupTests.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/SdkCommandSpec.cs
  src/Tests/Microsoft.NET.TestFramework/TestCommandLine.cs
  src/Tests/Microsoft.NET.TestFramework/TestDirectory.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  src/WebSdk/Publish/Tasks/MsDeploy/CommonUtility.cs
  src/WebSdk/Publish/Tasks/Tasks/GenerateEFSQLScripts.cs
  src/WebSdk/Publish/Tasks/Tasks/Kudu/KuduDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/Xdt/TransformXml.cs
Labels: Area-Infrastructure, untriaged

#35680 IDE0049 "Name can be simplified" cleanup
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/Cli/Microsoft.DotNet.Cli.Sln.Internal/SlnFile.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/NativeMethods.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/RuntimeEnvironment.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs
  src/Cli/dotnet/Installer/Windows/InstallClientElevationContext.cs
  src/Cli/dotnet/ReleasePropertyProjectLocator.cs
  src/Cli/dotnet/SlnFileExtensions.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/LaunchSettingsManager.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Cli/dotnet/commands/dotnet-test/Program.cs
  src/Cli/dotnet/commands/dotnet-tool/uninstall/ToolUninstallCommandLowLevelErrorConverter.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerServer.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Containers/Microsoft.NET.Build.Containers/BaseImageNotFoundException.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ParseContainerProperties.cs
  src/RazorSdk/Tool/ServerProtocol/NativeMethods.cs
  src/Resolvers/Microsoft.DotNet.SdkResolver/NETCoreSdkResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSet.cs
  src/Tasks/Common/ConflictResolution/ConflictItem.cs
  src/Tasks/Common/ConflictResolution/ConflictResolver.cs
  src/Tasks/Common/ItemUtilities.cs
  src/Tasks/Common/MSBuildUtilities.cs
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/GetDependsOnNETStandard.net46.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAnAssetsFileResolver.cs
  src/Tasks/Microsoft.NET.Build.Tasks/AllowEmptyTelemetry.cs
  src/Tasks/Microsoft.NET.Build.Tasks/CollectSDKReferencesDesignTime.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ProjectContext.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tests/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  src/Tests/HelixTasks/TarGzFileCreateFromDirectory.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithLibrariesAndRid.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASelfContainedApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToTestAMultitargetedSolutionWithPublishReleaseOrPackRelease.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishDepsFilePathTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.TestFramework/Assertions/StringAssertionsExtensions.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
  src/Tests/Microsoft.NET.TestFramework/TestAssetsManager.cs
  src/Tests/Microsoft.NET.TestFramework/TestPackageReference.cs
  src/Tests/Microsoft.Win32.Msi.Manual.Tests/Program.cs
  src/Tests/dotnet-run.Tests/GivenDotnetRunRunsVbProj.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  src/WebSdk/Publish/Tasks/Kudu/KuduConnect.cs
  src/WebSdk/Publish/Tasks/Kudu/KuduVfsDeploy.cs
  src/WebSdk/Publish/Tasks/Kudu/KuduZipDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/Kudu/KuduDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/GetPassword.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/VsMsdeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/ValidateParameter.cs
  src/WebSdk/Publish/Tasks/Tasks/Xdt/TaskTransformationLogger.cs
  src/WebSdk/Publish/Tasks/Tasks/Xdt/TransformXml.cs
  src/WebSdk/Publish/Tasks/WebConfigTransform.cs
Labels: Area-Infrastructure, untriaged

#35716 Add spelling exclusions file
  .editorconfig
  exclusion.dic
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ApiCompatServiceProvider.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/SuppressionFileHelper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/SuppressibleMSBuildLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/SuppressibleConsoleLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ISuppressibleLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleFactory.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/ApiCompatRunnerExtensions.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/BaselinePackageValidator.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/CompatibleFrameworkInPackageValidator.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/CompatibleTFMValidator.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/CompatibleFrameworkInPackageValidatorIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Microsoft.DotNet.ApiCompat.IntegrationTests.csproj
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Task/ValidatePackageTargetIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AssemblyIdentityMustMatchTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Runner/ApiCompatRunnerTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressibleTestLog.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Microsoft.DotNet.PackageValidation.Tests.csproj
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Validators/BaselinePackageValidatorTests.cs
  src/Tests/Microsoft.DotNet.PackageValidation.Tests/Validators/CompatibleTFMValidatorTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenFrameworkReferences.cs
Labels: untriaged, Area-ApiCompat

#35796 Don't add implicit package references when downloads have been disabled.
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
Labels: untriaged, Area-NetSDK
