Repository dotnet/sdk, pull requests merged in 2023-03, with the labels that each got.

#24935 [gh-23135] use parent path of manifest file path as rootConfigDirectory
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalInstaller.cs
Labels: Area-CLI

#30956 Update triggers for 8.0
  .vsts-ci.yml
Labels: Area-Infrastructure

#30950 GenAPI: Add unsafe keyword if the calls of the base constructor is unsafe
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30964 Remove unused razor dependency
  eng/Version.Details.xml
Labels: Area-Infrastructure

#30955 Add new line to C# item templates with file-scoped namespaces
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.class.langVersion=10.0.targetFramework=net6.0.verified/class/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.class.langVersion=preview.targetFramework=net7.0.verified/class/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.langVersion=10.targetFramework=net6.0.verified/enum/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.targetFramework=net7.0.verified/enum/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.interface.langVersion=10.0.targetFramework=net6.0.verified/interface/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.record.langVersion=10.targetFramework=net6.0.verified/record/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.struct.langVersion=10.targetFramework=net6.0.verified/struct/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.struct.langVersion=10.verified/struct/TestItem1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Class-CSharp/Class1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Enum-CSharp/Enum1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Interface-CSharp/Interface1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Record-CSharp/Record1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Struct-CSharp/Struct1.cs
Labels: Area-Infrastructure, Area-Common templates

#30971 [release/7.0.3xx] Add new line to C# item templates with file-scoped namespaces
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.class.langVersion=10.0.targetFramework=net6.0.verified/class/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.class.langVersion=preview.targetFramework=net7.0.verified/class/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.class.verified/class/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.langVersion=10.targetFramework=net6.0.verified/enum/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.targetFramework=net7.0.verified/enum/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.enum.verified/enum/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.interface.langVersion=10.0.targetFramework=net6.0.verified/interface/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.interface.verified/interface/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.record.langVersion=10.targetFramework=net6.0.verified/record/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.record.verified/record/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.struct.langVersion=10.targetFramework=net6.0.verified/struct/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.struct.langVersion=10.verified/struct/TestItem1.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetCSharpClassTemplatesTest.struct.verified/struct/TestItem1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Class-CSharp/Class1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Enum-CSharp/Enum1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Interface-CSharp/Interface1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Record-CSharp/Record1.cs
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Struct-CSharp/Struct1.cs
Labels: Area-Infrastructure

#31028 GenAPI: add support for reference parameters in constructors.
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/BodyBlockCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriterTests.cs
Labels: Area-GenAPI

#31036 Update branding to 6.0.408
  eng/Versions.props
Labels: Area-Infrastructure

#31034 Update branding to 6.0.116
  eng/Versions.props
Labels: Area-Infrastructure

#31035 Update branding to 6.0.311
  eng/Versions.props
Labels: Area-Infrastructure

#31037 Update branding to 7.0.105
  eng/Versions.props
Labels: Area-Infrastructure

#30985 add <OS><ARCH> argument help name
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure

#31038 Update branding to 7.0.203
  eng/Versions.props
Labels: Area-Infrastructure

#31023 Update the Newtonsoft.Json to 13.0.1
  src/Assets/TestProjects/NewtonsoftProfile/NewtonsoftFilterProfile.xml
  src/Assets/TestProjects/NewtonsoftProfile/NewtonsoftProfile.xml
  src/Assets/TestProjects/TestAppWithSlnAndSolutionFolders/src/App/App.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPreserveCompilationContext.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishToClickOnce.cs
Labels: Area-Infrastructure

#30773 [DO NOT Merge] [release/7.0.1xx] Create workloads enumerator lazily in dotnet-new hos
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/Cli/dotnet/commands/dotnet-new/WorkloadsInfoProvider.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Tests/dotnet.Tests/dotnet-new/WorkloadsInfoProviderTests.cs
Labels: Servicing-approved

#31069 Trim away netframework targets in source-build
  eng/SourceBuild.props
Labels: Area-Infrastructure

#30574 Add some more details on team triage
  README.md
Labels: Area-NetSDK

#29264 Add tracking of the nuget cache and update to a flag zip list
  build/RunTestsOnHelix.cmd
  src/Tests/UnitTests.proj
Labels: Area-Infrastructure

#30934 [GenAPI] add README
  src/GenAPI/README.md
Labels: Area-GenAPI

#31078 Fix documentation link
  documentation/specs/runtime-configuration-file.md
Labels: Area-Infrastructure

#31087 [release/7.0.3xx] fix columns when param is specified
  src/Cli/Microsoft.TemplateEngine.Cli/TabularOutput/TemplateGroupDisplay.cs
  src/Tests/dotnet-new.Tests/DotnetNewListTests.cs
Labels: Area-Infrastructure

#31129 Add explicit deployment tools dependency
  eng/Version.Details.xml
  eng/Versions.props
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
  src/Tests/TelemetryStdOutLogger/TelemetryStdOutLogger.csproj
Labels: Area-Infrastructure

#31007 30784 dotnet info workload info
  src/Cli/Microsoft.DotNet.Cli.Utils/LocalizableStrings.resx
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.DotNet.Cli.Utils/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/CommandLineInfo.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
Labels: Area-Infrastructure

#31167 Allow hashtag in response files
  src/Cli/dotnet/Parser.cs
  src/Tests/dotnet.Tests/ParserTests/ResponseFileTests.cs
Labels: Area-CLI

#31077 [Breaking Backport] Restore Console Encoding upon Exit
  src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs
  src/Cli/dotnet/AutomaticEncodingRestorer.cs
  src/Cli/dotnet/Program.cs
  src/Common/EnvironmentVariableNames.cs
Labels: Area-CLI

#31158 Cleanup and gen api should not reference internal type attribute argument
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AttributesMustMatch.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/AssemblySymbolOrderer.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/AttributeDataExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/Filtering/ImplicitSymbolFilter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxNodeExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/BodyBlockCSharpSyntaxRewriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/SingleLineStatementCSharpSyntaxRewriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/TypeDeclarationCSharpSyntaxRewriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/TypeForwardAttributeCSharpSyntaxRewriter.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/AttributeDataExtensions.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Filtering/AccessibilitySymbolFilter.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Filtering/CompositeSymbolFilter.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Filtering/DocIdSymbolFilter.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/IAssemblySymbolLoader.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriter/BodyBlockCSharpSyntaxRewriterTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriter/CSharpSyntaxRewriterTestBase.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriter/SingleLineStatementCSharpSyntaxRewriterTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriter/TypeDeclarationCSharpSyntaxRewriterTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriter/TypeForwardAttributeCSharpSyntaxRewriterTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriterTests.cs
Labels: Area-Infrastructure

#30970 Add tests for the operation(install/uninstall/update package) when global settings file is corrupted
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstallTests.CanShowError_WhenGlobalSettingsFileIsCorrupted.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewUninstallTests.CanShowError_WhenGlobalSettingsFileIsCorrupted.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewUpdateTests.CanShowError_WhenGlobalSettingsFileIsCorrupted.verified.txt
  src/Tests/dotnet-new.Tests/DotnetNewInstallTests.Approval.cs
  src/Tests/dotnet-new.Tests/DotnetNewUninstallTests.Approval.cs
  src/Tests/dotnet-new.Tests/DotnetNewUpdateTests.Approval.cs
Labels: Area-Infrastructure

#31186 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#31187 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#31190 Merging internal commits for release/7.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#31188 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#31054 Refactor command line options parsing, add/improve imp of --launch-profile and --no-launch-profile options.
  eng/Versions.props
  src/Assets/TestProjects/WatchAppWithLaunchSettings/Program.cs
  src/Assets/TestProjects/WatchAppWithLaunchSettings/Properties/launchSettings.json
  src/Assets/TestProjects/WatchHotReloadAppMultiTfm/Program.cs
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/BuiltInTools/dotnet-watch/DotNetWatchContext.cs
  src/BuiltInTools/dotnet-watch/Filters/DotNetBuildFilter.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/FileWatcherFactory.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/LaunchSettingsProfile.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/Tests/dotnet-watch.Tests/CommandLineOptionsTests.cs
  src/Tests/dotnet-watch.Tests/MsBuildFileSetFactoryTest.cs
  src/Tests/dotnet-watch.Tests/Utilities/MockReporter.cs
  src/Tests/dotnet-watch.Tests/Watch/ProgramTests.cs
  src/Tests/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
  src/Tests/dotnet-watch.Tests/dotnet-watch.Tests.csproj
Labels: Area-Watch

#30932 [GenAPI] add new keyword to member signature when base member is hidden
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/GenAPI/genapi.slnf
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#31189 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#31275 Emit AssemblyVersion and ReferenceAssembly assembly attributes
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
Labels: Area-GenAPI

#23086 Files not ending in css are probably not css files
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-Infrastructure

#31301 GenAPI should use the latest available codeanalysis workspaces package
  eng/Versions.props
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
Labels: Area-Infrastructure

#31265 Move RDG omission to ResolveTargetingPackAssets target
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/WebSdk/Web/Sdk/Sdk.props
Labels: Area-AspNetCore

#31328 Update the hardcoded to the current framework
  src/Tests/Microsoft.NET.Build.Tests/AppHostTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenFrameworkReferences.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseBinaryFormatter.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseContentFiles.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThereAreDefaultItems.cs
  src/Tests/Microsoft.NET.Build.Tests/GlobalPropertyFlowTests.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/TabCompletionTests.cs
  src/Tests/dotnet-new.Tests/DotnetNewHelpTests.Approval.cs
Labels: Area-Infrastructure

#31322 branding for preview4
  eng/Versions.props
Labels: Area-Infrastructure

#31319 Issue: 31133 backport pr 30762 to release/7.0.3xx: --platform
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetOsArchOptions.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetRestoreInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
Labels: Area-Infrastructure

#31359 Only enable scoped CSS when using Razor SDK
  src/StaticWebAssetsSdk/Targets/Sdk.StaticWebAssets.CurrentVersion.targets
Labels: Area-AspNetCore

#31020 Adding Roslyn IDE as code owners
  CODEOWNERS
Labels: Area-Infrastructure

#30266 Introduce `Workload Clean`: Garbage Collection Component
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadInfoHelper.cs
  src/Cli/dotnet/commands/dotnet-workload/clean/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/clean/WorkloadCleanCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/clean/WorkloadCleanCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/IInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallRecords/RegistryWorkloadInstallationRecordRepository.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/InstalledWorkloadsCollection.cs
  src/Cli/dotnet/commands/dotnet-workload/list/VisualStudioWorkloads.cs
  src/Cli/dotnet/commands/dotnet-workload/uninstall/WorkloadUninstallCommand.cs
  src/Cli/dotnet/dotnet.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestFormatException.cs
  src/Tests/dotnet-workload-install.Tests/GivenFileBasedWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/MockPackWorkloadInstaller.cs
  src/Tests/dotnet.Tests/dotnet-workload-clean/GivenDotnetWorkloadClean.cs
Labels: Area-Infrastructure

#31174 Blazor configuration for StartupMemoryCache and Jiterpreter
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/BootJsonData.cs
  src/BlazorWasmSdk/Tasks/GenerateBlazorWebAssemblyBootJson.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
Labels: Area-AspNetCore

#31443 Code optimization in containers tests
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/ArgumentEscaper.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/BasicCommand.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/Command.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/CommandResult.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/CommandResultAssertions.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/CommandResultExtensions.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/DotnetCommand.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/NativeMethods.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/ProcessReaper.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/SdkCommandSpec.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/StreamForwarder.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CommandUtils/TestCommand.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerSupportsArchInlineData.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerTestsFixture.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/FullFramework/CreateNewImageToolTaskTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ToolsetUtils.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/RunExeCommand.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/SdkCommandSpec.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/TestCommand.cs
  src/Tests/Microsoft.NET.TestFramework/SharedTestOutputHelper.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure, untriaged

#31450 Containers: added e2e containers tests for console app
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: Area-Containers

#31470 added e2e test for insertion to sdk
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: untriaged

#31471 [release/8.0.1xx-perview3] backpackport 30845 - Update dependencies from dotnet/arcade
  .editorconfig
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/cross/build-rootfs.sh
  eng/common/cross/toolchain.cmake
  eng/common/cross/x64/sources.list.xenial
  eng/common/templates/job/job.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/tools.ps1
  global.json
Labels: Area-Infrastructure, untriaged

#30700 [Blazor] Fix `publish --self-contained` for Blazor builds.
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BackCompatibilityPublish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  src/WasmSdk/Targets/Microsoft.NET.Sdk.WebAssembly.Current.props
Labels: Area-AspNetCore

#31313 Add AfterPublish target to ClickOnce target dependencies
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ClickOnce.targets
Labels: Area-Infrastructure

#31489 Wasm SDK code owners
  CODEOWNERS
Labels: Area-Infrastructure, untriaged

#31460 Update off-by-default analyzers to account for rename
  global.json
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.AoT.Tests/WasmAoTPublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/VanillaWasmTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Windows.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Windows.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Windows.verified.txt
Labels: untriaged, Area-AspNetCore

#31488 Using built-in package for package reference to `Microsoft.NET.Build.Containers`
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/GenerateLayout.targets
  src/WebSdk/Web/Sdk/Sdk.props
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: untriaged, Area-Containers

#31469 Use latest dogfood version
  eng/dogfood.ps1
Labels: Area-Infrastructure, untriaged

#31543 containers: updated 7.0.3xx release notes
  src/Containers/docs/ReleaseNotes/v0.5.0.md
  src/Containers/docs/ReleaseNotes/v7.0.300.md
  src/Containers/packaging/package.csproj
Labels: Area-Containers

#31542 syncing the logic in `CreateNewImage` and `ContainerBuilder`
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net7.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/containerize/ContainerizeCommand.cs
  src/Containers/packaging/package.csproj
Labels: untriaged, Area-Containers
