Repository dotnet/sdk, pull requests merged in 2023-10, with the labels that each got.

#35797 Disable IDE0200 "Lambda expression can be removed" warning
  .editorconfig
Labels: Area-Infrastructure, untriaged

#35661 branding update for 8.0.2xx
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35754 Containers: reuse HTTP connections more.
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultBlobOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultBlobUploadOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
Labels: Servicing-approved, Area-Containers

#35775 ComputeDotnetBaseImageTag: handle rtm and servicing channels.
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageTag.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: Servicing-approved, Area-Containers

#35828 Update branding to 6.0.124
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35829 Update branding to 6.0.319
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35830 Update branding to 6.0.416
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35831 Update branding to 7.0.113
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35832 Update branding to 7.0.310
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35833 Update branding to 7.0.403
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35807 SDK resolver perf: Optimize EnvironmentProvider.SearchPaths
  src/Resolvers/Microsoft.DotNet.NativeWrapper/EnvironmentProvider.cs
Labels: Area-Infrastructure, untriaged

#35835 Including RuntimePackAsset in DesignerRuntimeImplementationProjectOutputGroup
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets
  src/Tests/Microsoft.NET.Build.Tests/GiventThatWeWantDesignerSupport.cs
Labels: untriaged

#35755 Pass failure message reported from from getApplyUpdateCapabilities in WASM to dotnet watch
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
Labels: Servicing-approved, Area-AspNetCore

#35906 Declare dependencies for two Extensions.Logging packages
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35890 SDK resolver perf: Don't check current process for dotnet.exe on .NET Framework
  src/Resolvers/Microsoft.DotNet.NativeWrapper/EnvironmentProvider.cs
Labels: Area-Infrastructure, untriaged

#35489 APICompat - Use compatible assembly references
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/Suppression.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/SuppressionEngine.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/ApiCompatRunnerExtensions.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Package.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Logging/SuppressionEngineTests.cs
Labels: Area-ApiCompat

#35884 Fix concurrent tool restore and version range error
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
  src/Tests/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
Labels: Servicing-approved, untriaged, Area-Tools

#35958 Update APICompat & GenAPI CodeAnalysis versions
  src/ApiCompat/Directory.Build.props
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/Microsoft.DotNet.ApiCompat.Task.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Microsoft.DotNet.ApiCompat.Tool.csproj
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/Compatibility/Directory.Build.props
  src/Compatibility/Directory.Packages.props
  src/GenAPI/Directory.Build.props
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Microsoft.DotNet.GenAPI.Tool.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
  src/Microsoft.DotNet.ApiSymbolExtensions/Directory.Build.props
  src/Microsoft.DotNet.ApiSymbolExtensions/Microsoft.DotNet.ApiSymbolExtensions.csproj
Labels: Area-ApiCompat

#35975 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35977 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35978 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35979 Merging internal commits for release/7.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35976 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35697 Make CheckForDuplicateItems case insensitive
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenACheckForDuplicateItems.cs
  src/Tasks/Microsoft.NET.Build.Tasks/CheckForDuplicateItems.cs
Labels: untriaged, Area-NetSDK

#35948 Switch to the svc pool for 7.0.4xx
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#35956 IDE0036 "Modifiers are not ordered" cleanup
  src/Cli/Microsoft.DotNet.Cli.Sln.Internal/FileManipulation/FileUtil.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Extensions/ProcessExtensions.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/details/DetailsCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Containers/Microsoft.NET.Build.Containers/Layer.cs
  src/RazorSdk/Tool/Client.cs
  src/RazorSdk/Tool/ConnectionHost.cs
  src/RazorSdk/Tool/ShutdownCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestFormatException.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ProjectContext.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ProjectInitializer.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/DockerAvailableUtils.cs
  src/Tests/Microsoft.NET.Publish.Tests/FilesCopiedToPublishDirTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishItemsOutputGroupOutputsTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishItemsOutputGroupTests.cs
  src/WebSdk/Publish/Tasks/MsDeploy/CommonUtility.cs
  src/WebSdk/Publish/Tasks/MsDeploy/DynamicAssembly.cs
  src/WebSdk/Publish/Tasks/Tasks/Kudu/KuduDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/MSDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/NormalizeServiceUrl.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/VsMsdeploy.cs
Labels: Area-Infrastructure, untriaged

#35940 Add .gitignore to exclude files generated by test
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/.gitignore
  src/Tests/dotnet-new.Tests/Approvals/.gitignore
Labels: Area-Infrastructure, untriaged

#35963 [release/8.0.1xx] Fix CodeAnalysis version used by APICompat assemblies
  src/ApiCompat/Directory.Build.props
  src/ApiCompat/Directory.Packages.props
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/Microsoft.DotNet.ApiSymbolExtensions/Directory.Build.props
  src/Microsoft.DotNet.ApiSymbolExtensions/Microsoft.DotNet.ApiSymbolExtensions.csproj
Labels: Servicing-approved

#35980 Merging internal commits for release/7.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#35031 Update the sdk target to net9.0
  Directory.Build.props
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
  eng/SourceBuildPrebuiltBaseline.xml
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
  global.json
  src/Assets/TestPackages/PackageLibraryDirectDependency/PackageLibraryDirectDependency/PackageLibraryDirectDependency.csproj
  src/Assets/TestPackages/PackageLibraryDirectDependency/PackageLibraryTransitiveDependency/PackageLibraryTransitiveDependency.csproj
  src/Assets/TestPackages/PackageLibraryNoStaticAssets/PackageLibraryNoStaticAssets.csproj
  src/Assets/TestPackages/PackageLibraryTransitiveDependency/PackageLibraryTransitiveDependency.csproj
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.5_0.targets
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net9.0/PublicAPI.Shipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net9.0/PublicAPI.Unshipped.txt
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.props
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
  src/StaticWebAssetsSdk/Targets/Sdk.StaticWebAssets.CurrentVersion.targets
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/PackageTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeManifestSupportedFrameworks.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
  src/Tests/Microsoft.NET.Publish.Tests/PublishTestUtils.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_CrosstargetingTests_CanIncludeBrowserAssets.Build.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_CrosstargetingTests_CanIncludeBrowserAssets.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_CrosstargetingTests_CanIncludeBrowserAssets.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_CrosstargetingTests_CanIncludeBrowserAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsCrossTargetingTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Windows.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Windows.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Windows.verified.txt
  src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
Labels: Area-Infrastructure, untriaged

#35794 [release/8.0.1xx] Allow Worker SDK projects to invoke Publish Profile-derived targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ContainerCli.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/WebSdk/Publish/Targets/DotNetCLIToolTargets/Microsoft.NET.Sdk.DotNetCLITool.targets
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.props
  src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.targets
Labels: Servicing-approved, Area-WebSDK

#36065 SDK resolver perf: Optimize EnvironmentProvider.SearchPaths
  src/Resolvers/Microsoft.DotNet.NativeWrapper/EnvironmentProvider.cs
Labels: Area-Infrastructure, untriaged

#35859 Workload manifest updater cleanup
  src/Cli/dotnet/commands/dotnet-workload/WorkloadInfoHelper.cs
  src/Cli/dotnet/commands/dotnet-workload/install/IWorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadId.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  src/Tests/dotnet-workload-install.Tests/MockWorkloadManifestUpdater.cs
  src/Tests/dotnet-workload-list.Tests/GivenWorkloadInstallerAndWorkloadsInstalled.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: untriaged, Area-Workloads

#36047 Add escape hatch for publishing with SelfContained=true, but no RuntimeIdentifier.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
Labels: Area-External, untriaged

#36092 WorkloadCollection cleanup
  src/Cli/dotnet/commands/dotnet-workload/install/IWorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/dotnet.csproj
  src/Tests/dotnet-workload-list.Tests/GivenWorkloadInstallerAndWorkloadsInstalled.cs
  src/Tests/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Infrastructure, untriaged

#36159 Fix pending reboot check
  src/Cli/dotnet/Installer/Windows/WindowsUtils.cs
Labels: untriaged, Area-Workloads

#35891 Update GivenThatWeWantToPublishAFrameworkDependentApp.cs to fix chars…
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAFrameworkDependentApp.cs
Labels: Area-Infrastructure, untriaged

#36200 Replace explicit richCodeNavigationEnvironment in .vsts-ci-richnav.yml
  .vsts-ci-richnav.yml
Labels: Area-Infrastructure, untriaged

#36195 [release/8.0.1xx] Define a default set of hot reload capabilities for Blazor WebAssembly
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
Labels: Servicing-approved, Area-AspNetCore, Area-Watch

#36224 Update branding to 6.0.320
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36225 Update branding to 6.0.417
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36223 Update branding to 6.0.125
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36226 Update branding to 7.0.114
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36227 Update branding to 7.0.311
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36228 Update branding to 7.0.404
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36094 [wasm] Move PublishTrimmed=true from pack to SDK
  src/WasmSdk/Sdk/Sdk.props
Labels: Area-WasmSdk

#36240 Fix ASP.NET SDK test baseline generation when repo is part of a git worktree
  src/Tests/Microsoft.NET.TestFramework/TestContext.cs
Labels: Area-Infrastructure, untriaged

#36272 Fix: Validate attribute type defines when excluded
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ApiCompatServiceProvider.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparerSettings.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AttributesMustMatch.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleSettings.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AttributesMustMatchTests.cs
Labels: Area-ApiCompat

#36279 Fix: Emit attribute type defines when excluded
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/SyntaxNodeExtensions.cs
  src/Compatibility/Microsoft.DotNet.ApiSymbolExtensions/AttributeDataExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Microsoft.DotNet.ApiCompatibility.Tests.csproj
  src/Tests/Microsoft.DotNet.ApiSymbolExtensions.Tests/TempDirectory.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/Microsoft.DotNet.GenAPI.Tests.csproj
Labels: Area-GenAPI

#36253 [release/8.0.1xx] [wasm] Move PublishTrimmed=true from pack to SDK
  src/WasmSdk/Sdk/Sdk.props
Labels: Servicing-approved, Area-WasmSdk

#36021 Enable users to install unlisted version of tool if specify the exact match of the version of the tool
  src/Cli/dotnet/NugetPackageDownloader/INuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Tests/dotnet-workload-install.Tests/FailingNuGetPackageInstaller.cs
  src/Tests/dotnet-workload-install.Tests/MockNuGetPackageInstaller.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
Labels: untriaged, Area-Tools

#35761 Update 8.0.2xx for loc
  eng/build.yml
Labels: untriaged, Area-Workloads

#36284 [release/8.0.1xx] GenAPI - Emit attribute type defines when excluded
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxNodeExtensions.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/AttributeDataExtensions.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Microsoft.DotNet.ApiCompatibility.Tests.csproj
  src/Tests/Microsoft.DotNet.ApiSymbolExtensions.Tests/TempDirectory.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/Microsoft.DotNet.GenAPI.Tests.csproj
Labels: Servicing-consider, Area-GenAPI

#36282 [release/8.0.1xx] APICompat - Validate attribute type defines when excluded
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ApiCompatServiceProvider.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/ApiComparerSettings.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AttributesMustMatch.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleSettings.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Rules/AttributesMustMatchTests.cs
Labels: Servicing-consider, Area-ApiCompat

#36326 Revert "[release/7.0.4xx] Update dependencies from dotnet/templating"
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36337 Revert skipped tests due to VS 17.8-p3
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_BlazorWasm.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_WebApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAWebApp.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishIncrementally.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorMultitargetIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildLazyLoadTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmCompressionTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPwaManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ApplicationPartDiscoveryIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildIntrospectionTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponentsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/DesignTimeBuildIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/JsModulesIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTest50.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PackIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/PublishIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsCrossTargetingTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
Labels: Area-Infrastructure, untriaged

#36366 Localize GenAPI
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/Resources.resx
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.cs.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.de.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.es.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.fr.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.it.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.ja.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.ko.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.pl.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.pt-BR.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.ru.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.tr.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.zh-Hans.xlf
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/xlf/Resources.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#36340 [release/8.0] Fix emsdk dep for stable version
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36329 Log SDK Culture mismatch message at Low importance to unblock SDK migration
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolvePackageAssetsTask.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
Labels: Servicing-approved, untriaged, Area-NetSDK

#36433 [release/8.0.1xx] Stabilize package versions
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#36115 Remove the extra diag output
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#36393 Update change to test for deadlocks in `packageInstall`
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
Labels: Area-Infrastructure, untriaged

#36090 Reduce test timeout to speed up timeouts.
  src/Tests/UnitTests.proj
Labels: Area-Infrastructure, untriaged

#35571 [release/8.0.1xx] Use MicrosoftAspNetCoreComponentsSdkAnalyzersPackageVersion for aspnetcore version
  global.json
Labels: untriaged, Area-AspNetCore

#36480 add Internal args to AOT tests
  eng/build.yml
Labels: Area-Infrastructure, untriaged

#36503 Upgrade Ubuntu image for Template Engine pipeline to 2204
  .vsts-ci.yml
  eng/template-engine.yml
Labels: Area-Infrastructure, untriaged

#36499 Skip a templating test when run internally
  src/Tests/dotnet-new.Tests/DotnetNewDetailsTest.cs
Labels: Area-Infrastructure, untriaged

#36543 Update README.md
  README.md
Labels: Area-Infrastructure, untriaged

#36554 Declare dependencies for two Extensions.Logging packages
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#36364 update .idea/ since it's a folder
  src/Tests/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitignore-file#-n#item.verified/dotnet-gitignore-file/.gitignore
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitignore/.gitignore
Labels: Area-Infrastructure, untriaged

#36443 Silence workload install logging on `dotnet --info` and related commands.
  src/Cli/dotnet/Installer/Windows/ISynchronizingLogger.cs
  src/Cli/dotnet/Installer/Windows/InstallClientElevationContext.cs
  src/Cli/dotnet/Installer/Windows/NullInstallerLogger.cs
  src/Cli/dotnet/Installer/Windows/TimestampedFileLogger.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadInfoHelper.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallerFactory.cs
Labels: untriaged, Area-Workloads
