Repository dotnet/sdk, pull requests merged in 2023-04, with the labels that each got.

#31545 GenAPI should not filter out base generic interfaces.
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: untriaged, Area-GenAPI

#31541 changes to containers tests and `ComputeDotnetBaseImageTag`
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageTag.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TestSettings.cs
Labels: untriaged, Area-Containers

#31341 First pass at source build pre-built detection
  Directory.Build.props
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
Labels: Area-Infrastructure

#31588 Add Microsoft.NET.Sdk.WebAssembly.Tasks to source-build.slnf
  source-build.slnf
Labels: Area-Infrastructure, untriaged

#31386 Reenable a skipped cppcli test.
  src/Assets/TestProjects/NetCoreCsharpAppReferenceCppCliLib/NETCoreCppCliTest/NETCoreCppCliTest.vcxproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishACppCliProject.cs
Labels: untriaged

#31603 Update branding to 6.0.312
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31606 Update branding to 7.0.204
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31605 Update branding to 7.0.106
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31604 Update branding to 6.0.409
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31594 Update the hardcoded to the current TFM
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
Labels: untriaged

#31403 extend search table with trusted and owners info
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Cli/Microsoft.TemplateEngine.Cli/TabularOutput/TabularOutput.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TabularOutput/TextAlign.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TelemetryConstants.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateInvoker.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateSearch/CliTemplateSearchCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/TabularOutputTests.cs
  src/Tests/dotnet-new.Tests/DotnetNewSearchTests.cs
Labels: Area-Infrastructure, untriaged

#31640 Fix order of targets in WasmNestedPublishAppDependsOn
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: Area-AspNetCore

#31591 Disable BinaryFormatter across most .NET 8 project types
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.VisualBasic.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
Labels: Area-Infrastructure, untriaged

#31658 Revert "[main] Update dependencies from microsoft/vstest"
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#31231 add --create-manifest-if-needed flag
  src/Cli/Microsoft.DotNet.Cli.Utils/Constants.cs
  src/Cli/dotnet/ToolManifest/IToolManifestFinder.cs
  src/Cli/dotnet/ToolManifest/LocalizableStrings.resx
  src/Cli/dotnet/ToolManifest/ToolManifestFinder.cs
  src/Cli/dotnet/commands/dotnet-tool/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet.Tests/CommandTests/ToolInstallLocalCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolRestoreCommandWithMultipleNugetConfigTests.cs
Labels: Area-Tools

#31618 Prep 7.0.3xx for GA release
  .vsts-ci.yml
  eng/Versions.props
  eng/build.yml
  src/Layout/redist/targets/GenerateLayout.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/LayoutSanityTests.cs
Labels: Area-Infrastructure, untriaged

#31716 Merging internal commits for release/7.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31714 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31725 Update to 7.0.5 releasing today
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31712 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31760 Trim prebuilt exclusions
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31611 add implementation and test for add Trademark assembly attribute
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
Labels: untriaged, Area-Tools

#31754 Upgrade the Ubuntu build image
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#31753 Try upgrading the ubuntu build image
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#31533 Remove unused `SourceGenerator.Tooling.Internal` version property
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31781 Split blazor boot extension target for build and publish
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: untriaged, Area-AspNetCore

#14854 Ensure case-insensitive web.config file name is used
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/TransformWebConfigTests.cs
  src/WebSdk/Publish/Tasks/Tasks/TransformWebConfig.cs
Labels: Area-WebSDK

#31626 Add a JsonSerializerIsReflectionEnabledByDefault property
  src/Assets/TestProjects/KitchenSink/TestApp/TestApp.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAProjectWithAllFeatures.cs
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
Labels: Area-Infrastructure, untriaged

#31598 Respond to ProduceReferenceAssembly default changing to true
  eng/Version.Details.xml
  eng/Versions.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToProduceReferenceAssembly.cs
Labels: untriaged, Area-Compilers

#31421 Adding locked messages as there is overlocalization in at least 5 of …
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#31632 Bundle Source Link packages
  eng/Version.Details.xml
  eng/Versions.props
  src/Assets/TestProjects/SourceLinkTestApp/Directory.Build.props
  src/Assets/TestProjects/SourceLinkTestApp/Directory.Build.targets
  src/Assets/TestProjects/SourceLinkTestApp/Program.cs
  src/Assets/TestProjects/SourceLinkTestApp/SourceLinkTestApp.csproj
  src/Layout/redist/targets/BundledSdks.targets
  src/Layout/redist/targets/RestoreDependency.proj
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CrossTargeting.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.SourceLink.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.SourceLink.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  src/Tests/Microsoft.NET.Build.Tests/Microsoft.NET.Build.Tests.csproj
  src/Tests/Microsoft.NET.Build.Tests/SourceLinkTests.cs
  src/Tests/Microsoft.NET.TestFramework/TestAssetsManager.cs
Labels: Area-Infrastructure, untriaged

#31559 Move asset compression to the StaticWebAssets SDK
  sdk.sln
  source-build.slnf
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/BlazorWasmSdk/Tasks/ComputeBlazorFilesToCompress.cs
  src/Layout/redist/targets/GenerateLayout.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.5_0.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets
  src/StaticWebAssetsSdk/Targets/Sdk.StaticWebAssets.CurrentVersion.targets
  src/StaticWebAssetsSdk/Tasks/AssetToCompress.cs
  src/StaticWebAssetsSdk/Tasks/BrotliCompress.cs
  src/StaticWebAssetsSdk/Tasks/GZipCompress.cs
  src/StaticWebAssetsSdk/Tasks/Microsoft.NET.Sdk.StaticWebAssets.Tasks.csproj
  src/StaticWebAssetsSdk/Tasks/ResolveCompressedAssets.cs
  src/StaticWebAssetsSdk/Tool/Microsoft.NET.Sdk.StaticWebAssets.Tool.csproj
  src/StaticWebAssetsSdk/Tool/Program.cs
  src/StaticWebAssetsSdk/Tool/runtimeconfig.template.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/ComputeBlazorFilesToCompressTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/ResolveCompressedAssetsTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIncrementalismTest.cs
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmCompressionTests.cs
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/AspNetSdkBaselineTest.cs
  src/WasmSdk/Targets/Microsoft.NET.Sdk.WebAssembly.Current.targets
Labels: untriaged, Area-AspNetCore

#31814 Remove usages of CentOS 7
  .vsts-ci.yml
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToCrossPublish.cs
Labels: Area-Infrastructure, untriaged

#31809 Update CSS parser version
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#31843 Ensure GenAPI synthesize ctors when visibility filter would otherwise omit them
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: untriaged, Area-GenAPI

#31854 Don't emit `new` for explicit interface implementations
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: untriaged, Area-GenAPI

#31853 Some additional prebuilt baseline cleanup
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#31863 Fix incorrect MicrosoftSourceLinkBitbucketGitVersion property name
  eng/Versions.props
  src/Layout/redist/targets/BundledSdks.targets
Labels: Area-Infrastructure, untriaged

#31870 [wasm] Fix regression in blazor+aot
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: untriaged, Area-AspNetCore

#18502 Allow `dotnet sln list` to display solution folder paths
  src/Cli/dotnet/SlnProjectExtensions.cs
  src/Cli/dotnet/commands/dotnet-sln/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-sln/list/Program.cs
  src/Cli/dotnet/commands/dotnet-sln/list/SlnListParser.cs
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnList.cs
Labels: Area-CLI

#31852 Fix dotnet/sdk-container-builds#414 by using three-digit version
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageTag.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: Area-Containers

#31639 [release/7.0.4xx] containers: removed stack trace from logged error message
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
Labels: Area-Containers

#20449 Fix `dotnet list package` when current directory contains a `#` character in Unix systems
  src/Cli/Microsoft.DotNet.Cli.Utils/PathUtility.cs
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs
  src/Tests/dotnet-list-package.Tests/GivenDotnetListPackage.cs
Labels: Area-NuGet

#31909 Default JsonSerializerIsReflectionEnabledByDefault to true on Blazor WASM.
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
Labels: untriaged, Area-AspNetCore

#31868 Signing: enable NuGet signature verification by default on Linux
  src/Cli/dotnet/NuGetForwardingApp.cs
  src/Cli/dotnet/NuGetSignatureVerificationEnabler.cs
  src/Cli/dotnet/commands/RestoringCommand.cs
  src/Cli/dotnet/commands/dotnet-restore/Program.cs
  src/Tests/dotnet.Tests/NuGetSignatureVerificationEnablerTests.cs
Labels: Area-Infrastructure, untriaged

#31739 Add `-aot` parameter to the console template
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.TemplateCommand_GetAllSuggestions.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/AotVariants.console.cs.verified/MyProject/Program.cs
  src/Tests/dotnet-new.Tests/Approvals/AotVariants.console.cs.verified/MyProject/console.csproj
  src/Tests/dotnet-new.Tests/Approvals/AotVariants.console.cs.verified/std-streams/stdout.txt
  src/Tests/dotnet-new.Tests/Approvals/AotVariants.console.vb.verified/MyProject/Program.cs
  src/Tests/dotnet-new.Tests/Approvals/AotVariants.console.vb.verified/MyProject/vb-console.csproj
  src/Tests/dotnet-new.Tests/Approvals/AotVariants.console.vb.verified/std-streams/stdout.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelpForTemplate_MatchOnNonChoiceParam.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelpForTemplate_console.verified.txt
  src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/dotnetcli.host.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/ide.host.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.cs.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.en.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.es.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.fr.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.it.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.ja.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.ko.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.pl.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.pt-BR.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.ru.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.tr.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.zh-Hans.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/localize/templatestrings.zh-Hant.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/Company.ConsoleApplication1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/dotnetcli.host.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/ide.host.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.cs.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.en.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.es.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.fr.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.it.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.ja.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.ko.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.pl.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.pt-BR.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.ru.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.tr.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.zh-Hans.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/localize/templatestrings.zh-Hant.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/Company.ConsoleApplication1.vbproj
Labels: Area-Infrastructure, untriaged

#31871 Copied some out of sync loc files into main
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
Labels: Area-Infrastructure, untriaged

#31906 Invoke MakeDir task before invoking Touch task
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
Labels: untriaged

#31941 Re-enable Blazor AoT tests
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.AoT.Tests/WasmAoTPublishIntegrationTest.cs
Labels: untriaged, Area-AspNetCore

#31921 Remove Unnecessary Check In RazorSourceGenerator Targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-Infrastructure, untriaged

#32005 Add verbosity option to workload uninstall command.
  src/Cli/dotnet/commands/dotnet-workload/uninstall/WorkloadUninstallCommandParser.cs
  src/Tests/dotnet-workload-uninstall.Tests/GivenDotnetWorkloadUninstall.cs
Labels: Area-Infrastructure, untriaged

#31980 Update AOT console template
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.TemplateCommand_GetAllSuggestions.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/AotVariants.console.cs.verified/MyProject/console.csproj
  src/Tests/dotnet-new.Tests/Approvals/AotVariants.console.vb.verified/MyProject/vb-console.csproj
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelpForTemplate_MatchOnNonChoiceParam.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelpForTemplate_console.verified.txt
  src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/.template.config/dotnetcli.host.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-CSharp/Company.ConsoleApplication1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/.template.config/dotnetcli.host.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.8.0/content/ConsoleApplication-VisualBasic/Company.ConsoleApplication1.vbproj
Labels: Area-Infrastructure, untriaged

#31999 Adding support for additional auth scenarios for Zip Deploy
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpClientHelpers.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploymentStatus.cs
Labels: untriaged, Area-WebSDK

#32030 Remove ASP.NET Json feature switch
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: untriaged

#32040 Support new authentication type for msdeploy
  src/WebSdk/Publish/Tasks/MsDeploy/VsMSDeployObject.cs
Labels: untriaged

#31955 Use 'artifacts' instead of `.artifacts` for default artifacts path
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultArtifactsPath.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultOutputPaths.targets
  src/Tests/Microsoft.NET.Build.Tests/ArtifactsOutputPathTests.cs
  src/Tests/Microsoft.NET.TestFramework/OutputPathCalculator.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
Labels: untriaged, Area-NetSDK

#31720 Updating the minimum VS version
  NuGet.config
  eng/Versions.props
  src/Layout/redist/minimumMSBuildVersion
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-Infrastructure, untriaged

#32014 Workaround malformed `typeof` statements in TypeForwardedToAttributes
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/TypeForwardAttributeCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriter/TypeForwardAttributeCSharpSyntaxRewriterTests.cs
Labels: untriaged, Area-GenAPI

#32002 [main] Add Nuget vulnerabilities output
  src/Cli/Microsoft.DotNet.Cli.Utils/AnsiConsole.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/AnsiExtensions.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/uninstall/BaseUninstallCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/update/BaseUpdateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageDisplay.cs
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/WorkloadCleanCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/TemplatePackageDisplayTest.cs
  src/Tests/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
Labels: Area-Infrastructure, untriaged

#32072 Add Nuget vulnerabilities output
  src/Cli/Microsoft.DotNet.Cli.Utils/AnsiExtensions.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageDisplay.cs
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/clean/WorkloadCleanCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/TemplatePackageDisplayTest.cs
  src/Tests/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
Labels: Servicing-consider, Area-Infrastructure, untriaged

#32090 Switch format owner
  CODEOWNERS
Labels: Area-Infrastructure, untriaged

#32089 Remove msbuild properties that pointed to old versions
  eng/Versions.props
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/Microsoft.DotNet.ApiCompat.Task.csproj
  src/BuiltInTools/DotNetWatchTasks/DotNetWatchTasks.csproj
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/Microsoft.NET.Build.Containers.IntegrationTests.csproj
  src/WebSdk/Publish/Tasks/Microsoft.NET.Sdk.Publish.Tasks.csproj
Labels: Area-Infrastructure, untriaged

#32102 Try out osx 13 to balance out the queue utilization
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure, untriaged

#32091 Enable TestBaseTypeWithAmbiguousNonDefaultConstructorsRegression31655
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: untriaged, Area-GenAPI

#31432 [release/7.0.4xx] include container tasks and targets directly to `Microsoft.NET.Publish.Sdk`
  src/Layout/redist/targets/GenerateLayout.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/LayoutSanityTests.cs
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.props
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
  src/WebSdk/Web/Sdk/Sdk.props
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: Area-Containers

#32108 Cherry-picking the Auth changes to 8.0 branch
  src/WebSdk/Publish/Tasks/MsDeploy/VsMSDeployObject.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/HttpClientHelpers.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/ZipDeploy/ZipDeploymentStatus.cs
Labels: untriaged, Area-WebSDK

#31949 Change the workloads txt file name to KnownWorkloadManifests.txt.
  documentation/general/workloads/workload-fallback.md
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
Labels: Area-Infrastructure, untriaged

#18608 dotnet sln: Add error message for misplaced solution argument
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-sln/SlnArgumentValidator.cs
  src/Cli/dotnet/commands/dotnet-sln/add/Program.cs
  src/Cli/dotnet/commands/dotnet-sln/remove/Program.cs
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
Labels: Area-CLI

#32100 Allow opting-in to NativeAOT publishing using runtime packs
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
Labels: Area-Infrastructure, untriaged

#30908 Blazor hosted
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyHostedDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/DeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/HotReload.cs
  src/BuiltInTools/dotnet-watch/HotReload/IDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/NamedPipeContract.cs
  src/BuiltInTools/dotnet-watch/HotReload/SingleProcessDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/Tests/dotnet-watch.Tests/HotReload/DefaultDeltaApplierTest.cs
Labels: Area-Infrastructure

#32139 Revert "Remove Unnecessary Check In RazorSourceGenerator Targets"
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets
Labels: Area-Infrastructure, untriaged
