Repository dotnet/sdk, pull requests merged in 2023-07, with the labels that each got.

#33694 Fixed some issues with `details` command
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/SymbolStrings.Designer.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/SymbolStrings.resx
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.cs.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.de.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.es.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.fr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.it.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.ja.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.ko.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.pl.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.pt-BR.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.ru.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.tr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.zh-Hans.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/xlf/SymbolStrings.zh-Hant.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Cli/Microsoft.TemplateEngine.Cli/NuGet/NugetApiManager.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.DetailsCommand_GetAllSuggestions.verified.txt
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.Install_GetAllSuggestions.verified.txt
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.RootCommand_GetAllSuggestions.verified.txt
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.Update_GetAllSuggestions.verified.txt
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/TemplatePackageCoordinatorTests.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_InstalledPackage_NuGetFeed.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_InstalledPackage_OtherFeed.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_RemotePackage_NuGetFeedNoVersion.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_RemotePackage_NuGetFeedWithVersion.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_RemotePackage_OtherFeedNoVersion.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_RemotePackage_OtherFeedWithVersion.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelp_Install_common.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelp_Update_common.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelp_common.verified.txt
Labels: Area-Infrastructure, untriaged

#33720 Fix CmdOption name and aliases
  src/Containers/containerize/ContainerizeCommand.cs
Labels: untriaged, Area-Containers

#33761 Disabled `--version` option for `dotnet new details`
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/details/DetailsCommand.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/details/DetailsCommandArgs.cs
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.DetailsCommand_GetAllSuggestions.verified.txt
  src/Tests/dotnet-new.Tests/DotnetNewDetailsTest.Approval.cs
Labels: Area-Infrastructure, untriaged

#33799 Update branding to 6.0.121
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33802 Update branding to 7.0.110
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33800 Update branding to 6.0.316
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33803 Update branding to 7.0.307
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33801 Update branding to 6.0.413
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33572 Remove redundant SourceBuildTrimNetFrameworkTargets property
  eng/SourceBuild.props
Labels: Area-Infrastructure, source-build, untriaged

#33619 Fix printed version for APICompat.Tool and GenAPI.Tool
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Program.cs
Labels: untriaged, Area-ApiCompat

#33814 Replace ellipsis character with 3-dots
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#33775 Containers: support mapping non-portable (source-built) rids to container manifest platforms.
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
Labels: untriaged, Area-Containers

#33336 [release/7.0.3xx] Containers: prefer atomic layer upload
  src/Containers/Microsoft.NET.Build.Containers/AuthHeaderCache.cs
  src/Containers/Microsoft.NET.Build.Containers/Layer.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/AuthHeaderCacheTests.cs
Labels: Servicing-approved, Area-Containers

#33839 Create VS shortcut with SDK build environment automatically loaded
  documentation/project-docs/developer-guide.md
  eng/restore-toolset.ps1
Labels: Area-Infrastructure, untriaged

#22883 Support for DisableDiagnosticTracing to suppress TRACE
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: Area-Infrastructure

#33757 Add tests for disabling JsonSerializer.IsReflectionEnabledByDefault on `PublishTrimmed=true`
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
Labels: untriaged, Area-ILLink

#33618 Add explicit System.Text.Json dependency
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
Labels: untriaged, Area-AspNetCore

#33888 Ensure GenAPI doesn't emit reserved attributes
  src/GenAPI/Microsoft.DotNet.GenAPI/AttributeDataExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxNodeExtensions.cs
  src/Tests/Microsoft.DotNet.ApiSymbolExtensions.Tests/SymbolFactory.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-Infrastructure, untriaged

#33915 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#32964 Validate existing suppressions and remove unnecessary suppressions when re-generating suppression files
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/SuppressionFileHelper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidatePackage.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/xlf/Resources.zh-Hant.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Resources.resx
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/SuppressableConsoleLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.cs.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.de.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.es.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.fr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.it.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.ja.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.ko.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.pl.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.pt-BR.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.ru.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.tr.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.zh-Hans.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/xlf/Resources.zh-Hant.xlf
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ISuppressionEngine.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/Suppression.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/SuppressionEngine.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/AssemblyIdentityMustMatch.cs
  src/ApiCompat/apicompat.slnf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/CustomSideNameTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Logging/EmptyTestSuppressionEngine.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Logging/SuppressionEngineTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/Logging/TestSuppressionEngine.cs
Labels: Area-ApiCompat

#33920 Update the runtime to 7.0.9 in public before moving codeflow internal
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33916 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33919 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33901 Enable BinSkim scan in nightly validation
  eng/sdl-tsa-vars.config
Labels: Area-Infrastructure, untriaged

#33837 Unblock sln add for a shared project
  src/Assets/TestProjects/TestAppWithSlnAndCsprojFiles/Shared/Shared.cs
  src/Assets/TestProjects/TestAppWithSlnAndCsprojFiles/Shared/Shared.projitems
  src/Assets/TestProjects/TestAppWithSlnAndCsprojFiles/Shared/Shared.shproj
  src/Cli/Microsoft.DotNet.Cli.Sln.Internal/ProjectTypeGuids.cs
  src/Cli/dotnet/ProjectInstanceExtensions.cs
  src/Cli/dotnet/SlnFileExtensions.cs
  src/Tests/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
Labels: untriaged, Area-CLI

#33863 Handle when the target graph is TF/RID to pull out the TF piece
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
Labels: untriaged

#33765 Containers: sync CreateNewImageToolTask with new CreateNewImage properties.
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs
  src/Containers/containerize/ContainerizeCommand.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/FullFramework/CreateNewImageToolTaskTests.cs
Labels: Area-Infrastructure, untriaged

#33862 Stabilize branding for the 7.0.400 release
  eng/Versions.props
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/PackageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ToolsetUtils.cs
Labels: Area-Infrastructure, untriaged

#33446 Update the existing NETSDK 1045 error message to link to the download page
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
Labels: Servicing-approved

#33917 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33937 Fix feature bands for side-by-side manifests
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/ReadableWorkloadManifest.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestInfo.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSet.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/FakeManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  src/Tests/dotnet-workload-install.Tests/MockManifestProvider.cs
  src/Tests/dotnet-workload-list.Tests/GivenDotnetWorkloadList.cs
Labels: untriaged, Area-Workloads

#33954 Align EnableStrictModeForCompatibleTfms default between frontends
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidatePackageTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Program.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets
Labels: untriaged, Area-ApiCompat

#33938 VS Shortcut: Use version number file
  eng/restore-toolset.ps1
Labels: Area-Infrastructure, untriaged

#33935 First-run: Minor code adjustments
  .editorconfig
  src/Cli/Microsoft.DotNet.Cli.Utils/TelemetryEventEntry.cs
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstRunConfiguration.cs
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Cli/Microsoft.DotNet.Configurer/FirstTimeUseNoticeSentinel.cs
  src/Cli/dotnet/Program.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurer.cs
  src/Tests/Microsoft.DotNet.Configurer.UnitTests/GivenADotnetFirstTimeUseConfigurerWIthStateSetup.cs
  src/Tests/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs
Labels: Area-Infrastructure, untriaged

#33962 Update default TrimMode for WebSDK projects
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
Labels: untriaged, Area-WebSDK

#32882 [wasm] Override versions of previous runtime packs
  src/Layout/redist/targets/BuildToolsetTasks.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Layout/toolset-tasks/OverrideWasmRuntimePackVersions.cs
Labels: untriaged, Area-Workloads

#33756 Default to RazorLangVersion 8.0 in .NET 8.0
  src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets
Labels: untriaged, Area-AspNetCore

#34030 Keep TrimMode=partial for projects targeting .NET 7 or below
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
Labels: untriaged, Area-AspNetCore

#34044 Add .idea to .gitignore
  src/Tests/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitignore-file#-n#item.verified/dotnet-gitignore-file/.gitignore
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitignore/.gitignore
Labels: Area-Infrastructure, untriaged

#34072 Add EnableGeneratedComInterfaceComImportInterop property to control the source-generated/built-in COM interop interaction feature switch.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Area-NetSDK

#34092 RC 1 branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#33955 Containers: improved `DockerRegistryManager` for tests reliability
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
Labels: untriaged, Area-Containers

#34128 Update Container User Id to react to changes in dotnet/dotnet-docker#4715
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: Servicing-approved, Area-Infrastructure, untriaged

#34130 Include Mac in AOT testing
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: untriaged, Area-NativeAOT

#34142 [release/8.0.1xx-preview7] Disable ConfigurationBinder source generator in Blazor WASM
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
Labels: Servicing-approved, untriaged, Area-AspNetCore

#34177 Move `GenerateRuntimeConfigurationFiles=false` back to Blazor SDK from Wasm SDK
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: Area-AspNetCore

#34212 Port 33753 to main
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/AuthHeaderCache.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ContentStore.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/AuthenticatedRegistry/auth/htpasswd
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ContainerCli.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/Microsoft.NET.Build.Containers.IntegrationTests.csproj
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/RegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/AuthHeaderCacheTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: Area-Infrastructure, untriaged

#31581 Allow ResolveReadyToRunCompilers to be run under FreeBSD
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: untriaged, Area-ReadyToRun

#33753 Containers: Protocol correctness and quirk handling for Basic and Bearer authentication for registries
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/AuthHeaderCache.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ContentStore.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/AuthenticatedRegistry/auth/htpasswd
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ContainerCli.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/Microsoft.NET.Build.Containers.IntegrationTests.csproj
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/RegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/AuthHeaderCacheTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: Servicing-consider, Area-Containers

#34132 Revert "#30336 Default Dotnet Tool to Run on Latest Runtime - Build time change"
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProject.cs
Labels: Area-Infrastructure, untriaged, breaking-change, needs-breaking-change-doc-created

#34220 [main] Disable ConfigurationBinder source generator in Blazor WASM
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets
Labels: untriaged, Area-NetSDK

#34277 Revert "Allow ResolveReadyToRunCompilers to be run under FreeBSD"
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: untriaged, Area-ReadyToRun

#34302 Fix official build break
  src/Common/CompileOptions.cs
Labels: Area-Infrastructure, untriaged

#34289 Fix the end of build install of workloads to always refresh the rollback file
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#34318 Workaround issue with explicitly implemented indexers
  src/GenAPI/Microsoft.DotNet.GenAPI/Filtering/ImplicitSymbolFilter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: untriaged, Area-GenAPI

#34311 Remove tooltask validation for Entrypoint/EntrypointArgs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/FullFramework/CreateNewImageToolTaskTests.cs
Labels: Area-Containers
