Repository dotnet/sdk, pull requests merged in 2023-01, with the labels that each got.

#29698 Add escape switch for TargetPlatform and SupportedOS attributes
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets
Labels: Area-NetSDK

#29640 Unskip `Publish_HostedApp_WithoutTrimming_Works`
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
Labels: Area-AspNetCore

#29549 Use File.OpenRead when loading tool configuration (7.0.2xx backport)
  src/Cli/dotnet/ToolPackage/ToolConfigurationDeserializer.cs
Labels: Servicing-consider, Area-Tools

#29152 [release/7.0.2xx] Revert hot reload script injection response buffering
  src/BuiltInTools/BrowserRefresh/BrowserRefreshMiddleware.cs
  src/BuiltInTools/BrowserRefresh/ReadOnlySpanOfByteExtensions.cs
  src/BuiltInTools/BrowserRefresh/ResponseStreamWrapper.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserRefreshMiddlewareTest.cs
  src/Tests/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/WebSocketScriptInjectionTest.cs
Labels: Area-AspNetCore

#29723 Update branding to 7.0.103
  .vsts-ci.yml
  eng/Versions.props
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure

#29636 [release/7.0.1xx] Inverted language version conditions in console / classlib templates to support new language features for newer language versions
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.7.0/content/ClassLibrary-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.7.0/content/ConsoleApplication-CSharp/.template.config/template.json
Labels: Servicing-consider, Area-Infrastructure

#29350 extend typo correction functionality with StartsWith and Contains
  src/Cli/Microsoft.DotNet.Cli.Utils/TypoCorrection.cs
  src/Tests/Microsoft.DotNet.Cli.Utils.Tests/TypoCorrectionTests.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CannotShowHelpForTemplate_PartialNameMatch.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CanSuggestTypoCorrection_Command.verified.txt
Labels: Area-Infrastructure, Area-dotnet new

#29288 Update the correct nuget.config file and remove a bunch of extra sources
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
Labels: Area-Infrastructure

#29751 Branding for 6.0.300
  .vsts-ci.yml
  eng/Versions.props
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Assets/TestReleases/TestRelease/releases-index.json
Labels: Area-Infrastructure

#29752 Branding for 6.0.4xx
  .vsts-ci.yml
  eng/Versions.props
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Assets/TestReleases/TestRelease/releases-index.json
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure

#29534 Fix copy failures when building Microsoft.NET.Sdk.Razor.Tasks.csproj
  src/RazorSdk/Tasks/Microsoft.NET.Sdk.Razor.Tasks.csproj
Labels: Area-AspNetCore

#29750 Branding for 6.0.1xx
  .vsts-ci.yml
  eng/Versions.props
  src/Assets/TestProjects/AppWithLibraryAndRid/App/App.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/LibraryWithRids.csproj
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Assets/TestReleases/TestRelease/releases-index.json
Labels: Area-Infrastructure

#29805 Copying the files to publish intermediate path to help with .NET SDK container publish
  src/WebSdk/Publish/Targets/ComputeTargets/Microsoft.NET.Sdk.Publish.ComputeFiles.targets
  src/WebSdk/Publish/Targets/CopyTargets/Microsoft.NET.Sdk.Publish.CopyFiles.targets
Labels: Area-WebSDK

#29783 Improve the stage 0 template error message to be actionable
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure

#29548 Use File.OpenRead when loading tool configuration (6.0.4xx backport)
  src/Cli/dotnet/ToolPackage/ToolConfigurationDeserializer.cs
Labels: Servicing-consider, Area-Tools

#29818 update eol list
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetEolFrameworks.cs
Labels: Area-Infrastructure

#29579 Use File.OpenRead when loading tool configuration (6.0.1xx backport)
  src/Cli/dotnet/ToolPackage/ToolConfigurationDeserializer.cs
Labels: Servicing-consider, Area-Tools

#29584 Use File.OpenRead when loading tool configuration (7.0.1xx backport)
  src/Cli/dotnet/ToolPackage/ToolConfigurationDeserializer.cs
Labels: Servicing-approved, Area-Tools

#29719 Adding Microsoft.AspNetCore.EnsureJsonTrimmability host configuration
  sdk.sln
  src/Tests/Microsoft.NET.Sdk.Web.Tests/Microsoft.NET.Sdk.Web.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/WebSdk/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.targets
  src/WebSdk/Web/Sdk/Sdk.targets
Labels: Area-Infrastructure

#29372 Remove unnecessary sources from the test used nuget.config file to reduce 429s
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
Labels: Area-Infrastructure

#29856 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#29857 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#29858 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.AoT.Tests/Microsoft.NET.Sdk.BlazorWebAssembly.AoT.Tests.csproj
  src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests.csproj
Labels: Area-Infrastructure

#29862 Merging internal commits for release/3.1.4xx
  .vsts-ci.yml
Labels: Area-Infrastructure

#29871 Added test for new naming behavior of PreferDefaultName property
  src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithPreferDefaultName/.template.config/template.json
  src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithPreferDefaultName/toChange.cs
  src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithPreferDefaultNameButNoDefaultName/.template.config/template.json
  src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithPreferDefaultNameButNoDefaultName/toChange.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CannotInstantiateTemplate_WhenNoDefaultNameSpecified.verified.txt
  src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.Approval.cs
  src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.cs
Labels: Area-Infrastructure

#29855 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#29435 Fix bad merge that incorrectly didn't exclude some packages
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToExcludeAPackageFromPublish.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
  src/Tests/Microsoft.NET.TestFramework/TestPackageReference.cs
Labels: Area-NetSDK

#27849 [release/6.0.1xx] Use the portable rid for --use-current-runtime (backports #21748)
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
Labels: Area-External, Servicing-approved

#29872 Re-enable single-file tests
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Area-SingleFile

#29559 fix locale-sensitive comparison of UnmatchedArgument error strings
  src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs
  src/Cli/dotnet/ParseResultExtensions.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/TestCommand.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestsRunsInDifferentCultures.cs
Labels: Servicing-approved, Area-CLI

#29746 fix locale-sensitive comparison of UnmatchedArgument error strings
  src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs
  src/Cli/dotnet/ParseResultExtensions.cs
  src/Tests/Microsoft.NET.TestFramework/Commands/TestCommand.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestsRunsInDifferentCultures.cs
Labels: Area-CLI, cli-ux

#28811 Detect Corrupt Solution File in Dotnet Sln Add
  src/Cli/Microsoft.DotNet.Cli.Sln.Internal/LocalizableStrings.resx
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/SlnFileExtensions.cs
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure

#29557 [release/7.0.2xx] [Backport] Prevent `dotnet test` verbosity from being ignored
  src/Cli/dotnet/commands/dotnet-test/Program.cs
  src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
Labels: Area-Infrastructure

#29866 Add *.swp to gitignore template
  src/Tests/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitignore-file#-n#item.verified/dotnet-gitignore-file/.gitignore
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitignore/.gitignore
Labels: Area-Infrastructure

#29934 [release/7.0.2] add warning scrubber
  src/Tests/dotnet-new.Tests/DotnetClassTemplateTests.cs
Labels: Area-dotnet new

#28674 Make PublishAot an optional feature because Mono does not support it.
  eng/SourceBuild.props
  src/Layout/redist/targets/BundledSdks.targets
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Servicing-approved, Area-Infrastructure

#29961 Fix an issue with delegate declaration. Fix an issue with Simplifier and removing nullability.
  eng/Versions.props
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#29942 Stable branding for 7.0.200 GA release
  eng/Versions.props
  eng/build.yml
Labels: Area-Infrastructure

#28836 Do not eagerly discover CWD during parser construction
  src/Cli/dotnet/CommonOptions.cs
Labels: Area-CLI, cli-ux

#29984 Use better AOT defaults in Web SDK
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs
  src/Tests/Microsoft.NET.Sdk.Web.Tests/PublishTests.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
Labels: Area-Infrastructure

#29982 Add support for EnableRequestDelegateGenerator flag
  global.json
  src/BuiltInTools/BrowserRefresh/BlazorWasmHotReloadMiddleware.cs
  src/BuiltInTools/BrowserRefresh/Microsoft.AspNetCore.Watch.BrowserRefresh.csproj
  src/Layout/toolset-tasks/OverrideAndCreateBundledNETCoreAppPackageVersion.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Tests/HelixTasks/HelixTasks.csproj
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToUseAnalyzers.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Windows.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Windows.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Linux.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.OSX.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Windows.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/WebProjectsTests.CanShowHelp_Mvc.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/WebProjectsTests.CanShowHelp_WebAPI.verified.txt
  src/Tests/dotnet-new.Tests/Approvals/WebProjectsTests.CanShowHelp_Webapp_common.verified.txt
  src/Tests/dotnet-new.Tests/WebProjectsTests.cs
  src/Tests/xunit-runner/XUnitRunner.targets
  src/WebSdk/Web/Sdk/Sdk.props
Labels: Area-AspNetCore

#29870 Mention that preview SDKs in VS needs to be turned on in the dev guide
  documentation/project-docs/developer-guide.md
Labels: Area-Infrastructure

#29562 Create an SDK PR guide
  documentation/project-docs/SDK-PR-guide.md
Labels: Area-Infrastructure

#30030 Add support for destructor and explicit interface implementation generation.
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpSyntaxWriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/SymbolExtensions.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#29749 Add a reminder for the Area-AspNetCore PR authors to help with finding the schedule
  .github/fabricbot.json
Labels: Area-AspNetCore

#29755 Use UTF-8 Encoding by Default On Windows On Non English Languages
  src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs
Labels: Area-Infrastructure

#29990 Merge branch 'release/7.0.2xx' => 'main'
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
Labels: Area-Infrastructure

#30086 Update README.md
  README.md
Labels: documentation

#30077 BlazorWasmSdk: Serve .webcil as application/octet-stream
  src/BlazorWasmSdk/Targets/BlazorWasm.web.config
Labels: Area-AspNetCore

#30048 update output path in WebProjectsTests
  src/Tests/dotnet-new.Tests/WebProjectsTests.cs
Labels: Area-dotnet new

#30102 Make error optional in ApiSymbolExtensions logger
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/SuppressionFileHelper.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/SuppressableMSBuildLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/SuppressableConsoleLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ISuppressableLog.cs
  src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/ApiCompatRunnerExtensions.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/BaselinePackageValidator.cs
  src/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/CompatibleTFMValidator.cs
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/Microsoft.DotNet.ApiSymbolExtensions/Logging/ConsoleLog.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Logging/ILog.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Logging/MSBuildLog.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Logging/MessageLevel.cs
  src/Tests/Microsoft.DotNet.ApiCompat.IntegrationTests/Task/ValidatePackageTargetIntegrationTests.cs
  src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressableTestLog.cs
Labels: Area-ApiCompat

#30152 Update linker team name
  .github/fabricbot.json
  CODEOWNERS
Labels: Area-Infrastructure

#29155 Make `dotnet publish` use `Release` by default in 8.0+ Projects
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/ReleasePropertyProjectLocator.cs
  src/Cli/dotnet/commands/dotnet-pack/PackCommand.cs
  src/Cli/dotnet/commands/dotnet-publish/Program.cs
  src/Cli/dotnet/dotnet.csproj
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  src/Common/EnvironmentVariableNames.cs
  src/Common/MSBuildPropertyNames.cs
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf~RF243dc495.TMP
  src/Tasks/Common/Resources/xlf/Strings.it.xlf~RF30a3de88.TMP
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PackTool.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/Microsoft.DotNet.PackageInstall.Tests.csproj
  src/Tests/Microsoft.NET.Pack.Tests/GivenThatWeWantToPackAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Pack.Tests/Microsoft.NET.Pack.Tests.csproj
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToTestAMultitargetedSolutionWithPublishReleaseOrPackRelease.cs
  src/Tests/Microsoft.NET.Publish.Tests/Microsoft.NET.Publish.Tests.csproj
  src/Tests/Microsoft.NET.Publish.Tests/RuntimeIdentifiersTests.cs
  src/Tests/Microsoft.NET.TestFramework/ProjectConstruction/TestSolution.cs
  src/Tests/Microsoft.NET.TestFramework/TestAsset.cs
  src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProject.cs
  src/Tests/dotnet-publish.Tests/GivenDotnetPublishPublishesProjects.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
Labels: Area-Infrastructure

#30149 Move to osx 12
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.TestFramework/EnvironmentInfo.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure

#30138 add named monitor for fixing floating tests
  src/Tests/dotnet-new.Tests/SharedHomeDirectory.cs
  src/Tests/dotnet-new.Tests/Utilities.cs
Labels: Area-Infrastructure

#30141 Refactor CSharpSyntaxWrite. Introduce SingleLineStatement, FieldDeclaration, BodyBlock, TypeDeclaration *CSharpSyntaxRewriter.
  eng/Versions.props
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxNodeExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/BodyBlockCSharpSyntaxRewriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/FieldDeclarationCSharpSyntaxRewriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/SingleLineStatementCSharpSyntaxRewriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/TypeDeclarationCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriterTests.cs
Labels: Area-GenAPI

#30201 Create the Publish temp folder for Zip deploy if not exist
  src/WebSdk/Publish/Targets/PublishTargets/Microsoft.NET.Sdk.Publish.ZipDeploy.targets
Labels: Area-WebSDK

#30174 Merge 3xx to main
  .vsts-ci.yml
  src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithPreferDefaultName/.template.config/template.json
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tests/Microsoft.NET.TestFramework/EnvironmentInfo.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
  src/Tests/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CannotInstantiateTemplate_WhenNoDefaultNameSpecified.verified.txt
  src/WebSdk/Web/Sdk/Sdk.props
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Class-VisualBasic/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Class-VisualBasic/.template.config/localize/templatestrings.tr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Enum-VisualBasic/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Enum-VisualBasic/.template.config/localize/templatestrings.tr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Interface-VisualBasic/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Interface-VisualBasic/.template.config/localize/templatestrings.tr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Struct-VisualBasic/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Struct-VisualBasic/.template.config/localize/templatestrings.tr.json
Labels: Area-Infrastructure

#29628 Move Template Discovery Test from dotnet/templating to dotnet/sdk
  eng/Versions.props
  src/Tests/dotnet-new.Tests/TemplateDiscoveryTests.cs
  src/Tests/dotnet-new.Tests/TemplateDiscoveryTool.cs
  src/Tests/dotnet-new.Tests/dotnet-new.IntegrationTests.csproj
Labels: Area-Infrastructure

#30044 Prevent editors from auto-trimming trailing whitespaces in test approval files
  .editorconfig
Labels: Area-Infrastructure, Area-dotnet new
