Repository dotnet/sdk, pull requests merged in 2023-02, with the labels that each got.

#30203 Preview branding
  eng/Versions.props
Labels: Area-Infrastructure

#29921 Introduce Dependabot for updating the same dependencies used in dotnet/templating
  .github/dependabot.yml
  Directory.Build.targets
  eng/Packages.props
  eng/dependabot/Packages.props
  eng/dependabot/dependabot.csproj
  src/Cli/Microsoft.TemplateEngine.Cli/Microsoft.TemplateEngine.Cli.csproj
  src/Tests/Microsoft.TemplateEngine.Cli.UnitTests/Microsoft.TemplateEngine.Cli.UnitTests.csproj
  src/Tests/dotnet-new.Tests/dotnet-new.IntegrationTests.csproj
Labels: Area-Infrastructure

#30250 Upgrade to latest `CodeAnalysis.Workspaces`. Get rid of workarounds and cover latest supported features with Tests.
  eng/Versions.props
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/BodyBlockCSharpSyntaxRewriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/FieldDeclarationCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriterTests.cs
Labels: Area-GenAPI

#30190 Update the target framework for the non-restored test projects
  src/Assets/NonRestoredTestProjects/AppWithNonExistingToolDependency/AppWithNonExistingToolDependency.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/EmptyItemGroup/EmptyItemGroup.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/MoreThanOne/a.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/MoreThanOne/b.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/ValidRef/ValidRef.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/WithDoubledRef/WithDoubledRef.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/WithExistingRefCondOnItem/WithExistingRefCondOnItem.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/WithExistingRefCondWhitespaces/WithExistingRefCondWhitespaces.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/WithRefCondNonUniform/WithRefCondNonUniform.csproj
  src/Assets/NonRestoredTestProjects/DotnetAddP2PProjects/WithRefNoCondNonUniform/WithRefNoCondNonUniform.csproj
  src/Assets/NonRestoredTestProjects/TestProjectWithUnresolvedPlatformDependency/TestProjectWithUnresolvedPlatformDependency.csproj
Labels: Area-Infrastructure

#30265 Fix bug with `dotnet publish -p:Foo`
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs
  src/Cli/dotnet/ReleasePropertyProjectLocator.cs
  src/Cli/dotnet/commands/dotnet-pack/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-pack/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-publish/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-publish/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
Labels: Area-NetSDK

#30239 Warn if the publish profile provided is not present in the project
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets
Labels: Area-WebSDK

#30264 Generate a call of a base class constructor if the default constructor does not exist.
  src/GenAPI/Microsoft.DotNet.GenAPI/AttributeDataExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/SingleLineStatementCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriterTests.cs
Labels: Area-GenAPI

#30406 Update branding to 7.0.201
  eng/Versions.props
Labels: Area-Infrastructure

#30401 Update branding to 6.0.115
  eng/Versions.props
Labels: Area-Infrastructure

#30402 Update branding to 6.0.310
  eng/Versions.props
Labels: Area-Infrastructure

#30405 Update branding to 6.0.407
  eng/Versions.props
Labels: Area-Infrastructure

#30370 Update to the automated build pool variable
  .vsts-ci-richnav.yml
  .vsts-ci.yml
  eng/template-engine.yml
Labels: Area-Infrastructure

#30083 Enable PRs for all release builds and remove some CI
  .vsts-ci.yml
Labels: Area-Infrastructure

#30056 Fix NRE in installer tests
  src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs
Labels: Area-Infrastructure

#30403 Update branding to 7.0.104
  eng/Versions.props
Labels: Area-Infrastructure

#30081 Switch to OSX 12 for 7.0.1xx
  .vsts-ci.yml
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.TestFramework/EnvironmentInfo.cs
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure

#30212 Fix up 'CurrentTargetFramework' usage error
  src/Assets/TestProjects/SimpleDependencies/SimpleDependencies.csproj
Labels: Area-Infrastructure

#30379 fix repo build on non-ubuntu linux
  eng/restore-toolset.sh
Labels: Area-Infrastructure

#30420 Log MSI package ID instead of MSI filename
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
Labels: Area-Workloads

#30363 Introduce `exp` prefix in PR to allow better PR review process
  .vsts-ci.yml
Labels: Area-Infrastructure

#30263 READ.ME Includes PR Timeline Guide + Explain Nightly Builds in Documentation
  README.md
  documentation/project-docs/SDK-PR-guide.md
Labels: Area-Infrastructure

#30394 Filter out default member attribute for types with indexer. Implement filtering out base type and interfaces.
  src/GenAPI/Microsoft.DotNet.GenAPI/AttributeDataExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/SingleLineStatementCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriterTests.cs
Labels: Area-GenAPI

#30476 GenAPI: update event declaration and reference parameters.
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/BodyBlockCSharpSyntaxRewriter.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/SingleLineStatementCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30362 GenAPI: synthesize private fields for value types
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30516 GenAPI: correctly check that type has unbound type parameters
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30292 Fix dotnet new -v displaying exception callstack
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/Tests/dotnet-new.Tests/DotnetNewArgumentsTests.cs
Labels: Area-Infrastructure

#30539 GenAPI: add readonly keyword for synthesized fields.
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30037 Adding the linux feed removal to 6.0.1xx as I figured out the issue
  build/RunTestsOnHelix.sh
Labels: Area-Infrastructure

#30557 [release/7.0.3xx] Port Fix dotnet new -v displaying exception callstack (#30292)
  src/Cli/dotnet/commands/dotnet-new/NewCommandParser.cs
  src/Tests/dotnet-new.Tests/DotnetNewArgumentsTests.cs
Labels: Area-Infrastructure

#30556 [GenAPI] generate forwarded type assembly attributes.
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/GenAPITask.cs
  src/GenAPI/Microsoft.DotNet.GenAPI.Task/build/Microsoft.DotNet.GenAPI.Task.targets
  src/GenAPI/Microsoft.DotNet.GenAPI.Tool/Program.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/TypeForwardAttributeCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/SyntaxRewriterTests.cs
Labels: Area-GenAPI

#30597 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#30598 Merging internal commits for release/6.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#30573 Better fix for the OSX issues in installer repo
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.TestFramework/EnvironmentInfo.cs
Labels: Area-Infrastructure

#30579 Fix package cache group SID
  src/Cli/dotnet/Installer/Windows/MsiPackageCache.cs
Labels: Servicing-approved, Area-Workloads

#30480 Document `Workload Clean` Design
  documentation/general/workloads/README.md
  documentation/general/workloads/workload-clean.md
Labels: Area-Infrastructure

#30607 add @andriipatsula and @dotnet/area-infrastructure-libraries as codeowners for GenAPI
  CODEOWNERS
Labels: Area-Infrastructure

#30599 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#30611 Update to the .net runtime that released today.
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#30617 Bump FluentAssertions from 6.9.0 to 6.10.0
  eng/Versions.props
Labels: Area-Infrastructure

#30616 Bump FluentAssertions from 6.9.0 to 6.10.0
  eng/Versions.props
Labels: Area-Infrastructure

#30601 Merging internal commits for release/7.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure

#29376 Try not building the test assets and see what happens
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
  src/Assets/TestPackages/BuildTestPackages.targets
  src/Assets/TestPackages/Microsoft.NET.TestPackages.csproj
  src/Tests/Directory.Build.targets
  src/Tests/Microsoft.DotNet.CommandFactory.Tests/GivenAProjectToolsCommandResolver.cs
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
Labels: Area-Infrastructure

#30643 Port 30573 to 6.0.3xx
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.TestFramework/EnvironmentInfo.cs
Labels: Area-Infrastructure

#30269 Refactor allowEmptyTelemetry to use Items and support hashing
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAAllowEmptyTelemetry.cs
  src/Tasks/Microsoft.NET.Build.Tasks/AllowEmptyTelemetry.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
Labels: Area-Infrastructure

#30660 Downgrade errors for specifying `--output` for solutions to warnings
  src/Cli/dotnet/commands/dotnet-pack/PackCommandParser.cs
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions-ver/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets
  src/Tests/Microsoft.NET.Pack.Tests/SolutionPackTests.cs
  src/Tests/Microsoft.NET.TestFramework/TestAssetsManager.cs
  src/Tests/dotnet.Tests/OutputPathOptionTests.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
Labels: Servicing-approved

#30672 [GenAPI] Add abstract modifier for an abstract event.
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxRewriter/TypeForwardAttributeCSharpSyntaxRewriter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30572 GenAPI: add workaround for IFieldSymbol.Name that has angle brackets
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30707 Merge preview1
  src/Cli/dotnet/Installer/Windows/MsiPackageCache.cs
  src/Tests/dotnet-new.Tests/Utilities.cs
Labels: Area-Workloads

#30691 Bump Newtonsoft.Json to 13.0.1
  src/Assets/TestProjects/TargetManifests/NewtonsoftFilterProfile.xml
  src/Assets/TestProjects/TargetManifests/NewtonsoftMultipleVersions.xml
  src/Assets/TestProjects/TargetManifests/PrunePackages.xml
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerExtractTests.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExe.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantAutomaticTargetingPackReferences.cs
  src/Tests/dotnet-add-package.Tests/GivenDotnetPackageAdd.cs
  src/Tests/dotnet-list-package.Tests/GivenDotnetListPackage.cs
Labels: Area-Infrastructure

#30712 Update branding to enable a hotfix release
  eng/Versions.props
Labels: Area-Infrastructure

#30580 Enable Dependabot for branch release/7.0.3xx
  .github/dependabot.yml
Labels: Area-Infrastructure

#30594 [GenAPI] Synthesize an internal default constructor for the type with implicit default constructor and the base type without.
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Filtering/AccessibilitySymbolFilter.cs
  src/Microsoft.DotNet.ApiSymbolExtensions/Filtering/CompositeSymbolFilter.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30803 GenAPI: improve error handling, extend test coverage.
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/Tests/Microsoft.DotNet.ApiSymbolExtensions.Tests/SymbolFactory.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30481 Issue 25536 enable -disable-build-servers for pack, clean, test, msbuild
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/Parser.cs
  src/Cli/dotnet/commands/dotnet-build/BuildCommand.cs
  src/Cli/dotnet/commands/dotnet-build/BuildCommandParser.cs
  src/Cli/dotnet/commands/dotnet-clean/CleanCommandParser.cs
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildCommandParser.cs
  src/Cli/dotnet/commands/dotnet-msbuild/Program.cs
  src/Cli/dotnet/commands/dotnet-pack/PackCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/Program.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetCleanInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetMSBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetTestInvocation.cs
Labels: Area-NetSDK

#30615 24004: Add --configfile switch to dotnet list package
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommandParser.cs
  src/Tests/dotnet-list-package.Tests/GivenDotnetListPackage.cs
Labels: Area-Infrastructure

#30612 #28518: Stop generating NETSDK1138 warning when OutputType is Library.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetEolFrameworks.cs
Labels: Area-Infrastructure

#30851 GenAPI: Filter out generic base interfaces if type argument/s are filtered out.
  src/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/INamedTypeSymbolExtension.cs
  src/GenAPI/Microsoft.DotNet.GenAPI/SyntaxGeneratorExtensions.cs
  src/Tests/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#30686 Allow multiple loggers for VSTest command
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/Telemetry/TopLevelCommandNameAndOptionToLog.cs
  src/Cli/dotnet/commands/dotnet-vstest/Program.cs
  src/Tests/dotnet-vstest.Tests/VSTestTests.cs
Labels: Servicing-approved, Area-DotNet Test

#30674 Revert MSBuild to match VS 17.5.0 GA
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Servicing-approved, Area-Infrastructure
