Repository dotnet/sdk, pull requests merged in 2024-08, with the labels that each got.

#42498 Exclude bincore directory in diff test
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/SdkFileDiffExclusions.txt
Labels: Area-Infrastructure, untriaged

#42508 Replace obsolete nuget api in Microsoft.DotNet.PackageValidation
  src/Compatibility/ApiCompat/Microsoft.DotNet.PackageValidation/Package.cs
Labels: untriaged, Area-ApiCompat

#42529 Update SDK diff pipeline schedule
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
Labels: Area-Infrastructure, untriaged

#40344 Add BeforeMicrosoftNETSdkTargets
  src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.targets
Labels: untriaged, Area-NetSDK

#42551 use stage 2 MSBuild version instead of stage 0 for msbuild disjoint c…
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: untriaged, Area-Workloads

#42553 Update branding to 6.0.134
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42555 Update branding to 8.0.109
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42562 Update branding to 8.0.401
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42561 Update branding to 8.0.305
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42507 Update Skip Attribute to Issue Link
  test/crossgen.Tests/crossgen.Tests.cs
  test/dotnet-new.Tests/DotnetNewInstantiateTests.cs
  test/dotnet-new.Tests/DotnetNewListTests.cs
  test/dotnet-new.Tests/DotnetNewSearchTests.cs
  test/dotnet-new.Tests/TemplateDiscoveryTests.cs
Labels: Area-Infrastructure, untriaged

#42554 Update branding to 6.0.426
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42552 Avoid downloading of Microsoft.Net.Sdk.Compilers.Toolset when building in dogfood environment
  eng/dogfood.ps1
Labels: Area-Infrastructure, untriaged

#42585 Fix .net 8.0 test templates
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#42574 Only publish artifacts on success
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#42549 [Wasm] Moves wasm reload logic out of ASP.NET Core and into the SDK
  src/BuiltInTools/BrowserRefresh/BrowserRefreshMiddleware.cs
  test/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserRefreshMiddlewareTest.cs
Labels: untriaged, Area-AspNetCore

#38504 filter references for satellite assembly generation down to just the primary assemblies
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopExe.cs
Labels: untriaged, Area-ILLink

#42607 [Wasm] Fix request filters for blazor.boot.json
  src/BuiltInTools/BrowserRefresh/BrowserRefreshMiddleware.cs
  test/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserRefreshMiddlewareTest.cs
Labels: untriaged, Area-AspNetCore

#42580 Reenable test in GivenThatWeWantToRunILLink.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: untriaged, Area-ILLink

#41790 Plan for addressing torn SDK builds
  documentation/general/torn-sdk.md
Labels: Area-Infrastructure, untriaged

#42583 Add regression test for TrimmerSingleWarn with PublishAot
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: untriaged, Area-ILLink

#42639 [Web SDK] Avoid copying packages.lock.json to the output folder
  src/StaticWebAssetsSdk/Sdk/Sdk.StaticWebAssets.StaticAssets.ProjectSystem.props
Labels: Area-Infrastructure, untriaged

#42494 Handle Test Information from the New Testing Platform
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/CustomEventArgs.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/CommandLineOptionMessages.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/FileArtifactInfo.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/HandshakeInfo.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/Module.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/TestResultMessage.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/TestSessionEvent.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/ObjectFieldIds.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/BaseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/CommandLineOptionMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/FileArtifactInfoSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/HandshakeInfoSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/RegisterSerializers.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestResultMessageSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestSessionEventSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.Help.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
Labels: Area-DotNet Test, untriaged

#42624 Bump branding for 401 hotfix
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42317 [8.0.1xx] No .deps.json for net472 Container task
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
Labels: Servicing-approved, untriaged, Area-Containers

#42277 Update the version of System.Formats.Asn1
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/dotnet.csproj
  src/Layout/tool_fsharp/tool_fsc.csproj
Labels: Area-Infrastructure, untriaged, Branch Lockdown

#42278 Update the version of System.Formats.Asn1
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/dotnet.csproj
  src/Layout/tool_fsharp/tool_fsc.csproj
Labels: Area-Infrastructure, untriaged, Branch Lockdown

#42519 Drop FirstTimeMessageAspNetCertificateLinux
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Cli/Microsoft.DotNet.Configurer/LocalizableStrings.resx
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#42628 Download rsync if using mariner
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#42630 make error for workload info clean Fixes #42581
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
Labels: untriaged, Area-Workloads

#42653 Always print manifest versions in workload list command
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
Labels: untriaged, Area-Workloads

#42566 Fix feature band when assigning a workload to a workload install type
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
Labels: untriaged, Area-Workloads

#42657 Include LA64 in supported ILCompiler RIDs
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure, untriaged

#42536 fix bug in workload history recorder
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadHistoryRecorder.cs
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  test/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/FakeManifestProvider.cs
  test/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  test/dotnet-workload-install.Tests/MockManifestProvider.cs
  test/dotnet-workload-search.Tests/MockWorkloadResolver.cs
Labels: untriaged, Area-Workloads

#42706 Remove auditSources section
  src/SourceBuild/patches/nuget-client/0001-Remove-auditSources-section.patch
Labels: Area-Infrastructure, untriaged

#42703 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42670 Support globbing filter for dotnet test
  src/Cli/dotnet/commands/dotnet-test/ExitCodes.cs
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/TestApplicationActionQueue.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
Labels: Area-DotNet Test, untriaged

#42729 Fix --no-build option bug
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
Labels: Area-DotNet Test, untriaged

#42666 [release/8.0.4xx] Add CompilerVisibleProperty needed for analyzer in Windows SDK projection
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
Labels: Servicing-consider, untriaged, Area-NetSDK

#42664 [release/8.0.1xx] Add CompilerVisibleProperty needed for analyzer in Windows SDK projection
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
Labels: Servicing-consider, untriaged, Area-NetSDK

#42656 [release/6.0.1xx] Add CompilerVisibleProperty needed for analyzer in Windows SDK projection
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
Labels: Servicing-consider, untriaged, Area-NetSDK

#42655 [release/6.0.4xx] Add CompilerVisibleProperty needed for analyzer in Windows SDK projection
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
Labels: Servicing-consider, untriaged, Area-NetSDK

#42700 Merging internal commits for release/8.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/DestinationImageReference.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/RegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/AuthHandshakeMessageHandlerTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: Area-Infrastructure, untriaged

#42698 Merging internal commits for release/8.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/DestinationImageReference.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/RegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/AuthHandshakeMessageHandlerTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: Area-Infrastructure, untriaged

#42546 ResolvePackageReferences: PackageDependenciesDesignTime inherits transitive package DiagnosticLevel
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenThatWeWantToGetDependenciesViaDesignTimeBuild.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
Labels: Area-Infrastructure, untriaged

#42716 Remove 8.0.4xx from build table as it enters servicing phase
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#42740 Remove internet sources from auditSources section
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/RemoveInternetSourcesFromNuGetConfig.cs
  src/SourceBuild/patches/nuget-client/0001-Remove-auditSources-section.patch
Labels: Area-Infrastructure, untriaged

#42744 RC2 Branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42747 Enable CI builds for the public RC2 branch
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#42349 Enable tab-completion for nuget package versions
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs
  test/TestAssets/TestProjects/NugetCompletion/nuget.config
  test/dotnet.Tests/CommandTests/CompleteCommandTests.cs
  test/dotnet.Tests/ParserTests/AddReferenceParserTests.cs
Labels: Area-NuGet, Area-CLI, cli-ux

#42766 Enabled codeflow through 9.0.1xx
  github-merge-flow.jsonc
Labels: Area-Infrastructure, untriaged

#42745 Implicit version update to the live version for RC1
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42806 Update stage 0 to fix cppcli tests
  build/RunTestsOnHelix.cmd
  global.json
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: untriaged, Area-Workloads

#42822 Fix the cppcli tests by upgrading to preview 7 in stage 0
  build/RunTestsOnHelix.cmd
  global.json
  test/Microsoft.NET.Build.Tests/GivenFrameworkReferences.cs
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: Area-Infrastructure, untriaged

#42826 Backport of auditSources fix
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/RemoveInternetSourcesFromNuGetConfig.cs
Labels: Area-Infrastructure, untriaged

#42785 Create Pipe Server per Test Application in dotnet test
  src/Cli/dotnet/commands/dotnet-test/MSBuildConnectionHandler.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.Help.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
Labels: Area-DotNet Test, untriaged

#42829 Re-enable a torn SDK test
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: Area-Infrastructure, untriaged

#42830 Remove locale from diagnostic-ids link
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/SuppressionEngine.cs
Labels: untriaged, Area-ApiCompat

#42843 re-enable the framework hosted compiler test
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: Area-Infrastructure, untriaged

#42875 Enable public builds for all 9.0 branches
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#42863 Handle Execution ID in dotnet test
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/CustomEventArgs.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/FileArtifactInfo.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/HandshakeInfo.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/TestResultMessage.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/TestSessionEvent.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/ObjectFieldIds.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/BaseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/CommandLineOptionMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/FileArtifactInfoSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/HandshakeInfoSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestResultMessageSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestSessionEventSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
Labels: Area-DotNet Test, untriaged

#42800 Backport of auditSources fix
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/RemoveInternetSourcesFromNuGetConfig.cs
Labels: Area-Infrastructure, untriaged

#42401 Exclude Directory.Build.rsp from .gitignore template
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitignore/.gitignore
  test/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitignore-file#-n#item.verified/dotnet-gitignore-file/.gitignore
Labels: Area-Infrastructure, untriaged, needs team triage

#42949 Move WindowsProxy.winmd from allowed-sb-binaries.txt to allowed-vmr-binaries.txt
  src/SourceBuild/content/eng/allowed-sb-binaries.txt
  src/SourceBuild/content/eng/allowed-vmr-binaries.txt
Labels: Area-Infrastructure, untriaged

#42954 Update VMR README.md timeframe around two-way code flow
  src/SourceBuild/content/README.md
Labels: Area-Infrastructure, untriaged

#42883 Update the .NET 9 build table
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#42866 Stop using IReadOnlyList when it's always single
  src/Cli/dotnet/ToolPackage/IToolPackage.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageInstance.cs
  src/Cli/dotnet/commands/dotnet-tool/install/LocalToolsResolverCacheExtensions.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/uninstall/ToolUninstallGlobalOrToolPathCommand.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageDownloaderTests.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageInstallerNugetCacheTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageDownloaderMock.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageMock.cs
  test/dotnet.Tests/CommandTests/ToolListGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolRestoreCommandTests.cs
Labels: untriaged, Area-Tools

#42962 Tool install cleanup
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ParseResultExtension.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ProjectRestorer.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallCommandLowLevelErrorConverter.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalInstaller.cs
  test/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
Labels: untriaged, Area-Tools

#42707 Update OmniSharp version used by source build tests
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/OmniSharpTests.cs
Labels: Area-Infrastructure, untriaged

#43002 Increase license scan file timeout
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/LicenseScanTests.cs
Labels: Area-Infrastructure, untriaged

#43006 Update triggers for SB sdk diff and license scan pipelines
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#43004 fix regression in --property forwarding with an invalid argument
  src/Cli/dotnet/OptionForwardingExtensions.cs
  test/dotnet-watch.Tests/Watch/GlobbingAppTests.cs
  test/dotnet-watch.Tests/Watch/NoDepsAppTests.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetRunInvocation.cs
Labels: Area-Infrastructure, untriaged

#43012 [release/9.0.1xx-rc1] Update SBRP dependency
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#42984 Put binlog directly into the VMR's
  eng/pipelines/templates/jobs/vmr-build.yml
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#42743 Alpha Branding
  eng/Versions.props
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetFormatTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/SdkContentTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/HotReload/CompilationHandlerTests.cs
  test/dotnet-watch.Tests/HotReload/RuntimeProcessLauncherTests.cs
Labels: Area-Infrastructure, untriaged

#43003 Send supported protocol version to the testing platform
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
Labels: Area-DotNet Test, untriaged

#41936 Enable Windows.UI.Xaml profile for Windows SDK projections
  eng/ManualVersions.props
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/CreateWindowsSdkKnownFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
  test/EndToEnd.Tests/GivenWindowsApp.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsDesktopProject.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsRuntimeComponent.cs
  test/Microsoft.NET.Build.Tests/GivenWeWantToRequireWindowsForDesktopApps.cs
  test/Microsoft.NET.Build.Tests/GiventThatWeWantDesignerSupport.cs
  test/TestAssets/TestProjects/UseCswinrt/consolecswinrt.csproj
Labels: Area-Infrastructure, untriaged, Partner request

#43034 Support --no-restore option in dotnet test
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/MSBuildConnectionHandler.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestModulesFilterHandler.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-DotNet Test, untriaged

#43037 Explicity set UseConsolidatedMvcViews to false.
  src/RazorSdk/Tool/DiscoverCommand.cs
  src/RazorSdk/Tool/GenerateCommand.cs
Labels: untriaged, Area-AspNetCore

#42969 Add net10.0 known framework references
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/WebScenarioTests.cs
Labels: Area-Infrastructure, untriaged

#39268 add signature VerifySigning for dotnet tools
  src/Cli/dotnet/CommandFactory/CommandFactoryUsingResolver.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/DefaultCommandResolverPolicy.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/ICommandResolverPolicy.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/LocalToolsCommandResolver.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/PathCommandResolverPolicy.cs
  src/Cli/dotnet/CommandFactory/CommandResolver.cs
  src/Cli/dotnet/DotNetCommandFactory.cs
  src/Cli/dotnet/NugetPackageDownloader/FirstPartyNuGetPackageSigningVerifier.cs
  src/Cli/dotnet/NugetPackageDownloader/LocalizableStrings.resx
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/ToolPackage/IToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageFactory.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs
  test/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageDownloaderTests.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageInstallerNugetCacheTests.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageUninstallerTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageDownloaderMock.cs
  test/dotnet.Tests/CommandObjectTests.cs
  test/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
Labels: Area-Tools

#42606 Permit workload restore to work with new global.json
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  test/dotnet-MsiInstallation.Tests/Framework/VMTestBase.cs
  test/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs
Labels: untriaged, Area-Workloads

#42860 Revert disabling the toolset package in Helix
  build/RunTestsOnHelix.cmd
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: Area-Infrastructure, untriaged

#43052 Merge branch 'release/8.0.4xx' => 'release/9.0.1xx'
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/DestinationImageReference.cs
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.cs.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.de.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.es.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.fr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.it.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ja.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ko.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pl.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.pt-BR.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.ru.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.tr.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hans.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/xlf/Strings.zh-Hant.xlf
  test/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/RegistryTests.cs
  test/Microsoft.NET.Build.Containers.UnitTests/AuthHandshakeMessageHandlerTests.cs
  test/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: Area-Infrastructure, untriaged

#43068 VMR: Exit when error happens in Prepare BuildLogs step
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#43058 Handle --list-tests in dotnet test
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/CustomEventArgs.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/DiscoveredTestMessage.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/ObjectFieldIds.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/CommandLineOptionMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/DiscoveredTestMessageSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/FileArtifactInfoSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/HandshakeInfoSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/ModuleSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/RegisterSerializers.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestResultMessageSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestSessionEventSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/VoidResponseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/MSBuildConnectionHandler.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestModulesFilterHandler.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformOptions.cs
Labels: Area-DotNet Test, untriaged

#42475 Workload set garbage collection
  .gitignore
  src/Cli/dotnet/Installer/Windows/InstallMessageDispatcher.cs
  src/Cli/dotnet/Installer/Windows/InstallRequestMessage.cs
  src/Cli/dotnet/Installer/Windows/InstallRequestType.cs
  src/Cli/dotnet/Installer/Windows/InstallResponseMessage.cs
  src/Cli/dotnet/Installer/Windows/WorkloadSetRecord.cs
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/GlobalJsonWorkloadSetFile.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/IInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.InstallRecords.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerServer.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadGarbageCollector.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.JsonReader.cs
  test/dotnet-MsiInstallation.Tests/Framework/VMTestBase.cs
  test/dotnet-MsiInstallation.Tests/Framework/VMTestSettings.cs
  test/dotnet-MsiInstallation.Tests/README.md
  test/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs
  test/dotnet-MsiInstallation.Tests/dotnet-MsiInstallation.Tests.csproj
  test/dotnet-MsiInstallation.Tests/dotnet-MsiInstallation.Tests.runsettings
  test/dotnet-workload-install.Tests/MockPackWorkloadInstaller.cs
Labels: untriaged, Area-Workloads

#42652 Enable workload search for users to find latest set versions
  src/Cli/dotnet/NugetPackageDownloader/INuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-workload/search/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/search/SearchWorkloadSetsParser.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/search/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-workload-install.Tests/FailingNuGetPackageInstaller.cs
  test/dotnet-workload-install.Tests/MockNuGetPackageInstaller.cs
Labels: untriaged, Document for new feature

#42965 Enable --source for global/path tool install
  src/Cli/dotnet/ToolPackage/PackageLocation.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hant.xlf
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageDownloaderMock.cs
  test/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
Labels: untriaged, Area-Tools

#43038 [Static web assets] Reduce allocations on DefineStaticWebAssetEndpoints
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.ContentTypeMappings.props
  src/StaticWebAssetsSdk/Tasks/Data/ContentTypeMapping.cs
  src/StaticWebAssetsSdk/Tasks/Data/ContentTypeProvider.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssetEndpoints.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ApplyCompressionNegotiationTest.cs
Labels: Area-Infrastructure, untriaged

#43093 Update branding to 8.0.306
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43090 Update branding to 6.0.135
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43091 Update branding to 6.0.427
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#42327 Remove the install of all runtimes 5.0 and below.
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
  test/Microsoft.DotNet.Cli.Utils.Tests/GivenAppThrowingException.cs
  test/Microsoft.NET.Build.Tests/AppHostTests.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithoutTransitiveProjectRefs.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateADepsFileForATool.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAnAssembly.cs
  test/Microsoft.NET.Build.Tests/ReferenceExeTests.cs
  test/Microsoft.NET.Publish.Tests/GivenThatAPublishedDepsJsonShouldContainVersionInformation.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
  test/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProjectWithPackagedShim.cs
  test/TestAssets/NonRestoredTestProjects/AppThrowingException/App/AppThrowingException.csproj
  test/TestAssets/NonRestoredTestProjects/ToolWithRandomPackageName/AppWithDepOnTool/AppWithDepOnTool.csproj
  test/TestAssets/NonRestoredTestProjects/ToolWithRandomPackageName/ToolWithRandomPackageName/ToolWithRandomPackageName.csproj
  test/TestAssets/TestPackages/ToolWithOutputName/ToolWithOutputName.csproj
  test/TestAssets/TestPackages/dotnet-dependency-context-test/dotnet-dependency-context-test.csproj
  test/TestAssets/TestPackages/dotnet-fallbackfoldertool/dotnet-fallbackfoldertool.csproj
  test/TestAssets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  test/TestAssets/TestPackages/dotnet-portable-v1-prefercli/dotnet-portable-v1-prefercli.csproj
  test/TestAssets/TestPackages/dotnet-portable-v1/dotnet-portable-v1.csproj
  test/TestAssets/TestPackages/dotnet-portable/dotnet-portable.csproj
  test/TestAssets/TestPackages/dotnet-prefercliruntime/dotnet-prefercliruntime.csproj
  test/TestAssets/TestProjects/NuGetConfigDependentProject/NuGetConfigDependentProject.csproj
  test/TestAssets/TestProjects/TestAppEchoDotnetRoot/TestAppEchoDotnetRoot.csproj
  test/TestAssets/TestProjects/WatchGlobbingApp/WatchGlobbingApp.csproj
  test/dotnet-run.Tests/GivenDotnetRootEnv.cs
  test/dotnet-store.Tests/GivenDotnetStoresAndPublishesProjects.cs
  test/dotnet.Tests/PackagedCommandTests.cs
Labels: Area-Infrastructure, untriaged

#43094 Update branding to 8.0.403
  eng/Versions.props
  global.json
Labels: Area-Infrastructure, untriaged

#43092 Update branding to 8.0.110
  eng/Versions.props
  global.json
Labels: Area-Infrastructure, untriaged

#43138 [StaticWebAssets] Fix typo in some of the built-in definitions
  src/StaticWebAssetsSdk/Tasks/Data/ContentTypeProvider.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish60Hosted_Works.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_HostedApp_ReferencingNetStandardLibrary_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
Labels: Area-Infrastructure, untriaged

#43141 add additional package references to fix transitive versions
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Layout/tool_msbuild/tool_msbuild.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.csproj
Labels: untriaged, Area-Workloads

#43139 Downgrade implicit versions
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43100 [StaticWebAssets] Improve Up to date check logic
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Design.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.References.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsDesignTimeTest.cs
Labels: Area-Infrastructure, untriaged
