Repository dotnet/sdk, pull requests merged in 2024-10, with the labels that each got.

#43810 Fix WriteSize() in BaseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/BaseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/Models.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
Labels: Area-DotNet Test, untriaged

#43818 [DOCS] missing C++ requirements
  documentation/project-docs/developer-guide.md
Labels: Area-Infrastructure, untriaged

#43730 fix typos
  documentation/project-docs/repro-helix-failure.md
  src/Cli/dotnet/SudoEnvironmentDirectoryOverride.cs
  src/Cli/dotnet/commands/dotnet-publish/PublishCommandParser.cs
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.5_0.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/WebSdk/Publish/Tasks/MsDeploy/CommonUtility.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/CreateParameterFile.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/MSDeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/VsMsdeploy.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/ScopedCssIntegrationTests.cs
Labels: Area-Infrastructure, untriaged

#43822 Update branding to 8.0.111
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43823 Update branding to 8.0.307
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43824 Update branding to 8.0.404
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43699 Add Lock comments for Windows setup
  src/Installer/redist-installer/packaging/windows/LCID/1028/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1029/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1031/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1033/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1036/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1040/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1041/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1042/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1045/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1046/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1049/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/1055/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/2052/bundle.wxl
  src/Installer/redist-installer/packaging/windows/LCID/3082/bundle.wxl
Labels: Area-Infrastructure, untriaged

#43764 Create a dotnet-new template for .gitattributes
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.gitattrbutes
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/dotnetcli.host.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.cs.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.en.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.es.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.fr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.it.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.ja.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.ko.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.pl.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.pt-BR.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.ru.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.tr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.zh-Hans.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/localize/templatestrings.zh-Hant.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitattributes/.template.config/template.json
  test/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.Create_GetAllSuggestions.verified.txt
  test/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/Approvals/TabCompletionTests.RootCommand_GetAllSuggestions.verified.txt
  test/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitattributes-file#-n#item.verified/dotnet-gitattributes-file/.gitattributes
  test/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitattributes-file#-n#item.verified/std-streams/stdout.txt
  test/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Windows.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Windows.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Windows.verified.txt
Labels: Area-Infrastructure, untriaged

#43821 Update branding to 6.0.428
  .vsts-ci.yml
  .vsts-pr.yml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43872 Revert "Clean up error experience when downloading non-tools (#43045)"
  src/Cli/dotnet/NugetPackageDownloader/INuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/LocalizableStrings.resx
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageInstance.cs
  test/dotnet-workload-install.Tests/FailingNuGetPackageInstaller.cs
  test/dotnet-workload-install.Tests/MockNuGetPackageInstaller.cs
Labels: Servicing-approved

#43871 [release/9.0.1xx] Fix writing dotnet test results when terminal logger is off
  src/Cli/dotnet/commands/dotnet-test/Program.cs
Labels: Area-DotNet Test

#43840 Delete old crossgen conditions
  src/Installer/redist-installer/targets/Crossgen.targets
Labels: Area-Infrastructure, untriaged

#43879 Fix for source-build stage 2 compiler errors
  src/SourceBuild/patches/roslyn-analyzers/0001-Update-field-references.patch
  src/SourceBuild/patches/runtime/0001-Update-field-references-in-property-accessors.patch
  src/SourceBuild/patches/vstest/0001-Auto-property-suggestion.patch
Labels: Area-Infrastructure, untriaged

#43885 Update CODEOWNERS
  CODEOWNERS
Labels: Area-Infrastructure, untriaged

#43900 Fix WriteSize() and WriteString() methods
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/BaseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/CommandLineOptionMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/DiscoveredTestMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/FileArtifactMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestResultMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestSessionEventSerializer.cs
Labels: Area-DotNet Test

#43820 Update branding to 6.0.136
  .vsts-ci.yml
  .vsts-pr.yml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43631 Allow reading of OCI Image Indexes to determine RID-specific base image for multi-architecture images
  src/Containers/Microsoft.NET.Build.Containers/ManifestListV2.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net9.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/HttpExtensions.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/SchemaTypes.cs
Labels: untriaged, Area-Containers

#43794 [DO NOT MERGE] Restore ability for users to consume the containers package easily
  src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tasks/Microsoft.NET.Build.Tasks/sdk/Sdk.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: Servicing-approved, untriaged, DO NOT MERGE, Area-Containers

#43877 Fix extension comparison
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  test/Microsoft.Extensions.DotNetDeltaApplier.Tests/Microsoft.Extensions.DotNetDeltaApplier.Tests.csproj
  test/Microsoft.Extensions.DotNetDeltaApplier.Tests/StartupHookTests.cs
  test/TestAssets/TestProjects/WatchAppWithProjectDeps/AppWithDeps/App.WithDeps.csproj
Labels: untriaged, Area-Workloads

#43737 Fix baseline manifest version for RTM branding
  src/Cli/dotnet/CommandFactory/CommandSpec.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/LaunchSettingsApplyResult.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsModel.cs
  src/Cli/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsProvider.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandBase.cs
  src/Cli/dotnet/commands/dotnet-workload/clean/WorkloadCleanCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/config/WorkloadConfigCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.InstallRecords.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchVersionsCommand.cs
  src/Cli/dotnet/dotnet.csproj
  src/Common/WorkloadSetVersion.cs
  src/Installer/core-sdk-tasks/GetWorkloadSetFeatureBand.cs
  src/Installer/core-sdk-tasks/core-sdk-tasks.csproj
  src/Installer/redist-installer/targets/BuildCoreSdkTasks.targets
  src/Installer/redist-installer/targets/BundledManifests.targets
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSet.cs
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  test/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs
  test/dotnet-MsiInstallation.Tests/dotnet-MsiInstallation.Tests.csproj
  test/dotnet-workload-install.Tests/WorkloadSetVersionMappingTests.cs
Labels: untriaged, Area-Workloads

#43551 [Containers] Fix parsing and error reporting of ports that lack port type metadata
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net9.0/PublicAPI.Unshipped.txt
  test/Microsoft.NET.Build.Containers.UnitTests/ContainerHelpersTests.cs
  test/containerize.UnitTests/ParserTests.cs
Labels: Servicing-consider, untriaged, DO NOT MERGE, Area-Containers

#43775 Add missing conditions for illumos
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#43491 AuthHandshakeMessageHandler: sync behavior with other clients.
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  test/Microsoft.NET.Build.Containers.UnitTests/AuthHandshakeMessageHandlerTests.cs
Labels: untriaged, Area-Containers

#43939 Remove vstest 0001-Auto-property-suggestion.patch
  src/SourceBuild/patches/vstest/0001-Auto-property-suggestion.patch
Labels: Area-Infrastructure, untriaged

#43940 Don't fire azdo PR pipelines for simple documentation changes
  .vsts-pr.yml
  eng/pipelines/vmr-build-pr.yml
Labels: Area-Infrastructure, untriaged

#43943 WebSDK: OneDeploy - use 'PLACEHOLDER' value for variable that represent a secret in Unit Tests
  test/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/OneDeploy/OneDeployStatusServiceTests.cs
  test/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/OneDeploy/OneDeployTests.WebJob.cs
  test/Microsoft.NET.Sdk.Publish.Tasks.Tests/Tasks/OneDeploy/OneDeployTests.cs
Labels: Area-Infrastructure, untriaged

#43945 Update dependencies from dotnet/runtime
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#43721 [wasm] Include browser targets if RID is not wasi-wasm
  src/WasmSdk/Sdk/Sdk.targets
Labels: untriaged, Area-WasmSdk

#43723 Introduce a join point for SdkLocator and VSTemplateLocator
  eng/DotNetBuild.props
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
  src/Installer/redist-installer/projects/SdkResolver.csproj
  src/Installer/redist-installer/projects/VSTemplateLocator.csproj
  src/Installer/redist-installer/redist-installer.csproj
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#43974 source-build: ensure stdout for all test projects.
  src/SourceBuild/content/build.sh
Labels: Area-Infrastructure, untriaged

#43989 Remove unused prebuilt baseline
  src/SourceBuild/content/eng/tools/prebuilt-baseline.xml
Labels: Area-Infrastructure, untriaged

#43796 Fix roslyn issues with non-official version builds
  src/SourceBuild/content/repo-projects/roslyn.proj
Labels: untriaged, Area-SourceBuild

#43954 Remove the 6.0 and 8.0 templates
  eng/Versions.props
  src/Installer/redist-installer/targets/BundledTemplates.targets
Labels: Area-Infrastructure, untriaged

#43979 Update SB Prebuilts Tarball
  src/SourceBuild/content/eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43980 Merging internal commits for release/6.0.1xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRid/NativeCode.cs
  src/Assets/TestProjects/AppWithLibraryAndRid/LibraryWithRids/NativeCode.cs
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs
  src/Tests/msbuild.Integration.Tests/GivenDotnetInvokesMSBuild.cs
Labels: Area-Infrastructure, untriaged

#43440 Expand EOL list to include net7 6 months after it goes OOS per design
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetEolFrameworks.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
  src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs
Labels: Servicing-consider, Area-Infrastructure, breaking-change, needs-breaking-change-doc-created, Branch Lockdown

#43981 Merging internal commits for release/6.0.4xx
  .vsts-ci.yml
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  src/Tests/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs
  src/Tests/msbuild.Integration.Tests/GivenDotnetInvokesMSBuild.cs
Labels: Area-Infrastructure, untriaged

#44028 Add nowarn for NU1903
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ReplaceTextInFile.cs
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#43985 Merging internal commits for release/8.0.4xx
  Directory.Packages.props
  NuGet.config
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43983 Merging internal commits for release/8.0.3xx
  Directory.Packages.props
  NuGet.config
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43998 Update aspire to pull in remaining control changes
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44036 Bump OmniSharp Version to latest
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/OmniSharpTests.cs
Labels: Area-Infrastructure, untriaged

#43982 Merging internal commits for release/8.0.1xx
  Directory.Packages.props
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43987 Merge from rc2 to ensure we have internal flow changes
  .vsts-ci.yml
  .vsts-pr.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/dotnet-format/dotnet-format-integration.yml
  eng/dotnet-format/format-verifier.ps1
  eng/pipelines/templates/jobs/sdk-build.yml
  eng/pipelines/templates/jobs/sdk-job-matrix.yml
Labels: Area-Infrastructure, untriaged

#43795 Allow for older Windows SDK projection packages without profiles to build on .NET 9
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Windows.targets
  test/EndToEnd.Tests/GivenWindowsApp.cs
Labels: Servicing-approved, untriaged, Area-WindowsSDK

#43736 [StaticWebAssets] Process endpoint definitions in parallel
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAsset.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpoint.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssetEndpoints.cs
Labels: Area-Infrastructure, untriaged

#44076 Add local package patterns to source-mappings for online feeds
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/UpdateNuGetConfigPackageSourcesMappings.cs
Labels: Area-Infrastructure, untriaged

#44118 Update source-build team references
  eng/DotNetBuild.props
  eng/SourceBuildPrebuiltBaseline.xml
Labels: Area-Infrastructure, untriaged

#43523 Update to the November release downlevel versions
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44109 Add extra properties for test results in dotnet test
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/TestResultMessages.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/ObjectFieldIds.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/BaseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/TestResultMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/Models.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
Labels: Area-DotNet Test

#44149 Move log dirs under repo-projects and rename them
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#44086 Update bootstrap arcade
  src/SourceBuild/content/eng/Version.Details.xml
  src/SourceBuild/content/global.json
Labels: Area-Infrastructure, untriaged

#44156 Fix assembly version diff test for missing file
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/SdkContentTests.cs
Labels: Area-Infrastructure, untriaged

#44158 Execute GetTestsProject msbuild task if IsTestApplication property is true
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.targets/ImportAfter/Microsoft.TestPlatform.ImportAfter.targets
Labels: Area-Infrastructure

#43520 Pass official build id props via /p:
  src/SourceBuild/content/repo-projects/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#44162 .NET 9 RC 2, MAUI baseline manifests
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43995 Switch back to 17.8.3 for the minimum msbuild version
  src/Layout/redist/minimumMSBuildVersion
Labels: Servicing-approved, Area-Infrastructure, untriaged

#44192 Fix SB assembly version test
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/SdkContentTests.cs
Labels: Area-Infrastructure, untriaged

#44194 Create 0001-remove-buildxl-feed.patch
  src/SourceBuild/patches/msbuild/0001-remove-buildxl-feed.patch
Labels: Area-Infrastructure, untriaged

#43889 [release/9.0.1xx] Update Windows SDK projection versions
  eng/ManualVersions.props
Labels: Servicing-approved, untriaged, Area-NetSDK

#44084 Remove a extra item line
  test/Microsoft.NET.TestFramework/SetupTestRoot.targets
Labels: Area-Infrastructure, untriaged, needs-breaking-change-doc-created

#43826 use SpecialFolder.UserProfile in few places
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/CliPathInfo.cs
  src/RazorSdk/Tool/ServerProtocol/ServerConnection.cs
Labels: Area-Infrastructure, untriaged

#44199 msbuild patch to remove BuildXL feed
  src/SourceBuild/patches/msbuild/0001-Remove-BuildXL-feed.patch
Labels: Area-Infrastructure, untriaged

#44211 stabilize branding for release
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43978 Implement support for Aspire
  sdk.sln
  src/BuiltInTools/dotnet-watch/Aspire/AspireServerService.Extensions.cs
  src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs
  src/BuiltInTools/dotnet-watch/Browser/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  test/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.ApiService/Program.cs
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.ApiService/Properties/launchSettings.json
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.ApiService/WatchAspire.ApiService.csproj
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.ApiService/appsettings.Development.json
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.ApiService/appsettings.json
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.AppHost/Program.cs
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.AppHost/Properties/launchSettings.json
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.AppHost/WatchAspire.AppHost.csproj
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.AppHost/appsettings.Development.json
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.AppHost/appsettings.json
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.ServiceDefaults/Extensions.cs
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.ServiceDefaults/WatchAspire.ServiceDefaults.csproj
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/Utilities/AssertEx.cs
  test/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: untriaged, Area-AspNetCore

#44050 fix port error when fallback to http
  src/Containers/Microsoft.NET.Build.Containers/FallbackToHttpMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  test/Microsoft.NET.Build.Containers.UnitTests/FallbackToHttpMessageHandlerTests.cs
Labels: Area-Infrastructure, untriaged, Area-Containers

#44236 Remove backported wpf patch
  src/SourceBuild/patches/wpf/0001-Add-references-needed-by-Formatters.Nrbf.patch
Labels: Area-Infrastructure, untriaged

#44237 [StaticWebAssets] Enable analyzers
  sdk.sln
  src/StaticWebAssetsSdk/.editorconfig
  src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs
  src/StaticWebAssetsSdk/Tasks/ComputeReferenceStaticWebAssetItems.cs
  src/StaticWebAssetsSdk/Tasks/Data/ContentTypeMapping.cs
  src/StaticWebAssetsSdk/Tasks/ScopedCss/ConcatenateCssFiles.cs
  src/StaticWebAssetsSdk/Tasks/ScopedCss/ConcatenateCssFiles50.cs
  src/StaticWebAssetsSdk/Tasks/ScopedCss/RewriteCss.cs
Labels: Area-Infrastructure, untriaged

#43642 Remove WorkloadManifestValidator stub project
  sdk.sln
  source-build.slnf
  src/Resolvers/WorkloadManifestValidator/Program.cs
  src/Resolvers/WorkloadManifestValidator/WorkloadManifestValidator.csproj
  src/Tasks/Microsoft.NET.slnf
Labels: untriaged, Area-Workloads

#44175 Fix "NETSDK1214" referring to existing diagnostic
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenThatWeHaveErrorCodes.cs
Labels: untriaged, Area-NetSDK

#44238 Port sdk-diff-tests and license-scan pipelines to 1ES pipeline templates
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/templates/jobs/sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#44153 Fine tune first join point and VMR support for it
  Directory.Build.targets
  eng/Build.props
  eng/DotNetBuild.props
  eng/Publishing.props
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
  sdk.sln
  src/Installer/redist-installer/projects/SdkResolver.csproj
  src/Installer/redist-installer/projects/VSTemplateLocator/VS.Redist.Common.Net.Core.SDK.VSTemplateLocator.nuspec
  src/Installer/redist-installer/projects/VSTemplateLocator/VSTemplateLocator.csproj
  src/Installer/redist-installer/redist-installer.csproj
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Installer/redist-installer/targets/Versions.targets
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/build.proj
  src/SourceBuild/content/eng/merge-asset-manifests.proj
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/dotnet.proj
  src/SourceBuild/content/repo-projects/sdk.proj
  src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/Microsoft.DotNet.UnifiedBuild.Tests.csproj
Labels: Area-Infrastructure, untriaged

#44281 Fix NetRuntimeBlobVersion
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/online.NuGet.Config
Labels: Area-Infrastructure, untriaged

#44206 Improve error message for missing artifact files
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#44232 [StaticWebAssets] Make sure the quality is serialized as culture invariant
  src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs
Labels: Servicing-approved, Area-Infrastructure

#44207 Add a -sign switch and enable signing for some legs
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/eng/build.ps1
  src/SourceBuild/content/repo-projects/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#44294 [VMR] Install dependencies on macOS
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44289 Enable is shipping package in the installer redist to stabilize branding of the installers
  src/Installer/redist-installer/redist-installer.csproj
Labels: Area-Infrastructure, untriaged

#43607 Change from "sln" to "solution" as primary, and add "sln" as alias
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/Cli/dotnet-new3/Dotnet.cs
  src/Cli/dotnet/ReleasePropertyProjectLocator.cs
  src/Cli/dotnet/Telemetry/TelemetryFilter.cs
  src/Cli/dotnet/commands/dotnet-help/HelpUsageText.cs
  src/Cli/dotnet/commands/dotnet-new/DotnetCommandCallbacks.cs
  src/Cli/dotnet/commands/dotnet-sln/SlnArgumentValidator.cs
  src/Cli/dotnet/commands/dotnet-sln/SlnCommandParser.cs
  test/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
  test/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
  test/dotnet-sln.Tests/GivenDotnetSlnList.cs
  test/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
  test/dotnet-watch.Tests/CommandLineOptionsTests.cs
  test/dotnet.Tests/CommandTests/CompleteCommandTests.cs
  test/dotnet.Tests/TelemetryCommandTest.cs
Labels: Area-Infrastructure, untriaged, Document for new feature, Area-VMR

#44306 Enable signing on all except pgo
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44314 Fix installing dependencies in vmr-build.yml
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44324 Fix source-build legs
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44288 Generate VSMSBuildExtension package in join point
  eng/Build.props
  sdk.sln
  src/Installer/core-sdk-tasks/GenerateMSBuildExtensionsSWR.cs
  src/Installer/redist-installer/packaging/windows/VS.Redist.Common.Net.Core.SDK.MSBuildExtensions.nuspec
  src/Installer/redist-installer/projects/SdkResolver.csproj
  src/Installer/redist-installer/projects/VSMSBuildExtensions/VSMSBuildExtensions.csproj
  src/Installer/redist-installer/redist-installer.csproj
  src/Installer/redist-installer/targets/BuildCoreSdkTasks.targets
  src/Installer/redist-installer/targets/GenerateMSBuildExtensions.targets
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks/Microsoft.NET.Build.Extensions.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-Infrastructure, untriaged

#43143 Update the error for targeting net9 in 17.11
  eng/Versions.props
  src/Layout/redist/minimumMSBuildVersion
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenThatWeHaveErrorCodes.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.SupportedTargetFrameworks.props
  test/Microsoft.NET.Build.Tests/GivenThatWeManifestSupportedFrameworks.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToFloatWarningLevels.cs
  test/Microsoft.NET.Build.Tests/SourceLinkTests.cs
  test/Microsoft.NET.Clean.Tests/GivenThatWeWantToCleanAProject.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: untriaged, breaking-change, needs-breaking-change-doc-created

#44160 [Blazor] Update Microsoft.NET.Sdk.StaticWebAssets.JSModules.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.JSModules.targets
Labels: untriaged, Area-AspNetCore

#44290 Continue printing out redirected process output after we detect browser launch URL.
  src/BuiltInTools/dotnet-watch/Browser/BrowserConnector.cs
  test/dotnet-watch.Tests/Watch/BrowserLaunchTests.cs
Labels: untriaged, Area-AspNetCore

#44357 Remove Maestro feed automation from NuGet.config in main
  NuGet.config
Labels: Area-Infrastructure, untriaged

#44361 Ignore cleanWhileBuilding errors
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#44363 Update net-sdk-supporting-feed
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#44366 make the Details command faster to create and drag in fewer DLLs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/details/DetailsCommand.cs
Labels: Area-Infrastructure, untriaged

#43626 Rename SourceBuildUseMonoRuntime property, which is not SB specific
  eng/DotNetBuild.props
  src/Installer/redist-installer/redist-installer.csproj
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/patches/aspnetcore/0001-Rename-SourceBuildUseMonoRuntime-property-which-is-n.patch
  src/SourceBuild/patches/fsharp/0001-Rename-SourceBuildUseMonoRuntime-property-which-is-n.patch
  src/SourceBuild/patches/runtime/0001-Rename-SourceBuildUseMonoRuntime-property-which-is-n.patch
Labels: Area-Infrastructure, untriaged

#44362 Use non-stable SDK version for SB artifacts
  src/SourceBuild/content/eng/finish-source-only.proj
Labels: Area-Infrastructure, untriaged

#44371 Upgrade Fedora CI legs to 41
  eng/pipelines/templates/variables/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44387 Add Windows DevVersions VMR build leg
  Directory.Build.props
  eng/Versions.props
  eng/pipelines/templates/stages/vmr-build.yml
  src/Installer/redist-installer/projects/VSMSBuildExtensions/VSMSBuildExtensions.csproj
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.DotNet.SdkResolver/Microsoft.DotNet.SdkResolver.csproj
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#44376 Address MD linter issues in VMR README.md
  src/SourceBuild/content/README.md
Labels: Area-Infrastructure, untriaged

#44412 Fix and simplify logic for setting the minimum VS version to display in the installer UI
  eng/Versions.props
  src/Installer/redist-installer/targets/GenerateMSIs.targets
Labels: Servicing-approved

#44313 Aspire fixes
  src/BuiltInTools/AspireService/AspireServerService.cs
  src/BuiltInTools/AspireService/Contracts/IAspireServerEvents.cs
  src/BuiltInTools/AspireService/Helpers/LoggerProvider.cs
  src/BuiltInTools/AspireService/Microsoft.WebTools.AspireService.projitems
  src/BuiltInTools/AspireService/Models/SessionChangeNotification.cs
  src/BuiltInTools/dotnet-watch.slnf
  src/BuiltInTools/dotnet-watch/Aspire/AspireServerService.Extensions.cs
  src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs
  src/BuiltInTools/dotnet-watch/Browser/BrowserConnector.cs
  src/BuiltInTools/dotnet-watch/DotNetWatch.targets
  src/BuiltInTools/dotnet-watch/DotNetWatchContext.cs
  src/BuiltInTools/dotnet-watch/DotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/EvaluationResult.cs
  src/BuiltInTools/dotnet-watch/Filters/BuildEvaluator.cs
  src/BuiltInTools/dotnet-watch/HotReload/IRuntimeProcessLauncher.cs
  src/BuiltInTools/dotnet-watch/HotReload/ProjectLauncher.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/ConsoleReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/IReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/MessagePrefixingReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/Internal/NullReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/OutputCapture.cs
  src/BuiltInTools/dotnet-watch/Internal/OutputLine.cs
  src/BuiltInTools/dotnet-watch/Internal/OutputSink.cs
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/BuiltInTools/dotnet-watch/Internal/ProjectSpecificReporter.cs
  src/BuiltInTools/dotnet-watch/ProcessSpec.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/BuiltInTools/dotnet-watch/Properties/launchSettings.json
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  test/Microsoft.WebTools.AspireService.Tests/AspireServerServiceTests.cs
  test/Microsoft.WebTools.AspireService.Tests/Mocks/IAspireServerEventsMock.cs
  test/TestAssets/TestProjects/ProjectReferences_Graph/E/E.csproj
  test/dotnet-watch.Tests/ConsoleReporterTests.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/HotReload/CompilationHandlerTests.cs
  test/dotnet-watch.Tests/HotReload/RuntimeProcessLauncherTests.cs
  test/dotnet-watch.Tests/MSBuildEvaluationFilterTest.cs
  test/dotnet-watch.Tests/MsBuildFileSetFactoryTest.cs
  test/dotnet-watch.Tests/Utilities/AssertEx.cs
  test/dotnet-watch.Tests/Utilities/MockFileSetFactory.cs
  test/dotnet-watch.Tests/Utilities/MockReporter.cs
  test/dotnet-watch.Tests/Utilities/TestReporter.cs
  test/dotnet-watch.Tests/Utilities/TestRuntimeProcessLauncher.cs
  test/dotnet-watch.Tests/Watch/BrowserLaunchTests.cs
  test/dotnet-watch.Tests/Watch/ProgramTests.cs
  test/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: untriaged, Aspire

#44435 Fix official build. Correctly condition GenerateMSBuildExtensionsLayo…
  src/Installer/redist-installer/projects/VSMSBuildExtensions/VSMSBuildExtensions.csproj
Labels: Area-Infrastructure, untriaged

#44383 Update checksum links to use SHA512
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#43988 Linux: Installing/Updating packages with uppercase versions
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageInstance.cs
  src/Cli/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Mocks/MockPackageResolver.cs
Labels: Area-Infrastructure, untriaged

#44436 Add SDK support for rooting subsets of inputs in a composite image.
  src/Tasks/Microsoft.NET.Build.Tasks/PrepareForReadyToRunCompilation.cs
  src/Tasks/Microsoft.NET.Build.Tasks/RunReadyToRunCompiler.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets
Labels: untriaged, Area-NetSDK

#44008 Expand osx-arm64 test coverage
  .vsts-ci.yml
  .vsts-pr.yml
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishReadyToRun.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-Infrastructure, untriaged

#44441 Add *.props and *.targets to XML section of .editorconfig template
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/EditorConfig/Dotnet/.editorconfig
  test/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#EditorConfig-file#-n#item.verified/EditorConfig-file/.editorconfig
Labels: Area-Infrastructure, untriaged

#44453 Promote Ubuntu_Offline_MsftSdk SB leg to lite configuration
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44437 Re-enable VMR signing
  eng/pipelines/templates/jobs/vmr-build.yml
  src/SourceBuild/patches/runtime/0001-Forward-the-ForceDryRunSigning-variable-down-to-th.patch
Labels: untriaged, Area-VMR

#44309 [FIX] tool-install: Use restore action config options
  eng/dogfood.sh
  src/Cli/dotnet/ToolPackage/IToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalInstaller.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageDownloaderMock.cs
  test/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolInstallLocalCommandTests.cs
Labels: untriaged, Area-Tools

#44480 Run MoveDotNetBuildLogs target even when the repo build fails
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#44481 Fix .NET Framework test helix submission
  test/Microsoft.DotNet.ApiCompat.IntegrationTests/CompatibleFrameworkInPackageValidatorIntegrationTests.cs
  test/Microsoft.DotNet.ApiCompat.IntegrationTests/Task/ValidatePackageTargetIntegrationTests.cs
  test/UnitTests.proj
Labels: Area-Infrastructure, untriaged

#44489 Default sign to false for all SB legs
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44508 Update targeting and runtime packs for net9.0 TFM
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure, untriaged

#43060 Backport: add signature VerifySigning for dotnet tools (#39268)
  src/Cli/dotnet/CommandFactory/CommandFactoryUsingResolver.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/DefaultCommandResolverPolicy.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/ICommandResolverPolicy.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/LocalToolsCommandResolver.cs
  src/Cli/dotnet/CommandFactory/CommandResolution/PathCommandResolverPolicy.cs
  src/Cli/dotnet/CommandFactory/CommandResolver.cs
  src/Cli/dotnet/DotNetCommandFactory.cs
  src/Cli/dotnet/NugetPackageDownloader/FirstPartyNuGetPackageSigningVerifier.cs
  src/Cli/dotnet/NugetPackageDownloader/LocalizableStrings.resx
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/ToolPackage/IToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageFactory.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs
  test/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageDownloaderTests.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageInstallerNugetCacheTests.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageUninstallerTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageDownloaderMock.cs
  test/dotnet.Tests/CommandObjectTests.cs
  test/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUninstallGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
Labels: Area-Tools

#44419 [ADD] dotnet solution migrate
  Directory.Packages.props
  src/Cli/dotnet/commands/dotnet-sln/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-sln/SlnCommandParser.cs
  src/Cli/dotnet/commands/dotnet-sln/migrate/SlnMigrateCommand.cs
  src/Cli/dotnet/commands/dotnet-sln/migrate/SlnMigrateCommandParser.cs
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
  test/dotnet-sln.Tests/GivenDotnetSlnMigrate.cs
Labels: untriaged, Area-CLI

#44469 add `dotnet new sln --format slnx`
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/dotnetcli.host.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.cs.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.de.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.en.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.es.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.fr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.it.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.ja.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.ko.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.pl.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.pt-BR.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.ru.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.tr.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.zh-Hans.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/localize/templatestrings.zh-Hant.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Solution/Solution1.slnx
Labels: Area-Infrastructure, untriaged

#44348 Aspire notifications
  src/BuiltInTools/AspireService/AspireServerService.cs
  src/BuiltInTools/AspireService/Contracts/IAspireServerEvents.cs
  src/BuiltInTools/AspireService/Models/SessionChangeNotification.cs
  src/BuiltInTools/dotnet-watch/Aspire/AspireServerService.Extensions.cs
  src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs
  src/BuiltInTools/dotnet-watch/DotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/IRuntimeProcessLauncher.cs
  src/BuiltInTools/dotnet-watch/HotReload/ProjectLauncher.cs
  src/BuiltInTools/dotnet-watch/HotReload/RunningProject.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/BuiltInTools/dotnet-watch/ProcessLaunchResult.cs
  src/BuiltInTools/dotnet-watch/ProcessSpec.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/BuiltInTools/dotnet-watch/Watcher.cs
  test/Microsoft.WebTools.AspireService.Tests/AspireServerServiceTests.cs
  test/Microsoft.WebTools.AspireService.Tests/Mocks/IAspireServerEventsMock.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/HotReload/RuntimeProcessLauncherTests.cs
  test/dotnet-watch.Tests/Utilities/TestReporter.cs
  test/dotnet-watch.Tests/Utilities/TestRuntimeProcessLauncher.cs
Labels: untriaged, Area-ApiCompat

#44517 [FIX] tool-update: Compare tool versions correctly
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  test/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
Labels: Area-Infrastructure, untriaged

#44548 Remove prep-source-build.sh invocation from vmr devcontainer config
  .devcontainer/vmr/init.sh
  CODEOWNERS
Labels: Area-Infrastructure, untriaged
