Repository dotnet/sdk, pull requests merged in 2024-05, with the labels that each got.

#40580 Temporarily disable the publish of the installer manifest
  eng/Publishing.props
Labels: Area-Infrastructure, untriaged

#40594 Put toolset archive into its own category
  eng/DotNetBuild.props
Labels: Area-Infrastructure, untriaged

#39701 Ingest new props file from installer and use it to auto-include Toolset Compilers package
  global.json
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  test/Microsoft.NET.Build.Tests/DesignTimeBuildTests.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAnAppWithTransitiveNonSdkProjectRefs.cs
  test/Microsoft.NET.Build.Tests/GivenTransitiveFrameworkReferencesAreDisabled.cs
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
  test/Microsoft.NET.Sdk.Razor.Tests/BuildIntegrationTest.cs
  test/dotnet-add-package.Tests/GivenDotnetPackageAdd.cs
Labels: Area-Infrastructure, untriaged

#39666 Prevent the Roslyn compiler package from being used on .NET Core MSBuild
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
Labels: untriaged, Area-NetSDK

#40513 Fix missing files from container images when directory name starts with dot
  src/Containers/Microsoft.NET.Build.Containers/Layer.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/LayerEndToEndTests.cs
Labels: untriaged, Area-Containers

#40512 Fix CONTAINER2005 error from all caps project name
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  test/Microsoft.NET.Build.Containers.UnitTests/ContainerHelpersTests.cs
Labels: untriaged, Area-Containers

#40627 Change the pool for linux shortstack builds
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/variables/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#40630 fix dotnet/msbuild#10004 by making TL quiet on dotnet new's implicit restore
  src/Cli/dotnet/commands/dotnet-new/DotnetCommandCallbacks.cs
Labels: untriaged, Area-Templates

#40616 Update branding to 8.0.301
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40614 Update branding to 8.0.106
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40609 Update branding to 6.0.131
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40610 Update branding to 6.0.423
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39614 Use Ubuntu 24.04 Noble Numbat images by default starting in 8.0.300
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageAndTag.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: Servicing-approved, untriaged, DO NOT MERGE, Area-Containers

#40504 Fix doc typo in Microsoft.NET.Sdk.CSharp.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.targets
Labels: Area-Infrastructure, untriaged

#40542 Add preview VS note to developer guide
  documentation/project-docs/developer-guide.md
Labels: Area-Infrastructure, untriaged

#40719 Update src source build content
  eng/pipelines/templates/jobs/vmr-build.yml
  src/Installer/redist-installer/redist-installer.csproj
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/eng/Version.Details.xml
  src/SourceBuild/content/eng/Versions.props
  src/SourceBuild/content/eng/allowed-vmr-binaries.txt
  src/SourceBuild/content/eng/extract-sdk-archive.proj
  src/SourceBuild/content/eng/finish-source-only.proj
  src/SourceBuild/content/eng/pipelines/templates/jobs/sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/CreateSdkSymbolsLayout.cs
  src/SourceBuild/content/global.json
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/installer.proj
  src/SourceBuild/content/repo-projects/scenario-tests.proj
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseExclusions.txt
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/baselines/ArtifactsSizes/centos.9-x64.txt
  src/SourceBuild/content/test/scenario-tests/Directory.Build.targets
  src/SourceBuild/content/test/scenario-tests/scenario-tests.proj
  src/SourceBuild/content/test/tests.proj
  src/SourceBuild/patches/aspnetcore/0001-InternalServerError.patch
  src/SourceBuild/patches/roslyn/0001-ambiguous-call-site.patch
  src/SourceBuild/patches/scenario-tests/0001-Disable-Aspire-scenario-test.patch
  src/SourceBuild/patches/scenario-tests/0002-Disable-WPF-scenario-test.patch
  src/SourceBuild/patches/vstest/0001-Make-IDE0073-silent.patch
  template_feed/Microsoft.DotNet.Common.ItemTemplates/Microsoft.DotNet.Common.ItemTemplates.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/Microsoft.DotNet.Common.ProjectTemplates.9.0.csproj
Labels: Area-Infrastructure, untriaged

#40723 Update CODEOWNERS
  CODEOWNERS
Labels: Area-Infrastructure, untriaged

#40724 Sync the VMR from sdk into dotnet/dotnet main
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/jobs/vmr-synchronization.yml
  eng/pipelines/vmr-build-pr.yml
  eng/pipelines/vmr-sync-internal.yml
  eng/pipelines/vmr-sync.yml
  src/SourceBuild/content/eng/pipelines/ci.yml
  src/SourceBuild/content/eng/pipelines/pr.yml
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#40746 Restructure test assets and baselines
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/ArtifactsSizeTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/BaselineHelper.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetFormatTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExclusionsHelper.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/LicenseScanTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/PoisonTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/SdkContentTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/ArtifactsSizeTests/centos.9-x64.txt
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/DotNetFormatTests/FormatTestFormatted.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/DotNetFormatTests/FormatTestUnformatted.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseScanTests/LicenseExclusions.txt
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseScanTests/Licenses.runtime.json
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/LicenseScanTests/Licenses.source-build-externals.json
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/PoisonTests/PoisonUsage.txt
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/MsftToSbSdkAssemblyVersions.diff
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/MsftToSbSdkFiles.diff
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/SdkAssemblyVersionDiffExclusions.txt
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/SdkFileDiffExclusions.txt
Labels: Area-Infrastructure, untriaged

#40743 Add musl and arm64 prebuilts
  src/SourceBuild/content/eng/Versions.props
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/UpdateNuGetConfigPackageSourcesMappings.cs
Labels: Area-Infrastructure, untriaged

#40534 Permit installing unlisted Fixes #40440
  src/Cli/dotnet/NugetPackageDownloader/INuGetPackageDownloader.cs
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Tests/dotnet-workload-install.Tests/FailingNuGetPackageInstaller.cs
  src/Tests/dotnet-workload-install.Tests/MockNuGetPackageInstaller.cs
Labels: untriaged, Area-Workloads

#40391 Fix reporter encoding
  src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs
  src/Cli/dotnet/Program.cs
Labels: untriaged, Area-CLI

#40266 More workload set fixes
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hant.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadInstallType.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs
  src/Tests/dotnet-workload-install.Tests/GivenFileBasedWorkloadInstall.cs
  src/Tests/dotnet-workload-install.Tests/WorkloadGarbageCollectionTests.cs
  src/Tests/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: untriaged, Area-Workloads

#40742 Delete src/SourceBuild/content/repo-projects/installer.proj
  src/SourceBuild/content/repo-projects/installer.proj
Labels: Area-Infrastructure, untriaged

#40750 Remove unused files
  src/Installer/Microsoft.Dotnet.Sdk.Internal/Microsoft.Dotnet.Sdk.Internal.csproj
  src/Installer/snaps/arm/dotnet-sdk-3.1/snap/snapcraft.yaml
  src/Installer/snaps/arm/dotnet-sdk-5.0/snap/snapcraft.yaml
  src/Installer/snaps/arm64/dotnet-sdk-5.0/snap/snapcraft.yaml
  src/Installer/snaps/dotnet-sdk-2.1/snap/snapcraft.yaml
  src/Installer/snaps/dotnet-sdk-3.1/snap/snapcraft.yaml
  src/Installer/snaps/dotnet-sdk-5.0/snap/snapcraft.yaml
  src/Installer/snaps/dotnet-sdk-6.0/snap/snapcraft.yaml
  src/Installer/snaps/dotnet-sdk-7.0/snap/snapcraft.yaml
  src/Installer/snaps/dotnet-sdk-8.0/snap/snapcraft.yaml
  src/Installer/snaps/dotnet-sdk/snap/snapcraft.yaml
Labels: Area-Infrastructure, untriaged

#40749 Define run tests timeout for UB/SB CI
  CODEOWNERS
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-VMR

#40744 Cleanup snap artifacts
  CODEOWNERS
Labels: Area-Infrastructure, untriaged

#40773 Rebootstrap source-build/unified-build
  src/SourceBuild/content/eng/Versions.props
  src/SourceBuild/content/global.json
Labels: source-build, Area-VMR

#40745 Use asset manifests exclusively to produce/consume previously source built artifacts
  src/SourceBuild/content/eng/bootstrap/buildBootstrapPreviouslySB.csproj
  src/SourceBuild/content/eng/finish-source-only.proj
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/GetKnownPackagesFromAssetManifests.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/WritePackageVersionsProps.cs
  src/SourceBuild/content/prep-source-build.sh
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: source-build, Area-VMR

#40772 Clean up contents from previously-sb tarball post binary-cleanup
  src/SourceBuild/content/prep-source-build.sh
Labels: source-build, Area-VMR

#40790 Increase test timeout because of slow arm64 legs
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#40815 Delete src/SourceBuild/patches/winforms/0001-Disable-IL2055-for-a-new…
  src/SourceBuild/patches/winforms/0001-Disable-IL2055-for-a-new-callsite.patch
Labels: Area-Infrastructure, untriaged

#40809 [WebAssembly] Remove temporary workarounds
  src/WasmSdk/Sdk/Sdk.targets
  src/WasmSdk/Tasks/PatchWasmPublishStaticWebAsset.cs
  src/WasmSdk/targets/Microsoft.NET.Sdk.WebAssembly.9_0.temp.targets
Labels: Area-Infrastructure, untriaged, Area-WasmSdk

#40777 Fix ignored paths used by binary tool
  src/SourceBuild/content/eng/allowed-sb-binaries.txt
  src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs
Labels: Area-Infrastructure, untriaged

#40779 Stop Running SDK Diff Test Pipeline on Branches Affected by Installer -> SDK merge
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/templates/jobs/sdk-diff-tests.yml
Labels: Area-Infrastructure, untriaged

#40710 Remove the 7.0 template packages
  eng/Versions.props
  src/Installer/redist-installer/targets/BundledTemplates.targets
Labels: Area-Infrastructure, untriaged

#40753 Publish PRs for Source-Build Test Results
  src/SourceBuild/content/.vault-config/vmr-pipeline-secrets.yaml
  src/SourceBuild/content/Directory.Packages.props
  src/SourceBuild/content/eng/Versions.props
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/templates/jobs/sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/templates/steps/create-baseline-update-pr.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
  src/SourceBuild/content/eng/tools/CreateBaselineUpdatePR/CreateBaselineUpdatePR.csproj
  src/SourceBuild/content/eng/tools/CreateBaselineUpdatePR/Log.cs
  src/SourceBuild/content/eng/tools/CreateBaselineUpdatePR/PRCreator.cs
  src/SourceBuild/content/eng/tools/CreateBaselineUpdatePR/Pipelines.cs
  src/SourceBuild/content/eng/tools/CreateBaselineUpdatePR/Program.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/ArtifactsSizeTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/MsftToSbSdkAssemblyVersions.diff
Labels: source-build, Area-VMR

#40705 Show workload update notifications for workloads installed via Visual Studio
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Tests/dotnet-MsiInstallation.Tests/Framework/VMStateTree.cs
  src/Tests/dotnet-MsiInstallation.Tests/Framework/VMTestBase.cs
  src/Tests/dotnet-MsiInstallation.Tests/Framework/VirtualMachine.cs
  src/Tests/dotnet-MsiInstallation.Tests/MsiInstallerTests.cs
  src/Tests/dotnet-MsiInstallation.Tests/VSWorkloadTests.cs
  src/Tests/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs
Labels: untriaged, Area-Workloads

#40844 Fix well known non-checked in infrastructure binaries
  src/SourceBuild/content/eng/allowed-sb-binaries.txt
  src/SourceBuild/content/eng/pipelines/templates/stages/vmr-scan.yml
Labels: Area-Infrastructure, untriaged

#40683 Add bootstrapper validation to clickonce test
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishToClickOnce.cs
Labels: untriaged, Area-ClickOnce

#40787 Fix DisableWorkloadResolverSentinelPath on .NET Framework
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
Labels: untriaged, Area-ILLink

#40849 Port changes from VS where we stopped using custom tracing event arguments class based on BinaryFormatter
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/VsMsdeploy.cs
Labels: untriaged, Area-WebSDK

#40579 Have --no-restore imply -restore:false to override any response file command-line arguments
  src/Cli/dotnet/CommonOptions.cs
  test/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
Labels: untriaged, Area-CLI

#40872 Merging internal commits for release/8.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40876 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildWithGlobalJson.cs
Labels: Area-Infrastructure, untriaged

#40874 Merging internal commits for release/8.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40875 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/restore-toolset.sh
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildWithGlobalJson.cs
Labels: Area-Infrastructure, untriaged

#40886 Add back missing PGO properties after installer->sdk repo consolidation
  Directory.Build.props
Labels: Area-Infrastructure, untriaged

#39840 Add `http` prefix when docker config detect a insecure registry
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
Labels: untriaged, Area-Containers

#40903 [VMR] Publish scenario test results only when available
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#40792 Bug dotnet/sdk-container-builds#559: PublishContainer Appends "dotnet <Target>.dll" to ENTRYPOINT for Self Contained Builds
  src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  test/Microsoft.NET.Build.Containers.IntegrationTests/ProjectInitializer.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: untriaged, Area-Containers

#40919 Return framework toolset dependency
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#40941 Update branding to 7.0.410
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40939 Update branding to 7.0.120
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40940 Update branding to 7.0.317
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40942 Update branding to 8.0.206
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40933 Update Fedora and Ubuntu CI legs to latest
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/variables/vmr-build.yml
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
Labels: Area-Infrastructure, untriaged

#40908 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40909 Merging internal commits for release/7.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40945 Update branding to 6.0.132
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40946 Update branding to 6.0.424
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40948 Update branding to 8.0.302
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40972 Do not leak a TextReader in BuildFPMToolPreReqs.cs
  src/Installer/core-sdk-tasks/BuildFPMToolPreReqs.cs
Labels: Area-Infrastructure, untriaged

#40999 [VMR] Update internal mac pool image label
  eng/pipelines/templates/variables/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#40883 Backport PR to use latest MSBuild on core
  Directory.Packages.props
  eng/Versions.props
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CapturingLogger.cs
Labels: Area-Infrastructure, untriaged

#40638 Flow through generated container image names to callers
  src/Containers/Microsoft.NET.Build.Containers/DestinationImageReference.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net9.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
Labels: Area-Infrastructure, untriaged

#41028 Use exclusions that contain "src/<repo>"
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/LicenseScanTests.cs
Labels: Area-Infrastructure, untriaged

#41029 Skip Test Blocking Codeflow
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: Area-Infrastructure, untriaged

#41055 Simplify scenario-tests test invocation & define dependencies
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/scenario-tests.proj
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj
  src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/Microsoft.DotNet.UnifiedBuild.Tests.csproj
  src/SourceBuild/content/test/scenario-tests/Directory.Build.targets
  src/SourceBuild/content/test/scenario-tests/scenario-tests.proj
  src/SourceBuild/content/test/tests.proj
Labels: untriaged, Area-VMR

#41059 Improve repo artifacts logging
  src/SourceBuild/content/eng/finish-source-only.proj
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/GetKnownPackagesFromAssetManifests.cs
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#41065 Fix Test.binlog creation on Windows and provide better logging
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#40983 Refactor pipelines and add Installer jobs
  .vsts-ci-richnav.yml
  .vsts-ci.yml
  .vsts-pr.yml
  documentation/project-docs/repro-helix-failure.md
  eng/BuildConfiguration/build-configuration.json
  eng/Publishing.props
  eng/Signing.props
  eng/build-pr.yml
  eng/build.yml
  eng/dotnet-format/dotnet-format-integration.yml
  eng/pipelines/templates/jobs/sdk-build.yml
  eng/pipelines/templates/jobs/sdk-job-matrix.yml
  eng/pipelines/templates/variables/sdk-defaults.yml
  eng/template-engine.yml
  src/SourceBuild/content/Directory.Build.targets
  test/UnitTests.proj
Labels: Area-Infrastructure, untriaged

#41070 Revert "Stop Running SDK Diff Test Pipeline on Branches Affected by Installer -> SDK merge"
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/templates/jobs/sdk-diff-tests.yml
Labels: Area-Infrastructure, untriaged

#41090 Fix source-build-sdk-diff-tests pipeline
  eng/pipelines/templates/variables/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#41124 Use SdkTarballPath prop if provided
  src/SourceBuild/content/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#40843 Fix Alpine Target RID
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged, DO NOT MERGE

#41121 Fix empty lines when logging repo artifacts
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#41098 Add the installer's package table to SDK docs
  README.md
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#41130 List `win-x86` under known runtime packs for AOT
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure, untriaged

#40842 FreeBSD: simplify GetOSVersion
  src/Cli/Microsoft.DotNet.Cli.Utils/RuntimeEnvironment.cs
Labels: untriaged, Area-CLI

#36357 Fixes O(2^N) problem in HotReloadProfileReader #36356
  src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfileReader.cs
Labels: untriaged, Area-AspNetCore, Area-Watch

#41132 Update init-source-only.proj
  src/SourceBuild/content/eng/init-source-only.proj
Labels: Area-Infrastructure, untriaged

#40912 Draft of a workload diagnostic document
  documentation/general/workloads/README.md
  documentation/general/workloads/workload-diagnosis.md
Labels: untriaged, Area-Workloads

#41135 Re-enable test that was blocking codeflow
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: untriaged, Area-ILLink

#41200 Fix license scan test pipeline
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/Microsoft.DotNet.SourceBuild.SmokeTests.csproj
Labels: Area-Infrastructure, untriaged

#41190 Use the VMR commit hash for dotnet --info
  src/SourceBuild/content/repo-projects/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#41197 Fix fsharp stage 2 source-build
  src/SourceBuild/patches/fsharp/0001-fix-fsharp-r2r-rid.patch
Labels: source-build, Area-VMR

#41164 Update to may implicit version
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#41195 Fix localization in .NET Workload Information Display
  src/Cli/dotnet/commands/dotnet-workload/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#41082 Update DotNetBuild.props
  eng/DotNetBuild.props
Labels: Area-Infrastructure, untriaged

#41218 Added missing -nativeToolsOnMachine
  restore.cmd
  test.cmd
Labels: Area-Infrastructure, untriaged

#40895 Add warning for PreferNativeArm64
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildASelfContainedApp.cs
Labels: Area-Infrastructure, untriaged

#41212 Fix build-configuration.json upload
  eng/pipelines/templates/jobs/sdk-build.yml
Labels: Area-Infrastructure, untriaged

#41216 Fix CodeOwners file
  CODEOWNERS
Labels: Area-Infrastructure, untriaged

#41255 Fix license scan test results path for trx files
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#41281 Use `src/<repo>/` as regex
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/LicenseScanTests.cs
Labels: Area-Infrastructure, untriaged

#41275 [release/9.0.1xx-preview5] Fix Aspire version to Preview 2 version
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#41298 Delete src/SourceBuild/patches/fsharp/0001-fix-fsharp-r2r-rid.patch
  src/SourceBuild/patches/fsharp/0001-fix-fsharp-r2r-rid.patch
Labels: Area-VMR

#41242 Make SDK produced template nupkgs lowercase
  src/Installer/redist-installer/targets/BundledTemplates.targets
Labels: Area-Infrastructure, untriaged

#41287 Increment branding to allow for razor hotfix
  eng/Versions.props
Labels: Area-Infrastructure, untriaged
