Repository dotnet/sdk, pull requests merged in 2024-12, with the labels that each got.

#44931 Enable tests following the net10 transition
  test/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/HotReload/CompilationHandlerTests.cs
  test/dotnet-watch.Tests/HotReload/RuntimeProcessLauncherTests.cs
Labels: Area-Infrastructure, untriaged

#45225 Add projects, .config, and .nuspec to .editorconfig
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/EditorConfig/Dotnet/.editorconfig
  test/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#EditorConfig-file#-n#item.verified/EditorConfig-file/.editorconfig
Labels: Area-Infrastructure, untriaged

#45226 VMR: move DevVersions jobs to a separate stage
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45005 Disable VMR updates for `dotnet/scenario-tests`
  src/VirtualMonoRepo/source-mappings.json
Labels: Area-Infrastructure, untriaged

#45244 Move VSMSBuildExtensions & VSTemplateLocator under src
  eng/Build.props
  sdk.sln
  src/VSMSBuildExtensions/VSMSBuildExtensions.proj
  src/VSTemplateLocator/VSTemplateLocator.proj
Labels: Area-Infrastructure, untriaged

#45248 Pass the `--ci` argument to `darc` in SDK's CI
  .devcontainer/vmr/init.sh
  eng/pipelines/templates/steps/vmr-pull-updates.yml
  eng/vmr-sync.ps1
  eng/vmr-sync.sh
Labels: Area-Infrastructure, untriaged

#43085 Support publishing of multi-architecture OCI container images
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageIndexGenerator.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultManifestOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/IManifestOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageAndTag.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateImageIndex.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.props
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateImageIndexTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerSupportsArchFact.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerSupportsArchInlineData.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/ImageIndexGeneratorTests.cs
Labels: Servicing-approved, DO NOT MERGE, Area-Containers

#45055 Use WebAssemblyHotReloadCapabilities project property
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyHostedDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/Utilities/ProjectGraphNodeExtensions.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
Labels: untriaged, Area-AspNetCore

#45254 Enable debug logging from middleware in --verbose mode
  src/BuiltInTools/BrowserRefresh/BlazorWasmHotReloadMiddleware.cs
  src/BuiltInTools/BrowserRefresh/BrowserRefreshMiddleware.cs
  src/BuiltInTools/BrowserRefresh/BrowserScriptMiddleware.cs
  src/BuiltInTools/BrowserRefresh/HostingStartup.cs
  src/BuiltInTools/dotnet-watch/Browser/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReload/ProjectLauncher.cs
  test/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BlazorWasmHotReloadMiddlewareTest.cs
  test/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserScriptMiddlewareTest.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
Labels: untriaged, Area-AspNetCore

#45250 Update image to centos-stream9
  src/SourceBuild/content/.devcontainer/devcontainer.json
  src/SourceBuild/content/.devcontainer/prebuilt-sdk/devcontainer.json
Labels: Area-Infrastructure, untriaged

#45281 Log the build output when the repo build is successful but a manifest…
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#45300 Fix templates test failure
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Windows.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Windows.verified.txt
Labels: Area-Infrastructure, untriaged

#45167 Wait for project changes when unchanged project doesn't build
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  test/TestAssets/TestProjects/WatchNoDepsApp/WatchNoDepsApp.csproj
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/Utilities/TestReporter.cs
Labels: Area-Infrastructure, untriaged

#45310 Revert "Disable VMR updates for `dotnet/scenario-tests`"
  src/VirtualMonoRepo/source-mappings.json
Labels: Area-Infrastructure, untriaged

#45290 [dotnet-format] Include the .NET Framework buildhost executable in the SDK.
  src/Layout/redist/targets/GenerateLayout.targets
Labels: untriaged, Area-Format

#45022 Use temp directory as TestExecutionDirectory in RunTestsOnHelix.sh
  build/RunTestsOnHelix.sh
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/CreateMSDeployScript.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/CreateManifestFile.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/CreateParameterFile.cs
  test/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  test/Microsoft.DotNet.MSBuildSdkResolver.Tests/GivenAnEnvironmentForResolution.cs
  test/dotnet-workload-install.Tests/GivenFileBasedWorkloadInstall.cs
  test/dotnet-workload-install.Tests/GivenWorkloadManifestUpdater.cs
  test/dotnet-workload-install.Tests/WorkloadGarbageCollectionTests.cs
  test/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: Area-Infrastructure, untriaged

#45295 Fix warning level calculation for .NET 10
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToFloatWarningLevels.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToUseBinaryFormatter.cs
Labels: Area-Infrastructure, untriaged

#45291 [backport][dotnet-format] Include the .NET Framework buildhost executable in the SDK.
  src/Layout/redist/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#45047 Use arcade infra for DEB and RPM build
  .vsts-ci.yml
  eng/Versions.props
  sdk.sln
  source-build.slnf
  src/Installer/pkg/dotnet-sdk.proj
  src/Installer/redist-installer/redist-installer.csproj
  src/Installer/redist-installer/targets/GenerateDebs.targets
  src/Installer/redist-installer/targets/GenerateInstallers.targets
  src/Installer/redist-installer/targets/GenerateRPMs.targets
  src/Installer/redist-installer/targets/LinuxNativeInstallerDependencyVersions.targets
  src/Tasks/sdk-tasks/BuildFPMToolPreReqs.cs
  src/Tasks/sdk-tasks/DotNetDebTool.cs
  src/Tasks/sdk-tasks/sdk-tasks.InTree.targets
Labels: Area-Infrastructure, untriaged

#44570 sln-add: Support for slnx
  src/Cli/dotnet/commands/dotnet-sln/add/Program.cs
  test/TestAssets/TestProjects/InvalidSolution/InvalidSolution.slnx
  test/TestAssets/TestProjects/InvalidSolution/Sln/InvalidSolution.sln
  test/TestAssets/TestProjects/InvalidSolution/Slnx/InvalidSolution.slnx
  test/TestAssets/TestProjects/SlnFileWithNoProjectReferencesAndUnknownProjectType/App.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingLibProj.sln
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingLibProj.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingLibProjToEmptySln.sln
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingLibProjToEmptySln.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingNestedProj.sln
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingNestedProj.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingProjectWithInRootOption.sln
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingProjectWithInRootOption.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingProjectWithSolutionFolderOption.sln
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingProjectWithSolutionFolderOption.slnx
  test/TestAssets/TestProjects/TestAppWithEmptySln/App.slnx
  test/TestAssets/TestProjects/TestAppWithMultipleSlnFiles/App.slnx
  test/TestAssets/TestProjects/TestAppWithMultipleSlnFiles/App2.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAnd472CsprojFiles/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndCaseSensitiveSolutionFolders/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndCsprojFiles/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndCsprojInSubDir/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndCsprojInSubDirVS/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndCsprojProjectGuidFiles/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndExistingCsprojReferences/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndExistingCsprojReferencesWithEscapedDirSep/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithAdditionalConfigs.sln
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithAdditionalConfigs.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithMatchingConfigs.sln
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithMatchingConfigs.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithoutMatchingConfigs.sln
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithoutMatchingConfigs.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndSolutionFolders/App.slnx
  test/TestAssets/TestProjects/TestAppsWithSlnAndMultitargetedProjects/TestAppsWithSlnAndMultitargetedProjects.slnx
  test/dotnet-restore.Tests/GivenThatIWantToRestoreApp.cs
  test/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
  test/dotnet-sln.Tests/GivenDotnetSlnList.cs
  test/dotnet-sln.Tests/GivenDotnetSlnMigrate.cs
  test/dotnet-sln.Tests/dotnet-sln.Tests.csproj
Labels: Review for breaking changes, breaking-change, Area-CLI, Area-VS, needs-breaking-change-doc-created

#45360 Remove Ubuntu non dev versions leg from validation stage
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45346 Build the .NET SDK installer using the ASP.NET Core Runtime MSI instead of the wixlib
  src/Installer/redist-installer/packaging/windows/bundle.wxs
  src/Installer/redist-installer/packaging/windows/generatebundle.ps1
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/Installer/redist-installer/targets/GenerateMSIs.targets
Labels: Area-Infrastructure, untriaged

#45361 Remove unnecessary architecture parameter in vmr-build.yml
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45276 VMR: Temporarily disable tests on AzureLinux_x64_Cross_Mono
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45323 Fix BuildPass>1 artifacts and asset manifest content
  eng/pipelines/templates/jobs/vmr-build.yml
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/Directory.Build.targets
  src/SourceBuild/content/build.proj
  src/SourceBuild/content/eng/extract-sdk-archive.proj
  src/SourceBuild/content/eng/finish-source-only.proj
  src/SourceBuild/content/eng/init-cross-build.proj
  src/SourceBuild/content/eng/init-poison.proj
  src/SourceBuild/content/eng/join-verticals.proj
  src/SourceBuild/content/eng/merge-asset-manifests.proj
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/GetKnownArtifactsFromAssetManifests.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/GetKnownPackagesFromAssetManifests.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/MergeAssetManifests.cs
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#45159 Fix incorrect apphost being used when publishing for self-contained single-file with `NoBuild=true`
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishASingleFileApp.cs
Labels: Approved to merge, untriaged, Area-NetSDK

#45356 Check how often each command resolver is used
  src/Cli/dotnet/CommandFactory/CommandResolution/CompositeCommandResolver.cs
Labels: Area-Infrastructure, untriaged

#45144 Better search versions error experience
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchVersionsCommandParser.cs
  src/Common/WorkloadSetVersion.cs
  test/dotnet-workload-search.Tests/GivenDotnetWorkloadSearch.cs
Labels: untriaged, Area-Workloads

#45259 Don't publish PrivateAssets Fixes #39400
  src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopLibrary.cs
  test/Microsoft.NET.Sdk.Razor.Tests/MvcBuildIntegrationTestLegacy.cs
Labels: untriaged, Area-NetSDK

#45263 Avoid workload gc failure due to 4-part version in ReleaseVersion used to find a max
  src/Cli/dotnet/commands/dotnet-workload/WorkloadUtilities.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadGarbageCollector.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
Labels: untriaged, Area-Workloads

#45286 Force overwriting packs in FileBasedInstaller when repairing Fixes #31282
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
Labels: untriaged, Area-Workloads

#45366 sln-add: Only add guid on slnv12 files
  src/Cli/dotnet/commands/dotnet-sln/add/Program.cs
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingLibProj.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingLibProjToEmptySln.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingNestedProj.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingProjectWithInRootOption.slnx
  test/TestAssets/TestProjects/SolutionFilesTemplates/ExpectedSlnFileAfterAddingProjectWithSolutionFolderOption.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithAdditionalConfigs.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithMatchingConfigs.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndProjectConfigs/Results/ExpectedSlnFileAfterAddingProjectWithoutMatchingConfigs.slnx
Labels: untriaged

#45227 Add .json to editorconfig
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/EditorConfig/Dotnet/.editorconfig
  test/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#EditorConfig-file#-n#item.verified/EditorConfig-file/.editorconfig
Labels: Area-Infrastructure, untriaged

#45322 Add mstest dependency
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#45391 Stop generating VMR's component list
  eng/pipelines/templates/steps/vmr-pull-updates.yml
  eng/vmr-sync.ps1
  eng/vmr-sync.sh
  src/VirtualMonoRepo/Component.template.md
  src/VirtualMonoRepo/InitializeVMR.proj
  src/VirtualMonoRepo/Tasks/VirtualMonoRepo_Initialize.cs
Labels: Area-Infrastructure, untriaged

#45282 fix(cli): dotnet help new link opening
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/ICommandDocument.cs
  src/Cli/Microsoft.TemplateEngine.Cli/Commands/NewCommand.cs
  src/Cli/dotnet/DocumentedCommand.cs
  src/Cli/dotnet/commands/dotnet-help/HelpCommand.cs
Labels: Area-Infrastructure, untriaged

#45393 Extend build server shutdown tracing
  src/Cli/Microsoft.DotNet.Cli.Utils/Command.cs
  src/Cli/dotnet/BuildServer/VBCSCompilerServer.cs
Labels: untriaged, Area-CLI

#44958 format: stop checking for dotnet cli version
  src/BuiltInTools/dotnet-format/Commands/FormatCommandCommon.cs
  src/BuiltInTools/dotnet-format/Resources.resx
  src/BuiltInTools/dotnet-format/xlf/Resources.cs.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.de.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.es.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.fr.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.it.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.ja.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.ko.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.pl.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.pt-BR.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.ru.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.tr.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.zh-Hans.xlf
  src/BuiltInTools/dotnet-format/xlf/Resources.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#45343 Restore detailed test logging to console output
  test/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  test/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  test/dotnet-new.Tests/DotnetNewListTests.Approval.cs
Labels: Area-Infrastructure, untriaged

#45411 [main] Unlock build failed due to enabling nullable
  src/Cli/Microsoft.DotNet.Cli.Utils/Command.cs
Labels: Area-Infrastructure, untriaged

#44863 Use library-packs also when RestoreAdditionalProjectSources is explicitly set.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.NuGetOfflineCache.targets
Labels: Area-Infrastructure, untriaged

#44969 Run all steps in a container
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/variables/vmr-build.yml
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/eng/pipelines/ci.yml
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#45407 Fix manifest artifacts reading
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/GetKnownArtifactsFromAssetManifests.cs
Labels: Area-Infrastructure, untriaged

#45412 [WASM] Clean up of `HybridGlobalization` in tests
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BootJsonData.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
Labels: Area-Infrastructure, untriaged, arch-wasm

#45428 Use Build.ArtifactStagingDirectory now that we run with native contai…
  eng/pipelines/templates/jobs/vmr-build.yml
  src/SourceBuild/content/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#45096 Refresh browser for all transitively referencing projects
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/ScopedCssFileHandler.cs
  src/BuiltInTools/dotnet-watch/Utilities/ProjectGraphNodeExtensions.cs
Labels: Servicing-approved, untriaged, Area-AspNetCore, Area-Watch

#45443 Remove the LLVMJIT jobs from the VMR
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45317 Use legacy WASM APIs when newer ones are not available
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: untriaged, Area-AspNetCore

#45298 Fixes middleware invocation arguments use by legacy apply update code path
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-Infrastructure, untriaged

#45444 Make sure that sdk manifest has RepoOrigin attribute
  eng/Publishing.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#45437 Enable ASP.NET Core installers on Linux in the VMR
  src/SourceBuild/content/repo-projects/aspnetcore.proj
Labels: untriaged, Area-VMR

#44956 Don't download Windows SDK ref pack for C++ projects
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProject.cs
Labels: untriaged, Area-NetSDK

#45415 Upgrade latest Alpine to 3.21 for VMR builds
  eng/pipelines/templates/variables/vmr-build.yml
  src/SourceBuild/content/eng/pipelines/ci.yml
Labels: Area-Infrastructure, untriaged

#45364 Expand MSBuildSdkResolver
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Constants.cs
  test/Microsoft.DotNet.MSBuildSdkResolver.Tests/GivenAnMSBuildSdkResolver.cs
Labels: untriaged, Area-SdkResolvers

#45420 Fix a set of test issues caused by an old blob feed and try to fix up the nullable change we rushed in
  Directory.Build.targets
  src/Cli/Microsoft.DotNet.Cli.Utils/Command.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeHaveAPackageReferenceWithAliases.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateADepsFileForATool.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToIgnoreObsoleteDotNetCliToolPackages.cs
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreDotNetCliToolReference.cs
  test/Microsoft.NET.TestFramework/NuGetConfigWriter.cs
  test/TestAssets/TestProjects/UnmanagedStore/UnmanagedStore.csproj
Labels: Area-Infrastructure, untriaged

#45097 Fix `Change failed to apply (error code: ...)` intermittent failures
  src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs
  test/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
Labels: Servicing-approved, untriaged, Area-Watch

#45460 Enable dotnet/sdk debs and rpms in the VMR
  documentation/package-table.md
  src/Installer/pkg/dotnet-sdk.proj
  src/Installer/redist-installer/targets/Badge.targets
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/Installer/redist-installer/targets/GetRuntimeInformation.targets
  src/Installer/redist-installer/targets/SetBuildDefaults.targets
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: untriaged, Area-VMR

#45482 Remove references to the component list in VMR's readme
  src/SourceBuild/content/README.md
Labels: Area-Infrastructure, untriaged

#44855 Enable Signing in Repos that Override Build Actions
  src/SourceBuild/content/repo-projects/aspnetcore.proj
  src/SourceBuild/content/repo-projects/fsharp.proj
  src/SourceBuild/content/repo-projects/roslyn.proj
Labels: Area-Infrastructure, untriaged

#45479 [VMR] Use CopyFiles@2 task instead of manual copying
  eng/pipelines/templates/jobs/vmr-build.yml
  src/SourceBuild/content/repo-projects/scenario-tests.proj
Labels: Area-Infrastructure, untriaged

#45489 Update owner of artifacts staging directory for offline builds
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45490 Use variables for container values
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/variables/vmr-build.yml
  src/SourceBuild/content/eng/pipelines/ci.yml
Labels: Area-Infrastructure, untriaged

#45332 Use dotnet exec to run test app in CheckTargetFrameworkDisplayName
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
Labels: Area-Infrastructure, untriaged

#45511 [VMR] Disable codeql on arm64 mac builds
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45480 Fix missing test binlog
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/scenario-tests.proj
Labels: Area-Infrastructure, untriaged

#45528 [VMR] Actually disable codeql on arm64 Mac
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45151 Add hook for importing .props file after .NET SDK props
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
Labels: untriaged, Area-ILLink, consider-for-documentation

#45532 Use Agent.TempDirectory when building from archive in source-build
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45515 Change Aspire RunSessionRequest definition
  src/BuiltInTools/AspireService/Models/RunSessionRequest.cs
  test/Microsoft.WebTools.AspireService.Tests/AspireServerServiceTests.cs
  test/Microsoft.WebTools.AspireService.Tests/Mocks/IAspireServerEventsMock.cs
Labels: Area-Infrastructure, untriaged

#45540 SDK should only depend on netstandard-targetingpack-2.1 on x64
  src/Installer/pkg/dotnet-sdk.proj
Labels: Area-Infrastructure, untriaged

#45410 Do not automatically add nuget.org as a package source when it is absent from nuget.config Fixes #44312
  src/Cli/Microsoft.DotNet.Cli.Utils/PathUtility.cs
  src/Cli/Microsoft.TemplateEngine.Cli/NuGet/NugetApiManager.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/dotnet/commands/dotnet-tool/search/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/search/ToolSearchCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/search/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-new.Tests/DotnetNewDetailsTest.Approval.cs
Labels: untriaged, Area-Templates

#45554 Hardcode manifest name when building source-only
  eng/pipelines/templates/jobs/vmr-build.yml
  src/SourceBuild/content/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#45562 Fix identity of MSTest item templates
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/MSTest-CSharp-TestClass/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/MSTest-FSharp-TestClass/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/MSTest-VisualBasic-TestClass/.template.config/template.json
Labels: untriaged, Area-Common templates

#45462 Setup binskim globbing to artifacts/bin w/ workaround
  .config/tsaoptions.json
  .vsts-ci.yml
  eng/pipelines/templates/jobs/sdk-build.yml
  eng/sdl-tsa-vars.config
Labels: Area-Infrastructure, untriaged

#45553 Don't publish assets with Vertical visibility as part of the merged manifest for a vertical.
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/GetKnownArtifactsFromAssetManifests.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/JoinVerticals.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/MergeAssetManifests.cs
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#45278 Bump MSTest templates to 3.6.4
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/content/MSTest-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/content/MSTest-FSharp/Company.TestProject1.fsproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/content/MSTest-VisualBasic/Company.TestProject1.vbproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/content/Playwright-MSTest-CSharp/Company.TestProject1.csproj
Labels: Area-Infrastructure, Area-DotNet Test

#45495 [dotnet-watch] Make pipe reads and writes fully async
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/BuiltInTools/HotReloadAgent/AgentMessageSeverity.cs
  src/BuiltInTools/HotReloadAgent/Microsoft.DotNet.HotReload.Agent.Package.csproj
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/DeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/NamedPipeContract.cs
  test/Microsoft.Extensions.DotNetDeltaApplier.Tests/StaticAssetPayloadTests.cs
  test/Microsoft.Extensions.DotNetDeltaApplier.Tests/StreamExtensionsTests.cs
  test/Microsoft.Extensions.DotNetDeltaApplier.Tests/UpdatePayloadTests.cs
  test/dotnet-watch.Tests/HotReload/UpdatePayloadTests.cs
Labels: Area-Infrastructure, untriaged

#44461 Add support for using Digest for base image
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net10.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/SourceImageReference.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ParseContainerProperties.cs
  src/Containers/containerize/ContainerizeCommand.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  test/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  test/Microsoft.NET.Build.Containers.UnitTests/ContainerHelpersTests.cs
Labels: untriaged, Area-Containers

#45312 Support Interactive without setting verbosity explicitly in dotnet tool restore Fixes #22987
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/restore/ToolRestoreCommand.cs
Labels: untriaged, Area-Tools

#45596 [VMR] Remove setting .gdnbaselines file
  src/SourceBuild/content/eng/pipelines/ci.yml
Labels: Area-Infrastructure, untriaged

#45494 Added 🟣 to step names
  eng/dotnet-format/dotnet-format-integration.yml
  eng/pipelines/templates/jobs/sdk-build.yml
Labels: Area-Infrastructure, untriaged

#45602 Use project name in project path map to account for multi-targeting
  src/BuiltInTools/dotnet-watch/HotReload/IncrementalMSBuildWorkspace.cs
  test/TestAssets/TestProjects/WatchAppWithProjectDeps/Dependency/Dependency.csproj
Labels: Area-Infrastructure, untriaged

#45621 [release/9.0.1xx] dotnetcli.azureedge.net -> builds.dotnet.microsoft.com
  eng/pipelines/templates/jobs/vmr-build.yml
  src/SourceBuild/content/prep-source-build.sh
Labels: Area-Infrastructure, untriaged

#45635 Revert "[main] Update dependencies from dotnet/source-build-reference-packages"
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#45620 dotnetcli.azureedge.net -> builds.dotnet.microsoft.com
  eng/pipelines/templates/jobs/vmr-build.yml
  src/SourceBuild/content/prep-source-build.sh
Labels: Area-Infrastructure, untriaged

#45566 Look up the target OS for crossgen2 using the full target RID
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: untriaged, Area-ReadyToRun
