Repository dotnet/sdk, pull requests merged in 2024-04, with the labels that each got.

#39901 Fix loading of rollback installed workloads in Visual Studio
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
Labels: Servicing-consider, Area-Infrastructure

#39947 Update branding to 6.0.130
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39953 Update branding to 8.0.205
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39950 Update branding to 7.0.316
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39618 Rewrite dotnet watch command line parsing
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/BuiltInTools/dotnet-watch/DotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/EnvironmentOptions.cs
  src/BuiltInTools/dotnet-watch/EnvironmentVariablesBuilder.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/BuiltInTools/dotnet-watch/LaunchSettingsProfile.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/BuiltInTools/dotnet-watch/Resources.resx
  src/BuiltInTools/dotnet-watch/xlf/Resources.cs.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.de.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.es.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.fr.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.it.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ja.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ko.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.pl.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.pt-BR.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ru.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.tr.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.zh-Hans.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.zh-Hant.xlf
  test/dotnet-watch.Tests/CommandLineOptionsTests.cs
  test/dotnet-watch.Tests/Utilities/AssertEx.cs
  test/dotnet-watch.Tests/Utilities/TestOptions.cs
  test/dotnet-watch.Tests/Watch/ProgramTests.cs
  test/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: untriaged, Area-Watch

#39949 Update branding to 7.0.119
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39951 Update branding to 7.0.409
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39952 Update branding to 8.0.105
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39591 Add nuget.localization to codeflow
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39271 Don't use the xunit return code when running in helix only
  src/Tests/Common/Program.cs
Labels: Area-Infrastructure, untriaged

#39613 Use built-in SourceRevisionId instead of git rev-parse HEAD
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/GetRuntimeInformation.targets
  src/Layout/redist/targets/Version.targets
Labels: Area-Infrastructure, untriaged

#39975 [release/7.0.4xx] Temporarily disabling Build_Components_WithDesktopMSBuild_Works test
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponentsIntegrationTest.cs
Labels: untriaged, Area-AspNetCore

#39896 Update the compiling version to the latest MSBuild from that band to fix scanner issues
  NuGet.config
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39992 Disable CA2022 errors
  src/RazorSdk/Tool/Client.cs
  src/RazorSdk/Tool/ConnectionHost.cs
Labels: Area-Infrastructure, untriaged

#39641 Update the msbuild version to a version that includes additional fixes
  NuGet.config
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39979 [release/8.0.1xx] Temporarily disabling Build_Components_WithDesktopMSBuild_Works test
  src/Tests/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponentsIntegrationTest.cs
Labels: Area-Infrastructure, untriaged

#40078 Merging internal commits for release/8.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40079 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40080 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40082 Merging internal commits for release/7.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40083 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40077 Merging internal commits for release/8.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39645 Update EOL versions
  .vsts-ci.yml
  .vsts-pr.yml
Labels: Area-Infrastructure, untriaged

#39402 Respect the profile attribute on runtime packs
  global.json
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveRuntimePackAssets.cs
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
  test/Microsoft.NET.Build.Tests/GivenFrameworkReferences.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishTrimmedWindowsFormsAndWPFApps.cs
  test/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewCompleteTests.CanDoTabCompletion.Windows.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Windows.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Windows.verified.txt
Labels: Area-Infrastructure, untriaged

#40028 Set dotnet-watch timeout based on XUnitWorkItemTimeout
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  test/Common/Program.UnitTests.cs
  test/Common/Program.cs
  test/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
  test/Microsoft.NET.TestFramework/TestCommandLine.cs
  test/Microsoft.NET.TestFramework/TestContext.cs
  test/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
Labels: Area-Infrastructure, untriaged

#39827 Update the help text for dotnet tool run and dotnet tool local install
  src/Cli/dotnet/commands/dotnet-tool/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/run/xlf/LocalizableStrings.zh-Hant.xlf
Labels: untriaged, Area-Tools

#40139 Add nuget-team as CODEOWNER for dotnet-list-package
  CODEOWNERS
Labels: Area-Infrastructure, untriaged

#39573 Use System.Text.Json in Netfx build of MSBuildSdkResolver
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.SystemTextJson.cs
Labels: untriaged, Area-Workloads

#39956 Update warning message for containers package detection when building SDK-containerizable project types
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: Servicing-consider, untriaged, DO NOT MERGE, Area-Containers

#39942 Containers 8.0.3xx Package Release Notes
  src/Containers/docs/ReleaseNotes/v8.0.200.md
  src/Containers/docs/ReleaseNotes/v8.0.300.md
  src/Containers/packaging/package.csproj
Labels: Servicing-approved, untriaged, Area-Containers

#40169 Identify loongarch64 as valid arch
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateBundle.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs
Labels: untriaged, Area-ReadyToRun

#40186 Fix PR builds ran manually or against release branches
  .vsts-ci.yml
  .vsts-pr.yml
  eng/build-pr.yml
  eng/build.yml
Labels: Area-Infrastructure, untriaged

#39644 Consider global.json for workload* commands
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadGarbageCollector.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/install/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hant.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.GlobalJsonReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/ManifestTests.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
  src/Tests/dotnet-workload-install.Tests/GivenDotnetWorkloadInstall.cs
Labels: Servicing-approved, Area-Workloads

#40081 Merging internal commits for release/7.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40262 Only pack as tool shim in VMR builds when signing is possible
  src/BuiltInTools/dotnet-format/dotnet-format.csproj
Labels: Area-Infrastructure, untriaged

#40148 Request silent restore for all separate restore steps
  src/Cli/dotnet/commands/RestoringCommand.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
Labels: Area-Infrastructure, untriaged

#40120 Correct arguments passed to the subcommand in presence of --
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  test/dotnet-watch.Tests/CommandLineOptionsTests.cs
  test/dotnet-watch.Tests/Watch/DotNetWatcherTests.cs
  test/dotnet-watch.Tests/Watch/NoDepsAppTests.cs
  test/dotnet-watch.Tests/Watch/ProgramTests.cs
Labels: Area-Infrastructure, untriaged, Area-Watch

#38047 [release/7.0.4xx] Manual backport of #37832 servicing fix
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ParseContainerProperties.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/MSBuildCollection.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ParseContainerPropertiesTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: Servicing-approved, Area-Containers

#40290 Stabilize branding for the SDK 8.0.300
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40230 Add APICompat support for checking generic constraints
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/DiagnosticIds.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotChangeGenericConstraints.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/RuleFactory.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  test/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotChangeGenericConstraintsTests.cs
Labels: Area-ApiCompat

#40302 Fix dotnet fsi does not support DOTNET_CLI_UI_LANGUAGE
  src/Cli/Microsoft.DotNet.Cli.Utils/UILanguageOverride.cs
  src/Cli/dotnet/commands/dotnet-fsi/FsiForwardingApp.cs
Labels: untriaged, Area-CLI

#40321 [Blazor] Correct ETag and Content-Length computation, add more precision to quality definition
  src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssetEndpoints.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetEndpointsIntegrationTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ApplyCompressionNegotiationTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DefineStaticWebAssetEndpointsTest.cs
Labels: untriaged, Area-AspNetCore

#40138 4xx branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40147 Update loc branch target
  eng/build-pr.yml
  eng/build.yml
Labels: Area-Infrastructure, untriaged

#40145 Update target branch
  .vsts-ci.yml
  .vsts-pr.yml
Labels: Area-Infrastructure, untriaged

#40095 Fixed a reference to the supported .editorconfig options.
  src/BuiltInTools/dotnet-format/README.md
Labels: untriaged

#39689 [Wasm] Remove workarounds
  src/WasmSdk/Sdk/Sdk.targets
  src/WasmSdk/targets/Microsoft.NET.Sdk.WebAssembly.6_0.temp.targets
  src/WasmSdk/targets/Microsoft.NET.Sdk.WebAssembly.9_0.temp.targets
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorLegacyIntegrationTest60.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/VanillaWasmTests.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
Labels: Area-Infrastructure, untriaged

#40372 Mark UseWindowsThreadPool as feature switch
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: untriaged, Area-ILLink

#40394 Preview 5 branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#40417 Move Microsoft.DotNet.Tools.Tests.Utilities.Tests into Microsoft.DotNet.Cli.Utils.Tests
  sdk.sln
  src/Cli/Microsoft.DotNet.InternalAbstractions/Properties/Properties.cs
  test/Microsoft.DotNet.Cli.Utils.Tests/MockFileSystemTests.cs
  test/Microsoft.DotNet.Cli.Utils.Tests/NuGetTransientErrorDetectorTests.cs
  test/Microsoft.DotNet.Tools.Tests.Utilities.Tests/Microsoft.DotNet.Tools.Tests.Utilities.Tests.csproj
  test/Microsoft.NET.TestFramework/InternalsVisibleToAttributes.cs
Labels: Area-Infrastructure, untriaged

#38996 [Issue #37237 #19650] Dotnet Cli Feature: `dotnet tool update --all` Updating all tools with one command
  src/Cli/dotnet/commands/dotnet-tool/common/ToolAppliedOption.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallCommandParser.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalInstaller.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListCommandParser.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateCommandParser.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/update/xlf/LocalizableStrings.zh-Hant.xlf
  src/Tests/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallLocalCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUninstallGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateLocalCommandTests.cs
  src/Tests/dotnet.Tests/ParserTests/UpdateToolParserTests.cs
Labels: Area-Tools

#40420 Copy Installer Pipeline ymls
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/jobs/vmr-synchronization.yml
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/steps/vmr-prepare.yml
  eng/pipelines/templates/steps/vmr-pull-updates.yml
  eng/pipelines/templates/variables/vmr-build.yml
  eng/pipelines/vmr-build-pr.yml
  eng/pipelines/vmr-sync-internal.yml
  eng/pipelines/vmr-sync.yml
  eng/vmr-sync.ps1
  eng/vmr-sync.sh
Labels: Area-Infrastructure, untriaged

#40421 GitHub workflow for actions/stale to label and close stale issues
  .github/workflows/stale.yml
Labels: Area-Infrastructure, untriaged

#40463 Set main-sdk as the temporary VMR branch to push to
  eng/pipelines/vmr-sync-internal.yml
  eng/pipelines/vmr-sync.yml
Labels: Area-Infrastructure, untriaged

#40467 Update dotnet/dotnet checkout branch to main-sdk for VMR validation
  eng/pipelines/vmr-build-pr.yml
  eng/pipelines/vmr-sync-internal.yml
  eng/pipelines/vmr-sync.yml
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#40479 Allow pushing to VMR's `main-sdk` branch
  eng/pipelines/templates/jobs/vmr-synchronization.yml
Labels: Area-Infrastructure, untriaged

#40480 Update prep-source-build.sh
  src/SourceBuild/content/prep-source-build.sh
Labels: VMR

#40518 Fix cloaking of `aspnetcoremodeule-setup`
  src/VirtualMonoRepo/source-mappings.json
Labels: Area-Infrastructure, untriaged

#40191 Re-enable a bunch of container tests
  test/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: untriaged, Area-Containers

#40520 Remove Newtonsoft.Json usage
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.GlobalJsonReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.JsonReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.Localization.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.NewtonsoftJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.SystemTextJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadPackId.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSet.cs
Labels: Area-Infrastructure, untriaged

#40388 Add more workload set tests
  src/Tests/dotnet-MsiInstallation.Tests/Framework/RemoteDirectory.cs
  src/Tests/dotnet-MsiInstallation.Tests/Framework/VMTestBase.cs
  src/Tests/dotnet-MsiInstallation.Tests/Framework/VirtualMachine.cs
  src/Tests/dotnet-MsiInstallation.Tests/MsiInstallerTests.cs
  src/Tests/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs
Labels: untriaged, Area-Workloads

#40538 Manually update Microsoft.DotNet.Test.ProjectTemplates.8.0
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#40546 Remove duplicated Version file entries
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#40557 Don't fail log publishing when test results folder doesn't exist
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#40559 Source-build fixes and clean-up
  Directory.Packages.props
  eng/DotNetBuild.props
  eng/Publishing.props
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  source-build.slnf
  src/Installer/core-sdk-tasks/AzurePublisher.cs
  src/Installer/core-sdk-tasks/core-sdk-tasks.csproj
  src/Installer/redist-installer/projects/SdkResolver.csproj
  src/Installer/redist-installer/projects/VSTemplateLocator.csproj
  src/Installer/redist-installer/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#40486 Clean up PR artifacts publishing
  .vsts-ci.yml
  .vsts-pr.yml
  eng/build-pr.yml
Labels: Area-Infrastructure, untriaged

#40533 Reduced frequency of GitHub stale action; add action write permissions
  .github/workflows/stale.yml
Labels: Area-Infrastructure, untriaged

#40317 Mention package references from dotnet list help at the top level
  src/Cli/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
Labels: untriaged, Area-CLI

#40572 Add nativeToolsOnMachine flag
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/jobs/vmr-synchronization.yml
  eng/pipelines/templates/steps/vmr-prepare.yml
  eng/pipelines/vmr-build-pr.yml
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#40583 Fix and update vmr-sync scripts
  eng/vmr-sync.ps1
  eng/vmr-sync.sh
Labels: Area-Infrastructure, untriaged
