Repository dotnet/sdk, pull requests merged in 2024-06, with the labels that each got.

#41339 Add SdkTarballPath prop
  src/SourceBuild/content/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#41340 Fix license scan test results path for trx files
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#41354 Fix Target Branch for PR Updator
  src/SourceBuild/content/eng/pipelines/templates/steps/create-baseline-update-pr.yml
Labels: Area-Infrastructure, untriaged

#40133 Allow 'Add project reference' for existing projects
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectReference/Existing/.template.config/template.json
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectReference/Existing/Project1/Program.cs
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectReference/Existing/Project1/Project1.csproj
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectReference/ExistingWithRename/.template.config/template.json
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectReference/ExistingWithRename/Project1/Program.cs
  src/Assets/TestPackages/dotnet-new/test_templates/PostActions/AddProjectReference/ExistingWithRename/Project1/Project1.csproj
  src/Cli/Microsoft.TemplateEngine.Cli/PostActionProcessors/PostActionProcessorBase.cs
  src/Cli/dotnet/commands/dotnet-new/PostActions/DotnetAddPostActionProcessor.cs
  src/Cli/dotnet/commands/dotnet-new/PostActions/DotnetRestorePostActionProcessor.cs
  src/Cli/dotnet/commands/dotnet-new/PostActions/DotnetSlnPostActionProcessor.cs
  test/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_InstalledPackage_LocalPackage.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_InstalledPackage_LocalPackage.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_InstalledPackage_LocalPackage.Windows.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewDetailsTest.CanDisplayDetails_InstalledPackage_LocalPackage.verified.txt
  test/dotnet-new.Tests/PostActionTests.cs
  test/dotnet.Tests/dotnet-new/DotnetAddPostActionTests.cs
  test/dotnet.Tests/dotnet-new/DotnetSlnPostActionTests.cs
Labels: untriaged, Area-NetSDK

#41350 Update branch filters for SB SDK Diff Pipeline
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
Labels: Area-Infrastructure, untriaged

#41294 [release/8.0.1xx] Use a more reasonable timeout for HttpClient operations for Container Registry interactions
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
Labels: Servicing-approved, untriaged, Area-Containers

#41369 Update .NET 9 p4 to p5 in the table
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#41274 Fix Aspire version to Preview 2 version
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#41322 [Blazor] Removes problematic system.text.json switches
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: Servicing-approved, Area-AspNetCore

#40934 Fix getting path to full framework MSBuild
  src/Tests/Microsoft.NET.TestFramework/ToolsetInfo.cs
Labels: Area-Infrastructure, untriaged

#41385 Publish xUnit test results (non-Helix)
  eng/pipelines/templates/jobs/sdk-build.yml
  eng/pipelines/templates/jobs/sdk-job-matrix.yml
Labels: Area-Infrastructure, untriaged

#41381 Fix Alpine Target RID
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#41400 Update SDK Diff tests baselines
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/ArtifactsSizeTests/centos.9-x64.txt
Labels: Area-Infrastructure, untriaged

#41402 [VMR] Update .gdnbaselines with latest changes
  src/SourceBuild/content/.config/guardian/.gdnbaselines
Labels: Area-Infrastructure, untriaged

#41411 Delete dangling comments from exclusions file
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/SdkFileDiffExclusions.txt
Labels: Area-Infrastructure, untriaged

#41412 [Blazor] Disable problematic runtime switches, same as preview5
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
Labels: untriaged, Area-AspNetCore

#41319 Add implementation of Aspire service
  CODEOWNERS
  Directory.Build.props
  sdk.sln
  src/BuiltInTools/AspireService/AspireServerService.cs
  src/BuiltInTools/AspireService/Contracts/IAspireServerEvents.cs
  src/BuiltInTools/AspireService/Helpers/CertGenerator.cs
  src/BuiltInTools/AspireService/Helpers/ExceptionExtensions.cs
  src/BuiltInTools/AspireService/Helpers/HttpContextExtensions.cs
  src/BuiltInTools/AspireService/Helpers/SocketConnectionManager.cs
  src/BuiltInTools/AspireService/Helpers/SocketUtilities.cs
  src/BuiltInTools/AspireService/Helpers/WebSocketConnection.cs
  src/BuiltInTools/AspireService/Microsoft.WebTools.AspireService.Package.csproj
  src/BuiltInTools/AspireService/Microsoft.WebTools.AspireService.projitems
  src/BuiltInTools/AspireService/Microsoft.WebTools.AspireService.shproj
  src/BuiltInTools/AspireService/Models/ErrorResponse.cs
  src/BuiltInTools/AspireService/Models/InfoResponse.cs
  src/BuiltInTools/AspireService/Models/RunSessionRequest.cs
  src/BuiltInTools/AspireService/Models/SessionChangeNotification.cs
  src/BuiltInTools/dotnet-watch.slnf
Labels: Area-Infrastructure, untriaged, Area-Watch

#41418 Use AzureLinux 3.0 containers like dotnet/runtime for the VMR
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/variables/vmr-build.yml
Labels: untriaged, Area-VMR

#41416 Fix minimum macOS version in the .pkg manifest
  src/Installer/redist-installer/targets/GeneratePKG.targets
Labels: Area-Infrastructure, untriaged

#41306 [wasm] Import StaticWebAssets SDK only for browser-wasm
  src/WasmSdk/Sdk/Sdk.props
  src/WasmSdk/Sdk/Sdk.targets
Labels: Area-WasmSdk

#41417 Re-bootstrap with Preview 6 SDK
  src/SourceBuild/content/eng/Version.Details.xml
  src/SourceBuild/content/eng/Versions.props
  src/SourceBuild/content/global.json
  src/SourceBuild/patches/winforms/0001-Suppress-IDE0036-errors.patch
Labels: Area-Infrastructure, untriaged

#41399 Update Source-Build SDK Diff Tests Baselines and Exclusions
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/ArtifactsSizeTests/centos.9-x64.txt
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/SdkFileDiffExclusions.txt
Labels: Area-Infrastructure, untriaged

#41449 Dispose ZipArchive after usage in ExtractArchiveToDirectory
  src/Installer/core-sdk-tasks/ExtractArchiveToDirectory.cs
Labels: Area-Infrastructure, untriaged

#41468 [Blazor] Resolve tokens before copying files
  src/StaticWebAssetsSdk/Tasks/CollectStaticWebAssetsToCopy.cs
  src/StaticWebAssetsSdk/Tasks/Compression/ResolveCompressedAssets.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssetEndpoints.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: untriaged, Area-AspNetCore

#41479 Use ZipFile.ExtractToDirectory for extracting nupkg in tests
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/Utilities.cs
  src/SourceBuild/content/test/Microsoft.DotNet.UnifiedBuild.Tests/Utilities.cs
Labels: Area-Infrastructure, untriaged

#41430 Add tab completion for 'dotnet nuget why' command
  src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs
  test/dotnet-nuget.UnitTests/GivenANuGetCommand.cs
  test/dotnet.Tests/CommandTests/CompleteCommandTests.cs
Labels: Area-Infrastructure, untriaged

#41482 [Static Web Assets] Remove tokens before trying to match paths in static web assets
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetPathPattern.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.cs
Labels: Area-Infrastructure, untriaged

#41487 Dispose IDisposables in AssemblySymbolLoader
  src/Compatibility/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoader.cs
Labels: untriaged, Area-ApiCompat

#40548 Add test
  src/Tests/dotnet-MsiInstallation.Tests/Framework/VMTestBase.cs
  src/Tests/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs
Labels: Area-Infrastructure, untriaged

#41498 [Blazor] Ensure development manifest resolves tokens
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetsDevelopmentManifest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifestTest.cs
Labels: untriaged, Area-AspNetCore

#38087 Include version in deps.json
  src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs
Labels: Area-Infrastructure, untriaged

#41451 Revert TestPackage creation changes
  build/RunTestsOnHelix.cmd
  build/RunTestsOnHelix.sh
  src/Assets/TestPackages/Microsoft.NET.TestPackages.csproj
  src/Assets/TestPackages/dotnet-dependency-context-test/dotnet-dependency-context-test.csproj
  src/Assets/TestPackages/dotnet-outputsframeworkversion/dotnet-outputsframeworkversion-netcoreapp1.0/dotnet-outputsframeworkversion-netcoreapp1.0.csproj
  src/Assets/TestPackages/dotnet-portable-v1-prefercli/dotnet-portable-v1-prefercli.csproj
  src/Assets/TestPackages/dotnet-portable-v1/dotnet-portable-v1.csproj
  test/Microsoft.NET.TestFramework/BuildTestPackages.targets
  test/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
Labels: Area-Infrastructure, untriaged

#41396 Remove Out-of-Support .NET Core SDK 2.x Download Link
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#41511 [Static Web Assets] Fix compressed endpoint headers
  src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetPathPattern.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ApplyCompressionNegotiationTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DefineStaticWebAssetEndpointsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ResolveCompressedAssetsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_CorrectlyBundlesScopedCssFiles.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_IncorporatesInitializersFromClassLibraries.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_NoDependencies_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_NoDependencies_GeneratesJsonManifestAndCopiesItToOutputFolder_NoDependencies.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_WorksWithStaticWebAssetsV1ClassLibraries.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_CreatesEndpointsForAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DiscoversJsModulesBasedOnPatterns.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DoesNotUpdateManifest_WhenHasNotChanged.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_FingerprintsContent_WhenEnabled.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_UpdatesManifest_WhenFilesChange.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_UpdatesManifest_WhenFilesChange_Updated.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Clean_RemovesManifestFrom_BuildAndIntermediateOutput.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_WorksWithStaticWebAssetsV1ClassLibraries.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_WorksWithStaticWebAssetsV1ClassLibraries.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_CreatesEndpointsForAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_CreatesEndpointsForAssets_BuildAndPublish_Assets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_PublishesJsModuleBundleBundleToTheRightLocation.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Rebuild_RegeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Rebuild_RegeneratesJsonManifestAndCopiesItToOutputFolder_Rebuild.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/ScopedCss_IsBackwardsCompatible_WithPreviousVersions.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/ScopedCss_PublishIsBackwardsCompatible_WithPreviousVersions.Publish.staticwebassets.json
Labels: untriaged, Area-AspNetCore

#41508 Dispose FileStream after reading it and calculating Fingerprint & Integrity
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAsset.cs
Labels: Area-Infrastructure, untriaged

#41447 Fix a leak of ProjectCollection in dotnet-add-reference
  src/Cli/dotnet/commands/dotnet-add/dotnet-add-reference/Program.cs
Labels: untriaged, Area-CLI

#41316 remove installer from version file
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure, untriaged

#41042 Enable the Respecting Item's Culture by default
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Area-Infrastructure, untriaged

#41533 [Static Web Assets] Resolve tokens on the generated initializers module manifest
  src/StaticWebAssetsSdk/Tasks/JSModules/GenerateJSModuleManifest.cs
Labels: untriaged

#41532 Add missing Restore option for ArtifactsPath and tests
  src/Cli/dotnet/commands/dotnet-restore/RestoreCommandParser.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommandParser.cs
  src/Tests/dotnet.Tests/ParserTests/BuildRelatedCommandParserTests.cs
Labels: untriaged, Area-CLI

#41537 Add back a line that was lost in dotnet/installer migration
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure, untriaged

#41384 Respect DebugSymbols=false Fixes #41364
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs
Labels: Review for breaking changes, untriaged, breaking-change, Area-NetSDK, needs-breaking-change-doc-created

#41563 Create 0001-upgrade-jdk-version.patch
  src/SourceBuild/patches/aspnetcore/0001-upgrade-jdk-version.patch
Labels: Area-Infrastructure, untriaged

#41560 update sdk preview 5
  global.json
Labels: Area-Infrastructure, untriaged

#41160 Enhancements to Pull Request Creation/Update in `CreateBaselineUpdatePR` Tool
  src/SourceBuild/content/eng/tools/CreateBaselineUpdatePR/PRCreator.cs
Labels: Area-Infrastructure, untriaged

#41585 Fix frameworks option forwarding for 'dotnet nuget why'
  src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs
  test/dotnet.Tests/ParserTests/NuGetCommandParserTests.cs
Labels: Area-Infrastructure, untriaged

#41142 Implement dotnet test help option
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/CustomEventArgs.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/IClient.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/INamedPipeBase.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/INamedPipeSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/IRequest.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/IResponse.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/IServer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/CommandLineOptionMessages.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/Module.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/VoidResponse.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/NamedPipeBase.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/NamedPipeClient.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/NamedPipeServer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/ObjectFieldIds.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/PipeNameDescription.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/BaseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/CommandLineOptionMessagesSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/ModuleSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/RegisterSerializers.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/VoidResponseSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.Help.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.CrossTargeting.targets/ImportAfter/Microsoft.TestPlatform.CrossTargeting.targets
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.targets/ImportAfter/Microsoft.TestPlatform.ImportAfter.targets
  src/Tasks/Microsoft.NET.Build.Tasks/GetTestsProject.cs
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-DotNet Test, untriaged

#41653 Use correct property for _NetFrameworkHostedCompilersVersion in GenerateBundledVersions.targets
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure, untriaged

#41640 Fix newline bug when updating exclusion baseline
  src/SourceBuild/content/eng/tools/CreateBaselineUpdatePR/PRCreator.cs
Labels: Area-Infrastructure, untriaged

#41629 [StaticWebAssets] Adds metadata to JS initializers and JS modules
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.props
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.JSModules.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpoint.cs
  src/StaticWebAssetsSdk/Tasks/ResolveFingerprintedStaticWebAssetEndpointsForAssets.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ResolveFingerprintedStaticWebAssetEndpointsForAssetsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselineFactory.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_IncorporatesInitializersFromClassLibraries.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DiscoversJsModulesBasedOnPatterns.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_PublishesJsModuleBundleBundleToTheRightLocation.Publish.staticwebassets.json
Labels: untriaged, Area-AspNetCore

#41655 Clean-up Update sdk-build.yml
  eng/pipelines/templates/jobs/sdk-build.yml
Labels: Area-Infrastructure, untriaged

#41605 [release/8.0.4xx] Trusted roots: 2024-06 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
  src/Tests/trustedroots.Tests/GivenCodeSigningCtlFile.cs
  src/Tests/trustedroots.Tests/GivenTimestampingCtlFile.cs
Labels: Area-Infrastructure, untriaged

#41565 Trusted roots: 2024-06 CTL
  src/Layout/redist/trustedroots/codesignctl.pem
  src/Layout/redist/trustedroots/timestampctl.pem
  test/trustedroots.Tests/GivenCodeSigningCtlFile.cs
  test/trustedroots.Tests/GivenTimestampingCtlFile.cs
Labels: Area-Infrastructure, untriaged

#41569 Update dotnet help command description
  src/Cli/dotnet/commands/dotnet-help/HelpUsageText.cs
  src/Cli/dotnet/commands/dotnet-help/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-help/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-help.Tests/GivenThatIWantToShowHelpForDotnetCommand.cs
Labels: Area-Infrastructure, untriaged

#40212 Update CentOS tags in 8.0.4xx
  .vsts-ci.yml
  .vsts-pr.yml
Labels: Area-Infrastructure, untriaged

#41656 Add testFullMSBuild env var to the test step
  eng/pipelines/templates/jobs/sdk-build.yml
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
Labels: Area-Infrastructure, untriaged

#41506 Containers: insecure registries: allow https (ignore cert errors), and accept config from envvar.
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/FallbackToHttpMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/RegistrySettings.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  test/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: untriaged, Area-Containers

#41664 Fixup SDK build
  eng/pipelines/templates/jobs/sdk-build.yml
Labels: Area-Infrastructure, untriaged

#41198 source-build: bundle NativeAOT libraries with the SDK.
  src/Installer/redist-installer/redist-installer.csproj
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/eng/build.ps1
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/DebugTests.cs
  src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
Labels: Area-Infrastructure, untriaged

#41683 Remove live msbuild and runtime dependencies from fsharp
  src/SourceBuild/content/repo-projects/fsharp.proj
Labels: Area-Infrastructure, untriaged

#41671 Fix incremental build for extract-sdk-archive.proj
  src/SourceBuild/content/eng/extract-sdk-archive.proj
Labels: Area-Infrastructure, untriaged

#41681 [Static Web Assets] Fix issue with externally defined static assets and compression clashes
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Publish.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.References.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/Compression/ResolveCompressedAssets.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssetEndpoints.cs
  src/StaticWebAssetsSdk/Tasks/UpdateExternallyDefinedStaticWebAssets.cs
  src/StaticWebAssetsSdk/Tasks/Utils/FileHasher.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/Microsoft.NET.Sdk.Razor.Tests.csproj
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DefineStaticWebAssetEndpointsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/UpdateExternallyDefinedStaticWebAssetsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_CorrectlyBundlesScopedCssFiles.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_DeployOnBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_IncorporatesInitializersFromClassLibraries.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_NoDependencies_GeneratesJsonManifestAndCopiesItToOutputFolder.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/BuildProjectWithReferences_NoDependencies_GeneratesJsonManifestAndCopiesItToOutputFolder_NoDependencies.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DoesNotFailToCompress_TwoAssetsWith_TheSameContent.Build.files.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_DoesNotFailToCompress_TwoAssetsWith_TheSameContent.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_WithExternalProjectReference_UpdatesAssets.Build.files.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_WithExternalProjectReference_UpdatesAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_DifferentBuildAndPublish_LibraryInitializers.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_IncorporatesInitializersFromClassLibrariesAndPublishesAssetsToTheRightLocation.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishProjectWithReferences_PublishSingleFile_GeneratesPublishJsonManifestAndCopiesPublishAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_WithExternalProjectReference_UpdatesAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_WithExternalProjectReference_UpdatesAssets.Publish.files.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Publish_WithExternalProjectReference_UpdatesAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/content/ExternalStaticAssets.targets
Labels: untriaged, Area-AspNetCore

#41102 Use version comparison function
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/SdkDirectoryWorkloadManifestProviderTests.cs
Labels: untriaged, Area-Workloads

#41682 [release/8.0.4xx] Backport https://github.com/dotnet/sdk/pull/41506
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/FallbackToHttpMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultRegistryAPI.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/RegistrySettings.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: Area-Infrastructure, untriaged

#41704 Preview 7 Branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#41660 Add warning when targeting net standard less then 2.0
  src/Tasks/Common/Resources/Strings.resx
  src/Tasks/Common/Resources/xlf/Strings.cs.xlf
  src/Tasks/Common/Resources/xlf/Strings.de.xlf
  src/Tasks/Common/Resources/xlf/Strings.es.xlf
  src/Tasks/Common/Resources/xlf/Strings.fr.xlf
  src/Tasks/Common/Resources/xlf/Strings.it.xlf
  src/Tasks/Common/Resources/xlf/Strings.ja.xlf
  src/Tasks/Common/Resources/xlf/Strings.ko.xlf
  src/Tasks/Common/Resources/xlf/Strings.pl.xlf
  src/Tasks/Common/Resources/xlf/Strings.pt-BR.xlf
  src/Tasks/Common/Resources/xlf/Strings.ru.xlf
  src/Tasks/Common/Resources/xlf/Strings.tr.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hans.xlf
  src/Tasks/Common/Resources/xlf/Strings.zh-Hant.xlf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToTargetNotRecommendedFrameworks.cs
Labels: untriaged

#41747 Containers telemetry
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildLogger.cs
  src/Containers/Microsoft.NET.Build.Containers/BaseImageNotFoundException.cs
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/HttpExtensions.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/RegistryConstants.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageAndTag.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
Labels: untriaged, Area-Containers

#41788 Create 0001-define-runtime-dependencies.patch
  src/SourceBuild/patches/fsharp/0001-define-runtime-dependencies.patch
Labels: source-build

#41731 Avoid crossgen for Microsoft.CodeAnalysis.VisualBasic
  src/Installer/redist-installer/targets/Crossgen.targets
Labels: untriaged

#41738 Stop generating useless .dll.configs
  src/BlazorWasmSdk/Tasks/Microsoft.NET.Sdk.BlazorWebAssembly.Tasks.csproj
  src/BuiltInTools/dotnet-format/dotnet-format.csproj
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/RazorSdk/Tasks/Microsoft.NET.Sdk.Razor.Tasks.csproj
  src/StaticWebAssetsSdk/Tasks/Microsoft.NET.Sdk.StaticWebAssets.Tasks.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/WebSdk/Publish/Tasks/Microsoft.NET.Sdk.Publish.Tasks.csproj
Labels: Area-Infrastructure, untriaged

#41794 Disable templating tests on windows to unblock PR builds
  eng/pipelines/templates/jobs/sdk-job-matrix.yml
Labels: Area-Infrastructure, untriaged

#41769 rename SDK_CONTAINER_* to DOTNET_CONTAINER
  src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs
  src/Containers/Microsoft.NET.Build.Containers/ContainerHelpers.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/RegistrySettings.cs
  src/Containers/docs/ReleaseNotes/v7.0.400.md
  test/Microsoft.NET.Build.Containers.UnitTests/RegistryTests.cs
Labels: untriaged, Area-Containers

#41631 Add comments to resources to instruct loc team about 'fixed' portions of the strings
  src/BuiltInTools/dotnet-watch/Resources.resx
  src/BuiltInTools/dotnet-watch/xlf/Resources.cs.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.de.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.es.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.fr.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.it.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ja.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ko.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.pl.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.pt-BR.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.ru.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.tr.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.zh-Hans.xlf
  src/BuiltInTools/dotnet-watch/xlf/Resources.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-run/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#41772 Update package table for preview 6
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#41736 Allow runtime binary into the VMR
  src/SourceBuild/content/eng/allowed-vmr-binaries.txt
Labels: Area-Infrastructure, untriaged

#41828 Add trigger to run license tests when baseline or test changes are made
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#41746 Avoid reinstall tool already installed
  src/Cli/dotnet/ToolPackage/IToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  test/Microsoft.DotNet.PackageInstall.Tests/ToolPackageDownloaderTests.cs
  test/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageDownloaderMock.cs
  test/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
Labels: untriaged, Area-Tools

#41740 Minimize container dependency redistribution
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  test/Microsoft.NET.Build.Containers.IntegrationTests/PackageTests.cs
Labels: Area-Infrastructure, untriaged

#41829 Add xunit configuration to increase test logging
  test/dotnet-watch.Tests/dotnet-watch.Tests.csproj
  test/dotnet-watch.Tests/xunit.runner.json
Labels: Area-Infrastructure, untriaged

#41855 Upgrade rather than install, in case .NET is on container/machine alr…
  src/Installer/redist-installer/targets/GenerateRPMs.targets
Labels: Area-Infrastructure, untriaged

#40416 feat: Add support for updatedTypes in metadata updates
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
  src/BuiltInTools/BrowserRefresh/BlazorWasmHotReloadMiddleware.cs
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  test/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BlazorWasmHotReloadMiddlewareTest.cs
Labels: untriaged, Area-AspNetCore
