Repository dotnet/sdk, pull requests merged in 2024-02, with the labels that each got.

#38440 Revert "[release/8.0.2xx] Update dependencies from dotnet/razor"
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#38426 Add missing SDK dependency to global.json
  global.json
  src/Containers/packaging/package.csproj
Labels: Area-Infrastructure, untriaged

#38485 Use NetToolMinimum for Compatibility tools
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Task/Microsoft.DotNet.ApiCompat.Task.csproj
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.Task.targets
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Tool/Microsoft.DotNet.ApiCompat.Tool.csproj
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Microsoft.DotNet.ApiCompatibility.csproj
  src/Compatibility/ApiCompat/Microsoft.DotNet.PackageValidation/Microsoft.DotNet.PackageValidation.csproj
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI.Task/Microsoft.DotNet.GenAPI.Task.csproj
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI.Task/build/Microsoft.DotNet.GenAPI.Task.targets
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI.Tool/Microsoft.DotNet.GenAPI.Tool.csproj
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
  src/Compatibility/Microsoft.DotNet.ApiSymbolExtensions/Microsoft.DotNet.ApiSymbolExtensions.csproj
Labels: Area-ApiCompat

#38509 Update BaselinePackageValidator.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.PackageValidation/Validators/BaselinePackageValidator.cs
  test/Microsoft.DotNet.ApiCompatibility.Tests/SuppressibleTestLog.cs
  test/Microsoft.DotNet.PackageValidation.Tests/Validators/BaselinePackageValidatorTests.cs
Labels: untriaged, Area-ApiCompat

#38542 Don't attempt to run APICompat in design time builds
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Task/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets
Labels: untriaged, Area-ApiCompat

#38406 Remove the #nullable disable directive
  src/BuiltInTools/dotnet-watch/FileItem.cs
  src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfile.cs
  src/BuiltInTools/dotnet-watch/HotReload/NamedPipeContract.cs
  src/BuiltInTools/dotnet-watch/Internal/ConsoleReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/ConsoleRequester.cs
  src/BuiltInTools/dotnet-watch/Internal/Ensure.cs
  src/BuiltInTools/dotnet-watch/Internal/FileSetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/DotnetFileWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/FileWatcherFactory.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/IFileSystemWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/PollingFileWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/IConsole.cs
  src/BuiltInTools/dotnet-watch/Internal/IReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildProjectFinder.cs
  src/BuiltInTools/dotnet-watch/Internal/NullReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/OutputCapture.cs
  src/BuiltInTools/dotnet-watch/Internal/OutputSink.cs
  src/BuiltInTools/dotnet-watch/Internal/PhysicalConsole.cs
Labels: Area-Infrastructure, untriaged

#38543 Make the use of the Roslyn toolset package an opt-in
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.Common.targets
Labels: untriaged, Area-ApiCompat

#38545 Move SB metadata to intermediates
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38569 Run tests in different tfms in parallel
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.CrossTargeting.targets/ImportAfter/Microsoft.TestPlatform.CrossTargeting.targets
Labels: Area-DotNet Test, untriaged

#38554 Remove the more #nullable disable
  src/Cli/dotnet/ReleasePropertyProjectLocator.cs
  src/Common/NullableAttributes.cs
  src/Microsoft.DotNet.TemplateLocator/TemplateLocator.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/FXVersion.cs
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
  src/Resolvers/Microsoft.DotNet.NativeWrapper/EnvironmentProvider.cs
  src/Resolvers/Microsoft.DotNet.NativeWrapper/Interop.cs
  src/Resolvers/Microsoft.DotNet.NativeWrapper/NETCoreSdkResolverNativeWrapper.cs
  src/Resolvers/Microsoft.DotNet.NativeWrapper/SdkResolutionResult.cs
  src/Resolvers/Microsoft.DotNet.SdkResolver/NETCoreSdkResolver.cs
  src/Resolvers/Microsoft.DotNet.SdkResolver/VSSettings.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/CachingWorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver/WorkloadSdkResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/ManifestVersion.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.InstallStateReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.JsonReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkFeatureBand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.SystemTextJson.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadManifestReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSet.cs
  src/Tasks/Common/BuildErrorException.cs
  src/Tasks/Common/ConflictResolution/ConflictItem.cs
  src/Tasks/Common/ConflictResolution/ConflictResolver.cs
  src/Tasks/Common/ConflictResolution/FrameworkListReader.cs
  src/Tasks/Common/ConflictResolution/MetadataNames.cs
  src/Tasks/Common/ConflictResolution/PackageOverride.cs
  src/Tasks/Common/ConflictResolution/PackageOverrideResolver.cs
  src/Tasks/Common/ConflictResolution/PackageRank.cs
  src/Tasks/Common/ConflictResolution/PlatformManifestReader.cs
  src/Tasks/Common/ConflictResolution/ResolvePackageFileConflicts.cs
  src/Tasks/Common/ConflictResolution/ResolvePublishOutputConflicts.cs
  src/Tasks/Common/FileUtilities.MetadataReader.cs
  src/Tasks/Common/FileUtilities.cs
  src/Tasks/Common/ItemUtilities.cs
  src/Tasks/Common/LogAdapter.cs
  src/Tasks/Common/Logger.cs
  src/Tasks/Common/MSBuildUtilities.cs
  src/Tasks/Common/Message.cs
  src/Tasks/Common/MessageBase.cs
  src/Tasks/Common/MessageLevel.cs
  src/Tasks/Common/MetadataKeys.cs
  src/Tasks/Common/NETSdkError.cs
  src/Tasks/Common/NETSdkInformation.cs
  src/Tasks/Common/NETSdkWarning.cs
  src/Tasks/Common/NuGetUtils.cs
  src/Tasks/Common/TaskBase.cs
  test/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-Infrastructure, untriaged

#38581 Update branding to 8.0.103
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38579 Update branding to 7.0.314
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38577 Update branding to 6.0.420
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38576 Update branding to 6.0.128
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38578 Update branding to 7.0.117
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38506 Update to Unified Build controls
  Directory.Build.props
  Directory.Packages.props
  eng/Analyzers.props
  eng/Packages.props
  eng/Versions.props
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
  src/BuiltInTools/BrowserRefresh/Microsoft.AspNetCore.Watch.BrowserRefresh.csproj
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Cli/dotnet/dotnet.csproj
  src/Compatibility/Directory.Packages.props
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/Containers/packaging/package.csproj
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/BundledSdks.targets
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/tool_fsharp/tool_fsc.csproj
  src/Layout/tool_msbuild/tool_msbuild.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  src/WebSdk/Publish/Tasks/Microsoft.NET.Sdk.Publish.Tasks.csproj
  test/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#38573 Remove high priority message from test target
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.CrossTargeting.targets/ImportAfter/Microsoft.TestPlatform.CrossTargeting.targets
Labels: Area-Infrastructure, untriaged

#38606 DotNetOrchestrator->DotNetBuildOrchestrator
  src/Layout/tool_fsharp/tool_fsc.csproj
Labels: untriaged, Area-FSharp

#38277 [Issue #37501] Verbosity Options default to `minimal` from `quiet` in `tool install`
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
Labels: untriaged, Area-Workloads

#37394 add tool list format option
  src/Cli/dotnet/commands/dotnet-tool/list/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListCommandParser.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListJsonHelper.cs
  src/Cli/dotnet/commands/dotnet-tool/list/ToolListLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-tool/list/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/ToolListGlobalOrToolPathCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolListLocalCommandTests.cs
Labels: Approved to merge, untriaged, Document for new feature, Area-Tools

#37985 Update for loc
  eng/build.yml
Labels: localization, Area-Infrastructure

#38644 Don't require AppHost when publishing AOT
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
Labels: Area-External, untriaged

#38656 Fix runtime dependency name
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#38612 backport: Verbosity Options default to minimal from quiet in tool install
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Tests/Microsoft.DotNet.PackageInstall.Tests/NuGetPackageInstallerTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
Labels: untriaged, Area-Tools

#30066 Fix links in .gitignore
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/Gitignore/.gitignore
  test/dotnet-new.Tests/Approvals/AllCommonItemsCreate.-o#dotnet-gitignore-file#-n#item.verified/dotnet-gitignore-file/.gitignore
Labels: Area-Infrastructure

#38143 Add MSI garbage collection for side-by-side workload manifests
  src/Cli/Microsoft.DotNet.Cli.Utils/DependencyProvider.cs
  src/Cli/dotnet/Installer/Windows/DetectState.cs
  src/Cli/dotnet/Installer/Windows/InstallAction.cs
  src/Cli/dotnet/Installer/Windows/WorkloadManifestRecord.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  src/Cli/dotnet/commands/dotnet-workload/install/MsiInstallerBase.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.InstallRecords.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadGarbageCollector.cs
Labels: untriaged, Area-Workloads

#38690 Improve roslyn version mismatch error message
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/CommonResources.resx
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.cs.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.de.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.es.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.fr.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.it.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.ja.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.ko.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.pl.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.pt-BR.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.ru.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.tr.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.zh-Hans.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/xlf/CommonResources.zh-Hant.xlf
Labels: untriaged, Area-ApiCompat

#38695 Do not import LKG overlay targets in VMR build in general
  src/Layout/redist/redist.csproj
Labels: Area-Infrastructure, untriaged

#38680 Fix PublishAot with PublishSingleFile
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets
Labels: untriaged, Area-ILLink

#38306 [`dotnet list package`]Resolve relative paths
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs
  test/dotnet-list-package.Tests/GivenDotnetListPackage.cs
Labels: Area-Infrastructure, untriaged

#38737 Fix issue where applying rollback file would incorrectly uninstall workload packs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/FakeManifestProvider.cs
  src/Tests/dotnet-workload-install.Tests/MockManifestProvider.cs
Labels: Servicing-approved, untriaged, Area-Workloads

#38712 Fix issue where applying rollback file would incorrectly uninstall workload packs
  src/Cli/dotnet/commands/dotnet-workload/install/WorkloadInstallCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/TempDirectoryWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
  src/Tests/Microsoft.NET.Sdk.WorkloadManifestReader.Tests/FakeManifestProvider.cs
  src/Tests/dotnet-workload-install.Tests/MockManifestProvider.cs
Labels: Servicing-approved, untriaged, Area-Workloads

#37804 Include MSBuild version as part of --info, not every build.
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
  src/Cli/dotnet/CommandLineInfo.cs
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs
  src/Cli/dotnet/commands/dotnet-msbuild/Program.cs
  src/Cli/dotnet/commands/dotnet-restore/Program.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetCleanInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetOsArchOptions.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetStoreInvocation.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetTestInvocation.cs
Labels: untriaged, Area-CLI

#38802 Parse SdkFeatureBand from .version file
  src/Cli/Microsoft.DotNet.Cli.Utils/DotnetVersionFile.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Polyfills.cs
Labels: Area-Infrastructure, untriaged

#38803 Remove Valleysoft.DockerCredsProvider from SourceBuildPrebuiltBaseline.xml
  eng/SourceBuildPrebuiltBaseline.xml
Labels: Area-Infrastructure, untriaged

#38735 Merging internal commits for release/8.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-package/search/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#38729 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38730 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38732 Merging internal commits for release/7.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38731 Merging internal commits for release/7.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38733 Merging internal commits for release/7.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38734 Merging internal commits for release/8.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38792 Update branding
  eng/Versions.props
Labels: Area-Infrastructure, untriaged, Branding

#38812 Update to the Feb 8.0.2 runtime
  NuGet.config
  eng/SourceBuildPrebuiltBaseline.xml
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#38881 Fix unbalanced quote in error message
  src/Cli/dotnet/NugetPackageDownloader/LocalizableStrings.resx
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/NugetPackageDownloader/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#37312 Enable parallel copy in PublishDotnetWatchToRedist
  src/Layout/redist/targets/PublishDotnetWatch.targets
Labels: Area-Infrastructure, untriaged

#37315 Don't copy MSBuild to Container outputs
  src/Cli/Microsoft.DotNet.Cli.Utils/Microsoft.DotNet.Cli.Utils.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  src/Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests/Microsoft.NET.Sdk.Publish.Tasks.Tests.csproj
  src/Tests/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
Labels: Area-Infrastructure, untriaged

#38918 Update LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hans.xlf
Labels: Area-Infrastructure, untriaged

#38911 [dotnet list package] add an alias option, `-s`, to the option `--source`.
  src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommandParser.cs
  test/dotnet-list-package.Tests/GivenDotnetListPackage.cs
Labels: Area-Infrastructure, untriaged

#37192 Added test for .user file in outer build
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACrossTargetedLibrary.cs
Labels: Area-Infrastructure, untriaged

#38882 Containers: support using OCI base images.
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/Layer.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultManifestOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/SchemaTypes.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/LayerEndToEndTests.cs
Labels: untriaged, Area-Containers

#38967 Set ProducesDotNetReleaseShippingAssets property in Publishing.props
  eng/Publishing.props
Labels: Area-Infrastructure, untriaged

#38982 Revert "[main] Update dependencies from dotnet/roslyn-analyzers"
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#38987 Branding for Preview 3 🐺
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#39004 Update and rename SourceBuild.props to DotNetBuild.props
  eng/DotNetBuild.props
Labels: Area-Infrastructure, untriaged

#39049 Update dotnet/format to preview2
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#38965 Use `Convert.ToHexStringLower`
  src/Cli/Microsoft.DotNet.Cli.Utils/Sha256Hasher.cs
  src/Containers/Microsoft.NET.Build.Containers/DigestUtils.cs
  src/Containers/Microsoft.NET.Build.Containers/Layer.cs
  src/Tasks/Microsoft.NET.Build.Tasks/AllowEmptyTelemetry.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/LayerEndToEndTests.cs
Labels: Area-Infrastructure, untriaged

#38915 Fix typo in VsMsdeploy.cs
  src/WebSdk/Publish/Tasks/Tasks/MsDeploy/VsMsdeploy.cs
Labels: Area-Infrastructure, untriaged

#39060 Avoid race condition in ArgumentsReflector.csproj
  test/ArgumentForwarding.Tests/ArgumentForwarding.Tests.csproj
  test/ArgumentForwarding.Tests/reflector_cmd.cmd
  test/ArgumentsReflector/ArgumentsReflector.csproj
Labels: Area-Infrastructure, untriaged

#39070 Cherry-pick #38956 to release/8.0.3xx
  src/Cli/dotnet/commands/RestoringCommand.cs
  src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
Labels: Area-Infrastructure, untriaged
