Repository dotnet/sdk, pull requests merged in 2024-11, with the labels that each got.

#44575 Revert "[main] Update dependencies from dotnet/arcade-services"
  .config/dotnet-tools.json
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44569 Remove source build warn on diff test infra
  src/SourceBuild/content/eng/pipelines/templates/jobs/sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/BaselineHelper.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/Config.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/LicenseScanTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/Microsoft.DotNet.SourceBuild.Tests.csproj
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/README.md
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/SdkContentTests.cs
Labels: Area-Infrastructure, untriaged

#44565 Prevent propagation of Ctrl+C to child processes
  src/BuiltInTools/dotnet-watch/EnvironmentOptions.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/IConsole.cs
  src/BuiltInTools/dotnet-watch/Internal/PhysicalConsole.cs
  src/BuiltInTools/dotnet-watch/Internal/ProcessRunner.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  test/dotnet-watch.Tests/ConsoleReporterTests.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/Utilities/TestConsole.cs
  test/dotnet-watch.Tests/Watch/ProgramTests.cs
  test/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: Area-Infrastructure, untriaged

#44595 Increase Arm64 test build timeout
  test/UnitTests.proj
Labels: Area-Infrastructure, untriaged

#44604 Make dotnet-watch tests TFM agnostic
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/Utilities/AssertEx.cs
Labels: Area-Infrastructure, untriaged

#44628 vmr to macos-13
  eng/pipelines/templates/variables/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44537 sln-list: Support for slnx
  src/Cli/dotnet/commands/dotnet-sln/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-sln/SlnCommandParser.cs
  src/Cli/dotnet/commands/dotnet-sln/list/Program.cs
  src/Cli/dotnet/commands/dotnet-sln/migrate/SlnMigrateCommand.cs
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-sln.Tests/GivenDotnetSlnList.cs
Labels: untriaged, Area-CLI

#44651 Update branding to 8.0.112
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44652 Update branding to 8.0.308
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44653 Update branding to 8.0.405
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#43938 Outline of CLI UX/Option/behavior expectations for the dotnet CLI
  documentation/project-docs/cli-guidelines.md
Labels: Area-Infrastructure, untriaged

#44530 Set mediaType from http response if manifest mediaType is not present
  src/Containers/Microsoft.NET.Build.Containers/BuiltImage.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ManifestV2.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultManifestOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/IManifestOperations.cs
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/ImageBuilderTests.cs
Labels: Servicing-approved, Area-Containers

#44487 [FIX] tool-install: Support --ignore-failed-sources flag correctly
  src/Cli/dotnet/ToolPackage/IToolPackageDownloader.cs
  src/Cli/dotnet/ToolPackage/ToolPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallLocalInstaller.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs
  src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateLocalCommand.cs
  src/Tests/Microsoft.DotNet.Tools.Tests.ComponentMocks/ToolPackageDownloaderMock.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolInstallLocalCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
  src/Tests/dotnet.Tests/CommandTests/ToolUpdateLocalCommandTests.cs
Labels: Servicing-approved, untriaged, Area-Tools

#44660 Update branding to 9.0.101
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44455 Gather test diag logging to track down nuget issue
  test/Microsoft.NET.TestFramework/Commands/MSBuildCommand.cs
Labels: Area-Infrastructure, untriaged, Branch Lockdown

#44442 Remove additional TL characters from the dotnet run output special casing for tests
  test/Microsoft.NET.TestFramework/Utilities/TerminalLoggerStringExtensions.cs
Labels: Area-Infrastructure

#44661 sln-list: Fix char conversions
  src/Cli/dotnet/commands/dotnet-sln/list/Program.cs
  test/dotnet-sln.Tests/GivenDotnetSlnList.cs
Labels: Area-Infrastructure, untriaged

#44539 Browser refresh and WASM delta applier refactoring
  src/BuiltInTools/BrowserRefresh/.editorconfig
  src/BuiltInTools/BrowserRefresh/BlazorHotReload.js
  src/BuiltInTools/BrowserRefresh/BlazorWasmHotReloadMiddleware.cs
  src/BuiltInTools/BrowserRefresh/BrowserRefreshMiddleware.cs
  src/BuiltInTools/BrowserRefresh/BrowserScriptMiddleware.cs
  src/BuiltInTools/BrowserRefresh/HostingStartup.cs
  src/BuiltInTools/BrowserRefresh/Microsoft.AspNetCore.Watch.BrowserRefresh.csproj
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
  src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs
  src/BuiltInTools/DotNetDeltaApplier/Microsoft.Extensions.DotNetDeltaApplier.csproj
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/BuiltInTools/dotnet-watch/Browser/BrowserConnection.cs
  src/BuiltInTools/dotnet-watch/Browser/BrowserConnector.cs
  src/BuiltInTools/dotnet-watch/Browser/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReload/AgentMessageSeverity.cs
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/DeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/NamedPipeContract.cs
  src/BuiltInTools/dotnet-watch/HotReload/ProjectLauncher.cs
  src/BuiltInTools/dotnet-watch/HotReload/ResponseLoggingLevel.cs
  src/BuiltInTools/dotnet-watch/HotReload/ScopedCssFileHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/StaticFileHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/UpdateDelta.cs
  src/BuiltInTools/dotnet-watch/Internal/BrowserSpecificReporter.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  test/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BlazorWasmHotReloadMiddlewareTest.cs
  test/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/BrowserRefreshMiddlewareTest.cs
  test/Microsoft.AspNetCore.Watch.BrowserRefresh.Tests/HostingStartupTest.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/HotReload/UpdatePayloadTests.cs
Labels: untriaged, Area-AspNetCore

#44667 Revert "[release/9.0.1xx] Update dependencies from dotnet/templating"
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44563 Update the loc build to target 9.0.2xx
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#44686 Fix native install-dependencies.sh ref
  eng/common/native/install-dependencies.sh
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44692 Pass down PublicBaseURL for aspnetcore to direct it to download assets from the local artifacts assets path
  src/SourceBuild/content/repo-projects/aspnetcore.proj
Labels: untriaged, Area-VMR

#44631 Build
  src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs
  src/BuiltInTools/dotnet-watch/Browser/BrowserConnector.cs
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/BuiltInTools/dotnet-watch/Filters/BuildEvaluator.cs
  src/BuiltInTools/dotnet-watch/HotReload/IRuntimeProcessLauncherFactory.cs
  src/BuiltInTools/dotnet-watch/HotReload/ProjectLauncher.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/Program.cs
  src/BuiltInTools/dotnet-watch/ProjectOptions.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Cli/dotnet/OptionForwardingExtensions.cs
  src/Cli/dotnet/Parser.cs
  src/Cli/dotnet/dotnet.csproj
  test/TestAssets/TestProjects/WatchNoDepsApp/WatchNoDepsApp.csproj
  test/dotnet-watch.Tests/CommandLineOptionsTests.cs
  test/dotnet-watch.Tests/HotReload/CompilationHandlerTests.cs
  test/dotnet-watch.Tests/HotReload/RuntimeProcessLauncherTests.cs
  test/dotnet-watch.Tests/MsBuildFileSetFactoryTest.cs
  test/dotnet-watch.Tests/Utilities/MockFileSetFactory.cs
  test/dotnet-watch.Tests/Utilities/TestRuntimeProcessLauncher.cs
  test/dotnet-watch.Tests/Watch/DotNetWatcherTests.cs
  test/dotnet-watch.Tests/Watch/ProgramTests.cs
Labels: untriaged

#44593 Allow ProjectReferences to not have the _GetRequiredWorkloads Target
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.ImportWorkloads.targets
  test/TestAssets/TestProjects/ProjectWithEsProjReference/App.csproj
  test/TestAssets/TestProjects/ProjectWithEsProjReference/Lib.esproj
  test/TestAssets/TestProjects/ProjectWithEsProjReference/package-lock.json
  test/TestAssets/TestProjects/ProjectWithEsProjReference/package.json
  test/dotnet-workload-restore.Tests/GivenDotnetWorkloadRestore.cs
Labels: Area-Infrastructure, untriaged

#44709 Use STJToolsetVersion property and use SkipUnchangedFiles metadata
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/Containers/containerize/containerize.csproj
Labels: Area-Infrastructure, untriaged

#44687 improve SDK incremental builds by not running redist-installer layout generation on inner loop builds
  build.cmd
  build.sh
  src/Installer/redist-installer/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#44711 Update vmr-build.yml
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#44498 Update tfm of dotnet/format test project to current
  test/TestAssets/dotnet-format/for_workspace_finder/multiple_projects/project_a.csproj
  test/TestAssets/dotnet-format/for_workspace_finder/multiple_projects/project_b.csproj
  test/TestAssets/dotnet-format/for_workspace_finder/project_and_solution/project_and_solution.csproj
  test/TestAssets/dotnet-format/for_workspace_finder/single_project/single_project.csproj
  test/dotnet-format.Tests/tests/MSBuild/MSBuildWorkspaceFinderTests.cs
Labels: Area-Infrastructure, untriaged

#44756 Revert "[main] Update dependencies from dotnet/arcade (#44712)"
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: Area-Infrastructure, untriaged

#44762 Update source build prebuilts tarball
  src/SourceBuild/content/eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44603 [dotnet-watch] Simplify file watching
  src/BuiltInTools/dotnet-watch/DotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/EnvironmentOptions.cs
  src/BuiltInTools/dotnet-watch/EnvironmentVariables.cs
  src/BuiltInTools/dotnet-watch/Filters/BuildEvaluator.cs
  src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/EventBasedDirectoryWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/FileWatcherFactory.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/IDirectoryWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher/PollingDirectoryWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/HotReloadFileSetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/Properties/launchSettings.json
  test/dotnet-watch.Tests/FileWatcherTests.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/HotReload/RuntimeProcessLauncherTests.cs
  test/dotnet-watch.Tests/Utilities/AwaitableProcess.cs
  test/dotnet-watch.Tests/Utilities/TestOptions.cs
  test/dotnet-watch.Tests/Watch/DotNetWatcherTests.cs
  test/dotnet-watch.Tests/Watch/ProgramTests.cs
  test/dotnet-watch.Tests/Watch/Utilities/DotNetWatchTestBase.cs
  test/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: untriaged, Area-AspNetCore

#44693 Fix publishing OCI image as tarball
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/ManifestListV2.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerRegistryManager.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: Servicing-approved, DO NOT MERGE, Area-Containers

#44740 Install .NET 9.0 template
  test/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelpForTemplate_MatchOnLanguage.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelpForTemplate_MatchOnNonChoiceParam.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelpForTemplate_classlib.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CanShowHelpForTemplate_console.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewHelpTests.CannotShowHelpForTemplate_MatchOnChoiceWithoutValue.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CannotInstantiateTemplate_OnMultipleParameterErrors.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CannotInstantiateTemplate_WhenChoiceParameterValueIsInvalid.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewInstantiateTests.CannotInstantiateTemplate_WhenChoiceParameterValueIsNotComplete.verified.txt
  test/dotnet-new.Tests/SharedHomeDirectory.cs
  test/dotnet-new.Tests/dotnet-new.IntegrationTests.csproj
Labels: Area-Infrastructure, untriaged

#44778 Updated template condition in GenerateSdkBundle target
  src/Installer/redist-installer/targets/GenerateMSIs.targets
Labels: Area-Infrastructure, untriaged

#44798 Forward PgoInstrument down to aspnetcore's build
  src/SourceBuild/content/repo-projects/aspnetcore.proj
Labels: untriaged, Area-VMR

#44800 Use the BaseOS property as the "portable" rid for building installers
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/aspnetcore.proj
  src/SourceBuild/content/repo-projects/runtime.proj
  src/SourceBuild/patches/arcade/0002-Fall-back-to-the-portable-parent-RID-for-the-installer.patch
  src/SourceBuild/patches/runtime/0001-Pass-BaseOS-property-down-to-the-inner-build-as-well.patch
Labels: untriaged, Area-VMR

#44612 Workaround for issue 40015: nuget restore uses 'resource' instead of 'resources'
  src/Tasks/Microsoft.NET.Build.Tasks/ResolvedFile.cs
Labels: untriaged, Area-NetSDK

#44695 Run 'AddImplicitDefineConstants' on 'BeforeCompile'
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
Labels: untriaged, Area-NetSDK

#44819 Revert "[main] Update triggers for SB sdk diff and license scan pipelines (#43011)
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#44826 Merging internal commits for release/6.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44825 Merging internal commits for release/6.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44832 Revert "Update triggers for SB sdk diff and license scan pipelines" (#43011)
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Area-Infrastructure, untriaged

#44824 Merging internal commits for release/8.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/dotnet-new.Tests/Approvals/sample03.optional-page.EnableContactPage=true.verified/sample03/Program.cs
  src/Tests/dotnet-new.Tests/Approvals/sample03.optional-page.verified/sample03/Program.cs
Labels: Area-Infrastructure, untriaged

#44823 Merging internal commits for release/8.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/dotnet-new.Tests/Approvals/sample03.optional-page.EnableContactPage=true.verified/sample03/Program.cs
  src/Tests/dotnet-new.Tests/Approvals/sample03.optional-page.verified/sample03/Program.cs
Labels: Area-Infrastructure, untriaged

#44821 Merging internal commits for release/8.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  src/Tests/dotnet-new.Tests/Approvals/sample03.optional-page.EnableContactPage=true.verified/sample03/Program.cs
  src/Tests/dotnet-new.Tests/Approvals/sample03.optional-page.verified/sample03/Program.cs
Labels: Area-Infrastructure, untriaged

#44857 Don't cloak the ANCM setup folder
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/assets/LicenseScanTests/LicenseExclusions.txt
  src/VirtualMonoRepo/source-mappings.json
Labels: untriaged, Area-VMR

#44859 Fix failing tests because of "UseUwpTools" property
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsDesktopProject.cs
Labels: Area-Infrastructure, untriaged

#44845 .NET 9 GA, MAUI baseline manifests
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44871 Update SB dev container image
  src/SourceBuild/content/.devcontainer/devcontainer.json
  src/SourceBuild/content/.devcontainer/prebuilt-sdk/devcontainer.json
Labels: Area-Infrastructure, untriaged

#44850 Fix images used for helix tests in CI
  .vsts-ci.yml
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildAWindowsDesktopProject.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorLegacyIntegrationTest60.cs
  test/Microsoft.NET.Sdk.Razor.Tests/BuildWithComponentsIntegrationTest.cs
Labels: Area-Infrastructure, untriaged

#44699 [dotnet-watch] Separate build from run
  eng/Versions.props
  src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs
  src/BuiltInTools/dotnet-watch/FileItem.cs
  src/BuiltInTools/dotnet-watch/Filters/BuildEvaluator.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/ProjectLauncher.cs
  src/BuiltInTools/dotnet-watch/HotReload/ProjectNodeMap.cs
  src/BuiltInTools/dotnet-watch/HotReload/RunningProject.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/FileWatcher.cs
  src/BuiltInTools/dotnet-watch/Internal/IReporter.cs
  src/BuiltInTools/dotnet-watch/Internal/MsBuildFileSetFactory.cs
  src/BuiltInTools/dotnet-watch/Internal/PhysicalConsole.cs
  src/BuiltInTools/dotnet-watch/Properties/launchSettings.json
  src/BuiltInTools/dotnet-watch/Utilities/BuildUtilities.cs
  test/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
  test/Microsoft.NET.TestFramework/TestAsset.cs
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.AppHost/WatchAspire.AppHost.csproj
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.ServiceDefaults/WatchAspire.ServiceDefaults.csproj
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/HotReload/RuntimeProcessLauncherTests.cs
  test/dotnet-watch.Tests/MSBuildEvaluationFilterTest.cs
  test/dotnet-watch.Tests/Utilities/TestReporter.cs
  test/dotnet-watch.Tests/Watch/GlobbingAppTests.cs
  test/dotnet-watch.Tests/Watch/Utilities/WatchableApp.cs
Labels: untriaged, Area-AspNetCore

#44918 Distribute 9.0 stable packs in 10.0 SDK
  eng/Versions.props
  eng/restore-toolset.ps1
  eng/restore-toolset.sh
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure, untriaged

#44834 Update implicit versions and to GA
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#44780 Remove the 9.0 template
  eng/Versions.props
  src/Installer/redist-installer/targets/BundledTemplates.targets
Labels: Area-Infrastructure, untriaged

#44853 tool-install: Avoid duplicate sources
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  test/TestAssets/TestProjects/NuGetConfigRandomPackageSources/NuGet.config
  test/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
Labels: untriaged, Area-Tools

#44930 Work around concurrency issue in COM API
  eng/pipelines/templates/jobs/sdk-job-matrix.yml
  src/Cli/dotnet/commands/dotnet-workload/list/VisualStudioWorkloads.cs
Labels: untriaged, Area-Workloads

#44924 [VMR] Enable building Mono Cross AOT verticals
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/repo-projects/runtime.proj
  src/SourceBuild/patches/runtime/0001-mono-Fix-output-directory-for-cross-compilers-if-Out.patch
Labels: Area-Infrastructure, untriaged

#44807 [release/9.0.1xx] Update Windows SDK projection
  eng/ManualVersions.props
Labels: Area-Infrastructure, untriaged

#44896 Remove eventlistener guard
  test/HelixTasks/AssemblyScheduler.cs
Labels: Area-Infrastructure, untriaged

#44938 [CP to release/9.0.2xx] Run 'AddImplicitDefineConstants' on 'BeforeCompile'
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
Labels: Area-Infrastructure, untriaged

#44964 tool-install: Fix NuGet Feed test
  test/TestAssets/TestProjects/NuGetConfigRandomPackageSources/NuGet.config
  test/dotnet.Tests/CommandTests/ToolInstallGlobalOrToolPathCommandTests.cs
Labels: Area-Infrastructure, untriaged

#44927 Workaround for MSBuildProjectLoader.LoadProjectInfoAsync throwing on unrecognized project language
  src/BuiltInTools/dotnet-watch/HotReload/IncrementalMSBuildWorkspace.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
Labels: untriaged, Area-AspNetCore

#44829 Remove 6 from the branch codeflow
  github-merge-flow.jsonc
Labels: Area-Infrastructure, untriaged

#44973 Split GivenThatWeWantToRunILLink test class into multiple so Helix can run them separately
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToRunILLink.cs
Labels: untriaged, Area-ILLink

#44965 Write APICompat suppressions when baseline suppressions aren't empty
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/SuppressionFileHelper.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/ISuppressionEngine.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Logging/SuppressionEngine.cs
  test/Microsoft.DotNet.ApiCompatibility.Tests/Logging/SuppressionEngineTests.cs
Labels: untriaged, Area-ApiCompat

#44986 Add .npmrc to prevent npmjs usage, even accidentally
  test/TestAssets/TestProjects/ProjectWithEsProjReference/.npmrc
Labels: Area-Infrastructure, untriaged

#44976 [StaticWebAssets] Detects pre-compressed assets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets
  src/StaticWebAssetsSdk/Tasks/Compression/DiscoverPrecompressedAssets.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DiscoverPrecompressedAssetsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ResolveCompressedAssetsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_Detects_PrecompressedAssets.Build.files.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_Detects_PrecompressedAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishWorks_With_PrecompressedAssets.Build.files.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/PublishWorks_With_PrecompressedAssets.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsCompressionIntegrationTest.cs
Labels: Servicing-consider, Area-AspNetCore

#45003 Update Source-Build SDK Diff Tests Baselines
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/assets/SdkContentTests/MsftToSbSdkFiles.diff
Labels: Area-Infrastructure, untriaged

#44989 Allow nuget-client test binaries
  src/SourceBuild/content/eng/allowed-vmr-binaries.txt
Labels: Area-Infrastructure, untriaged

#45015 [release/9.0.1xx] Using ConsoleLogger to prevent unexpected behavior
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
Labels: Servicing-approved, untriaged, Area-CLI

#44730 Enable test timeout dump collection
  src/Cli/Microsoft.DotNet.Cli.Utils/ForwardingAppImplementation.cs
  src/Cli/Microsoft.DotNet.Cli.Utils/Muxer.cs
  test/ArgumentForwarding.Tests/ArgumentForwardingTests.cs
  test/HelixTasks/AssemblyScheduler.cs
  test/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
Labels: Area-Infrastructure, untriaged

#44159 [StaticWebAssets] Improve globbing match performance
  src/StaticWebAssetsSdk/Tasks/Compression/ResolveCompressedAssets.cs
  src/StaticWebAssetsSdk/Tasks/ComputeReferenceStaticWebAssetItems.cs
  src/StaticWebAssetsSdk/Tasks/ComputeStaticWebAssetsForCurrentProject.cs
  src/StaticWebAssetsSdk/Tasks/Data/ContentTypeMapping.cs
  src/StaticWebAssetsSdk/Tasks/Data/ContentTypeProvider.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAsset.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetPathPattern.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetPathSegment.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetSegmentPart.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssetEndpoints.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.cs
  src/StaticWebAssetsSdk/Tasks/FilterStaticWebAssetEndpoints.cs
  src/StaticWebAssetsSdk/Tasks/FingerprintPatternMatcher.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetsPropsFile.cs
  src/StaticWebAssetsSdk/Tasks/Legacy/GenerateStaticWebAssetsPropsFile50.cs
  src/StaticWebAssetsSdk/Tasks/Legacy/ValidateStaticWebAssetsUniquePaths.cs
  src/StaticWebAssetsSdk/Tasks/Microsoft.NET.Sdk.StaticWebAssets.Tasks.csproj
  src/StaticWebAssetsSdk/Tasks/ResolveFingerprintedStaticWebAssetEndpointsForAssets.cs
  src/StaticWebAssetsSdk/Tasks/ScopedCss/ComputeCssScope.cs
  src/StaticWebAssetsSdk/Tasks/ScopedCss/ConcatenateCssFiles.cs
  src/StaticWebAssetsSdk/Tasks/ScopedCss/ConcatenateCssFiles50.cs
  src/StaticWebAssetsSdk/Tasks/ScopedCss/RewriteCss.cs
  src/StaticWebAssetsSdk/Tasks/ServiceWorker/GenerateServiceWorkerAssetsManifest.cs
  src/StaticWebAssetsSdk/Tasks/UpdateStaticWebAssetEndpoints.cs
  src/StaticWebAssetsSdk/Tasks/Utils/Globbing/GlobMatch.cs
  src/StaticWebAssetsSdk/Tasks/Utils/Globbing/GlobNode.cs
  src/StaticWebAssetsSdk/Tasks/Utils/Globbing/PathTokenizer.cs
  src/StaticWebAssetsSdk/Tasks/Utils/Globbing/StaticWebAssetGlobMatcher.cs
  src/StaticWebAssetsSdk/Tasks/Utils/Globbing/StaticWebAssetGlobMatcherBuilder.cs
  src/StaticWebAssetsSdk/Tasks/Utils/OSPath.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ContentTypeProviderTests.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DefineStaticWebAssetEndpointsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/FingerprintPatternMatcherTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/GenerateStaticWebAssetEndpointsManifestTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/Globbing/PathTokenizerTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/Globbing/StaticWebAssetGlobMatcherTest.Compatibility.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/Globbing/StaticWebAssetGlobMatcherTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/StaticWebAssetPathPatternTest.cs
Labels: untriaged, Area-AspNetCore

#44916 Remove `global::` from generated global usings
  src/Tasks/Microsoft.NET.Build.Tasks/GenerateGlobalUsings.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_BlazorWasm.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_DotNet.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_WebApp.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateGlobalUsings_Worker.cs
Labels: untriaged, Area-ImplicitUsings

#45018 Update vs-solutionpersistence to 1.0.23
  Directory.Packages.props
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#44995 Remove AspNET substraction logic
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#45124 Add accidentally removed JS functions back
  src/BuiltInTools/BrowserRefresh/WebSocketScriptInjection.js
Labels: Area-Infrastructure, untriaged

#45133 Fail in case of hybrid projects (new testing platform and vstest) in dotnet test
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/ModuleMessage.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/ModuleMessageSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/MSBuildConnectionHandler.cs
  src/Cli/dotnet/commands/dotnet-test/Models.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.CrossTargeting.targets/ImportAfter/Microsoft.TestPlatform.CrossTargeting.targets
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.targets/ImportAfter/Microsoft.TestPlatform.ImportAfter.targets
  src/Tasks/Microsoft.NET.Build.Tasks/GetTestsProject.cs
Labels: Area-Infrastructure, Area-DotNet Test

#45130 randomize GetTestDestinationDirectoryPath
  test/Microsoft.NET.TestFramework/TestAssetsManager.cs
Labels: Area-Infrastructure, untriaged

#45149 Add option to include/exclude previews to workload search version command Fixes #43890
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchVersionsCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchVersionsCommandParser.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkFeatureBand.cs
Labels: untriaged, Area-Workloads

#45129 Improve error experience for Restore command without a project
  src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs
Labels: untriaged, Area-Workloads

#45095 Refresh browser for all transitively referencing projects
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/ScopedCssFileHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/StaticFileHandler.cs
  src/BuiltInTools/dotnet-watch/Utilities/ProjectGraphNodeExtensions.cs
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Components/App.razor
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Components/Layout/MainLayout.razor
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Components/Layout/MainLayout.razor.css
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Components/Layout/NavMenu.razor
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Components/Layout/NavMenu.razor.css
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Components/Pages/Home.razor
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Components/Routes.razor
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Components/_Imports.razor
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Program.cs
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/Properties/launchSettings.json
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/RazorApp.csproj
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorApp/wwwroot/app.css
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorClassLibrary/Components/Example.razor
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorClassLibrary/Components/Example.razor.css
  test/TestAssets/TestProjects/WatchRazorWithDeps/RazorClassLibrary/RazorClassLibrary.csproj
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
Labels: untriaged, Area-AspNetCore

#44899 Factor Hot Reload agent implementation into a source package
  sdk.sln
  src/BuiltInTools/DotNetDeltaApplier/Microsoft.Extensions.DotNetDeltaApplier.csproj
  src/BuiltInTools/DotNetDeltaApplier/StartupHook.cs
  src/BuiltInTools/HotReloadAgent.Package/Microsoft.DotNet.HotReload.Agent.Package.csproj
  src/BuiltInTools/HotReloadAgent/AgentMessageSeverity.cs
  src/BuiltInTools/HotReloadAgent/AgentReporter.cs
  src/BuiltInTools/HotReloadAgent/HotReloadAgent.cs
  src/BuiltInTools/HotReloadAgent/MetadataUpdateHandlerInvoker.cs
  src/BuiltInTools/HotReloadAgent/Microsoft.DotNet.HotReload.Agent.projitems
  src/BuiltInTools/HotReloadAgent/Microsoft.DotNet.HotReload.Agent.shproj
  src/BuiltInTools/HotReloadAgent/ResponseLoggingLevel.cs
  src/BuiltInTools/HotReloadAgent/UpdateDelta.cs
  src/BuiltInTools/dotnet-watch.slnf
  src/BuiltInTools/dotnet-watch/HotReload/BlazorWebAssemblyDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/DeltaApplier.cs
  src/BuiltInTools/dotnet-watch/HotReload/NamedPipeContract.cs
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  test/Microsoft.Extensions.DotNetDeltaApplier.Tests/HotReloadAgentTest.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToControlGeneratedAssemblyInfo.cs
  test/dotnet-watch.Tests/HotReload/UpdatePayloadTests.cs
Labels: untriaged, Area-AspNetCore

#45154 [VMR] Add verticals for Linux/Windows NativeAOT runtime packs
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#45180 Adding Microsoft.Testing.Platform dependencies
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#45194 Fix TargetRid for Mono CrossAOT Alpine arm64 build
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#45198 VMR: Set outputParentDirectory for 1ES outputs
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/steps/vmr-pull-updates.yml
Labels: Area-Infrastructure, untriaged

#45109 Re-enable scenario-tests execution in VMR
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/scenario-tests.proj
  src/SourceBuild/content/test/tests.proj
Labels: Area-Infrastructure, untriaged

#45219 [WASI] Remove apphost to align with other mobile targets
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
Labels: Area-Infrastructure, untriaged, arch-wasm

#45186 Bump darc
  .config/dotnet-tools.json
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#45224 fix hanging issue in dotnet test --coverage
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
Labels: Area-DotNet Test, untriaged
