Repository dotnet/sdk, pull requests merged in 2025-10, with the labels that each got.

#51082 Add `.slnx` to default `.editorconfig` template
  template_feed/Microsoft.DotNet.Common.ItemTemplates/content/EditorConfig/Dotnet/.editorconfig
  test/dotnet-new.IntegrationTests/Approvals/AllCommonItemsCreate.-o#EditorConfig-file#-n#item.verified/EditorConfig-file/.editorconfig
Labels: Area-Infrastructure

#51118 Fix 2xx builds
  src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers.sarif
Labels: Area-Infrastructure

#51120 Remove dnx.ps1
  src/Layout/redist/dnx.ps1
  src/Layout/redist/targets/GenerateInstallerLayout.targets
Labels: Servicing-approved, breaking-change, needs-breaking-change-doc-created

#51114 Have copilot handle formatting better
  .github/copilot-instructions.md
Labels: Area-Infrastructure

#51150 Update branding to 8.0.416
  eng/Versions.props
Labels: Area-Containers
