Repository dotnet/sdk, pull requests merged in 2025-05, with the labels that each got.

#48797 Adjust dotnet test UX (for MTP)
  src/Cli/dotnet/Commands/Test/Terminal/TerminalTestReporter.cs
  src/Cli/dotnet/Commands/Test/Terminal/TestProgressState.cs
  src/Cli/dotnet/Commands/Test/TestApplicationEventHandlers.cs
  test/TestAssets/TestProjects/TestAppSimpleWithRetry/TestAppSimpleWithRetry.csproj
  test/TestAssets/TestProjects/TestAppSimpleWithRetry/TestClass1.cs
  test/TestAssets/TestProjects/TestAppSimpleWithRetry/dotnet.config
  test/dotnet.Tests/CommandTests/Test/GivenDotnetTestBuildsAndRunsTests.cs
Labels: Area-dotnet test

#48800 Fix build ordering issue when dotnet-sdk depends on redist
  src/Layout/VS.Redist.Common.Net.Core.SDK.RuntimeAnalyzers/VS.Redist.Common.Net.Core.SDK.RuntimeAnalyzers.proj
  src/Layout/pkg/dotnet-sdk.proj
  src/Layout/redist/targets/Crossgen.targets
  src/Layout/redist/targets/GenerateArchives.targets
  src/Layout/redist/targets/GenerateInstallerLayout.targets
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/GenerateMSIs.targets
  src/Layout/redist/targets/GeneratePKG.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure

#48803 [10.0.1xx-preview4] Propagate DotNetReleaseShipping to the vertical manifests
  src/SourceBuild/content/eng/Publishing.props
Labels: Area-VMR

#48798 Add RoslynCompilerType Vbc tests
  test/Microsoft.NET.Build.Tests/RoslynBuildTaskTests.cs
  test/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
  test/TestAssets/ProjectConstruction/NetFrameworkProjectVB/NetFrameworkProject.vbproj
Labels: Area-Infrastructure

#48437 Update multi-file 'dotnet run file' documentation
  documentation/general/dotnet-run-file.md
Labels: documentation, untriaged, Area-run-file

#48815 sln-add: --include-references when adding a project
  src/Cli/dotnet/Commands/CliCommandStrings.resx
  src/Cli/dotnet/Commands/Solution/Add/SolutionAddCommand.cs
  src/Cli/dotnet/Commands/Solution/Add/SolutionAddCommandParser.cs
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.cs.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.de.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.es.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.fr.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.it.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.ja.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.ko.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.pl.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.pt-BR.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.ru.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.tr.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.zh-Hans.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.zh-Hant.xlf
  test/TestAssets/TestProjects/SlnFileWithReferencedProjects/A/A.csproj
  test/TestAssets/TestProjects/SlnFileWithReferencedProjects/App.sln
  test/TestAssets/TestProjects/SlnFileWithReferencedProjects/App.slnx
  test/TestAssets/TestProjects/SlnFileWithReferencedProjects/B/B.csproj
  test/dotnet.Tests/CommandTests/Solution/Add/GivenDotnetSlnAdd.cs
  test/dotnet.Tests/CompletionTests/snapshots/bash/DotnetCliSnapshotTests.VerifyCompletions.verified.sh
  test/dotnet.Tests/CompletionTests/snapshots/pwsh/DotnetCliSnapshotTests.VerifyCompletions.verified.ps1
  test/dotnet.Tests/CompletionTests/snapshots/zsh/DotnetCliSnapshotTests.VerifyCompletions.verified.zsh
Labels: Area-CLI

#48749 Add file-based program API for use by IDE
  src/Cli/dotnet/Commands/Project/Convert/ProjectConvertCommand.cs
  src/Cli/dotnet/Commands/Run/Api/RunApiCommand.cs
  src/Cli/dotnet/Commands/Run/Api/RunApiCommandParser.cs
  src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs
  src/Cli/dotnet/Parser.cs
  test/Microsoft.NET.TestFramework/Commands/SdkCommandSpec.cs
  test/Microsoft.NET.TestFramework/Commands/TestCommand.cs
  test/dotnet.Tests/CommandTests/Project/Convert/DotnetProjectConvertTests.cs
  test/dotnet.Tests/CommandTests/Run/RunFileTests.cs
Labels: Area-run-file

#48611 sln-add: Don't add solution folders outside the scope of solution directory
  src/Cli/dotnet/commands/dotnet-sln/add/Program.cs
Labels: Servicing-approved, Area-CLI

#48722 macOS Installer: Update relese notes link
  src/Installer/redist-installer/packaging/osx/resources/cs.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/de.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/en.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/es.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/fr.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/it.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/ja.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/ko.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/pl.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/pt-br.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/ru.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/tr.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/zh-hans.lproj/conclusion.html
  src/Installer/redist-installer/packaging/osx/resources/zh-hant.lproj/conclusion.html
  src/Installer/redist-installer/targets/GeneratePKG.targets
Labels: Servicing-approved

#48922 Remove bad assert
  src/Cli/dotnet/Commands/Test/TestCommandParser.cs
Labels: Area-CLI

#48729 Ignore .slnx
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets
Labels: Servicing-approved

#48943 Update file-based program doc
  documentation/general/dotnet-run-file.md
Labels: documentation, Area-run-file

#48952 [StaticWebAssets] Add the cache files to the list of written files so they get deleted during clean
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.JSModules.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.Cache.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DiscoverStaticWebAssetsTest.cs
Labels: Area-AspNetCore

#48813 Ensure file-based program artifacts are restricted to the current user
  src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs
  test/dotnet.Tests/CommandTests/Run/RunFileTests.cs
Labels: Area-run-file

#46218 Include only PackageReferences included at runtime in deps.json
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenADependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/LockFiles/simpleApp.project.lock.json
  src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs
  src/Tasks/Microsoft.NET.Build.Tasks/PackageReferenceConverter.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildADesktopLibrary.cs
  test/TestAssets/TestProjects/RazorSimpleMvc22/SimpleMvc22.csproj
Labels: Area-Infrastructure, untriaged, breaking-change, needs-breaking-change-doc-created

#49020 [StaticWebAssets] Support disabling the task result caching, do not write the cache file if up to date or no assets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.JSModules.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.Cache.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_Can_DisableAssetCaching.Build.files.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsBaselines/Build_Can_DisableAssetCaching.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: Area-AspNetCore

#49041 Source package cleanup
  Directory.Build.targets
  eng/SourcePackage.editorconfig
  src/BuiltInTools/AspireService/.editorconfig
  src/BuiltInTools/AspireService/AspireServerService.cs
  src/BuiltInTools/AspireService/Contracts/IAspireServerEvents.cs
  src/BuiltInTools/AspireService/Helpers/CertGenerator.cs
  src/BuiltInTools/AspireService/Helpers/ExceptionExtensions.cs
  src/BuiltInTools/AspireService/Helpers/HttpContextExtensions.cs
  src/BuiltInTools/AspireService/Helpers/LoggerProvider.cs
  src/BuiltInTools/AspireService/Helpers/SocketConnectionManager.cs
  src/BuiltInTools/AspireService/Helpers/SocketUtilities.cs
  src/BuiltInTools/AspireService/Helpers/WebSocketConnection.cs
  src/BuiltInTools/AspireService/Models/ErrorResponse.cs
  src/BuiltInTools/AspireService/Models/InfoResponse.cs
  src/BuiltInTools/AspireService/Models/RunSessionRequest.cs
  src/BuiltInTools/AspireService/Models/SessionChangeNotification.cs
  src/BuiltInTools/HotReloadAgent.Data/.editorconfig
  src/BuiltInTools/HotReloadAgent.Data/AgentEnvironmentVariables.cs
  src/BuiltInTools/HotReloadAgent.Data/AgentMessageSeverity.cs
  src/BuiltInTools/HotReloadAgent.Data/ResponseLoggingLevel.cs
  src/BuiltInTools/HotReloadAgent.Data/StaticAssetUpdate.cs
  src/BuiltInTools/HotReloadAgent.Data/UpdateDelta.cs
  src/BuiltInTools/HotReloadAgent.PipeRpc/.editorconfig
  src/BuiltInTools/HotReloadAgent.PipeRpc/NamedPipeContract.cs
  src/BuiltInTools/HotReloadAgent.PipeRpc/StreamExtensions.cs
  src/BuiltInTools/HotReloadAgent/.editorconfig
  src/BuiltInTools/HotReloadAgent/AgentReporter.cs
  src/BuiltInTools/HotReloadAgent/HotReloadAgent.cs
  src/BuiltInTools/HotReloadAgent/MetadataUpdateHandlerInvoker.cs
Labels: Area-AspNetCore

#49025 Removing 9.0.2xx from codeflow
  github-merge-flow.jsonc
Labels: Area-CodeFlow

#48916 [browser/blazor] enable GenerateRuntimeConfigurationFiles
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIncrementalismTest.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
  test/Microsoft.NET.TestFramework/Utilities/FileThumbPrint.cs
  test/TestAssets/TestProjects/BlazorWasmWithLibrary/blazorwasm/App.razor
  test/TestAssets/TestProjects/BlazorWasmWithLibrary/blazorwasm/blazorwasm.csproj
  test/TestAssets/TestProjects/WatchBlazorWasm/App.razor
Labels: Area-AspNetCore, arch-wasm

#48909 Fix Hot Reload profile detection for web apps
  src/BuiltInTools/dotnet-watch/Browser/BrowserConnector.cs
  src/BuiltInTools/dotnet-watch/DotNetWatcher.cs
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfile.cs
  src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfileReader.cs
  src/BuiltInTools/dotnet-watch/HotReload/ProjectLauncher.cs
  src/BuiltInTools/dotnet-watch/Internal/IReporter.cs
  src/BuiltInTools/dotnet-watch/Utilities/ProjectGraphNodeExtensions.cs
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.AppHost/WatchAspire.AppHost.csproj
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.Wasm/App.razor
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.Wasm/Pages/Index.razor
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.Wasm/Program.cs
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.Wasm/Properties/launchSettings.json
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.Wasm/WatchAspire.Wasm.csproj
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.Wasm/_Imports.razor
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.Wasm/wwwroot/css/app.css
  test/TestAssets/TestProjects/WatchAspire/WatchAspire.Wasm/wwwroot/index.html
Labels: Area-AspNetCore

#45883 Fix the path check to ensure it correctly handles casing and character codes
  src/Tasks/sdk-tasks/ExtractArchiveToDirectory.cs
Labels: untriaged

#48966 Fix reporting rude edits
  src/BuiltInTools/dotnet-watch/HotReload/CompilationHandler.cs
  src/BuiltInTools/dotnet-watch/HotReload/RestartPrompt.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
  test/dotnet-watch.Tests/HotReload/CompilationHandlerTests.cs
Labels: Area-AspNetCore

#49073 [StaticWebAssets] Add file to FileWrites even when the content is the same in OverrideHtmlAssetPlaceholders
  src/StaticWebAssetsSdk/Tasks/OverrideHtmlAssetPlaceholders.cs
Labels: Area-AspNetCore

#49087 Update branding to p6
  eng/Versions.props
Labels: Area-CodeFlow

#48763 Enable container test execution
  .vsts-ci.yml
  .vsts-pr.yml
  eng/pipelines/templates/jobs/sdk-job-matrix.yml
  test/Microsoft.NET.TestFramework/EnvironmentInfo.cs
  test/dotnet.Tests/CommandTests/Workload/Restore/GivenDotnetWorkloadRestore.cs
  test/dotnet.Tests/CommandTests/Workload/Update/GivenDotnetWorkloadUpdate.cs
Labels: Area-Infrastructure

#49093 Change pr.yml -> sb-pr.yml
  src/SourceBuild/content/eng/pipelines/sb-pr.yml
Labels: Branch Lockdown

#49094 Change pr.yml -> sb-pr.yml
  src/SourceBuild/content/eng/pipelines/sb-pr.yml
Labels: Branch Lockdown

#49109 Use new SB secrets variable group
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/vmr-license-scan.yml
Labels: Branch Lockdown

#49124 Skip CanFilterAuthor_WithoutName test to unblock main
  test/dotnet-new.IntegrationTests/DotnetNewSearchTests.cs
Labels: Area-Infrastructure

#49159 Inner loop improvements
  Directory.Build.props
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  test/Directory.Build.targets
  test/UnitTests.proj
  test/dotnet.Tests/dotnet.Tests.csproj
  test/trustedroots.Tests/trustedroots.Tests.csproj
Labels: Area-Infrastructure

#49164 Fix API Diff args + async
  src/Compatibility/ApiDiff/Microsoft.DotNet.ApiDiff.Tool/Program.cs
  src/Compatibility/ApiDiff/Microsoft.DotNet.ApiDiff/FileOutputDiffGenerator.cs
  src/Compatibility/ApiDiff/Microsoft.DotNet.ApiDiff/IDiffGenerator.cs
  src/Compatibility/ApiDiff/Microsoft.DotNet.ApiDiff/MemoryOutputDiffGenerator.cs
  test/Microsoft.DotNet.ApiDiff.Tests/Diff.Base.Tests.cs
  test/Microsoft.DotNet.ApiDiff.Tests/Diff.Disk.Tests.cs
Labels: Area-ApiCompat
