Repository dotnet/sdk, pull requests merged in 2025-04, with the labels that each got.

#47874 Simplify exit code logic for dotnet test (MTP) and consider no results correctly as "zero tests ran"
  src/Cli/dotnet/Commands/Test/ExitCode.cs
  src/Cli/dotnet/Commands/Test/TestApplicationActionQueue.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestBasedOnGlobbingFilter.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsForMultipleTFMs.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
Labels: Area-Infrastructure, untriaged

#48059 Fix using undefined property in GeneratePKG.targets
  src/Layout/redist/targets/GeneratePKG.targets
Labels: Area-Infrastructure, untriaged

#48044 Revert arm64 queue to MacOS 13 due to limited capacity
  .vsts-ci.yml
  .vsts-pr.yml
Labels: Area-Infrastructure, untriaged

#48015 Installer job should fail if tests have failed
  eng/pipelines/templates/stages/vmr-validation.yml
  eng/pipelines/templates/steps/vmr-validate-installers.yml
Labels: Area-Infrastructure, untriaged

#48033 Only publish FSharp packages when needed
  eng/Publishing.props
Labels: Area-Infrastructure, untriaged

#48080 Tweak baseline based on newest build
  eng/vmr-msft-comparison-baseline.json
Labels: Area-Infrastructure, untriaged

#48040 Update baseline for VS redist assets
  eng/vmr-msft-comparison-baseline.json
Labels: Area-Infrastructure, untriaged

#48071 Don't use colon in dotnet.config
  src/Cli/dotnet/Commands/Test/TestCommandParser.cs
  test/TestAssets/TestProjects/HybridTestRunnerTestProjects/dotnet.config
  test/TestAssets/TestProjects/MSTestMetaPackageProjectWithMultipleTFMsSolution/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithDifferentFailures/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithDiscoveredTests/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithTests/dotnet.config
  test/TestAssets/TestProjects/MultipleTestProjectSolution/dotnet.config
  test/TestAssets/TestProjects/MultipleTestProjectsWithoutSolution/dotnet.config
  test/TestAssets/TestProjects/ProjectSolutionForMultipleTFMs/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolution/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolutionWithCodeCoverage/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolutionWithTestsAndArtifacts/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithClassLibrary/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithConditionOnGlobalProperty/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithDiscoveredTests/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsSolution/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithTests/dotnet.config
Labels: Area-Infrastructure, untriaged

#48030 Use PackageDownload in GeneratePackagePruneData
  src/Layout/redist/targets/GeneratePackagePruneData.targets
  src/Tasks/Microsoft.NET.Build.Tasks/CollatePackageDownloads.cs
  src/Tasks/sdk-tasks/CollatePackageDownloads.cs
  src/Tasks/sdk-tasks/GeneratePackagePruneDataDownloads.cs
Labels: untriaged

#48079 Fix layout path for pkg files
  src/Layout/redist-installer/targets/GeneratePKG.targets
Labels: Servicing-approved, Area-Infrastructure, untriaged

#48043 Added 30 to the width and X location to make sure there is room for the progress label
  src/Layout/pkg/windows/bundle.thm
Labels: Area-Infrastructure, untriaged

#47712 Use CDN Fixes #47503
  .vsts-ci.yml
  eng/Versions.props
  src/Layout/redist/targets/RestoreLayout.targets
Labels: Area-Infrastructure, untriaged

#48074 Reuse specific job artifacts in installer test jobs
  eng/pipelines/templates/stages/vmr-validation.yml
  eng/pipelines/templates/steps/vmr-validate-installers.yml
Labels: Area-Infrastructure, untriaged

#48101 Use `dotnet/runtime-deps` images instead of `dotnet/nightly/runtime-deps` for AOT
  src/Containers/Microsoft.NET.Build.Containers/Tasks/ComputeDotnetBaseImageAndTag.cs
  test/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: untriaged, Area-Containers

#48104 Add logic to track SBRP project references in the SBRPUsageReport
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/WriteSbrpUsageReport.cs
Labels: Area-Infrastructure, untriaged

#47744 Improve Post-Build Signing Validation in the VMR
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/stages/vmr-validation.yml
  eng/pipelines/templates/steps/vmr-validate-signing.yml
  src/SourceBuild/content/eng/SignCheckExclusionsFile.txt
  src/SourceBuild/content/eng/signing-validation.proj
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/SigningValidation.cs
Labels: Area-Infrastructure, untriaged

#48111 Update branding to 9.0.204
  eng/Versions.props
Labels: Area-Infrastructure, Branding

#48105 Publish productVersion.txt for all repos
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsAssetSelector.cs
Labels: untriaged, Area-VMR

#48107 Update branding to 8.0.116
  eng/Versions.props
Labels: Area-Infrastructure

#48108 Update branding to 8.0.312
  eng/Versions.props
Labels: Area-Infrastructure

#48109 Update branding to 8.0.409
  eng/Versions.props
Labels: Area-Infrastructure

#48110 Update branding to 9.0.106
  eng/Versions.props
Labels: Area-Infrastructure

#48075 Add ux for retry in dotnet test
  src/Cli/dotnet/Commands/Test/LocalizableStrings.resx
  src/Cli/dotnet/Commands/Test/Terminal/AnsiTerminalTestProgressFrame.cs
  src/Cli/dotnet/Commands/Test/Terminal/NonAnsiTerminal.cs
  src/Cli/dotnet/Commands/Test/Terminal/TerminalTestReporter.cs
  src/Cli/dotnet/Commands/Test/Terminal/TestProgressState.cs
  src/Cli/dotnet/Commands/Test/TestApplicationEventHandlers.cs
  src/Cli/dotnet/Commands/Test/TestingPlatformCommand.cs
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#47924 Update to the latest application insights
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47398 Force OCI format for inner images when publishing tarballs or to local docker instances
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: Servicing-approved, Area-Containers

#48146 Remove duplicated azl cert declarations
  src/SourceBuild/patches/runtime/0001-Remove-specific-AZL-sign-certs.patch
Labels: Area-Infrastructure, untriaged

#48147 Fix truncated symbols paths in log output from CreateSdkSymbolsLayout
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/CreateSdkSymbolsLayout.cs
Labels: Area-Infrastructure, untriaged

#47915 [StaticWebAssets] Generate Link elements based on StaticWebAssets manifest properties
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.HtmlAssetPlaceholders.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/OverrideHtmlAssetPlaceholders.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/OverrideHtmlAssetPlaceholdersTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsFingerprintingTest.cs
  test/TestAssets/TestProjects/VanillaWasm/VanillaWasm.csproj
  test/TestAssets/TestProjects/VanillaWasm/wwwroot/index.html
Labels: Area-AspNetCore

#47833 [StaticWebAssets] Make all the properties in StaticWebAssetEndpoint lazy
  src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs
  src/StaticWebAssetsSdk/Tasks/CollectStaticWebAssetsToCopy.cs
  src/StaticWebAssetsSdk/Tasks/Compression/DiscoverPrecompressedAssets.cs
  src/StaticWebAssetsSdk/Tasks/Compression/ResolveCompressedAssets.cs
  src/StaticWebAssetsSdk/Tasks/ComputeEndpointsForReferenceStaticWebAssets.cs
  src/StaticWebAssetsSdk/Tasks/ComputeReferenceStaticWebAssetItems.cs
  src/StaticWebAssetsSdk/Tasks/ComputeStaticWebAssetsForCurrentProject.cs
  src/StaticWebAssetsSdk/Tasks/ComputeStaticWebAssetsTargetPaths.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAsset.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpoint.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.Cache.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.cs
  src/StaticWebAssetsSdk/Tasks/FilterStaticWebAssetEndpoints.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetEndpointsManifest.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetEndpointsPropsFile.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetsManifest.cs
  src/StaticWebAssetsSdk/Tasks/MergeConfigurationProperties.cs
  src/StaticWebAssetsSdk/Tasks/MergeStaticWebAssets.cs
  src/StaticWebAssetsSdk/Tasks/ResolveFingerprintedStaticWebAssetEndpointsForAssets.cs
  src/StaticWebAssetsSdk/Tasks/ResolveStaticWebAssetEndpointRoutes.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ComputeEndpointsForReferenceStaticWebAssetsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ComputeReferenceStaticWebAssetItemsTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ComputeStaticWebAssetsForCurrentProjectTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/GenerateStaticWebAssetEndpointsPropsFileTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ResolveFingerprintedStaticWebAssetEndpointsForAssetsTest.cs
Labels: untriaged, Area-AspNetCore

#47956 Make it possible to prep other RIDs and architectures
  src/SourceBuild/content/prep-source-build.sh
Labels: Area-Infrastructure, untriaged

#47611 Update to AwesomeAssertions
  Directory.Packages.props
  eng/Signing.props
  eng/Versions.props
  src/Tasks/Microsoft.NET.Build.Extensions.Tasks.UnitTests/Microsoft.NET.Build.Extensions.Tasks.UnitTests.csproj
  src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
  test/ArgumentsReflector/ArgumentsReflector.csproj
  test/Directory.Build.props
  test/HelixTasks/HelixTasks.csproj
  test/Microsoft.NET.Build.Containers.IntegrationTests/Microsoft.NET.Build.Containers.IntegrationTests.csproj
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  test/Microsoft.NET.Build.Tests/GivenThereAreDefaultItems.cs
  test/Microsoft.NET.Build.Tests/Microsoft.NET.Build.Tests.csproj
  test/Microsoft.NET.Clean.Tests/Microsoft.NET.Clean.Tests.csproj
  test/Microsoft.NET.Pack.Tests/Microsoft.NET.Pack.Tests.csproj
  test/Microsoft.NET.Publish.Tests/Microsoft.NET.Publish.Tests.csproj
  test/Microsoft.NET.Rebuild.Tests/Microsoft.NET.Rebuild.Tests.csproj
  test/Microsoft.NET.Restore.Tests/Microsoft.NET.Restore.Tests.csproj
  test/Microsoft.NET.Sdk.BlazorWebAssembly.AoT.Tests/Microsoft.NET.Sdk.BlazorWebAssembly.AoT.Tests.csproj
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests.csproj
  test/Microsoft.NET.Sdk.Razor.Tests/Microsoft.NET.Sdk.Razor.Tests.csproj
  test/Microsoft.NET.Sdk.Web.Tests/Microsoft.NET.Sdk.Web.Tests.csproj
  test/Microsoft.NET.TestFramework/Assertions/AssemblyAssertions.cs
  test/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs
  test/Microsoft.NET.TestFramework/Assertions/DirectoryInfoAssertions.cs
  test/Microsoft.NET.TestFramework/Assertions/FileInfoAssertions.cs
  test/Microsoft.NET.TestFramework/Assertions/StringAssertionsExtensions.cs
  test/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
  test/Microsoft.NET.ToolPack.Tests/Microsoft.NET.ToolPack.Tests.csproj
  test/Microsoft.Net.Sdk.AnalyzerRedirecting.Tests/Microsoft.Net.Sdk.AnalyzerRedirecting.Tests.csproj
  test/Microsoft.Win32.Msi.Manual.Tests/Microsoft.Win32.Msi.Manual.Tests.csproj
  test/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
  test/System.CommandLine.StaticCompletions.Tests/System.CommandLine.StaticCompletions.Tests.csproj
  test/TestAssets/TestProjects/MultiDependentProject/MultiDependentProject.csproj
  test/UnitTests.proj
  test/dotnet-MsiInstallation.Tests/Framework/RemoteDirectory.cs
  test/dotnet-MsiInstallation.Tests/Framework/RemoteFile.cs
  test/dotnet-MsiInstallation.Tests/dotnet-MsiInstallation.Tests.csproj
  test/dotnet-new.Tests/dotnet-new.IntegrationTests.csproj
  test/dotnet-run.Tests/GivenDotnetRunBuildsCsProj.cs
  test/dotnet-run.Tests/GivenDotnetRunBuildsVbProj.cs
  test/trustedroots.Tests/trustedroots.Tests.csproj
Labels: Area-Infrastructure, untriaged

#47979 Improve MTP dotnet test exit code messages
  src/Cli/dotnet/Commands/Test/ExitCode.cs
  src/Cli/dotnet/Commands/Test/LocalizableStrings.resx
  src/Cli/dotnet/Commands/Test/Terminal/TerminalTestReporter.cs
  src/Cli/dotnet/Commands/Test/TestingPlatformCommand.cs
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/Commands/Test/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#48166 Disable synchronization of sourcelink to the VMR
  src/VirtualMonoRepo/source-mappings.json
Labels: Area-Infrastructure, untriaged

#48153 Do not use live shims for tools packages in VMR
  Directory.Build.targets
  src/BuiltInTools/dotnet-format/dotnet-format.csproj
Labels: Area-Infrastructure, untriaged

#48142 Auto enable retry when detected
  src/Cli/dotnet/Commands/Test/Terminal/TerminalTestReporter.cs
Labels: Area-Infrastructure, untriaged

#38091 Hide stack on WorkloadResolver constructor error
  src/Cli/dotnet/Parser.cs
Labels: Area-SdkResolvers

#48186 Update package-table.md
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#48039 Allow additional package types with PackAsTool
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
  test/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProject.cs
Labels: Area-Infrastructure, untriaged

#48063 Basic support for launchSettings in the new dotnet test
  src/Cli/dotnet/Commands/Test/CliConstants.cs
  src/Cli/dotnet/Commands/Test/MSBuildUtility.cs
  src/Cli/dotnet/Commands/Test/Models.cs
  src/Cli/dotnet/Commands/Test/Options.cs
  src/Cli/dotnet/Commands/Test/SolutionAndProjectUtility.cs
  src/Cli/dotnet/Commands/Test/TestApplication.cs
  src/Cli/dotnet/Commands/Test/TestCommandParser.cs
  src/Cli/dotnet/Commands/Test/TestModulesFilterHandler.cs
  src/Cli/dotnet/Commands/Test/TestingPlatformOptions.cs
  test/TestAssets/TestProjects/TestProjectWithLaunchSettings/Program.cs
  test/TestAssets/TestProjects/TestProjectWithLaunchSettings/Properties/launchSettings.json
  test/TestAssets/TestProjects/TestProjectWithLaunchSettings/TestProjectWithLaunchSettings.csproj
  test/TestAssets/TestProjects/TestProjectWithLaunchSettings/dotnet.config
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
Labels: Area-Infrastructure, untriaged

#48102 Make some targets in redist incremental
  src/Layout/redist/targets/GenerateLayout.targets
  src/Tasks/sdk-tasks/RemoveAssetFromDepsPackages.cs
Labels: Area-Infrastructure, untriaged

#48187 Update README.md
  README.md
Labels: Area-Infrastructure, untriaged

#48097 Simplify logic around _MTPBuild target
  src/Cli/dotnet/Commands/Test/MSBuildUtility.cs
  src/Cli/dotnet/Commands/Test/TestingPlatformOptions.cs
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.CrossTargeting.targets/ImportAfter/Microsoft.TestPlatform.CrossTargeting.targets
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.targets/ImportAfter/Microsoft.TestPlatform.ImportAfter.targets
Labels: Area-Infrastructure, untriaged

#48167 [release/9.0.3xx] Open Test1.cs in Visual Studio, not MSTestSettings.cs
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/content/MSTest-CSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/content/MSTest-FSharp/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/content/MSTest-VisualBasic/.template.config/template.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.9.0/content/Playwright-MSTest-CSharp/.template.config/template.json
Labels: Area-Infrastructure, untriaged

#48168 Fix incorrect index in MSTest template
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-CSharp/.template.config/template.json
Labels: Area-Infrastructure

#48224 [StaticWebAssets] Additional endpoints were incorrectly being passed to consuming projects
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.References.targets
Labels: Area-Infrastructure, untriaged

#48218 Keep artifact directory
  src/SourceBuild/content/eng/allowed-sb-binaries.txt
Labels: Area-Infrastructure, untriaged

#48227 Publish scenario-tests logs for installer tests
  eng/pipelines/templates/steps/vmr-validate-installers.yml
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/Config.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/LinuxInstallerTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/Microsoft.DotNet.Installer.Tests.csproj
Labels: Area-Infrastructure, untriaged

#48229 Ignore .dwarf files in signing validation
  src/SourceBuild/content/eng/SignCheckExclusionsFile.txt
Labels: Area-Infrastructure, untriaged

#48249 Fix productCommit(.txt|.json) content in VMR
  src/Layout/redist/targets/GenerateBundledVersions.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#48225 Remove `testfx` from VMR source mappings
  src/VirtualMonoRepo/source-mappings.json
Labels: Area-Infrastructure, untriaged

#48245 [GitHub Actions] Add synchronize Event
  .github/workflows/pr-analysis.yml
Labels: Area-Infrastructure, untriaged

#47996 Sign and harden pkgs
  eng/Signing.props
Labels: Area-Infrastructure, untriaged

#48246 dotnet test for MTP: Support TestTfmsInParallel
  src/Cli/dotnet/Commands/Test/CliConstants.cs
  src/Cli/dotnet/Commands/Test/MSBuildHandler.cs
  src/Cli/dotnet/Commands/Test/MSBuildUtility.cs
  src/Cli/dotnet/Commands/Test/Models.cs
  src/Cli/dotnet/Commands/Test/SolutionAndProjectUtility.cs
  src/Cli/dotnet/Commands/Test/TestApplicationActionQueue.cs
  src/Cli/dotnet/Commands/Test/TestModulesFilterHandler.cs
  src/Cli/dotnet/Commands/Test/TestingPlatformCommand.cs
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsParallelization/TestProject/Program.cs
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsParallelization/TestProject/TestProject.csproj
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsParallelization/TestProjectWithMultipleTFMsParallelization.sln
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsParallelization/dotnet.config
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsForMultipleTFMs.cs
Labels: Area-dotnet test, untriaged

#48316 Disable VMR synchronization for aspire
  src/VirtualMonoRepo/source-mappings.json
Labels: Area-Infrastructure, untriaged

#48184 Updating breaking change guidance
  documentation/project-docs/breaking-change-guidelines.md
Labels: Area-Infrastructure, untriaged

#48319 Enable arm64 DEB tests
  eng/pipelines/templates/stages/vmr-validation.yml
  eng/pipelines/templates/steps/vmr-validate-installers.yml
Labels: Area-Infrastructure

#48264 Make 'dotnet run file' tests runnable on localized machines
  test/dotnet-project-convert.Tests/DotnetProjectConvertTests.cs
  test/dotnet-run.Tests/RunFileTests.cs
Labels: untriaged, Area-run-file

#48306 dotnet test for MTP: Normalize TFMs
  src/Cli/dotnet/Commands/Test/SolutionAndProjectUtility.cs
Labels: Area-Infrastructure, untriaged

#48304 Support --no-launch-profile-arguments in dotnet test for MTP
  src/Cli/dotnet/Commands/Test/MSBuildUtility.cs
  src/Cli/dotnet/Commands/Test/Options.cs
  src/Cli/dotnet/Commands/Test/TestApplication.cs
  src/Cli/dotnet/Commands/Test/TestCommandParser.cs
  src/Cli/dotnet/Commands/Test/TestingPlatformOptions.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
Labels: Area-dotnet test, untriaged

#48065 [dotnet test for MTP] Throw exception if the project doesn't produce executable
  src/Cli/dotnet/Commands/Test/CliConstants.cs
  src/Cli/dotnet/Commands/Test/TestApplication.cs
Labels: Area-Infrastructure, untriaged

#48350 Remove compiler toolset opt-out and move properties
  src/SourceBuild/content/repo-projects/roslyn.proj
Labels: Area-Infrastructure, untriaged

#47508 Fix dotnet format failure to handle slnx files
  src/BuiltInTools/dotnet-format/Workspaces/MSBuildWorkspaceFinder.cs
  test/TestAssets/dotnet-format/for_workspace_finder/multiple_solutions/solution_c.slnx
  test/TestAssets/dotnet-format/for_workspace_finder/single_slnx/single_slnx.slnx
  test/dotnet-format.Tests/tests/MSBuild/MSBuildWorkspaceFinderTests.cs
Labels: Servicing-approved, Area-NetSDK

#48355 Inline DotNetBuild.props settings into the repo
  Directory.Build.props
  eng/Build.props
  eng/DotNetBuild.props
  src/Layout/redist/targets/Crossgen.targets
Labels: Area-Infrastructure, untriaged

#48322 Do not build SDK installers in source-build
  src/Layout/pkg/dotnet-sdk.proj
Labels: Area-Infrastructure, untriaged

#48266 Merging internal commits for release/9.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48389 Rename DISABLE_CROSSGEN
  build.cmd
  build.sh
  src/Layout/redist/targets/Crossgen.targets
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#48388 Add back Microsoft.NET.Workload.Emscripten.Current.Manifest.10.0.100-Transport package
  src/Workloads/Manifests/Directory.Build.props
  src/Workloads/Manifests/Directory.Build.targets
  src/Workloads/Manifests/Microsoft.NET.Workload.Emscripten.Current.Transport.Manifest/Microsoft.NET.Workload.Emscripten.Current.Transport.Manifest.proj
Labels: Area-Infrastructure, untriaged

#48390 Use pull_request_target event for GH Actions workflows
  .github/workflows/pr-analysis.yml
  .github/workflows/remove-lockdown-label.yml
Labels: Area-Infrastructure, untriaged

#48394 Remove scenario-tests from Version.Details.xml
  eng/Version.Details.xml
Labels: Area-Infrastructure

#47904 Remove unnecessary CA2022 suppressions
  test/dotnet.Tests/CommandTests/Solution/Add/GivenDotnetSlnAdd.cs
  test/dotnet.Tests/CommandTests/Solution/Remove/GivenDotnetSlnRemove.cs
Labels: Area-Infrastructure

#48085 tool install/update: Support package@version syntax
  src/Cli/dotnet/CliStrings.resx
  src/Cli/dotnet/Commands/Tool/Install/ParseResultExtension.cs
  src/Cli/dotnet/Commands/Tool/Install/ToolInstallCommand.cs
  src/Cli/dotnet/Commands/Tool/Install/ToolInstallCommandParser.cs
  src/Cli/dotnet/Commands/Tool/Install/ToolInstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/Commands/Tool/Install/ToolInstallLocalCommand.cs
  src/Cli/dotnet/Commands/Tool/Uninstall/ToolUninstallCommandParser.cs
  src/Cli/dotnet/Commands/Tool/Uninstall/ToolUninstallGlobalOrToolPathCommand.cs
  src/Cli/dotnet/Commands/Tool/Update/ToolUpdateCommand.cs
  src/Cli/dotnet/Commands/Tool/Update/ToolUpdateCommandParser.cs
  src/Cli/dotnet/Commands/Tool/Update/ToolUpdateGlobalOrToolPathCommand.cs
  src/Cli/dotnet/Commands/Tool/Update/ToolUpdateLocalCommand.cs
  src/Cli/dotnet/CommonArguments.cs
  src/Cli/dotnet/xlf/CliStrings.cs.xlf
  src/Cli/dotnet/xlf/CliStrings.de.xlf
  src/Cli/dotnet/xlf/CliStrings.es.xlf
  src/Cli/dotnet/xlf/CliStrings.fr.xlf
  src/Cli/dotnet/xlf/CliStrings.it.xlf
  src/Cli/dotnet/xlf/CliStrings.ja.xlf
  src/Cli/dotnet/xlf/CliStrings.ko.xlf
  src/Cli/dotnet/xlf/CliStrings.pl.xlf
  src/Cli/dotnet/xlf/CliStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CliStrings.ru.xlf
  src/Cli/dotnet/xlf/CliStrings.tr.xlf
  src/Cli/dotnet/xlf/CliStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CliStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/Tool/Install/InstallToolParserTests.cs
  test/dotnet.Tests/CommandTests/Tool/Uninstall/UninstallToolParserTests.cs
  test/dotnet.Tests/CommandTests/Tool/Update/UpdateToolParserTests.cs
  test/dotnet.Tests/CompletionTests/snapshots/zsh/DotnetCliSnapshotTests.VerifyCompletions.verified.zsh
Labels: Area-Infrastructure

#48398 Add synchronize event trigger to pr-analysis.yml
  .github/workflows/pr-analysis.yml
Labels: Area-Infrastructure, untriaged

#48397 Stop copying PSB reference packages
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/eng/finish-source-only.proj
  src/SourceBuild/content/eng/init-source-only.proj
  src/SourceBuild/content/eng/tools/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#48275 Update the sign check to remove the exclusions but only check on sign…
  src/Installer/redist-installer/targets/BundledManifests.targets
Labels: untriaged, Area-NetSDK

#48268 Merging internal commits for release/8.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48267 Merging internal commits for release/8.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48265 Merging internal commits for release/9.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48417 Copy logs on failure in vmr-join-verticals.yml
  eng/pipelines/templates/steps/vmr-join-verticals.yml
Labels: Area-Infrastructure, untriaged

#48419 Remove emsdk sb intermediate from Version.Details.xml
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#48422 Build emsdk in the VMR in non-source-build
  src/SourceBuild/content/repo-projects/emsdk.proj
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#48269 Merging internal commits for release/8.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48431 Add back SourceBuild tag for emsdk in Version.Details.xml
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#48353 --interactive should actually default to true in user-facing situations.
  src/Cli/dotnet/CommonOptions.cs
  test/dotnet-watch.Tests/CommandLineOptionsTests.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetBuildInvocation.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetCleanInvocation.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetOsArchOptions.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetPackInvocation.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetPublishInvocation.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetRestoreInvocation.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetRunInvocation.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetTestInvocation.cs
  test/dotnet.Tests/CommandTests/Package/Remove/GivenDotnetRemovePackage.cs
  test/dotnet.Tests/CommandTests/Reference/Add/AddReferenceParserTests.cs
  test/dotnet.Tests/CommandTests/Reference/Add/GivenDotnetAddReference.cs
  test/dotnet.Tests/CommandTests/Run/GivenDotnetRunBuildsCsProj.cs
Labels: untriaged, Area-CLI

#48425 Update runtimes to the public 9.0.4
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48438 Rename PrebuiltSourceBuiltPackagesPath to PreviouslySourceBuiltPackagesPath
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/eng/init-poison.proj
  src/SourceBuild/content/eng/init-source-only.proj
  src/SourceBuild/content/eng/tools/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#48396 Add /t:CompareCliSnapshots and /t:UpdateCliSnapshots
  test/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Infrastructure

#48433 Document brotli dependency
  src/SourceBuild/content/README.md
Labels: Area-Infrastructure, untriaged

#48400 Remove the TestSdkRpm
  src/Installer/redist-installer/targets/GenerateRPMs.targets
Labels: Area-Infrastructure, untriaged

#48440 Stabilize branding for release and update implicit version
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48441 gitignore: .received target completion snapshots
  .gitignore
Labels: Area-Infrastructure, untriaged

#48473 Fix artifactsStagingDir in VMR dotnet/dotnet public builds
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#48312 [StaticWebAssets] Rename WriteImportMapToHtml to OverrideHtmlAssetPlaceholders
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.HtmlAssetPlaceholders.targets
Labels: Area-AspNetCore

#48318 Skip second build if possible with 'dotnet run file'
  src/Cli/dotnet/Commands/CliCommandStrings.resx
  src/Cli/dotnet/Commands/Run/RunCommand.cs
  src/Cli/dotnet/Commands/Run/RunCommandParser.cs
  src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.cs.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.de.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.es.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.fr.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.it.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.ja.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.ko.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.pl.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.pt-BR.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.ru.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.tr.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.zh-Hans.xlf
  src/Cli/dotnet/Commands/xlf/CliCommandStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/Run/RunFileTests.cs
  test/dotnet.Tests/CompletionTests/snapshots/bash/DotnetCliSnapshotTests.VerifyCompletions.verified.sh
  test/dotnet.Tests/CompletionTests/snapshots/pwsh/DotnetCliSnapshotTests.VerifyCompletions.verified.ps1
  test/dotnet.Tests/CompletionTests/snapshots/zsh/DotnetCliSnapshotTests.VerifyCompletions.verified.zsh
Labels: untriaged, Area-run-file

#48484 Exclude directories in aspnetcore .tgz files in asset comparison
  eng/vmr-msft-comparison-baseline.json
Labels: Area-Infrastructure, untriaged

#48485 Exclude `*.whl/**/*.exe` and `libbinaryen.dylib` from VMR SignCheck
  src/SourceBuild/content/eng/SignCheckExclusionsFile.txt
Labels: Area-Infrastructure, untriaged

#48521 Set OfficialBuilder when building VMR in MSFT official builds
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-verticals.yml
  eng/pipelines/templates/variables/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#48518 [wasm] Explicitly opt-out from inlining boot config in tests
  test/Microsoft.NET.TestFramework/AspNetSdkTest.cs
Labels: Area-WasmSdk

#48544 Update System.CommandLine version to beta5
  src/SourceBuild/content/eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48539 Update the scope of dpkg failure suppressions
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/LinuxInstallerTests.cs
Labels: Area-Infrastructure, untriaged

#48549 Don't consider linux-bionic as a cross-build in UB builds
  src/SourceBuild/patches/runtime/0003-dont-consider-linux-bionic-cross-build.patch
Labels: untriaged, Area-VMR

#48546 Re-enable IBC by default
  eng/pipelines/templates/variables/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#48557 Respect BuildWithNetFrameworkHostedCompiler on netxf
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
Labels: Area-Infrastructure, untriaged

#48327 Support OfficialBuildId for SB
  eng/pipelines/templates/jobs/source-only-build-and-validate.yml
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-verticals.yml
  eng/pipelines/templates/steps/download-artifacts.yml
  src/Layout/redist/targets/RestoreLayout.targets
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/scenario-tests.proj
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/Config.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/DotNetHelper.cs
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/Microsoft.DotNet.SourceBuild.Tests.csproj
Labels: Area-Infrastructure, untriaged

#48572 Baseline SOS.Hosting in vmr-msft-comparison-baseline.json
  eng/vmr-msft-comparison-baseline.json
Labels: Area-Infrastructure, untriaged

#48436 Clean-up VMR repo projects
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/arcade.proj
  src/SourceBuild/content/repo-projects/aspnetcore.proj
  src/SourceBuild/content/repo-projects/command-line-api.proj
  src/SourceBuild/content/repo-projects/fsharp.proj
  src/SourceBuild/content/repo-projects/msbuild.proj
  src/SourceBuild/content/repo-projects/roslyn-analyzers.proj
  src/SourceBuild/content/repo-projects/roslyn.proj
  src/SourceBuild/content/repo-projects/runtime.proj
  src/SourceBuild/content/repo-projects/sdk.proj
  src/SourceBuild/content/repo-projects/sourcelink.proj
  src/SourceBuild/content/repo-projects/templating.proj
  src/SourceBuild/content/repo-projects/windowsdesktop.proj
  src/SourceBuild/content/repo-projects/winforms.proj
  src/SourceBuild/content/repo-projects/wpf.proj
  src/SourceBuild/content/repo-projects/xdt.proj
Labels: Area-Infrastructure, untriaged

#48542 Allow `@` as separator in `#:package`
  documentation/general/dotnet-run-file.md
  src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs
  test/dotnet.Tests/CommandTests/Project/Convert/DotnetProjectConvertTests.cs
Labels: untriaged, Area-run-file

#48590 [wasm] Use inline boot config in tests
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JSModules_ManifestIncludesModuleTargetPaths.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_CanHaveDifferentBuildAndPublishModules.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/JsModules_Hosted_CanCustomizeBlazorInitialization.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Publish_DoesNotGenerateManifestJson_IncludesJSModulesOnBlazorBootJsonManifest.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_BuildMinimal_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Build_Hosted_Works.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_PublishMinimal_Works.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets.Publish.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/StaticWebAssets_Publish_Hosted_Works.Publish.staticwebassets.json
  test/Microsoft.NET.TestFramework/AspNetSdkTest.cs
Labels: untriaged, Area-WasmSdk

#48028 Use Roslyn from SDK always for SDK-based project builds
  Directory.Packages.props
  documentation/general/decouple-vs-and-net-sdk.md
  documentation/general/torn-sdk.md
  sdk.sln
  src/Layout/redist/targets/Crossgen.targets
  src/Layout/redist/targets/GenerateLayout.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Compilation.targets
  src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.Component.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
  test/Microsoft.NET.Build.Tests/Microsoft.NET.Build.Tests.csproj
  test/Microsoft.NET.Build.Tests/RoslynBuildTaskTests.cs
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToUseFrameworkRoslyn.cs
  test/Microsoft.NET.TestFramework/Commands/DotnetBuildCommand.cs
  test/Microsoft.NET.TestFramework/ProjectConstruction/TestProject.cs
Labels: Area-Infrastructure, untriaged

#48600 Add dotnet-suggest to the skip list in JoinVerticalsAssetSelector.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsAssetSelector.cs
Labels: Area-Infrastructure, untriaged

#48495 Adding new training and labeler per the instructions
  .github/policies/untriaged-label.yml
  .github/workflows/labeler-build-predictor.yml
  .github/workflows/labeler-cache-retention.yml
  .github/workflows/labeler-predict-issues.yml
  .github/workflows/labeler-predict-pulls.yml
  .github/workflows/labeler-promote.yml
  .github/workflows/labeler-train.yml
Labels: Area-Infrastructure, untriaged

#48402 package-add: Use PackageIdentityArgument
  src/Cli/dotnet/Commands/Package/Add/PackageAddCommandParser.cs
  src/Cli/dotnet/CommonArguments.cs
  test/dotnet.Tests/CompletionTests/snapshots/bash/DotnetCliSnapshotTests.VerifyCompletions.verified.sh
  test/dotnet.Tests/CompletionTests/snapshots/pwsh/DotnetCliSnapshotTests.VerifyCompletions.verified.ps1
  test/dotnet.Tests/CompletionTests/snapshots/zsh/DotnetCliSnapshotTests.VerifyCompletions.verified.zsh
Labels: untriaged

#48604 Lift VMR's eng/versions.props to PSB in source only builds
  src/SourceBuild/content/eng/Versions.props
  src/SourceBuild/content/eng/tools/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#48082 [StaticWebAssets] Cleanup ApplyCompressionNegotiation.cs and ResolveCompressedAssets.cs
  src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs
  src/StaticWebAssetsSdk/Tasks/Compression/ResolveCompressedAssets.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpoint.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssetEndpoints.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.Cache.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/ResolveCompressedAssetsTest.cs
Labels: untriaged, Area-AspNetCore

#48624 [RuntimeInteference.targets] add property to opt out of R2R error message
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets
Labels: Area-External, untriaged

#48623 [StaticWebAssets] Ensure HtmlAssetPlaceholders are executed before ServiceWorker
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.HtmlAssetPlaceholders.targets
Labels: Area-AspNetCore

#48595 Re-enable telemetry notice tests by removing attribute
  test/dotnet.Tests/GivenThatTheUserIsRunningDotNetForTheFirstTime.cs
Labels: Area-Infrastructure, untriaged

#48511 Re-enable C++/CLI tests
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildACppCliProjectWithTransitiveDeps.cs
  test/TestAssets/TestProjects/NetCoreCppCliLibWithTransitiveDeps/NETCoreCppCliTest/NETCoreCppCliTest.vcxproj
  test/TestAssets/TestProjects/NetCoreCppCliLibWithTransitiveDeps/NETCoreCppCliTestB/NETCoreCppCliTestB.vcxproj
  test/TestAssets/TestProjects/NetCoreCppCliLibWithTransitiveDeps/NETCoreCppCliTestC/NETCoreCppCliTestC.vcxproj
Labels: Area-Infrastructure, untriaged

#48635 Runtime diagnostics publishing fixes
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#48629 Update implicit version for april versions
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48637 Add VersionFeature80ForWorkloads and VersionFeature90ForWorkloads
  eng/Versions.props
  src/Workloads/Manifests/Microsoft.NET.Workload.Emscripten.net8.Manifest/Microsoft.NET.Workload.Emscripten.net8.Manifest.proj
  src/Workloads/Manifests/Microsoft.NET.Workload.Emscripten.net9.Manifest/Microsoft.NET.Workload.Emscripten.net9.Manifest.proj
  src/Workloads/Manifests/Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest/Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest.proj
  src/Workloads/Manifests/Microsoft.NET.Workload.Mono.Toolchain.net8.Manifest/Microsoft.NET.Workload.Mono.Toolchain.net8.Manifest.proj
  src/Workloads/Manifests/Microsoft.NET.Workload.Mono.Toolchain.net9.Manifest/Microsoft.NET.Workload.Mono.Toolchain.net9.Manifest.proj
Labels: untriaged, Area-Workloads

#48621 [workloads] Update maui,ios,android baselines to preview3
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48626 Updating branding for preview 5
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#48628 Remove xliff-tasks from source-mappings.json
  eng/Version.Details.xml
  src/VirtualMonoRepo/source-mappings.json
Labels: Area-Infrastructure, untriaged

#48475 Add the test verifying property functions used in dotnet console/webapp don't need a reflection
  test/Microsoft.NET.Build.Tests/EvaluatorFastPathTests.cs
  test/TestAssets/TestProjects/MSBuildBareBonesProject/BareBones.proj
Labels: Area-Infrastructure, untriaged

#48403 Update SDK-PR-guide.md to include servicing changes to upstream repos
  documentation/project-docs/SDK-PR-guide.md
Labels: Area-Infrastructure, untriaged

#48658 Remove the use of MSBuildLocator from dotnet-format
  src/BuiltInTools/dotnet-format/Commands/FormatCommandCommon.cs
  src/BuiltInTools/dotnet-format/dotnet-format.csproj
  test/dotnet-format.UnitTests/Analyzers/ThirdPartyAnalyzerFormatterTests.cs
  test/dotnet-format.UnitTests/CodeFormatterTests.cs
  test/dotnet-format.UnitTests/MSBuild/MSBuildWorkspaceLoaderTests.cs
  test/dotnet-format.UnitTests/Utilities/MSBuildRegistrar.cs
Labels: Area-Infrastructure

#48677 Create SymbolPublishingExclusionsFile.txt
  src/SourceBuild/content/eng/SymbolPublishingExclusionsFile.txt
Labels: Area-Infrastructure

#48311 Promote `NuGet.Client` builds during official CI
  .vsts-ci.yml
  eng/pipelines/templates/jobs/promote-nuget-client.yml
  eng/pipelines/templates/steps/get-asset-info.yml
  eng/pipelines/templates/steps/install-darc.yml
Labels: Area-Infrastructure

#48693 Remove main from SDK vmr PR build triggers
  eng/pipelines/vmr-build-pr.yml
Labels: Area-Infrastructure

#48698 Remove CoherentParentDependency metadata for entries both inside the VMR
  eng/Version.Details.xml
Labels: Area-Infrastructure

#48663 [wasm] Enable tests disabled by preloading & compression endpoint issue
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmJsModulesIntegrationTests.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetEndpointsIntegrationTest.cs
Labels: Area-WasmSdk

#48744 Remove dead VMR files
  eng/GatherDrops.ps1
  eng/install-scancode.sh
  eng/vmr-msft-comparison-baseline.json
  eng/vmr-sync.ps1
  eng/vmr-sync.sh
Labels: Area-CodeFlow

#48584 ensure that single-rid container publishes populate all container information
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  test/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: untriaged, Area-Containers

#48540 Add / in between skipped tests and retrie tests
  src/Cli/dotnet/Commands/Test/Terminal/NonAnsiTerminal.cs
Labels: Area-Infrastructure, untriaged

#48704 Downgrade implicit version to unblock workloads testing from main
  eng/Versions.props
Labels: Area-CodeFlow

#48713 Fix launch profile test failure
  test/dotnet.Tests/CommandTests/Run/GivenDotnetRunBuildsCsProj.cs
Labels: Area-Infrastructure

#47076 Use Arcade's publishing logic to publish a given VMR vertical
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build-with-join.yml
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/Directory.Build.targets
  src/SourceBuild/content/build.proj
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/eng/PublishSourceBuild.props
  src/SourceBuild/content/eng/Publishing.props
  src/SourceBuild/content/eng/RuntimeIdentifier.props
  src/SourceBuild/content/eng/Tests.targets
  src/SourceBuild/content/eng/Tools.props
  src/SourceBuild/content/eng/VmrLayout.props
  src/SourceBuild/content/eng/build.ps1
  src/SourceBuild/content/eng/finish-source-only.proj
  src/SourceBuild/content/eng/init-source-only.proj
  src/SourceBuild/content/eng/merge-asset-manifests.proj
  src/SourceBuild/content/eng/tools/Directory.Build.props
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/JoinVerticals.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/BuildAssetsManifest.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/MergeAssetManifests.cs
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/aspnetcore.proj
  src/SourceBuild/content/repo-projects/fsharp.proj
  src/SourceBuild/content/repo-projects/roslyn.proj
  src/SourceBuild/content/repo-projects/runtime.proj
  src/SourceBuild/patches/arcade/0001-Add-loose-PDB-relative-blob-path.patch
Labels: untriaged, Area-VMR

#48747 Use LangVersion=Preview
  Directory.Build.props
  src/Common/Polyfills.cs
  src/Microsoft.DotNet.TemplateLocator/Microsoft.DotNet.TemplateLocator.csproj
  src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/Microsoft.DotNet.MSBuildSdkResolver.csproj
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/Microsoft.NET.Sdk.WorkloadManifestReader.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
  test/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
Labels: Area-Infrastructure

#48662 Support build/restore of file-based programs
  documentation/general/dotnet-run-file.md
  src/Cli/dotnet/CliStrings.resx
  src/Cli/dotnet/CommandBase.cs
  src/Cli/dotnet/Commands/Build/BuildCommand.cs
  src/Cli/dotnet/Commands/Build/BuildCommandParser.cs
  src/Cli/dotnet/Commands/MSBuild/MSBuildForwardingApp.cs
  src/Cli/dotnet/Commands/Restore/RestoreCommand.cs
  src/Cli/dotnet/Commands/Restore/RestoreCommandParser.cs
  src/Cli/dotnet/Commands/Restore/RestoringCommand.cs
  src/Cli/dotnet/Commands/Run/RunCommand.cs
  src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs
  src/Cli/dotnet/Commands/Workload/Restore/WorkloadRestoreCommand.cs
  src/Cli/dotnet/Commands/Workload/Restore/WorkloadRestoreCommandParser.cs
  src/Cli/dotnet/xlf/CliStrings.cs.xlf
  src/Cli/dotnet/xlf/CliStrings.de.xlf
  src/Cli/dotnet/xlf/CliStrings.es.xlf
  src/Cli/dotnet/xlf/CliStrings.fr.xlf
  src/Cli/dotnet/xlf/CliStrings.it.xlf
  src/Cli/dotnet/xlf/CliStrings.ja.xlf
  src/Cli/dotnet/xlf/CliStrings.ko.xlf
  src/Cli/dotnet/xlf/CliStrings.pl.xlf
  src/Cli/dotnet/xlf/CliStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CliStrings.ru.xlf
  src/Cli/dotnet/xlf/CliStrings.tr.xlf
  src/Cli/dotnet/xlf/CliStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CliStrings.zh-Hant.xlf
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetBuildInvocation.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetOsArchOptions.cs
  test/dotnet.Tests/CommandTests/MSBuild/GivenDotnetRestoreInvocation.cs
  test/dotnet.Tests/CommandTests/MSBuild/MSBuildArgumentCommandLineParserTests.cs
  test/dotnet.Tests/CommandTests/Restore/RestoreParserTests.cs
  test/dotnet.Tests/CommandTests/Run/RunFileTests.cs
  test/dotnet.Tests/CompletionTests/snapshots/zsh/DotnetCliSnapshotTests.VerifyCompletions.verified.zsh
  test/dotnet.Tests/GivenParserDirectives.cs
  test/dotnet.Tests/ParserTests/ResponseFileTests.cs
Labels: Area-run-file

#48766 Remove unnecessary CA2022 suppressions
  src/RazorSdk/Tool/Client.cs
  src/RazorSdk/Tool/ConnectionHost.cs
Labels: Area-AspNetCore

#48756 Exclude tests from binskim scanning
  eng/pipelines/templates/jobs/sdk-build.yml
Labels: Area-Infrastructure
