Repository dotnet/sdk, pull requests merged in 2025-02, with the labels that each got.

#46446 Use dotnet run in case of --arch in dotnet test
  src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs
  src/Cli/dotnet/commands/dotnet-test/MSBuildUtility.cs
  src/Cli/dotnet/commands/dotnet-test/Options.cs
  src/Cli/dotnet/commands/dotnet-test/SolutionAndProjectUtility.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  test/Microsoft.NET.TestFramework/Utilities/RegexPatternHelper.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndDiscoversTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsForMultipleTFMs.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
  test/dotnet-test.Tests/MSBuildHandlerTests.cs
Labels: Area-Infrastructure, Area-DotNet Test

#46381 Reuse browser when restarting project
  src/BuiltInTools/dotnet-watch/Browser/BrowserConnector.cs
  src/BuiltInTools/dotnet-watch/Browser/BrowserRefreshServer.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
  test/dotnet-watch.Tests/Browser/BrowserConnectorTests.cs
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
Labels: untriaged, Area-AspNetCore

#46254 Enable IBC data for Roslyn
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/variables/vmr-build.yml
  src/SourceBuild/content/repo-projects/roslyn.proj
  src/SourceBuild/patches/roslyn/0001-Move-internal-tools-restore-out-of-CI-yaml-and-into-.patch
  src/SourceBuild/patches/roslyn/0002-Update-IBC-optimization-settings-to-conditionally-en.patch
Labels: Area-Infrastructure, untriaged

#46442 Set and/or respect NUGET_PACKAGES env var correctly in VMR builds
  src/SourceBuild/content/Directory.Build.props
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/eng/build.ps1
  src/SourceBuild/content/eng/tools/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/dotnet.proj
  src/SourceBuild/content/test/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#46478 [release/10.0.1xx-preview1] Update Source-Build SDK Diff Tests Baseli…
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/assets/SdkContentTests/MsftToSbSdkFiles.diff
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/assets/SdkContentTests/SdkFileDiffExclusions.txt
Labels: Area-Infrastructure, untriaged

#46404 SlnFileFactory.CreateFromFilteredSolutionFile: Refactor
  src/Cli/dotnet/SlnFileFactory.cs
Labels: untriaged, Area-CLI

#46495 Add tests for globbing filter
  src/Cli/dotnet/commands/dotnet-test/TestModulesFilterHandler.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestBasedOnGlobbingFilter.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
  test/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-DotNet Test

#46430 Go up two more levels looking for dmp
  test/UnitTests.proj
Labels: Area-Infrastructure, untriaged

#46456 Fix bug when adding solution folder containing `..`
  src/Cli/dotnet/commands/dotnet-sln/add/Program.cs
Labels: untriaged, Area-CLI

#46493 Fix sdk artifact classification
  eng/Signing.props
Labels: Area-Infrastructure, untriaged

#46480 Make Testhost packable except in source-only
  src/SourceBuild/patches/vstest/0001-Make-Testhost-packable-except-in-source-only.patch
Labels: Area-Infrastructure, untriaged

#46516 Enable IBC for msbuild
  src/SourceBuild/content/repo-projects/msbuild.proj
Labels: Area-Infrastructure, untriaged

#46523 Update branding to 9.0.201
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46522 Update branding to 9.0.104
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46521 Update branding to 8.0.407
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46519 Update branding to 8.0.114
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46520 Update branding to 8.0.310
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46526 Update CODEOWNERS to account for name changes and retirements
  CODEOWNERS
Labels: Area-Infrastructure, untriaged

#46432 Increasing the test timeout
  test/HelixTasks/SDKCustomCreateXUnitWorkItemsWithTestExclusion.cs
Labels: Area-Infrastructure, untriaged

#46431 Port a set of test fixes for the templating tests and some feed tests to 9.0.1xx (#45549)
  test/Microsoft.NET.Build.Tests/GivenThatWeHaveAPackageReferenceWithAliases.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateADepsFileForATool.cs
  test/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToIgnoreObsoleteDotNetCliToolPackages.cs
  test/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreDotNetCliToolReference.cs
  test/Microsoft.NET.TestFramework/NuGetConfigWriter.cs
  test/TestAssets/TestProjects/UnmanagedStore/UnmanagedStore.csproj
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenLegacyCommandIsUsed_common.Windows.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Linux.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.OSX.verified.txt
  test/dotnet-new.Tests/Approvals/DotnetNewListTests.BasicTest_WhenListCommandIsUsed.Windows.verified.txt
  test/dotnet-new.Tests/DotnetNewListTests.Approval.cs
Labels: Area-Infrastructure, untriaged

#46405 Use official templates even for PRs when run internal
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#46016 Add net10 feed to the readme
  README.md
Labels: Area-Infrastructure, untriaged

#46535 Update dependencies from dotnet/source-build-externals
  eng/Version.Details.xml
Labels: Area-Infrastructure, untriaged

#46528 Create dependencies for each dotnet/templating version
  eng/Version.Details.xml
  eng/Versions.props
Labels: untriaged, Area-CodeFlow

#46530 Create dependencies for aspnetcore template packages
  eng/Version.Details.xml
  eng/Versions.props
  src/Installer/redist-installer/targets/BundledTemplates.targets
  src/SourceBuild/patches/wpf/0001-Create-arch-neutral-packages-when-building-inside-th.patch
  src/SourceBuild/patches/wpf/0004-Fix-the-ArtifactsPackagingDir-on-win-x64.patch
Labels: untriaged, Area-CodeFlow

#46534 [GenAPI] Fix header handling in GenAPI and CSharpFileBuilder
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/CSharpFileBuilder.cs
  src/Compatibility/GenAPI/Microsoft.DotNet.GenAPI/GenAPIApp.cs
  test/Microsoft.DotNet.GenAPI.Tests/CSharpFileBuilderTests.cs
Labels: Area-GenAPI

#42437 Add analyzer redirecting proposal
  documentation/general/analyzer-redirecting.md
Labels: Area-Infrastructure, untriaged

#46564 Fix default runtime framework versions for .NET 9 targeting
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: untriaged, Area-Workloads

#46568 Remove duplicate assets that were only present in ShortStack legs
  src/SourceBuild/content/eng/join-verticals.proj
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/runtime.proj
  src/SourceBuild/patches/runtime/0001-use-standard-arcade-publish.patch
Labels: untriaged, Area-VMR

#44843 Add VMR leg that builds test projects
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/repo-projects/sdk.proj
  src/SourceBuild/content/repo-projects/winforms.proj
Labels: Area-Infrastructure, untriaged

#46567 Properly change loc branch
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#46562 Support msbuild params in dotnet test
  src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs
  src/Cli/dotnet/commands/dotnet-test/MSBuildUtility.cs
  src/Cli/dotnet/commands/dotnet-test/Options.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformOptions.cs
  src/Cli/dotnet/commands/dotnet-test/ValidationUtility.cs
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.CrossTargeting.targets/ImportAfter/Microsoft.TestPlatform.CrossTargeting.targets
  src/Layout/redist/MSBuildImports/Current/Microsoft.Common.targets/ImportAfter/Microsoft.TestPlatform.ImportAfter.targets
  test/Microsoft.NET.TestFramework/Utilities/RegexPatternHelper.cs
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsSolution/OtherTestProject/OtherTestProject.csproj
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsSolution/OtherTestProject/Program.cs
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsSolution/TestProjectWithMultipleTFMsSolution.sln
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsForMultipleTFMs.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
  test/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-DotNet Test, untriaged

#46490 slnx: ParseAndValidateArguments include .slnx
  src/Cli/dotnet/commands/dotnet-sln/SlnArgumentValidator.cs
  test/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
  test/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
Labels: Area-Infrastructure, untriaged

#46513 Unified build publishing
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/JoinVerticals.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/BuildAssetsManifest.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsAssetSelector.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsConfig.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsManifestExportHelper.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/Microsoft.DotNet.UnifiedBuild.Tasks.csproj
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/AssetsLoader.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/JoinVertialsTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Pgo_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Pgo_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_ShortStack_Mono_LLVMAOT_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_ShortStack_Mono_LLVMAOT_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Browser_Multithreaded_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Browser_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/MacCatalyst_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/MacCatalyst_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Wasi_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x64_BuildPass2.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOSSimulator_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOSSimulator_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOS_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOSSimulator_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOSSimulator_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOS_Shortstack_arm64.xml
Labels: Area-Infrastructure, untriaged

#46575 Simplify SB bootstrap package logic
  src/SourceBuild/content/eng/bootstrap/buildBootstrapPreviouslySB.csproj
  src/SourceBuild/content/prep-source-build.sh
Labels: Area-Infrastructure, untriaged

#46636 Refactor MsBuildUtility
  src/Cli/dotnet/SlnFileFactory.cs
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/MSBuildUtility.cs
Labels: Area-Infrastructure, untriaged

#46632 Remove 9.0.2xx and add 10.0.1-preview1 from package-table
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#46397 Publish dotnet test options
  src/Cli/dotnet/Properties/launchSettings.json
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/Terminal/TerminalTestReporter.cs
  src/Cli/dotnet/commands/dotnet-test/Terminal/TestProgressStateAwareTerminal.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformOptions.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-DotNet Test, untriaged

#46606 Deduplicate more assets produced by dotnet/runtime
  src/SourceBuild/patches/runtime/0001-use-standard-arcade-publish.patch
Labels: untriaged, Area-VMR

#46651 Enable building tests in vstest repo
  src/SourceBuild/content/repo-projects/vstest.proj
Labels: Area-Infrastructure, untriaged

#46653 Fix array length Fixes #45632
  src/Cli/Microsoft.DotNet.Cli.Utils/Uuid.cs
Labels: Area-Infrastructure, untriaged

#46660 Enable building tests in efcore repo
  src/SourceBuild/content/repo-projects/efcore.proj
Labels: Area-Infrastructure, untriaged

#46655 Only build the compiler package that the SDK redists from in UB.
  eng/Publishing.props
  src/SourceBuild/patches/fsharp/0001-Only-build-the-Microsoft.FSharp.Compiler.sln.patch
Labels: Area-VMR

#46643 Add Microsoft.Extensions.Configuration.Ini package
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
Labels: Area-Infrastructure, untriaged

#46689 React to NuGet package pruning warnings
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Containers/Microsoft.NET.Build.Containers/Microsoft.NET.Build.Containers.csproj
  src/Layout/redist/redist.csproj
  src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj
Labels: Area-Infrastructure, untriaged

#46686 Write help via dotnet test terminal logger
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/Terminal/TerminalTestReporter.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.Help.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-DotNet Test, untriaged

#46663 Workflows: Don't allow merge if pr in lockdown
  .github/workflows/pr-analysis.yml
Labels: Area-Infrastructure, untriaged

#46693 Add a patch for fixing the InteractiveHost32 ambiguous package
  src/SourceBuild/patches/roslyn/0003-Set-a-RID-for-InteractiveHost32.patch
Labels: untriaged, Area-VMR

#46661 Fix NativeAot_hw_runs_with_no_warnings_when_PublishAot_is_enabled Test
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
  src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs
Labels: untriaged, Area-ILLink

#46695 [Backport to 8.0.1xx] Workflows: Don't allow merge if pr in lockdown (#46663)
  .github/workflows/pr-analysis.yml
Labels: Area-Infrastructure, untriaged

#46715 Add tests for help in dotnet test
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsHelp.cs
  test/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-DotNet Test

#46467 [release/8.0.4xx] Multi-arch OCI images export as tarballs
  src/Containers/Microsoft.NET.Build.Containers/BuiltImage.cs
  src/Containers/Microsoft.NET.Build.Containers/DigestUtils.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageIndexGenerator.cs
  src/Containers/Microsoft.NET.Build.Containers/ImagePublisher.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/ArchiveFileRegistry.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/DockerCli.cs
  src/Containers/Microsoft.NET.Build.Containers/LocalDaemons/ILocalRegistry.cs
  src/Containers/Microsoft.NET.Build.Containers/MultiArchImage.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateImageIndex.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateImageIndex.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/Microsoft.NET.Build.Containers/Telemetry.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ArchiveFileRegistryTests.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/ContainerCli.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerIsAvailableAndSupportsArchFact.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerIsAvailableAndSupportsArchTheory.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerSupportsArchFact.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/DockerSupportsArchInlineData.cs
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/DockerAvailableUtils.cs
  src/Tests/Microsoft.NET.Build.Containers.UnitTests/ImageIndexGeneratorTests.cs
Labels: Servicing-approved, Area-Containers

#46659 Fix missing flag for --debug in VS
  eng/restore-toolset.ps1
Labels: Area-Infrastructure, untriaged

#45552 Warn on :: use in dotnet new install towards #45422
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.Designer.cs
  src/Cli/Microsoft.TemplateEngine.Cli/LocalizableStrings.resx
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.cs.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.de.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.es.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.fr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.it.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ja.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ko.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pl.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.ru.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.tr.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/Microsoft.TemplateEngine.Cli/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-new.Tests/Approvals/DotnetNewInstallTests.CannotInstallMultiplePackageAvailableFromBuiltIns.verified.txt
  test/dotnet-new.Tests/DotnetNewInstallTests.Approval.cs
  test/dotnet-new.Tests/DotnetNewInstallTests.cs
  test/dotnet-new.Tests/DotnetNewInstantiateTests.Approval.cs
Labels: Area-Infrastructure

#46475 .NET 10 Preview 1 MAUI baseline manifests
  eng/Versions.props
Labels: Area-Infrastructure

#46732 Merging internal commits for release/8.0.3xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46735 Merging internal commits for release/9.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46736 Merging internal commits for release/9.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46140 [release/8.0.4xx] Manual Backport of #40611 to 8.0.4xx - Allow users to set a specific ContainerImageFormat to force OCI support
  src/Containers/Microsoft.NET.Build.Containers/ContainerBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net8.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Registry/SchemaTypes.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.Designer.cs
  src/Containers/Microsoft.NET.Build.Containers/Resources/Strings.resx
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.cs.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.de.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.es.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.fr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.it.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ja.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ko.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pl.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.pt-BR.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.ru.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.tr.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hans.xlf
  src/Containers/Microsoft.NET.Build.Containers/Resources/xlf/Strings.zh-Hant.xlf
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImageToolTask.cs
  src/Containers/containerize/ContainerizeCommand.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  src/Tests/Microsoft.NET.Build.Containers.IntegrationTests/CreateNewImageTests.cs
Labels: Servicing-approved, Area-Containers, Branch Lockdown

#46730 Update runtime publishing to update host artifact visibility in Publishing.props
  src/SourceBuild/patches/runtime/0001-use-standard-arcade-publish.patch
Labels: untriaged, Area-VMR

#46742 Add Mono_LLVMAOT OSX_x64 leg
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#46722 Temporary exclude stable assets from Unified Build
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/JoinVerticals.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsAssetSelector.cs
Labels: Area-Infrastructure, untriaged

#46717 Read dotnet.config file to use MTP or VSTest in dotnet test
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  test/TestAssets/TestProjects/EmptyFolder/dotnet.config
  test/TestAssets/TestProjects/HybridTestRunnerTestProjects/dotnet.config
  test/TestAssets/TestProjects/MSTestMetaPackageProjectWithMultipleTFMsSolution/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithDifferentFailures/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithDiscoveredTests/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithTests/dotnet.config
  test/TestAssets/TestProjects/MultipleTestProjectSolution/dotnet.config
  test/TestAssets/TestProjects/MultipleTestProjectsWithoutSolution/dotnet.config
  test/TestAssets/TestProjects/ProjectSolutionForMultipleTFMs/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolution/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolutionWithCodeCoverage/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolutionWithTestsAndArtifacts/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithClassLibrary/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithDiscoveredTests/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsSolution/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithTests/dotnet.config
Labels: Area-DotNet Test

#46377 Sign the DAC and build (and sign) the cross-OS DACs in the VMR
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/UpdateNuGetConfigPackageSourcesMappings.cs
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/dotnet.proj
  src/SourceBuild/content/repo-projects/runtime.proj
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/PackageSourceMappingsTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/expected/sb-mappings-offline.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/expected/sb-mappings-online.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/expected/sb-nomappings-offline.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/expected/sb-nomappings-online.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/expected/ub-mappings.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/expected/ub-nomappings.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/original/sb-mappings-offline.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/original/sb-mappings-online.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/original/sb-nomappings-offline.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/original/sb-nomappings-online.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/original/ub-mappings.config
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/PackageSourceMappingsTests/original/ub-nomappings.config
  src/SourceBuild/patches/runtime/0003-dont-build-host-tools.patch
Labels: untriaged, Area-VMR

#46733 Merging internal commits for release/8.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46734 Merging internal commits for release/8.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46789 Set target rid based on passed in prop, instead of host SDK
  src/Installer/pkg/dotnet-sdk.proj
Labels: Area-Infrastructure, untriaged

#46697 Revert Roslyn to the Feb release version
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46767 Enable roslyn tests in VMR
  src/SourceBuild/content/repo-projects/roslyn.proj
  src/SourceBuild/patches/roslyn/0004-Enable-tests-in-VMR.patch
Labels: Area-Infrastructure, untriaged

#46558 Manual VMR re-bootstrap to 10.0.100-preview.2.25104.28
  src/SourceBuild/content/Directory.Build.targets
  src/SourceBuild/content/eng/Version.Details.xml
  src/SourceBuild/content/eng/Versions.props
  src/SourceBuild/content/global.json
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/scenario-tests.proj
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#46827 Support short forms of some options in dotnet test
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformOptions.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsHelp.cs
Labels: Area-DotNet Test

#46337 Update SDK-PR-guide.md to include branch lockdown label
  .github/workflows/add-lockdown-label.yml
  documentation/project-docs/SDK-PR-guide.md
Labels: Area-Infrastructure, untriaged

#46859 React to NuGet package pruning warnings
  Directory.Packages.props
  test/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj
  test/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-Infrastructure, untriaged

#46831 Unified build assets filter
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/JoinVerticals.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsAssetSelector.cs
Labels: Area-Infrastructure, untriaged

#46800 Set PDB artifacts dir for VMR inter-build storage
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#46853 Allow roslyn binary into VMR
  src/SourceBuild/content/eng/allowed-vmr-binaries.txt
Labels: Area-Infrastructure, untriaged

#46745 Use internationally viable formatting for dates used in, for example, file paths
  src/Cli/dotnet/Installer/Windows/TimestampedFileLogger.cs
  src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs
Labels: untriaged, Area-Workloads

#46865 Allow zip test binaries in razor repo
  src/SourceBuild/content/eng/allowed-vmr-binaries.txt
Labels: Area-Infrastructure, untriaged

#46835 Add test case for adding projects outside solution dir descendants
  test/TestAssets/TestProjects/TestAppWithSlnAndCsprojInParentDir/Dir/App.sln
  test/TestAssets/TestProjects/TestAppWithSlnAndCsprojInParentDir/Dir/App.slnx
  test/TestAssets/TestProjects/TestAppWithSlnAndCsprojInParentDir/Lib/Lib.csproj
  test/TestAssets/TestProjects/TestAppWithSlnAndCsprojInParentDir/Lib/Library.cs
  test/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
Labels: Area-Infrastructure, untriaged

#45969 Parallelize workload pack downloads Fixes #43870
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
  test/dotnet-workload-install.Tests/GivenFileBasedWorkloadInstall.cs
  test/dotnet-workload-install.Tests/MockNuGetPackageInstaller.cs
Labels: Area-Workloads

#46824 Update Skip Reason for Tests Requiring New Parser Feature (Refs #46822)
  test/dotnet-msbuild.Tests/GivenDotnetMSBuildBuildsProjects.cs
Labels: Area-Infrastructure, untriaged

#46895 Avoid downloading unrelated arcade packages in DownloadPackages.csproj
  src/Installer/redist-installer/projects/Directory.Build.targets
  src/Installer/redist-installer/projects/DownloadPackage.csproj
Labels: untriaged, Area-Workloads

#46894 Don't set explicit version for Microsoft.Build.NoTargets in project file
  src/Installer/finalizer/finalizer-build.csproj
  src/Installer/redist-installer/projects/DownloadPackage.csproj
Labels: untriaged, Area-Workloads

#46896 Minor clean-up in redist-installer
  Directory.Build.props
  eng/Versions.props
  src/Installer/redist-installer/Directory.Build.props
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/projects/Directory.Build.props
  src/Installer/redist-installer/projects/Directory.Build.targets
  src/Installer/redist-installer/redist-installer.csproj
  src/Installer/redist-installer/targets/Badge.targets
  src/Installer/redist-installer/targets/Branding.targets
  src/Installer/redist-installer/targets/Crossgen.targets
  src/Installer/redist-installer/targets/FileExtensions.targets
  src/Installer/redist-installer/targets/GenerateArchives.targets
  src/Installer/redist-installer/targets/GenerateInstallers.targets
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Installer/redist-installer/targets/GeneratePKG.targets
  src/Installer/redist-installer/targets/GetRuntimeInformation.targets
  src/Installer/redist-installer/targets/SetBuildDefaults.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#46911 Remove app host packages for different archs from packs folder
  src/Installer/redist-installer/targets/GenerateLayout.targets
Labels: untriaged

#46913 Use PackageDownload in Crossgen.targets
  src/Installer/redist-installer/Directory.Build.props
  src/Installer/redist-installer/targets/Crossgen.targets
  src/Installer/redist-installer/targets/GenerateLayout.targets
Labels: untriaged, Area-Workloads

#46907 Update Skip attribute with issue link for unimplemented tests
  test/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs
Labels: Area-Infrastructure, untriaged

#46914 Use package download in bundled dotnet tools
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/redist-installer.csproj
  src/Installer/redist-installer/targets/BundledDotnetTools.targets
  src/Installer/redist-installer/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#46797 [ApiCompat] Warn if abstract keyword is removed from member
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Resources.resx
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/Rules/CannotAddOrRemoveVirtualKeyword.cs
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.cs.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.de.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.es.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.fr.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.it.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ja.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ko.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pl.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.pt-BR.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.ru.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.tr.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hans.xlf
  src/Compatibility/ApiCompat/Microsoft.DotNet.ApiCompatibility/xlf/Resources.zh-Hant.xlf
  test/Microsoft.DotNet.ApiCompatibility.Tests/Rules/CannotAddOrRemoveVirtualKeywordTests.cs
Labels: Area-ApiCompat

#46924 Disable Flaky GivenDotnetTest Tests
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
Labels: Area-dotnet test, untriaged

#46741 Remove vertical priority list
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsAssetSelector.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsConfig.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/JoinVertialsTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Pgo_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Pgo_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_ShortStack_Mono_LLVMAOT_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_ShortStack_Mono_LLVMAOT_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Browser_Multithreaded_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Browser_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/MacCatalyst_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/MacCatalyst_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_Shortstack_Mono_LLVMAOT_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Wasi_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x64_BuildPass2.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x86_BuildPass2.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOSSimulator_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOSSimulator_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOS_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOSSimulator_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOSSimulator_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOS_Shortstack_arm64.xml
Labels: untriaged, Area-VMR

#46928 Update implicit versions for the Feb release
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46942 Remove incorrect text from --blame-hang docs
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
Labels: untriaged, Area-Workloads

#46893 Fix utility HaveStdErrContainingOnce
  test/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs
  test/dotnet-run.Tests/GivenDotnetRunThrowsAParseError.cs
Labels: Area-Infrastructure, untriaged

#46944 Don't restore crossgen packs on unsupported envs
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/targets/Crossgen.targets
Labels: Area-Infrastructure, untriaged

#46233 Write import map to html files
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.HtmlImportMap.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/Utils/ArtifactWriter.cs
  src/StaticWebAssetsSdk/Tasks/WriteImportMapToHtml.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsFingerprintingTest.cs
  test/TestAssets/TestProjects/BlazorWasmMinimal/wwwroot/index.html
  test/TestAssets/TestProjects/VanillaWasm/VanillaWasm.csproj
  test/TestAssets/TestProjects/VanillaWasm/wwwroot/index.html
Labels: untriaged, Area-WasmSdk

#46953 Update preview branding
  eng/Versions.props
Labels: Area-Infrastructure

#46959 Fix typo for forwarding the DAC signing arguments
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#46964 Fix definition of PgoTerm and properties based on Versions
  src/Installer/redist-installer/Directory.Build.props
  src/Installer/redist-installer/Directory.Build.targets
Labels: untriaged, Area-VMR

#46979 Fix GenerateLayout target dependencies when skipping crossgen
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/targets/Crossgen.targets
Labels: Area-Infrastructure, untriaged

#46978 Remove dead code from redist-installer
  src/Installer/pkg/deb/postinst
  src/Installer/pkg/dotnet-sdk.proj
  src/Installer/redist-installer/packaging/deb/dotnet-debian_config.json
  src/Installer/redist-installer/packaging/rpm/dotnet-config.json
  src/Installer/redist-installer/packaging/rpm/scripts/after_install_host.sh
  src/Installer/redist-installer/packaging/rpm/scripts/after_remove_host.sh
  src/Installer/redist-installer/packaging/rpm/templates/changelog
  src/Installer/redist-installer/packaging/rpm/templates/copyright
Labels: Area-Infrastructure, untriaged

#47011 Don't reference windowsdesktop from sdk when building source-only
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#43073 [wasm] Enable previously disabled tests
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.files.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/StaticWebAssetsBaselines/Build_SatelliteAssembliesAreCopiedToBuildOutput.Build.staticwebassets.json
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs
  test/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs
Labels: Area-WasmSdk

#47018 Fix branch trigger for CI builds
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#47017 Fix SDKBundleVersion calculation
  src/Installer/redist-installer/targets/GenerateMSIs.targets
Labels: Area-Infrastructure, untriaged

#47045 Enable arm64 DEBs
  .vsts-ci.yml
Labels: Area-Infrastructure, untriaged

#46833 Unescape slnf original solution path
  src/Cli/dotnet/SlnFileFactory.cs
  test/TestAssets/TestProjects/TestAppWithSlnAndSlnfWithSpecialCharactersInPath/App.slnf
  test/TestAssets/TestProjects/TestAppWithSlnAndSlnfWithSpecialCharactersInPath/App@something.slnx
  test/dotnet-sln.Tests/GivenDotnetSlnList.cs
Labels: untriaged, Area-CLI

#46994 Clean-up in src/Layout/redist
  Directory.Build.props
  src/Installer/redist-installer/Directory.Build.props
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/Layout/Directory.Build.props
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/BundledSdks.targets
  src/Layout/redist/targets/BundledTools.targets
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/GetRuntimeInformation.targets
  src/Layout/redist/targets/MSBuildExtensions.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Layout/redist/targets/PublishDotnetWatch.targets
  src/Layout/redist/targets/RestoreDependency.proj
  src/Layout/redist/targets/Version.targets
  src/Layout/redist/targets/sdks/sdks.csproj
  src/Layout/redist/targets/test/Empty.props
  src/Layout/redist/targets/test/Empty.targets
  src/Layout/tool_fsharp/tool_fsc.csproj
  src/Layout/tool_msbuild/tool_msbuild.csproj
  src/Layout/tool_nuget/tool_nuget.csproj
Labels: Area-Infrastructure, untriaged

#47054 Update .net10 p1 to p2 in the table
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#47103 Enable building sdk tests in the VMR
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#47095 Add test-tools feed to NuGet.config
  NuGet.config
Labels: Area-Infrastructure, untriaged

#47053 Update implicit version
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46927 Add installer tests project
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/Config.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/DockerHelper.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/LinuxInstallerTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/Microsoft.DotNet.Installer.Tests.csproj
Labels: Area-Infrastructure, untriaged

#47104 Simplify redist-installer and build installers in the VMR
  build.cmd
  build.sh
  eng/DotNetBuild.props
  eng/Signing.props
  src/Installer/redist-installer/Directory.Build.props
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/targets/BundledTemplates.targets
  src/Installer/redist-installer/targets/Checksum.targets
  src/Installer/redist-installer/targets/GenerateInstallers.targets
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Installer/redist-installer/targets/GeneratePKG.targets
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#47136 Add latest build table to VMR README
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/targets/Badge.targets
  src/Installer/redist-installer/version_badge.svg
  src/SourceBuild/content/README.md
  src/SourceBuild/content/docs/builds-table.md
Labels: Area-Infrastructure, untriaged

#47133 Update MTP name in config file for dotnet test
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  test/TestAssets/TestProjects/EmptyFolder/dotnet.config
  test/TestAssets/TestProjects/HybridTestRunnerTestProjects/dotnet.config
  test/TestAssets/TestProjects/MSTestMetaPackageProjectWithMultipleTFMsSolution/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithDifferentFailures/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithDiscoveredTests/dotnet.config
  test/TestAssets/TestProjects/MultiTestProjectSolutionWithTests/dotnet.config
  test/TestAssets/TestProjects/MultipleTestProjectSolution/dotnet.config
  test/TestAssets/TestProjects/MultipleTestProjectsWithoutSolution/dotnet.config
  test/TestAssets/TestProjects/ProjectSolutionForMultipleTFMs/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolution/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolutionWithCodeCoverage/dotnet.config
  test/TestAssets/TestProjects/TestProjectSolutionWithTestsAndArtifacts/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithClassLibrary/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithDiscoveredTests/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithMultipleTFMsSolution/dotnet.config
  test/TestAssets/TestProjects/TestProjectWithTests/dotnet.config
Labels: Area-Infrastructure, untriaged

#47139 Don't run the VMR Final Join in public rolling/scheduled builds
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#47117 dotnet-watch: Fix race condition in tests
  src/BuiltInTools/dotnet-watch/Internal/ConsoleInputReader.cs
Labels: untriaged

#46991 Add VMR step to validate asset baseline
  eng/CompareVMRArtifactsToManifest.ps1
  eng/GatherDrops.ps1
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/steps/vmr-validate-asset-baseline.yml
Labels: Area-Infrastructure, untriaged

#46796 Use pipeline artifacts for final artifacts and enable caching
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/eng/pipelines/ci.yml
Labels: Area-Infrastructure, untriaged

#47126 Add --configfile option to dotnet nuget push command
  src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs
  test/dotnet.Tests/CommandTests/CompleteCommandTests.cs
Labels: Area-Infrastructure, untriaged

#47114 Remove dotnet-new3
  CODEOWNERS
  TemplateEngine.slnf
  sdk.sln
  src/Cli/Microsoft.TemplateEngine.Cli/TemplateListCoordinator.cs
  src/Cli/Microsoft.TemplateEngine.Cli/TemplatePackageCoordinator.cs
  src/Cli/dotnet-new3/ArgumentEscaper.cs
  src/Cli/dotnet-new3/BuiltInTemplatePackagesProvider.cs
  src/Cli/dotnet-new3/CompleteCommand.cs
  src/Cli/dotnet-new3/Dotnet.cs
  src/Cli/dotnet-new3/HostFactory.cs
  src/Cli/dotnet-new3/New3CommandFactory.cs
  src/Cli/dotnet-new3/ParserFactory.cs
  src/Cli/dotnet-new3/Program.cs
  src/Cli/dotnet-new3/component_registry.json
  src/Cli/dotnet-new3/defaultinstall.template.list.debug
  src/Cli/dotnet-new3/defaultinstall.template.list.release
  src/Cli/dotnet-new3/dotnet-new3.cmd
  src/Cli/dotnet-new3/dotnet-new3.csproj
  src/Cli/dotnet-new3/dotnet-new3.sh
  test/dotnet-new.Tests/dotnet-new.IntegrationTests.csproj
Labels: Area-Infrastructure, untriaged

#47132 Fix Regex pattern in test for dotnet test
  test/Microsoft.NET.TestFramework/Utilities/RegexPatternHelper.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsForMultipleTFMs.cs
Labels: Area-dotnet test

#47106 Build tests on Linux and Windows
  eng/pipelines/templates/stages/vmr-build.yml
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#47161 Unify line endings
  .github/policies/resourceManagement.yml
  .github/workflows/backport.yml
  src/SourceBuild/content/docs/builds-table.md
  src/SourceBuild/content/eng/pipelines/ci.yml
  src/SourceBuild/content/eng/pipelines/source-build-sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/templates/jobs/sdk-diff-tests.yml
  src/SourceBuild/content/eng/pipelines/templates/variables/pipelines.yml
Labels: Area-Infrastructure, untriaged

#47156 Fix version badge moniker for linux-musl-*
  src/Installer/redist-installer/targets/Badge.targets
Labels: untriaged, Area-Workloads

#47160 Update to released .NET MAUI manifests
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47162 Don't scan src dirs for project.assets.json files
  src/SourceBuild/content/eng/finish-source-only.proj
Labels: Area-Infrastructure, untriaged

#47029 Ignore .lutconfig files via .gitignore
  .gitignore
Labels: Area-Infrastructure, untriaged

#47112 `dotnet sln remove` smart project matching
  src/Cli/dotnet/commands/dotnet-sln/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-sln/remove/Program.cs
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-sln/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
Labels: untriaged, Area-CLI

#47178 Update various runtimes to the public 9.0.2 version
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47189 Update help option in dotnet test
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/Options.cs
  src/Cli/dotnet/commands/dotnet-test/Terminal/TerminalTestReporter.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.Help.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformOptions.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsHelp.cs
Labels: Area-dotnet test

#47173 Skip CanIgnoreTemplateGroupsWithConstraints
  test/Microsoft.TemplateEngine.Cli.UnitTests/ParserTests/TabCompletionTests.cs
Labels: Area-Infrastructure, untriaged

#47110 Delete workload-related things if the rest of the operation was unsuccessful
  src/Cli/dotnet/commands/dotnet-workload/install/FileBasedInstaller.cs
Labels: untriaged, Area-Workloads

#46836 Fix home calculation Fixes #46821
  src/Cli/dotnet/SudoEnvironmentDirectoryOverride.cs
Labels: Area-Infrastructure, untriaged
