Repository dotnet/sdk, pull requests merged in 2025-03, with the labels that each got.

#47193 Bump MSTest version to 3.8.2 in MSTest templates
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-FSharp/Company.TestProject1.fsproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-VisualBasic/Company.TestProject1.vbproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/NUnit-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/NUnit-FSharp/Company.TestProject1.fsproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/NUnit-VisualBasic/Company.TestProject1.vbproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/Playwright-MSTest-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/Playwright-NUnit-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/XUnit-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/XUnit-FSharp/Company.TestProject1.fsproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/XUnit-VisualBasic/Company.TestProject1.vbproj
Labels: Area-Infrastructure

#47064 light up container publish for all Exe/WinExe projects by default
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  test/Microsoft.NET.Build.Containers.IntegrationTests/EndToEndTests.cs
Labels: untriaged, Area-Containers

#46988 Allow to fingerprint Blazor.js
  src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsFingerprintingTest.cs
Labels: Area-AspNetCore

#47201 Update to clarify the first tuesday branding date
  documentation/project-docs/SDK-PR-guide.md
Labels: Area-Infrastructure, untriaged

#47233 Revert "Use pipeline artifacts for final artifacts"
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#47232 Fix signing opt in/out
  eng/pipelines/templates/variables/vmr-build.yml
  src/SourceBuild/content/eng/pipelines/ci.yml
Labels: Area-Infrastructure, untriaged

#47229 Sync NativeAOTRuntimePack with ILCompilerSupported RIDs
  src/Installer/redist-installer/targets/GenerateBundledVersions.targets
Labels: Area-Infrastructure, untriaged

#47197 Suppress welcome message with get* builds Fixes #38444
  src/Cli/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs
  src/Cli/dotnet/Program.cs
Labels: Area-Infrastructure, untriaged

#47204 Create copilot-instructions.md
  .github/copilot-instructions.md
Labels: Area-Infrastructure, untriaged

#47247 Remove Skip attribute from tests related to issue #47246
  test/dotnet-pack.Tests/PackTests.cs
Labels: Area-Infrastructure, untriaged

#47260 Move branding information to targets file
  src/Installer/redist-installer/Directory.Build.props
  src/Installer/redist-installer/Directory.Build.targets
Labels: Area-Infrastructure, untriaged

#47268 Simplify reused artifact download for VMR builds
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#47262 Remove "aspnetcoremodule_$(Architecture)_en_v2_..." bundled installer…
  src/Installer/redist-installer/targets/GenerateLayout.targets
Labels: Area-Infrastructure, untriaged

#47264 Validate while publishing from the VMR
  eng/pipelines/templates/stages/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#47281 Refactor copilot instructions to include specific issue link for Fact…
  .github/copilot-instructions.md
Labels: Area-Infrastructure, untriaged

#47288 Change help structure in dotnet test
  src/Cli/dotnet/commands/dotnet-test/Terminal/TerminalTestReporter.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.Help.cs
Labels: Area-dotnet test

#47310 Delete vmr-pipeline-secrets YAML
  src/SourceBuild/content/.vault-config/vmr-pipeline-secrets.yaml
Labels: Area-Infrastructure, untriaged

#47312 Update builds table in VMR and SDK
  documentation/package-table.md
  src/SourceBuild/content/docs/builds-table.md
Labels: Area-Infrastructure, untriaged

#47318 Add variable template for signing to stage and fixup manifest paths
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/steps/vmr-validate-asset-baseline.yml
Labels: Area-Infrastructure, untriaged

#47325 Update branding to 9.0.105
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47326 Update branding to 9.0.203
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47322 Update branding to 8.0.115
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47323 Update branding to 8.0.311
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47324 Update branding to 8.0.408
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47234 Ensure container generation uniformly reports outputs to MSBuild
  src/Containers/Microsoft.NET.Build.Containers/ImageBuilder.cs
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net10.0/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/PublicAPI/net472/PublicAPI.Unshipped.txt
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.Interface.cs
  src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
Labels: untriaged, Area-Containers

#47361 Set build number to arcade build revision for VMR builds
  src/SourceBuild/patches/nuget-client/0001-Set-build-number-to-arcade-build-revision-for-VMR-bu.patch
Labels: Area-Infrastructure, untriaged

#47368 [release/8.0.1xx] NugetConfigWriter: Update CDN tests
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeHaveAPackageReferenceWithAliases.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateADepsFileForATool.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToIgnoreObsoleteDotNetCliToolPackages.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreDotNetCliToolReference.cs
  src/Tests/Microsoft.NET.TestFramework/NuGetConfigWriter.cs
Labels: Area-Infrastructure, untriaged

#47369 [release/8.0.4xx] NugetConfigWriter: Update CDN tests
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeHaveAPackageReferenceWithAliases.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateADepsFileForATool.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToIgnoreObsoleteDotNetCliToolPackages.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreDotNetCliToolReference.cs
  src/Tests/Microsoft.NET.TestFramework/NuGetConfigWriter.cs
Labels: Area-Infrastructure, untriaged

#47360 [release/8.0.3xx] NugetConfigWriter: Update CDN tests
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeHaveAPackageReferenceWithAliases.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildANetCoreApp.cs
  src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToGenerateADepsFileForATool.cs
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToStoreAProjectWithDependencies.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToIgnoreObsoleteDotNetCliToolPackages.cs
  src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreDotNetCliToolReference.cs
  src/Tests/Microsoft.NET.TestFramework/NuGetConfigWriter.cs
Labels: Area-Infrastructure, untriaged

#47328 vs-solutionpersistence: 1.0.28 -> 1.0.52
  Directory.Packages.props
  eng/Version.Details.xml
Labels: untriaged, Area-NetSDK

#47226 Enable --interactive by default for sessions that are local.
  src/BuiltInTools/dotnet-watch/CommandLineOptions.cs
  src/Cli/dotnet/CommonOptions.cs
  src/Cli/dotnet/OptionForwardingExtensions.cs
  src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs
  src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs
  src/Cli/dotnet/commands/dotnet-package/add/PackageAddCommandParser.cs
  src/Cli/dotnet/commands/dotnet-package/list/PackageListCommandParser.cs
  src/Cli/dotnet/commands/dotnet-package/remove/PackageRemoveCommandParser.cs
  src/Cli/dotnet/commands/dotnet-package/search/PackageSearchCommandParser.cs
  src/Cli/dotnet/commands/dotnet-reference/dotnet-reference-add/ReferenceAddCommandParser.cs
  src/Cli/dotnet/commands/dotnet-run/Program.cs
  src/Cli/dotnet/commands/dotnet-tool/ToolCommandRestorePassThroughOptions.cs
  src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandNuGetRestoreActionConfigOptions.cs
  test/dotnet-add-reference.Tests/GivenDotnetAddReference.cs
  test/dotnet-completions.Tests/snapshots/bash/DotnetCliSnapshotTests.VerifyCompletions.verified.sh
  test/dotnet-completions.Tests/snapshots/pwsh/DotnetCliSnapshotTests.VerifyCompletions.verified.ps1
  test/dotnet-completions.Tests/snapshots/zsh/DotnetCliSnapshotTests.VerifyCompletions.verified.zsh
  test/dotnet-remove-package.Tests/GivenDotnetRemovePackage.cs
  test/dotnet-run.Tests/GivenDotnetRunBuildsCsProj.cs
  test/dotnet-watch.Tests/CommandLineOptionsTests.cs
  test/dotnet-watch.Tests/NoRestoreTests.cs
  test/dotnet.Tests/GivenParserDirectives.cs
  test/dotnet.Tests/ParserTests/AddReferenceParserTests.cs
  test/dotnet.Tests/ParserTests/InstallToolParserTests.cs
  test/dotnet.Tests/ParserTests/ToolRestoreParserTests.cs
  test/dotnet.Tests/ParserTests/UpdateToolParserTests.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetBuildInvocation.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetCleanInvocation.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetOsArchOptions.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetPackInvocation.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetPublishInvocation.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetRestoreInvocation.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetRunInvocation.cs
  test/dotnet.Tests/dotnet-msbuild/GivenDotnetTestInvocation.cs
Labels: untriaged, Document for new feature, cli-ux

#47371 [Github Actions] Remove Branch Lockdown Labels on Branding Merge
  .github/workflows/remove-lockdown-label.yml
Labels: Area-Infrastructure, untriaged

#47321 NuGetPackageDownloader: Only verify signing on windows by default
  src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs
Labels: untriaged, Area-Workloads

#47394 Delete GetTestsProject task
  src/Tasks/Microsoft.NET.Build.Tasks/GetTestsProject.cs
Labels: untriaged

#47407 Update logic of mixed mode of dotnet test
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
Labels: Area-Infrastructure, untriaged

#47067 Move BuildWithNetFrameworkHostedCompiler to common
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Common.targets
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets
Labels: Area-Infrastructure, untriaged

#42861 Add analyzer redirecting VSIX
  Directory.Packages.props
  NuGet.config
  eng/Signing.props
  eng/Versions.props
  sdk.sln
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/packaging/windows/VS.Redist.Common.Net.Core.SDK.RuntimeAnalyzers.nuspec
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Installer/redist-installer/targets/GenerateRuntimeAnalyzers.targets
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/RuntimeAnalyzers.targets
  src/Microsoft.Net.Sdk.AnalyzerRedirecting/AnalyzerRedirectingPackage.cs
  src/Microsoft.Net.Sdk.AnalyzerRedirecting/Microsoft.Net.Sdk.AnalyzerRedirecting.csproj
  src/Microsoft.Net.Sdk.AnalyzerRedirecting/SdkAnalyzerAssemblyRedirector.cs
  src/Microsoft.Net.Sdk.AnalyzerRedirecting/source.extension.vsixmanifest
  src/Tasks/sdk-tasks/GenerateRuntimeAnalyzersSWR.cs
  src/Tasks/sdk-tasks/sdk-tasks.InTree.targets
  test/Microsoft.Net.Sdk.AnalyzerRedirecting.Tests/Microsoft.Net.Sdk.AnalyzerRedirecting.Tests.csproj
  test/Microsoft.Net.Sdk.AnalyzerRedirecting.Tests/SdkAnalyzerAssemblyRedirectorTests.cs
  test/UnitTests.proj
Labels: Area-Infrastructure, untriaged

#47416 Revert "Fixup sourcelink information"
  src/SourceBuild/content/repo-projects/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#47415 WorkloadRestoreCommand.DiscoverAllProjects: Return full paths
  src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs
Labels: untriaged, Area-Workloads

#47417 Reapply "Fixup sourcelink information" (#47416)
  src/SourceBuild/content/repo-projects/Directory.Build.props
Labels: Area-Infrastructure, untriaged

#47427 Wait for file change when process exits
  src/BuiltInTools/dotnet-watch/EnvironmentVariables.cs
  src/BuiltInTools/dotnet-watch/HotReloadDotNetWatcher.cs
Labels: Area-Infrastructure, untriaged

#47220 Attempt to Fix and Re-enable HasIncludedFiles Test
  test/TestAssets/TestProjects/EndToEndTestApp/EndToEndTestApp.csproj
  test/TestAssets/TestProjects/EndToEndTestApp/Program.cs
  test/TestAssets/TestProjects/EndToEndTestApp/packfiles/pack1.txt
  test/TestAssets/TestProjects/EndToEndTestApp/packfiles/pack2.txt
  test/dotnet-pack.Tests/PackTests.cs
Labels: Area-Infrastructure, untriaged

#47422 [REF] SolutionProjectModel Full Paths
  src/Cli/dotnet/ReleasePropertyProjectLocator.cs
Labels: Area-Infrastructure, untriaged

#47449 Add more logging to dotnet test tracing
  src/Cli/dotnet/commands/dotnet-test/SolutionAndProjectUtility.cs
Labels: Area-dotnet test, untriaged

#47411 Create logger directory if it doesn't exist in dotnet test
  src/Cli/dotnet/commands/dotnet-test/Logger.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
Labels: Area-dotnet test, untriaged

#47431 Fix MAUI static asset updates
  src/BuiltInTools/dotnet-watch/DotNetWatch.targets
  test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs
Labels: Area-Infrastructure, untriaged

#47424 make container app/entrypoint argument defaults only happen on the RID-specific builds, not the outer RID-less build
  src/Containers/Microsoft.NET.Build.Containers/KnownStrings.cs
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
  test/Microsoft.NET.Build.Containers.IntegrationTests/TargetsTests.cs
Labels: untriaged, Area-Containers

#47455 add a flag to let users opt into serial builds of inner-RID containers
  src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
Labels: untriaged, Document for new feature, Area-Containers

#47468 Merging internal commits for release/8.0.4xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47471 Merging internal commits for release/9.0.2xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47474 Add version property for Microsoft.VisualStudio.SolutionPersistence
  Directory.Packages.props
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47479 Update to the 9.0.3 release
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47469 Merging internal commits for release/8.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47470 Merging internal commits for release/9.0.1xx
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47397 Generate the sdk msi bundles inside the VMR on windows BuildPass=2 verticals
  eng/Build.props
  eng/Signing.props
  eng/pipelines/templates/stages/vmr-build.yml
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/redist-installer.proj
  src/Installer/redist-installer/targets/BundledManifests.targets
  src/Installer/redist-installer/targets/GenerateLayout.targets
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Installer/redist-installer/targets/GeneratePKG.targets
  src/Installer/redist-installer/targets/GenerateRuntimeAnalyzers.targets
  src/Installer/redist-installer/targets/RestoreLayout.targets
  src/SourceBuild/content/repo-projects/dotnet.proj
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#47464 Fix global properties not propagating in new dotnet test for MTP
  src/Cli/dotnet/commands/dotnet-test/MSBuildUtility.cs
  src/Cli/dotnet/commands/dotnet-test/Options.cs
  src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
  test/TestAssets/TestProjects/TestProjectWithConditionOnGlobalProperty/OtherTestProject/OtherTestProject.csproj
  test/TestAssets/TestProjects/TestProjectWithConditionOnGlobalProperty/OtherTestProject/Program.cs
  test/TestAssets/TestProjects/TestProjectWithConditionOnGlobalProperty/TestProject/Program.cs
  test/TestAssets/TestProjects/TestProjectWithConditionOnGlobalProperty/TestProject/TestProject.csproj
  test/TestAssets/TestProjects/TestProjectWithConditionOnGlobalProperty/TestProjectWithConditionOnGlobalProperty.sln
  test/TestAssets/TestProjects/TestProjectWithConditionOnGlobalProperty/dotnet.config
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
Labels: Area-Infrastructure, untriaged

#46915 Add basic support for 'dotnet run file.cs'
  src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs
  src/Cli/dotnet/commands/VirtualProjectBuildingCommand.cs
  src/Cli/dotnet/commands/dotnet-run/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-run/Program.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
  test/dotnet-run.Tests/RunFileTests.cs
  test/dotnet.Tests/dotnet.Tests.csproj
Labels: Area-run-file

#47020 Add spec for `dotnet run file.cs`
  documentation/general/dotnet-run-file.md
Labels: documentation, Area-run-file

#47454 Use exe file if it exists in dotnet test
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/SolutionAndProjectUtility.cs
  test/Microsoft.NET.TestFramework/Utilities/RegexPatternHelper.cs
Labels: Area-dotnet test

#47501 Rename VSMSBuildExtensions and VSTemplateLocator and move under src/Layout
  eng/Build.props
  sdk.sln
  src/Layout/VS.Redist.Common.Net.Core.SDK.MSBuildExtensions/VS.Redist.Common.Net.Core.SDK.MSBuildExtensions.proj
  src/Layout/VS.Redist.Common.Net.Core.SDK.VSTemplateLocator/VS.Redist.Common.Net.Core.SDK.VSTemplateLocator.proj
Labels: Area-Infrastructure, untriaged

#47502 Extract nuget packages from redist-installer infra
  Directory.Build.props
  sdk.sln
  src/Installer/redist-installer/Directory.Build.props
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/packaging/windows/VS.Redist.Common.NetCore.SdkPlaceholder.nuspec
  src/Installer/redist-installer/packaging/windows/VS.Redist.Common.NetCore.Toolset.nuspec
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Installer/redist-installer/targets/GeneratePKG.targets
  src/Layout/Directory.Build.props
  src/Layout/VS.Redist.Common.NetCore.SdkPlaceholder/VS.Redist.Common.NetCore.SdkPlaceholder.proj
  src/Layout/VS.Redist.Common.NetCore.Toolset/VS.Redist.Common.NetCore.Toolset.proj
Labels: Area-Infrastructure, untriaged

#47505 VMR: remove FallbackPublicBaseURL from sdk.proj
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#47506 Set PackageProjectUrl in Directory.Build.props instead of sdk.proj
  Directory.Build.props
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure, untriaged

#47420 Update SDK-PR-guide.md to include inter-branch codeflow
  documentation/project-docs/SDK-PR-guide.md
Labels: Area-Infrastructure, untriaged

#47489 Cleanup TFM handling for the new dotnet test for MTP
  src/Cli/dotnet/commands/dotnet-test/SolutionAndProjectUtility.cs
Labels: Area-Infrastructure, untriaged

#47499 Extract RuntimeAnalyzers infra from redist
  sdk.sln
  src/Installer/redist-installer/packaging/windows/VS.Redist.Common.Net.Core.SDK.RuntimeAnalyzers.nuspec
  src/Installer/redist-installer/targets/GenerateMSIs.targets
  src/Layout/VS.Redist.Common.Net.Core.SDK.RuntimeAnalyzers/VS.Redist.Common.Net.Core.SDK.RuntimeAnalyzers.proj
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/RuntimeAnalyzers.targets
Labels: Area-Infrastructure, untriaged

#47519 Roll back to previous SDK
  global.json
  test/EndToEnd.Tests/ProjectBuildTests.cs
Labels: Area-Infrastructure, untriaged

#47547 Cleanup new dotnet test tests
  test/Microsoft.NET.TestFramework/Commands/TestCommand.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndDiscoversTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsHelp.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestBasedOnGlobbingFilter.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsForMultipleTFMs.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithArtifacts.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
  test/dotnet-test.Tests/GivenDotnetTestsRunsWithDifferentCultures.cs
Labels: Area-dotnet test, untriaged

#47512 ToolManifestFinder detect .slnx
  src/Cli/dotnet/ToolManifest/ToolManifestFinder.cs
Labels: untriaged, Area-Tools

#47520 Add comment for updating version
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47564 [Github Actions] Labels: Add extra labels to check
  .github/workflows/pr-analysis.yml
Labels: Area-Infrastructure, untriaged

#47560 Don't run the GetProducedPackages target early when previous build pass dependencies are referenced
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/dotnet.proj
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: untriaged, Area-VMR

#47542 Avoid intermediate FullNugetVersion file
  eng/Publishing.props
  eng/Signing.props
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/redist-installer.proj
Labels: Area-Infrastructure, untriaged

#47557 Cleanup special handling of command-line options that are now forwarded as global properties
  src/Cli/dotnet/commands/dotnet-test/MSBuildUtility.cs
  src/Cli/dotnet/commands/dotnet-test/Options.cs
Labels: Area-Infrastructure, untriaged

#47544 Extract version badge generation from redist-installer.proj
  eng/Badge.proj
  eng/Publishing.props
  eng/Signing.props
  eng/version_badge.svg
  src/Installer/redist-installer/Directory.Build.targets
  src/Installer/redist-installer/targets/Badge.targets
Labels: Area-Infrastructure, untriaged

#47493 Rely on RunCommand for the new dotnet test experience for MTP
  src/Cli/dotnet/commands/CommonRunHelpers.cs
  src/Cli/dotnet/commands/RunProperties.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs
  src/Cli/dotnet/commands/dotnet-test/MSBuildUtility.cs
  src/Cli/dotnet/commands/dotnet-test/Models.cs
  src/Cli/dotnet/commands/dotnet-test/Options.cs
  src/Cli/dotnet/commands/dotnet-test/SolutionAndProjectUtility.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplicationEventHandlers.cs
  src/Cli/dotnet/commands/dotnet-test/TestModulesFilterHandler.cs
  test/TestAssets/TestProjects/MultipleTestProjectSolution/TestProject/Program.cs
  test/TestAssets/TestProjects/MultipleTestProjectSolution/TestProject/TestProject.csproj
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
Labels: Area-dotnet test, untriaged

#47562 Add baselining mechanism to the build comparison tool
  eng/pipelines/templates/steps/vmr-validate-asset-baseline.yml
  eng/vmr-msft-comparison-baseline.json
  src/SourceBuild/content/eng/tools/BuildComparer/AssetMapping.cs
  src/SourceBuild/content/eng/tools/BuildComparer/AssetType.cs
  src/SourceBuild/content/eng/tools/BuildComparer/BaselineEntry.cs
  src/SourceBuild/content/eng/tools/BuildComparer/ComparisonReport.cs
  src/SourceBuild/content/eng/tools/BuildComparer/Issue.cs
  src/SourceBuild/content/eng/tools/BuildComparer/IssueType.cs
  src/SourceBuild/content/eng/tools/BuildComparer/Program.cs
Labels: Area-Infrastructure, untriaged

#47605 Update sln in reaction to the recent file moves
  sdk.sln
Labels: Area-Infrastructure, untriaged

#47565 [release/9.0.1xx] Update GivenThatWeWantMSBuildToRespectCustomCulture.cs
  test/Microsoft.NET.Build.Tests/GivenThatWeWantMSBuildToRespectCustomCulture.cs
Labels: Area-Infrastructure, untriaged

#47604 Consolidate redist infrastructure
  Directory.Build.props
  Directory.Build.targets
  src/Layout/Directory.Build.props
  src/Layout/Directory.Build.targets
  src/Layout/VS.Redist.Common.Net.Core.SDK.RuntimeAnalyzers/VS.Redist.Common.Net.Core.SDK.RuntimeAnalyzers.proj
  src/Layout/VS.Redist.Common.NetCore.SdkPlaceholder/VS.Redist.Common.NetCore.SdkPlaceholder.proj
  src/Layout/VS.Redist.Common.NetCore.Toolset/VS.Redist.Common.NetCore.Toolset.proj
  src/Layout/pkg/dotnet-sdk.proj
  src/Layout/redist-installer/Directory.Build.props
  src/Layout/redist-installer/Directory.Build.targets
  src/Layout/redist-installer/redist-installer.proj
  src/Layout/redist-installer/targets/BundledDotnetTools.targets
  src/Layout/redist-installer/targets/BundledManifests.targets
  src/Layout/redist-installer/targets/BundledTemplates.targets
  src/Layout/redist-installer/targets/Crossgen.targets
  src/Layout/redist-installer/targets/GenerateArchives.targets
  src/Layout/redist-installer/targets/GenerateBundledVersions.targets
  src/Layout/redist-installer/targets/GenerateLayout.targets
  src/Layout/redist-installer/targets/GenerateMSIs.targets
  src/Layout/redist/redist.csproj
  src/Layout/redist/targets/Directory.Build.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged

#47509 Update Microsoft.AspNetCore.Watch.BrowserRefresh to net8.0
  eng/Version.Details.xml
  src/BuiltInTools/BrowserRefresh/BrowserRefreshMiddleware.cs
  src/BuiltInTools/BrowserRefresh/Microsoft.AspNetCore.Watch.BrowserRefresh.csproj
Labels: untriaged, Area-AspNetCore

#44611 Installer/finalizer in c#
  Directory.Build.props
  build.cmd
  global.json
  sdk.sln
  src/Layout/finalizer/CMakeLists.txt
  src/Layout/finalizer/Directory.Build.props
  src/Layout/finalizer/Program.cs
  src/Layout/finalizer/finalizer-build.csproj
  src/Layout/finalizer/finalizer.cpp
  src/Layout/finalizer/finalizer.csproj
  src/Layout/finalizer/finalizer.nativeproj
  src/Layout/finalizer/native.rc
  src/Layout/finalizer/precomp.h
  src/Layout/redist-installer/redist-installer.proj
  src/Layout/redist-installer/targets/GenerateMSIs.targets
  src/Microsoft.Win32.Msi/Error.cs
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: Area-Infrastructure

#47617 dotnet CLI: Removed .Designer files
  src/Cli/dotnet/commands/dotnet-tool/restore/LocalizableStrings.Designer.cs
  src/Cli/dotnet/commands/dotnet-tool/search/LocalizableStrings.Designer.cs
Labels: untriaged, Area-CLI

#47610 Don't get produced packages from transitive references in other build passes
  src/SourceBuild/content/repo-projects/Directory.Build.targets
Labels: Area-VMR

#47616 Add validation for command-line arguments related to new dotnet test
  src/Cli/dotnet/commands/dotnet-test/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestModulesFilterHandler.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
  src/Cli/dotnet/commands/dotnet-test/ValidationUtility.cs
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-test/xlf/LocalizableStrings.zh-Hant.xlf
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
Labels: Area-Infrastructure, untriaged

#47443 Revert changes to NativeAot test due to runtime update
  src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAnAotApp.cs
Labels: untriaged, Area-NativeAOT

#47657 Extract templates nupkg generation from GenerateMSIs.targets
  sdk.sln
  src/Layout/VS.Redist.Common.NetCore.Templates/VS.Redist.Common.NetCore.Templates.proj
  src/Layout/redist-installer/packaging/windows/Init.cmd
  src/Layout/redist-installer/packaging/windows/VS.Redist.Common.NetCore.Templates.nuspec
  src/Layout/redist-installer/packaging/windows/generatenupkg.ps1
  src/Layout/redist-installer/targets/BundledTemplates.targets
  src/Layout/redist-installer/targets/GenerateMSIs.targets
Labels: Area-Infrastructure, untriaged

#47656 Remove unnecessary 32bit arm architecture checks in the Windows build
  src/Layout/Directory.Build.props
  src/Layout/redist-installer/targets/BundledManifests.targets
  src/Layout/redist-installer/targets/BundledTemplates.targets
  src/Layout/redist-installer/targets/RestoreLayout.targets
Labels: Area-Infrastructure, untriaged

#47421 Permit specifying to use workload versions in global.json
  src/Cli/dotnet/commands/InstallingWorkloadCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/GlobalJsonWorkloadSetFile.cs
  src/Cli/dotnet/commands/dotnet-workload/config/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/config/WorkloadConfigCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/config/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-workload/update/WorkloadUpdateCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-workload/update/xlf/LocalizableStrings.zh-Hant.xlf
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadManifestProvider.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.GlobalJsonReader.cs
  src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs
  test/dotnet-workload-update.Tests/GivenDotnetWorkloadUpdate.cs
Labels: untriaged, Area-Workloads

#47598 Publish symbols of RuntimeAnalyzers
  src/Installer/redist-installer/packaging/windows/generatenupkg.ps1
  src/Installer/redist-installer/targets/GenerateMSIs.targets
Labels: Area-Infrastructure, untriaged

#47662 Add missing VersionTools package version
  src/SourceBuild/content/Directory.Packages.props
  src/SourceBuild/content/eng/Version.Details.xml
  src/SourceBuild/content/eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47619 dotnet CLI: Removed CommandLineValidation directory
  src/Cli/dotnet/CommandLineValidation/LocalizableStrings.resx
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/CommandLineValidation/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/CommandParsingException.cs
  src/Cli/dotnet/CommonLocalizableStrings.resx
  src/Cli/dotnet/Extensions/ParseResultExtensions.cs
  src/Cli/dotnet/Parser.cs
  src/Cli/dotnet/Program.cs
  src/Cli/dotnet/commands/dotnet-workload/search/WorkloadSearchVersionsCommandParser.cs
  src/Cli/dotnet/xlf/CommonLocalizableStrings.cs.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.de.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.es.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.fr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.it.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ja.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ko.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pl.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.ru.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.tr.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/xlf/CommonLocalizableStrings.zh-Hant.xlf
  test/dotnet-add-reference.Tests/GivenDotnetAddReference.cs
  test/dotnet-list-reference.Tests/GivenDotnetListReference.cs
  test/dotnet-remove-reference.Tests/GivenDotnetRemoveP2P.cs
  test/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
  test/dotnet-sln.Tests/GivenDotnetSlnList.cs
  test/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
  test/dotnet-sln.Tests/dotnet-sln.Tests.csproj
  test/dotnet-workload-search.Tests/GivenDotnetWorkloadSearch.cs
  test/dotnet.Tests/ParserTests/AddReferenceParserTests.cs
  test/dotnet.Tests/ParserTests/BuildRelatedCommandParserTests.cs
  test/dotnet.Tests/ParserTests/ToolSearchParserTests.cs
Labels: untriaged, Area-CLI

#47620 dotnet CLI: Move command folder sources
  src/Cli/dotnet/commands/dotnet-restore/RestoringCommand.cs
  src/Cli/dotnet/commands/dotnet-run/CommonRunHelpers.cs
  src/Cli/dotnet/commands/dotnet-run/RunProperties.cs
  src/Cli/dotnet/commands/dotnet-run/VirtualProjectBuildingCommand.cs
  src/Cli/dotnet/commands/dotnet-workload/InstallingWorkloadCommand.cs
Labels: untriaged, Area-CLI

#47664 Check for Muxer path relative to base directory
  src/Cli/Microsoft.DotNet.Cli.Utils/Muxer.cs
Labels: untriaged, Area-CLI

#47543 Update `dotnet run file.cs` spec with new ignored directives syntax
  documentation/general/dotnet-run-file.md
Labels: untriaged, Area-run-file

#47670 Add IBC switch and disable by default
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/variables/vmr-build.yml
  src/SourceBuild/content/eng/pipelines/ci.yml
Labels: Area-Infrastructure, untriaged

#47668 Create tsaoptions.json for VMR
  src/SourceBuild/content/.config/tsaoptions.json
Labels: Area-Infrastructure, untriaged

#47658 Update MSTest templates for .NET 10
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-FSharp/Company.TestProject1.fsproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-VisualBasic/Company.TestProject1.vbproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/Playwright-MSTest-CSharp/Company.TestProject1.csproj
Labels: Area-Infrastructure, untriaged

#47660 Refactor binlog and use in dotnet test and dotnet run
  src/Cli/dotnet/LoggerUtility.cs
  src/Cli/dotnet/commands/dotnet-run/Program.cs
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Cli/dotnet/commands/dotnet-run/VirtualProjectBuildingCommand.cs
  src/Cli/dotnet/commands/dotnet-test/MSBuildUtility.cs
  src/Cli/dotnet/commands/dotnet-test/SolutionAndProjectUtility.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
Labels: Area-dotnet test

#47667 Compare tar.gz files between VMR and current .NET builds
  src/SourceBuild/content/eng/tools/BuildComparer/Program.cs
Labels: Area-Infrastructure, untriaged

#47500 Add command 'dotnet project convert'
  src/Cli/dotnet/Parser.cs
  src/Cli/dotnet/commands/dotnet-project/ProjectCommandParser.cs
  src/Cli/dotnet/commands/dotnet-project/convert/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-project/convert/ProjectConvertCommand.cs
  src/Cli/dotnet/commands/dotnet-project/convert/ProjectConvertCommandParser.cs
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-project/convert/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/commands/dotnet-run/LocalizableStrings.resx
  src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
  src/Cli/dotnet/commands/dotnet-run/VirtualProjectBuildingCommand.cs
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/commands/dotnet-run/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
  test/dotnet-completions.Tests/snapshots/bash/DotnetCliSnapshotTests.VerifyCompletions.verified.sh
  test/dotnet-completions.Tests/snapshots/pwsh/DotnetCliSnapshotTests.VerifyCompletions.verified.ps1
  test/dotnet-completions.Tests/snapshots/zsh/DotnetCliSnapshotTests.VerifyCompletions.verified.zsh
  test/dotnet-project-convert.Tests/DotnetProjectConvertTests.cs
  test/dotnet-run.Tests/RunFileTests.cs
  test/dotnet.Tests/CommandTests/CompleteCommandTests.cs
  test/dotnet.Tests/dotnet.Tests.csproj
Labels: untriaged, Area-run-file

#47694 Forward global props to dotnet run
  src/Cli/dotnet/commands/dotnet-test/SolutionAndProjectUtility.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
Labels: Area-dotnet test, untriaged

#47338 Remove primary vertical concept from JoinVerticals
  eng/Publishing.props
  eng/pipelines/templates/stages/vmr-build-with-join.yml
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/stages/vmr-verticals.yml
  eng/pipelines/templates/steps/vmr-join-verticals.yml
  src/SourceBuild/content/eng/join-verticals.proj
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/AzureDevOpsClient.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/JoinVerticals.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/BuildAssetsManifest.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsAssetSelector.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ManifestAssets/JoinVerticalsConfig.cs
  src/SourceBuild/content/eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/Models/AzureDevOpsArtifactInformation.cs
  src/SourceBuild/content/repo-projects/Directory.Build.props
  src/SourceBuild/content/repo-projects/Directory.Build.targets
  src/SourceBuild/content/repo-projects/runtime.proj
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/JoinVerticalsTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Android_Shortstack_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Pgo_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Pgo_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_ShortStack_Mono_LLVMAOT_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_ShortStack_Mono_LLVMAOT_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Browser_Multithreaded_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Browser_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/LinuxBionic_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/MacCatalyst_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/MacCatalyst_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_Shortstack_Mono_LLVMAOT_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Wasi_Shortstack_wasm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_Pgo_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x64_BuildPass2.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x86.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x86_BuildPass2.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOSSimulator_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOSSimulator_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/iOS_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOSSimulator_Shortstack_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOSSimulator_Shortstack_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/tvOS_Shortstack_arm64.xml
Labels: untriaged, Area-VMR

#47402 dotnet package list should not throw if project not specified
  src/Cli/dotnet/commands/dotnet-package/list/ListPackageReferencesCommand.cs
Labels: Area-Infrastructure, untriaged

#47703 Remove no longer used TestOptions.Configuration
  src/Cli/dotnet/commands/dotnet-test/Options.cs
  src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
Labels: Area-Infrastructure, untriaged

#47706 Remove RunSettingsFilePath support from dotnet test for MTP
  src/Cli/dotnet/commands/dotnet-test/CliConstants.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Models/ModuleMessage.cs
  src/Cli/dotnet/commands/dotnet-test/IPC/Serializers/ModuleMessageSerializer.cs
  src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs
  src/Cli/dotnet/commands/dotnet-test/Models.cs
  src/Cli/dotnet/commands/dotnet-test/SolutionAndProjectUtility.cs
  src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
  src/Cli/dotnet/commands/dotnet-test/TestModulesFilterHandler.cs
Labels: Area-dotnet test, untriaged

#47652 Add cgmanifest.json for test templates
  eng/cgmanifest.json
  sdk.sln
Labels: Area-Infrastructure, untriaged

#47733 Fix runtimeIdentifier for macOS PR jobs
  eng/pipelines/templates/jobs/sdk-job-matrix.yml
Labels: Area-Infrastructure, untriaged

#47688 Bump versions for test templates
  eng/cgmanifest.json
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-FSharp/Company.TestProject1.fsproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/MSTest-VisualBasic/Company.TestProject1.vbproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/NUnit-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/NUnit-FSharp/Company.TestProject1.fsproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/NUnit-VisualBasic/Company.TestProject1.vbproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/Playwright-MSTest-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/Playwright-NUnit-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/XUnit-CSharp/Company.TestProject1.csproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/XUnit-FSharp/Company.TestProject1.fsproj
  template_feed/Microsoft.DotNet.Common.ProjectTemplates.10.0/content/XUnit-VisualBasic/Company.TestProject1.vbproj
Labels: Area-Infrastructure

#47709 Update prerelease branding for preview 4
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#47700 Improve baselining
  eng/vmr-msft-comparison-baseline.json
  src/SourceBuild/content/eng/tools/BuildComparer/BaselineEntry.cs
  src/SourceBuild/content/eng/tools/BuildComparer/IssueType.cs
  src/SourceBuild/content/eng/tools/BuildComparer/Program.cs
Labels: Area-Infrastructure, untriaged

#47742 Remove duplicate nuget packages from asset manifests baseline
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_Alpine_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_arm.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/AzureLinux_x64_Cross_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/OSX_x64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_arm64.xml
  src/SourceBuild/content/test/Microsoft.DotNet.Tests/assets/JoinVerticalsTests/manifests/verticals/Windows_x86.xml
Labels: Area-Infrastructure, untriaged

#47433 Harden metadata handler invoker against bad metadata
  src/BuiltInTools/HotReloadAgent/MetadataUpdateHandlerInvoker.cs
Labels: Area-Infrastructure, untriaged

#47710 Update implicit versions for March
  eng/Versions.props
Labels: Area-Infrastructure, untriaged

#46477 Decoupling Visual Studio and the .NET SDK
  documentation/general/decouple-vs-and-net-sdk.md
Labels: Area-Infrastructure, untriaged

#45288 Adding guidance on what is considered a breaking change in the .NET SDK
  documentation/README.md
  documentation/project-docs/breaking-change-guidelines.md
Labels: Area-Infrastructure, untriaged

#47313 Run installer tests in pipeline
  eng/pipelines/templates/stages/vmr-build.yml
  eng/pipelines/templates/steps/vmr-validate-installers.yml
  src/SourceBuild/content/build.sh
  src/SourceBuild/content/eng/build.ps1
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/Config.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/LinuxInstallerTests.cs
  src/SourceBuild/content/test/Microsoft.DotNet.Installer.Tests/Microsoft.DotNet.Installer.Tests.csproj
Labels: Area-Infrastructure, untriaged

#47759 [wasm] Remove explicit WasmBootConfigFileName from tests
  test/Microsoft.NET.TestFramework/AspNetSdkTest.cs
Labels: untriaged, Area-WasmSdk

#47701 [StaticWebAssets] Adds incrementalism to DefineStaticWebAssets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.JSModules.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.Cache.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.cs
  src/StaticWebAssetsSdk/Tasks/FingerprintPatternMatcher.cs
  src/StaticWebAssetsSdk/Tasks/Utils/HashingUtils.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/DiscoverStaticWebAssetsTest.cs
Labels: untriaged, Area-AspNetCore

#47787 [main] Update Source-Build SDK Diff Tests Baselines
  src/SourceBuild/content/test/Microsoft.DotNet.SourceBuild.Tests/assets/SdkContentTests/MsftToSbSdkFiles.diff
Labels: Area-Infrastructure, untriaged

#47745 Allow winforms binaries in the VMR
  src/SourceBuild/content/eng/allowed-vmr-binaries.txt
Labels: Area-Infrastructure, untriaged

#47788 Fix path to tool settings file in build
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PackTool.targets
Labels: untriaged, Area-NetSDK

#45877 Run `AddImplicitDefineConstants` after `PrepareForBuild`.
  src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets
Labels: untriaged, Area-NetSDK

#47689 [StaticWebAssets] Backport perf fixes
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Pack.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.Publish.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
  src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs
  src/StaticWebAssetsSdk/Tasks/Data/Serialization/StaticWebAssetsJsonSerializerContext.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticAssetsManifest.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAsset.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpointProperty.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpointResponseHeader.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpointSelector.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssetEndpoints.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetEndpointsManifest.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetsDevelopmentManifest.cs
  src/StaticWebAssetsSdk/Tasks/GenerateStaticWebAssetsManifest.cs
  src/StaticWebAssetsSdk/Tasks/Utils/ArtifactWriter.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssets/GenerateStaticWebAssetsDevelopmentManifestTest.cs
  test/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs
Labels: untriaged, Area-AspNetCore

#47764 Add instance id to protocol with MTP
  eng/Version.Details.xml
  eng/Versions.props
  src/Cli/dotnet/commands/Test/CliConstants.cs
  src/Cli/dotnet/commands/Test/CustomEventArgs.cs
  src/Cli/dotnet/commands/Test/IPC/Models/DiscoveredTestMessages.cs
  src/Cli/dotnet/commands/Test/IPC/Models/FileArtifactMessages.cs
  src/Cli/dotnet/commands/Test/IPC/Models/HandshakeMessage.cs
  src/Cli/dotnet/commands/Test/IPC/Models/TestResultMessages.cs
  src/Cli/dotnet/commands/Test/IPC/Models/TestSessionEvent.cs
  src/Cli/dotnet/commands/Test/IPC/ObjectFieldIds.cs
  src/Cli/dotnet/commands/Test/IPC/Serializers/DiscoveredTestMessagesSerializer.cs
  src/Cli/dotnet/commands/Test/IPC/Serializers/FileArtifactMessagesSerializer.cs
  src/Cli/dotnet/commands/Test/IPC/Serializers/TestResultMessagesSerializer.cs
  src/Cli/dotnet/commands/Test/TestApplication.cs
  src/Cli/dotnet/commands/Test/TestApplicationEventHandlers.cs
  src/Cli/dotnet/commands/Test/TestingPlatformCommand.cs
Labels: Area-dotnet test

#47686 Clean up #nullable disable from test directory
  test/ArgumentForwarding.Tests/ArgumentForwardingTests.cs
  test/Microsoft.NET.TestFramework/NuGetConfigWriter.cs
  test/Microsoft.NET.TestFramework/TestAssetsManager.cs
  test/crossgen.Tests/crossgen.Tests.cs
  test/dotnet-add-package.Tests/GivenDotnetPackageAdd.cs
  test/dotnet-add-reference.Tests/GivenDotnetAddReference.cs
  test/dotnet-back-compat.Tests/GivenThatWeWantToBeBackwardsCompatibleWith1xProjects.cs
  test/dotnet-build.Tests/GivenDotnetBuildBuildsCsproj.cs
Labels: Area-Infrastructure, untriaged

#47836 Update exit code logic for dotnet test
  src/Cli/dotnet/commands/Test/SolutionAndProjectUtility.cs
  src/Cli/dotnet/commands/Test/TestApplicationActionQueue.cs
  src/Cli/dotnet/commands/Test/TestingPlatformCommand.cs
  test/Microsoft.NET.TestFramework/Constants.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndDiscoversTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsHelp.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestBasedOnGlobbingFilter.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTests.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsForMultipleTFMs.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithArtifacts.cs
  test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestsWithDifferentOptions.cs
  test/dotnet-test.Tests/GivenDotnetTestsRunsWithDifferentCultures.cs
Labels: Area-dotnet test

#47838 [StaticWebAssets] Optimized JSON serialization logic
  src/StaticWebAssetsSdk/Tasks/Data/Serialization/StaticWebAssetsJsonSerializerContext.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpointProperty.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpointResponseHeader.cs
  src/StaticWebAssetsSdk/Tasks/Data/StaticWebAssetEndpointSelector.cs
  src/StaticWebAssetsSdk/Tasks/DefineStaticWebAssets.Cache.cs
Labels: Area-Infrastructure, untriaged

#47065 Use right hand side references even when not compatible
  src/Compatibility/ApiCompat/Microsoft.DotNet.PackageValidation/ApiCompatRunnerExtensions.cs
Labels: untriaged, Area-ApiCompat

#47870 Enable winforms tests
  src/SourceBuild/content/repo-projects/winforms.proj
  src/SourceBuild/patches/winforms/0001-Condition-out-the-native-tests-in-VMR.patch
Labels: Area-Infrastructure, untriaged

#47858 Update Skip attribute with issue link for unimplemented tests
  test/dotnet-sln.Tests/GivenDotnetSlnAdd.cs
  test/dotnet-sln.Tests/GivenDotnetSlnRemove.cs
  test/dotnet.Tests/GivenExponentialRetry.cs
  test/dotnet.Tests/TelemetryCommandTest.cs
Labels: Area-Infrastructure, untriaged

#47809 Do not show VS workloads from an old version Fixes #47794
  src/Cli/dotnet/commands/dotnet-workload/WorkloadInfoHelper.cs
Labels: untriaged, Area-Workloads

#47461 Remove `ForceDryRunSigning=true` on Mac & Linux signed builds
  eng/pipelines/templates/jobs/vmr-build.yml
Labels: Area-Infrastructure, untriaged

#47846 Remove nuget-client from non-SB VMR
  src/SourceBuild/content/repo-projects/sdk.proj
Labels: untriaged, Area-VMR

#47875 Adjust how we enable dac signing to get it working on VMR release branches
  eng/pipelines/templates/jobs/vmr-build.yml
  eng/pipelines/templates/stages/vmr-verticals.yml
  eng/pipelines/templates/variables/vmr-build.yml
Labels: untriaged, Area-VMR

#47910 Fix missing files from rpm and deb packages
  src/Layout/pkg/dotnet-sdk.proj
Labels: Area-Infrastructure, untriaged

#47887 Do not include symbols nupkgs in PSB archive
  src/SourceBuild/content/eng/finish-source-only.proj
Labels: Area-Infrastructure, untriaged

#47876 Enable TSA tools
  src/SourceBuild/content/eng/pipelines/ci.yml
Labels: Area-Infrastructure, untriaged

#47767 Consolidate redist output paths
  src/BuiltInTools/dotnet-watch/dotnet-watch.csproj
  src/Layout/Directory.Build.targets
  src/Layout/redist/targets/BundledDotnetTools.targets
  src/Layout/redist/targets/BundledTemplates.targets
  src/Layout/redist/targets/Directory.Build.targets
  src/Layout/redist/targets/GenerateBundledVersions.targets
  src/Layout/redist/targets/GenerateInstallerLayout.targets
  src/Layout/redist/targets/GenerateLayout.targets
  src/Layout/redist/targets/GenerateMSIs.targets
  src/Layout/redist/targets/GeneratePKG.targets
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
  src/Layout/redist/targets/PublishDotnetWatch.targets
  src/Tasks/sdk-tasks/Chmod.cs
  src/Tasks/sdk-tasks/sdk-tasks.InTree.targets
Labels: Area-Infrastructure, untriaged

#45666 Create trust boundary doc Fixes #45340
  documentation/general/trust-code.md
Labels: untriaged, Area-NetSDK

#47798 Update message for PRs labeled as breaking-change
  .github/policies/resourceManagement.yml
Labels: Area-Infrastructure, untriaged

#47812 Update message for issues labeled as breaking-change
  .github/policies/resourceManagement.yml
Labels: Area-Infrastructure, untriaged

#47797 Update breaking-change-guidelines.md
  documentation/project-docs/breaking-change-guidelines.md
Labels: Area-Infrastructure, untriaged

#45633 simplify CreateTempSubdirectory
  src/Cli/Microsoft.DotNet.InternalAbstractions/DirectoryPath.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/EnvironmentWrapper.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/FilePath.cs
  src/Cli/Microsoft.DotNet.InternalAbstractions/Microsoft.DotNet.InternalAbstractions.csproj
  src/Common/PathUtilities.cs
  test/dotnet.Tests/CommandTests/ToolRunCommandTests.cs
  test/dotnet.Tests/CommandTests/ToolUpdateGlobalOrToolPathCommandTests.cs
Labels: Area-Infrastructure, untriaged

#47905 Try to update queue to macOS 15
  .vsts-ci.yml
  .vsts-pr.yml
Labels: Area-Infrastructure, untriaged

#47724 Update .net10 p2 to p3 in the table
  documentation/package-table.md
Labels: Area-Infrastructure, untriaged

#47702 Process C# directives in file-based programs
  documentation/general/dotnet-run-file.md
  src/Cli/dotnet/Commands/Project/Convert/ProjectConvertCommand.cs
  src/Cli/dotnet/Commands/Run/LocalizableStrings.resx
  src/Cli/dotnet/Commands/Run/RunCommand.cs
  src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.cs.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.de.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.es.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.fr.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.it.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.ja.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.ko.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.pl.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.pt-BR.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.ru.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.tr.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.zh-Hans.xlf
  src/Cli/dotnet/Commands/Run/xlf/LocalizableStrings.zh-Hant.xlf
  src/Cli/dotnet/dotnet.csproj
  test/dotnet-project-convert.Tests/DotnetProjectConvertTests.cs
  test/dotnet-run.Tests/RunFileTests.cs
Labels: untriaged, Area-run-file

#47940 Ignore duplicate content items
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.JSModules.targets
  src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets
Labels: Area-Infrastructure, untriaged

#47938 Fix sdk msi's relative layout path
  src/Layout/redist/targets/GenerateInstallerLayout.targets
  src/Layout/redist/targets/GenerateMSIs.targets
  src/Layout/redist/targets/GeneratePKG.targets
Labels: Area-Infrastructure, untriaged

#47939 Use hardlinks for preparing the testhost folder
  src/Layout/redist/targets/OverlaySdkOnLKG.targets
Labels: Area-Infrastructure, untriaged
